### ISSUE TITLE
won't build with STATIC=1 in Fedora environments due to missing static libraries

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1004]
Whenever trying to build tracee-ebpf in a fedora environment - outside docker - I realized that RHEL based distros won't compile because of their compat-libs approach of having /usr/lib and /usr/lib64 as prefixes for their OS environment. This leads to the following error:

```
# github.com/aquasecurity/tracee/tracee-ebpf
/usr/lib/golang/pkg/tool/linux_amd64/link: running clang failed: exit status 1
/bin/ld: cannot find -lelf
/bin/ld: cannot find -lz
/bin/ld: cannot find -lpthread
/bin/ld: cannot find -lc
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

and should be fixed in the Makefile.

> This was identified during tests for https://github.com/aquasecurity/tracee/pull/1001 and it is also part of the supported environments effort: https://github.com/aquasecurity/tracee/issues/971.

**Comment by rafaeldtinoco** [comment]
Together with this, I can make some other improvements to Makefile (tracee and libbpfgo) such as:

```patch
diff --git a/Makefile b/Makefile
index 08abb51..81fad3e 100644
--- a/Makefile
+++ b/Makefile
@@ -83,12 +83,20 @@ libbpfgo-static-test: libbpfgo-test-bpf-static
                -tags netgo -ldflags $(CGO_EXTLDFLAGS_STATIC) \
                .

+# checks
+
+.PHONY: static-checks
+static-checks:
+ifeq ($(BPFTOOL),)
+       $(error ERROR: you should have bpftool installed (linux-tools))
+endif
+
 # vmlinux header file

 .PHONY: vmlinuxh
 vmlinuxh: $(VMLINUXH)

-$(VMLINUXH): $(OUTPUT)
+$(VMLINUXH): $(OUTPUT) | static-checks
        @if [ ! -f $(BTFFILE) ]; then \
                echo "ERROR: kernel does not seem to support BTF"; \
                exit 1; \
```

**Comment by grantseltzer** [comment]
I'm not able to reproduce this on fedora 33, my .a and .so libraries are in fact in /usr/lib64

**Comment by rafaeldtinoco** [comment]
STATIC=0 solves this issue. Fedora stopped providing static library packages for libelf, for example, since Fedora 33. This way, in Fedora environments, it is only possible to compile tracee dynamically linked with libelf & libz.
