### ISSUE TITLE
Unmarshal "envp" using json output

### ISSUE THREAD

**Issue by michaelkatch** [aquasecurity/tracee#1009]
Hey,
I have an issue when using tracee-ebpf with the flag "-o option :exec-env" when output format is JSON. 
The exec-env outputs a slice of string ([]string) when execve syscall is made.
Gob output handles it well but, JSON output won't.

**Comment by grantseltzer** [comment]
To clarify, are you saying the keys and values should be separated in JSON output, or are you seeing something different?

Given the sample paste below:
```
[*] sudo ./dist/tracee-ebpf -o option:exec-env --trace event=execve -o format:json | jq
{
  "timestamp": 1631630490580528000,
  "processId": 53336,
  "threadId": 53336,
  "parentProcessId": 53334,
  "hostProcessId": 53336,
  "hostThreadId": 53336,
  "hostParentProcessId": 53334,
  "userId": 1000,
  "mountNamespace": 4026531840,
  "pidNamespace": 4026531836,
  "processName": "zsh",
  "hostName": "localhost.local",
  "containerId": "me.Terminal.",
  "eventId": "59",
  "eventName": "execve",
  "argsNum": 3,
  "returnValue": 0,
  "stackAddresses": null,
  "args": [
    {
      "name": "pathname",
      "type": "const char*",
      "value": "/usr/bin/git"
    },
    {
      "name": "argv",
      "type": "const char*const*",
      "value": [
        "git",
        "status",
        "--porcelain",
        "--ignore-submodules=dirty"
      ]
    },
    {
      "name": "envp",
      "type": "const char*const*",
      "value": [
        "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh",
        "SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/2142,unix/unix:/tmp/.ICE-unix/2142",
        "GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/3bfc765f_dda4_4c2a_b291_eecad1318aed",
        "MOZ_GMP_PATH=/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed",
        "XDG_CURRENT_DESKTOP=GNOME",
        "LANG=en_US.UTF-8",
        "WAYLAND_DISPLAY=wayland-0",
        "LESSOPEN=||/usr/bin/lesspipe.sh %s",
        "QT_IM_MODULE=ibus",
        "DESKTOP_SESSION=gnome",
        "HOSTNAME=fedora",
        "XDG_MENU_PREFIX=gnome-",
        "HISTSIZE=50000",
        "COLORTERM=truecolor",
        "OLDPWD=/home/rotscale/go/src/github.com/aquasecurity/tracee/tracee-ebpf",
        "USER=rotscale",
        "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus",
        "PWD=/home/rotscale/go/src/github.com/aquasecurity/tracee/tracee-ebpf",
        "XDG_DATA_DIRS=/home/rotscale/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/",
        "VTE_VERSION=6203",
        "XDG_SESSION_DESKTOP=gnome",
        "HOME=/home/rotscale",
        "GNOME_SETUP_DISPLAY=:1",
        "MAIL=/var/spool/mail/rotscale",
        "LOGNAME=rotscale",
        "GNOME_TERMINAL_SERVICE=:1.875",
        "PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/rotscale/bin:/usr/local/go/bin:/home/rotscale/go/bin",
        "XDG_RUNTIME_DIR=/run/user/1000",
        "XMODIFIERS=@im=ibus",
        "SHELL=/usr/bin/zsh",
        "XDG_SESSION_TYPE=wayland",
        "HISTCONTROL=ignoredups",
        "USERNAME=rotscale",
        "EDITOR=/usr/bin/nano",
        "GDM_LANG=en_US.UTF-8",
        "XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.QLNN90",
        "SHLVL=1",
        "XDG_SESSION_CLASS=user",
        "TERM=xterm-256color",
        "GDMSESSION=gnome",
        "..."
      ]
    }
  ]
}
```

**Comment by michaelkatch** [comment]
I'll be more specific. Totally forgot to mention that it affects only tracee-rules.
When writing a signature on tracee rules I sometimes use "envp" argument. 
When I use "--input-tracee format:gob" I'm able to cast "envp" argument to ([]string).
But, while using "--input-tracee format:json" the casting does not work and another conversion needs to be made.

**Comment by grantseltzer** [comment]
How are you handling this extra conversion? I assume the root of this issue is that 'Value' is an interface{}, not a []string ([link](https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/external/external.go#L115)). I'm actually surprised it's not an issue with Gob format. Perhaps we can be more explicit with types of arguments in the event definition.

**Comment by grantseltzer** [comment]
The approach @itaysk takes here: https://github.com/aquasecurity/tracee/pull/988 is interesting and somewhat related. Perhaps we can provide API in the external package that uses json.RawMessage and checks types to properly cast the Value. 

Please do elaborate on how your doing "another conversion" though.

**Comment by itaysk** [comment]
> Perhaps we can provide API in the external package that uses json.RawMessage and checks types to properly cast the Value.

If I understood correctly what you say this is what we already do with our custom unmarshaler? Anyway for this issue, we probably just need to add a case to handle this conversation like you said

**Comment by roikol** [comment]
hey @grantseltzer,
i'll answer about the "another conversion":

when using `format:gob` we can convert like this: `envpArg.Value.([]string)`

when using `format:json` we have to convert to slice of interfaces, and then convert each elemnt to string. like this: `
envpInterfaces, _ := envpArg.Value.([]interface{})
for _, envInterface := range envpInterfaces{
    envString, _ := envInterface.(string)
    ........
}
`

**Comment by grantseltzer** [comment]
Ok, i'm able to reproduce this issue and i'm working on a fix.

**Comment by grantseltzer** [comment]
It seems that when the event is encoded in gob format, the type ([]string) is encoded with it, allowing gob decoder to treat it as the correct type. 

Would it be helpful to provide a helper function that will do this conversion for you (regardless of it's gob or json format)?

**Comment by grantseltzer** [comment]
I don't think that code is actually being used 


https://github.com/aquasecurity/tracee/blob/c81d97531b13bb067a011e98199de311afc2a591/tracee-rules/input.go#L71-L88

**Comment by itaysk** [comment]
it's being used when you `json.Unmarshal`

**Comment by grantseltzer** [comment]
Itay you're correct that c81d975 fixes the issue, we just haven't upgraded the external package in go.mod to take this into account. Fixing that now, see #1023
