### ISSUE TITLE
Change argument type in parseArgs() when required

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1029]
`prepareArgs()` may change the type of a given argument to a different type (for example, `flags` argument of type long may be change to type string to reflect the selected flags). This type change may cause issues when marshalling/unmarshalling the arguments and counting on a correct value of the argument type (see https://github.com/aquasecurity/tracee/pull/988#issuecomment-927364548).

A possible fix for this issue may be to change the type in external.ArgMeta when the value is changed in `prepareArgs()`. This can be done by passing the argMetas slice (used by `processEvents()`) as a pointer argument to `prepareArgs()`

**Comment by itaysk** [comment]
We've discussed in the past about always returning the raw values instead of the "pretty" values in all the output modes except table. I think that might be a better solution to this problem as well, WDYT? Now that the printers are available to the consumer via libbpfgo they can "print" them if they want.

**Comment by yanivagman** [comment]
> We've discussed in the past about always returning the raw values instead of the "pretty" values in all the output modes except table. I think that might be a better solution to this problem as well, WDYT? Now that the printers are available to the consumer via libbpfgo they can "print" them if they want.

Yes, I thought about it too when I killed the events pipeline.
The thing is, that in the event pipeline we decode the arguments into an arguments map (maps argument name to value), which is also given as an argument to `prepareArgs()` to easily look and replace arguments of a given event. If we will take `prepareArgs()` out of `processEvents()` into main, then we will either need to recreate the arguments map, or use the `external.Argument` slice (which is ordered by the argument index) where we will have to iterate the slice everytime we want to find some specific argument.

**Comment by itaysk** [comment]
> If we will take prepareArgs() out of processEvents() into main,

I didn't say we need to do this.. we just need to wrap the translation code in with a flag which is turned on only if output=table

**Comment by yanivagman** [comment]
I think that table printer shouldn't be any different from other printers. Maybe we should have output option:pretty instead?

**Comment by itaysk** [comment]
yes.. this is what I meant what I said to wrap the code with a flag which is tuned on when output=table

> we want pretty printing to be enabled by default (as this is the current state)

only for table. every other mode won't need this.
I think we can do option:pretty which will be turned on by default when format:table

**Comment by rafaeldtinoco** [comment]
I'm +1 on having pretty print by default only for table (like we do) and keeping regular types for other printers (like json, fixing the unmarshaling).

**Comment by yanivagman** [comment]
Whether we choose to have the same (default) behavior for all printers or not,  I think that prepareArgs(), used for pretty print, should also change the type of the argument where necessary
