### ISSUE TITLE
Add ctime container creation to tracee-ebpf event

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#1075]

**Comment by mtcherni95** [comment]
we would like tracee-ebpf to output also the ctime of the container creation once an event happens. this is because we would like to compare the time of container creation vs (for example) the time a file is created and executed inside the container.

**Comment by mtcherni95** [comment]
we could be aware of container creation by maybe checking process id = 1 and execv to runc and save timestamp, however this would be done with a signature and at user level, not sure that it's what we want.

**Comment by yanivagman** [comment]
Exactly. This is why we need to better define this task.
I understand the benefit of adding ctime, as well as other metadata of an executable.
But I don't think it should be related to "container creation", but maybe to process execution.
So, a good place for adding ctime might be sched_process_exec event, I think.
Then, tracee-rules can use this data however it wants, for example, when a "container created" signature is triggered.
