### ISSUE TITLE
Tweak TRC-8 to be less noisy

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#1085]
**User story**:
Currently, TRC-8 can be noisy with a lot of processes that are genuine but can trigger this signature.

**Acceptance Criteria:**
TRC-8 is has a better signal to noise ratio.

**Ideas:**
Maybe we expand the list of "safe" processes to the following: etcd, apiserver, coredns, kube-controller in addition to what's out there  today.

List is found here: https://github.com/aquasecurity/tracee/blob/main/tracee-rules/signatures/rego/k8s_service_account_token.rego#L40

**Comment by yanivagman** [comment]
@roikol can we close this now that #1118 is merged?

**Comment by itaysk** [comment]
cc: @raesene

**Comment by raesene** [comment]
I think that'll help for sure :) Ultimately any white-list solution here is unlikely to be perfect, as different k8s distros/CNI provers etc will make use of service account tokens.

However, I think a better solution would be tricky to implement (essentially, it'd need to be able to dynamically pull information from the k8s API on what services were running and then use that to inform which binaries should be white-listed), so from the perspective of this issue it seems fine.
