### ISSUE TITLE
Improve serialization between tracee-ebpf and tracee-rules

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1099]
As pointed out in https://github.com/aquasecurity/libbpfgo/issues/42#issuecomment-932912172, our current bottleneck is the event printer, whether it's gob/json used.

Here is a possible direction:
As raw tracee events coming from the kernel are decoded with binary decoder (https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/events.go#L42) I thought it might be possible to use it as an encoder as well. This should be possible because `processEvents()` decodes the event received from the kernel for some basic processing (e.g. capture executalbes) and event arguments enrichment using prepareArgs. Most of the data in external.Event is not changed from what we receive from the kernel, but the event arguments, which shouldn't be a problem to encode with encoding/binary package as well. So I believe that using encoding/binary to encode events in tracee-ebpf and decoding it in tracee-rules will have a better performance than using json/gob

**Comment by rafaeldtinoco** [comment]
With the work of @NDStrahilevitz and @mtcherni95, I believe this issue can be closed (on behalf of more specific performance issues they're addressing). WDYT @mtcherni95 ? If you and @yanivagman agree, could you close this one ?

**Comment by NDStrahilevitz** [comment]
Actually, when I pprofed the OS case of piping tracee-ebpf to tracee-rules, encoding and decoding was a significant drawback compared to the channel connected version. 
I definitely think there's room to improve here (unless we're going to move to a single binary version as the official OS release).

**Comment by yanivagman** [comment]
The new tracee experience uses one binary and channels
