### ISSUE TITLE
Combine accept event and security_socket_accept to detailed connection event

### ISSUE THREAD

**Issue by michaelkatch** [aquasecurity/tracee#1115]
Hey,
At the moment, "security_socket_accept" outputs the local address information while "accept"/"accept4" events output the remote address.
I would like to have a combination of those two events to monitor who connected to the machine and from what address.

For example in the following picture - I opened netcat and listened on port 7777 . On another shell (on the same machine) I initiated a connection to to port 7777.
![image](https://user-images.githubusercontent.com/70207874/139026751-e966778e-8990-4ed8-acdc-0f42b60eed22.png)

**Comment by yanivagman** [comment]
We can implement a mechanism to enrich events with ebpf tail calls.
For example, here, if enrichment is chosen (can be a "high level event" like @itaysk described in #1105), then sys_exit won't submit the accept/accept4 event, but will call a tail call that will add any enrichment data (e.g. local address), and send the original event with the enriched data (as additional arguments).

**Comment by yanivagman** [comment]
Already fixed by #1758
