### ISSUE TITLE
Failed to create kprobe perf event: no such file or directory

### ISSUE THREAD

**Issue by jacobwgillespie** [aquasecurity/tracee#1119]
Hi, I am trying to use Tracee inside Kata Containers - this involves running the Kata Containers VM with a custom-compiled kernel that enables BTF. I almost have everything working, with a few remaining issues...

Most tracing events work, however it appears the `security_socket_*` kprobe events fail to attach:

```
/tracee # ./tracee-ebpf --debug
OSInfo: ID: alpine
OSInfo: VERSION_ID: 3.14.2
OSInfo: PRETTY_NAME: "Alpine Linux v3.14"
OSInfo: KERNEL_RELEASE: 5.10.25
BTF: bpfenv = false, btfenv = false, vmlinux = true
BPF: using embedded BPF object
unpacked CO:RE bpf object file into memory
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
libbpf: kprobe perf_event_open() failed: No such file or directory
libbpf: prog 'trace_security_socket_accept': failed to create kprobe 'security_socket_accept' perf event: No such file or directory
2021/10/31 23:06:06 error creating Tracee: error attaching event security_socket_accept: failed to attach security_socket_accept k(ret)probe to program trace_security_socket_accept: no such file or directory
```

I assume this error is related to some kernel misconfiguration on my end, but I've been having trouble tracking down what exactly is breaking here. Is there a kernel config option or mount or param I'm missing for that event type? Might you have any guidance on what could cause this error, or what the next debugging step would be?

🔗 my [kernel config](https://gist.github.com/jacobwgillespie/8a9b719c80ed4fdbc74e100812f0174d)

**Comment by yanivagman** [comment]
I think CONFIG_SECURITY_NETWORK is what you are missing here: https://elixir.bootlin.com/linux/latest/source/include/linux/security.h#L1375

**Comment by jacobwgillespie** [comment]
That was exactly it, thank you @yanivagman! 🎉
