### ISSUE TITLE
Plugin was built with a different version of package internal/cpu

### ISSUE THREAD

**Issue by pomozoff** [aquasecurity/tracee#1120]
I'm newbie in Docker & Golang
I use this [doc](https://aquasecurity.github.io/tracee/dev/rules-authoring/)
I've built an image using this **Dockerfile**:
```
FROM aquasec/tracee:latest
COPY --from=golang:1.17.2-alpine /usr/local/go/ /usr/local/go/
ENV PATH="/usr/local/go/bin:${PATH}"
ENTRYPOINT ["/tracee/entrypoint.sh"]
```
I created a Go project
I successfully built [the stdio_over_socket.go with export.go](https://github.com/aquasecurity/tracee/tree/main/tracee-rules/signatures/golang) using next command: `go build -buildmode=plugin -o my_plugin.so *.go`
However, tracee cannot load my plugin:
```
2021/11/02 12:45:11 error opening plugin /rules/1.17/my_plugin.so: plugin.Open("/rules/1.17/my_plugin"): plugin was built with a different version of package internal/cpu
Loaded 0 signature(s): []
```
Could you point me what I'm doing wrong?

**Comment by mtcherni95** [comment]
Hi! maybe you compiled the signature shared object in an env with go version/packages different than the one used by tracee-rules?

**Comment by pomozoff** [comment]
Hi! Yes, it could be, but I have no idea what Golang version was used to build `tracee-rules` binary
So I prepared two images of tracee v0.6.3 with golang 1.17.2 & 1.16.9
When I try to use the plugin built with golang 1.16 I see the next error:
`2021/11/02 13:08:25 error opening plugin /rules/1.16/my_plugin.so: plugin.Open("/rules/1.16/my_plugin"): plugin was built with a different version of package github.com/aquasecurity/tracee/tracee-ebpf/external`
That, I think, is worse than the previous one

**Comment by mtcherni95** [comment]
tracee-rules uses go 1.16 if I'm not wrong. Maybe @itaysk can clarify here.

**Comment by pomozoff** [comment]
Thanks. I've found an article about [go plugins](https://www.reddit.com/r/golang/comments/b6h8qq/is_anyone_actually_using_go_plugins/)
It seems like I need more details about the environment where tracee was built. At least I need full version of golang used to build `tracee-rules` - 1.16.?

**Comment by yanivagman** [comment]
We currently use go 1.16 but might move to 1.17 soon:
https://github.com/aquasecurity/tracee/pull/1084

The error you got with 1.16
`2021/11/02 13:08:25 error opening plugin /rules/1.16/my_plugin.so: plugin.Open("/rules/1.16/my_plugin"): plugin was built with a different version of package github.com/aquasecurity/tracee/tracee-ebpf/external`
might imply that your external package go module is of different version from what was used to build tracee-rules, which you can check here:
https://github.com/aquasecurity/tracee/blob/main/tracee-rules/go.mod#L7

**Comment by pomozoff** [comment]
I see, thank you

**Comment by itaysk** [comment]
possibly related to #1312
