### ISSUE TITLE
Don't use (compilation time) LINUX_VERSION_CODE variable for CO-RE builds

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1132]
`LINUX_VERSION_CODE` is used in the bpf code in several places.
One example is:
```
#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 6, 0))
    /* kernel 4.18-5.5:

    this is a workaround for reading sk_protocol bit-field, because bpf_probe_read doesn't really support reading
    this type of fields. so we use the sk_gso_max_segs field and go 24 bits backwards (i.e. 3 bytes) because
    sk_type is 16 bits, and sk_protocol is 8 bits (i.e. 1 byte).

    note: we define protocol as u16 so it'll be compatible with newer kernels.
    */

    u16 protocol = 0;
    bpf_probe_read(&protocol, 1, (void *)(&sock->sk_gso_max_segs) - 3);

    return protocol;
#else
    // kernel 5.6 onwards:
    return READ_KERN(sock->sk_protocol);
#endif
```

For CO-RE bpf code, however, there is no meaning for the linux kernel version used to compile the CO-RE artifact as it can be used on different linux kernel versions.
So in the above example, if we build the CO-RE artifact on linux 5.7 but run it on 5.4 kernel - this will actually be a bug!

The fix for CO-RE builds is to use `extern u32 LINUX_KERNEL_VERSION __kconfig;` , checking the version in runtime (see Andrii's blog: https://facebookmicrosites.github.io/bpf/blog/2020/02/19/bpf-portability-and-co-re.html)

**Comment by rafaeldtinoco** [comment]
**Note**: we've decided to use "type checks", instead of relying in the `externs` provided by libbpf kconfig relocations. (It has been discussed at: https://github.com/aquasecurity/tracee/pull/1130#issuecomment-973836497 and warned that kernels bellow < 5.5 could face dead branch non-elimination issue).

**Comment by rafaeldtinoco** [comment]
I'm able to run CO-RE ebpf object in a 5.0.0 kernel (5.0.0-38):

```
$ sudo TRACEE_BTF_FILE=/5.0.0-38-generic.btf ./dist/tracee-ebpf --debug --trace event=openat,openat2
OSInfo: ID_LIKE: debian
OSInfo: PRETTY_NAME: "Ubuntu 18.04.6 LTS"
OSInfo: VERSION_ID: "18.04"
OSInfo: VERSION_CODENAME: bionic
OSInfo: KERNEL_RELEASE: 5.0.0-38-generic
OSInfo: ARCH: x86_64
OSInfo: VERSION: "18.04.6 LTS (Bionic Beaver)"
OSInfo: ID: ubuntu
BTF: bpfenv = false, btfenv = true, vmlinux = false
BPF: using embedded BPF object
BTF: using BTF file from environment: /5.0.0-38-generic.btf
unpacked CO:RE bpf object file into memory
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
libbpf: Error loading BTF: Invalid argument(22)
libbpf: magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
type_off: 0
type_len: 60928
str_off: 60928
str_len: 88110
btf_total_size: 149062
Invalid string section
libbpf: Error loading .BTF into kernel: -22. BTF is optional, ignoring.
22:43:12:981137  1000   ls               1433    1433    3                openat               dirfd: -100, pathname: /etc/ld.so.cache, flags: O_RDONLY|O_CLOEXEC, mode: 0
22:43:12:981226  1000   ls               1433    1433    3                openat               dirfd: -100, pathname: /lib/x86_64-linux-gnu/libselinux.so.1, flags: O_RDONLY|O_CLOEXEC, mode: 0
22:43:12:981447  1000   ls               1433    1433    3                openat               dirfd: -100, pathname: /lib/x86_64-linux-gnu/libc.so.6, flags: O_RDONLY|O_CLOEXEC, mode: 0
```

But I am not able to run CO-RE object in a v4.18 kernel:

```
76: (63) *(u32 *)(r10 -88) = r6
77: (bf) r1 = r10
78: (07) r1 += -88
79: (b7) r2 = 4
80: (85) call bpf_probe_read#4
81: (61) r9 = *(u32 *)(r10 -88)
82: (7b) *(u64 *)(r10 -88) = r6
83: (85) call unknown#195896080
invalid func unknown#195896080
```

@yanivagman I wonder if we ever tested CO-RE object in v4.19 kernels and, if so, lately ?

**Comment by rafaeldtinoco** [comment]
This commit disables the LINUX_VERSION_CODE variable usage for CORE:

https://github.com/aquasecurity/tracee/pull/1159/commits/be147b207bacc1086d093f2a6f0be8a7558ce380

And we could rely in type based checks like:

https://github.com/aquasecurity/tracee/pull/1159/commits/bc2033733f22963743429aaf393df5e39b9e6ffc

Nevertheless, I wonder why v4.18 CO-RE is not working, will have to check (so I have a correct environment to test type based checks for those versions to be able to run tracee's eBPF CO-RE object).

**Comment by rafaeldtinoco** [comment]
With the introduction of slim vmlinux.h file (being made at https://github.com/aquasecurity/tracee/pull/1160) we will be able to address the type checks need for this bug right after.

**Comment by rafaeldtinoco** [comment]
@yanivagman I've address this fix in:

https://github.com/aquasecurity/tracee/pull/1160

together with the slim header implementation (as it made sense).

**Comment by rafaeldtinoco** [comment]
The type check made for sock->sk_prototocol fix is also good when done by btfgen:

kernel v5.4:
```
[75] STRUCT 'sock' size=760 vlen=4
        '__sk_common' type_id=69 bits_offset=0
        'sk_protocol' type_id=81 bits_offset=4232 bitfield_size=8
        '__sk_flags_offset' type_id=113 bits_offset=4224
        'sk_gso_max_segs' type_id=115 bits_offset=4256
```

kernel v5.13:
```
[137] STRUCT 'sock' size=760 vlen=3
        '__sk_common' type_id=124 bits_offset=0
        'sk_gso_max_segs' type_id=13 bits_offset=4272
        'sk_protocol' type_id=13 bits_offset=4256
```
