### ISSUE TITLE
Use a slim header instead of vmlinux.h

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1133]
As per Andrii's blog (https://nakryiko.com/posts/bpf-core-reference-guide/#defining-own-co-re-relocatable-type-definitions) we don't really need vmlinux.h to make CO-RE work. Instead, we can tailor our own header file for CO-RE, and use it instead.

Some benefits for doing this:
1. vmlinux.h is huge. We now have one such header for x86, and another one for arm64, but there is no actual need for this.
2. Having a header which only contains the types needed by tracee simplifies its maintainance. For example, we can then have just one header for all architectures, making only the relevant architecture specific structs (e.g. pt_regs) guarded by compilation flags.
3. If a struct's field is changed between different kernel versions, we can use struct flavors, as suggested in Andrii's blog

**Comment by rafaeldtinoco** [comment]
@yanivagman 

A ~500 line vmlinux.h that allows compilation BUT doesn't work (runtime relocations fail):
https://gist.github.com/rafaeldtinoco/178553edf0eb75e6dab787b08302eeb4

A ~5000 line vmlinux.h that allows compilation AND works:
https://gist.github.com/rafaeldtinoco/bbaaaa029b9f1da20ec8abe1fe7fb09f

The difference:

The smaller version was created from the relocation information contained in BTF.EXT section of tracee.bpf.o. I think the fields are out of order (because of btfgen, not sure this is a problem) and there are missing fields (since they're not used in relocations, not sure this is a problem also).

The bigger version was created from ALL BTF types information of tracee.bpf.o and considers padding, field ordering and includes more fields than the ones being directly used.

I **think** that the ~500 line version should work IF we fix all the CO-RE related calls in tracee.bpf.c, but that is just theory. 

WDYT ?

**Comment by yanivagman** [comment]
Thanks Rafael.
Can you please provide the error message received with the ~500 lines header?
Also, on which environment does it fail?

Maybe we can add the missing parts manually

**Comment by rafaeldtinoco** [comment]
> Thanks Rafael. Can you please provide the error message received with the ~500 lines header? Also, on which environment does it fail?
> 
> Maybe we can add the missing parts manually

I don't think its about missing parts, but about CO-RE capability of using partial struct types and missing members. I created a draft at:

https://github.com/aquasecurity/tracee/pull/1160

and the commit https://github.com/aquasecurity/tracee/pull/1160/commits/6c587e209a25d6d8b4f1a19be7f3680578a0a875 

has 2 files:

- vmlinux-core.h (~600 lines)
- vmlinux-core-complete.h (~5000 lines)

the "vmlinux-core-complete.h" was generated from the BTF contained in a compiled tracee.bpf.core.o (so it contains all types and members/fields). the smaller version was created by parsing used types only.

The error for the smaller vmlinux.h is:

```
regs=4 stack=0 before 962: (77) r2 >>= 32
regs=4 stack=0 before 961: (67) r2 <<= 32
regs=4 stack=0 before 960: (07) r2 += 1
regs=4 stack=0 before 959: (61) r2 = *(u32 *)(r10 -168)
966: (bf) r3 = r10
; if (bpf_probe_read(&(data->submit_p->buf[data->buf_off+1]), size, ptr) == 0) {
967: (07) r3 += -160
; if (bpf_probe_read(&(data->submit_p->buf[data->buf_off+1]), size, ptr) == 0) {
968: (b7) r2 = 4
969: (85) call bpf_probe_read#4
 R0=map_value(id=0,off=0,ks=4,vs=4,imm=0) R1_w=map_value(id=0,off=0,ks=4,vs=32768,umax_value=32768,var_off=(0x0; 0xffffffff)) R2_w=inv4 R3_w=fp-160 R6=fp-256 R7=ctx(id=0,off=0,imm=0) R8=fp-220 R9=map_value_or_null(id=14,off=0,ks=4,vs=4,imm=0) R10=fp0 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=???????m fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=00000000 fp-104=00000000 fp-112=00000000 fp-120=00000000 fp-128=00000000 fp-136=00000000 fp-144=00000000 fp-152=mmmmmmmm fp-160=0000mmmm fp-168=0000mmmm fp-176=map_value fp-184=ctx fp-192=00000000 fp-200=00000000 fp-208=0000mmmm fp-216=mmmmmmmm fp-224=mmmmmmmm fp-232=mmmmmmmm fp-240=mmmmmmmm fp-248=mmmmmmmm fp-256=mmmmmmmm fp-264=mmmmmmmm fp-272=mmmmmmmm fp-280=mmmmmmmm fp-288=mmmmmmmm fp-296=mmmmmmmm fp-304=ctx fp-312=fp fp-320=fp fp-328=mmmmmmmm
invalid access to map value, value_size=32768 off=32768 size=4
R1 max value is outside of the allowed memory range
processed 580 insns (limit 1000000) max_states_per_insn 0 total_states 41 peak_states 41 mark_read 37
```

**Comment by rafaeldtinoco** [comment]
Based on Andrii's documents, and CO-RE, if we solve:

https://github.com/aquasecurity/tracee/issues/898

it might be easier to get the smaller version to work (as it is fully dependent of field offsets, since all types will have missing fields/members).

WDYT ?

**Comment by rafaeldtinoco** [comment]
I'm working in reducing the 5k vmlinux header file (making sure tracee is able to run). Hopefully we can get something around 1 or 2k lines and then debug the CO-RE issue above.

**Comment by rafaeldtinoco** [comment]
@yanivagman could you please check my PR and tests (comments in the PR) so we can address this issue (and I can use this to fix issue https://github.com/aquasecurity/tracee/issues/898 as now we have full CO-RE vmlinux header file enabled).

**Comment by rafaeldtinoco** [comment]
I have address this fix at:

https://github.com/aquasecurity/tracee/pull/1160

together with the fix for LINUX_VERSION_CODE dependency.

**Comment by yanivagman** [comment]
> The error for the smaller vmlinux.h is:
> 
> ```
> regs=4 stack=0 before 962: (77) r2 >>= 32
> regs=4 stack=0 before 961: (67) r2 <<= 32
> regs=4 stack=0 before 960: (07) r2 += 1
> regs=4 stack=0 before 959: (61) r2 = *(u32 *)(r10 -168)
> 966: (bf) r3 = r10
> ; if (bpf_probe_read(&(data->submit_p->buf[data->buf_off+1]), size, ptr) == 0) {
> 967: (07) r3 += -160
> ; if (bpf_probe_read(&(data->submit_p->buf[data->buf_off+1]), size, ptr) == 0) {
> 968: (b7) r2 = 4
> 969: (85) call bpf_probe_read#4
>  R0=map_value(id=0,off=0,ks=4,vs=4,imm=0) R1_w=map_value(id=0,off=0,ks=4,vs=32768,umax_value=32768,var_off=(0x0; 0xffffffff)) R2_w=inv4 R3_w=fp-160 R6=fp-256 R7=ctx(id=0,off=0,imm=0) R8=fp-220 R9=map_value_or_null(id=14,off=0,ks=4,vs=4,imm=0) R10=fp0 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=???????m fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=00000000 fp-104=00000000 fp-112=00000000 fp-120=00000000 fp-128=00000000 fp-136=00000000 fp-144=00000000 fp-152=mmmmmmmm fp-160=0000mmmm fp-168=0000mmmm fp-176=map_value fp-184=ctx fp-192=00000000 fp-200=00000000 fp-208=0000mmmm fp-216=mmmmmmmm fp-224=mmmmmmmm fp-232=mmmmmmmm fp-240=mmmmmmmm fp-248=mmmmmmmm fp-256=mmmmmmmm fp-264=mmmmmmmm fp-272=mmmmmmmm fp-280=mmmmmmmm fp-288=mmmmmmmm fp-296=mmmmmmmm fp-304=ctx fp-312=fp fp-320=fp fp-328=mmmmmmmm
> invalid access to map value, value_size=32768 off=32768 size=4
> R1 max value is outside of the allowed memory range
> processed 580 insns (limit 1000000) max_states_per_insn 0 total_states 41 peak_states 41 mark_read 37
> ```

Just out of interest - what was the problem here?

**Comment by rafaeldtinoco** [comment]
> > The error for the smaller vmlinux.h is:
> > ```
> > regs=4 stack=0 before 962: (77) r2 >>= 32
> > regs=4 stack=0 before 961: (67) r2 <<= 32
> > regs=4 stack=0 before 960: (07) r2 += 1
> > regs=4 stack=0 before 959: (61) r2 = *(u32 *)(r10 -168)
> > 966: (bf) r3 = r10
> > ; if (bpf_probe_read(&(data->submit_p->buf[data->buf_off+1]), size, ptr) == 0) {
> > 967: (07) r3 += -160
> > ; if (bpf_probe_read(&(data->submit_p->buf[data->buf_off+1]), size, ptr) == 0) {
> > 968: (b7) r2 = 4
> > 969: (85) call bpf_probe_read#4
> >  R0=map_value(id=0,off=0,ks=4,vs=4,imm=0) R1_w=map_value(id=0,off=0,ks=4,vs=32768,umax_value=32768,var_off=(0x0; 0xffffffff)) R2_w=inv4 R3_w=fp-160 R6=fp-256 R7=ctx(id=0,off=0,imm=0) R8=fp-220 R9=map_value_or_null(id=14,off=0,ks=4,vs=4,imm=0) R10=fp0 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=???????m fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=00000000 fp-104=00000000 fp-112=00000000 fp-120=00000000 fp-128=00000000 fp-136=00000000 fp-144=00000000 fp-152=mmmmmmmm fp-160=0000mmmm fp-168=0000mmmm fp-176=map_value fp-184=ctx fp-192=00000000 fp-200=00000000 fp-208=0000mmmm fp-216=mmmmmmmm fp-224=mmmmmmmm fp-232=mmmmmmmm fp-240=mmmmmmmm fp-248=mmmmmmmm fp-256=mmmmmmmm fp-264=mmmmmmmm fp-272=mmmmmmmm fp-280=mmmmmmmm fp-288=mmmmmmmm fp-296=mmmmmmmm fp-304=ctx fp-312=fp fp-320=fp fp-328=mmmmmmmm
> > invalid access to map value, value_size=32768 off=32768 size=4
> > R1 max value is outside of the allowed memory range
> > processed 580 insns (limit 1000000) max_states_per_insn 0 total_states 41 peak_states 41 mark_read 37
> > ```
> 
> Just out of interest - what was the problem here?

By try-n-attempt I found out the 2 structs with TODO of being turned CO-RE capable (in the new slim vmlinux header file change). By having them as they are I'm not facing this issue, which I opened the issue: https://github.com/aquasecurity/tracee/issues/1172 to investigate.
