### ISSUE TITLE
Adding gRPC server to tracee-ebpf

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#1136]
I think would be nice if tracee-ebpf could be configured to output its events to a remote server. I suggest gRPC as communication framework/protocol.

**Comment by yanivagman** [comment]
I don't think it should be the responsibilty of tracee-ebpf to send its events to a remote server.
A consumer of tracee-ebpf can take the output and send it to a remote server.

On the other hand, I did have adding gRPC server in mind that will enable an external user to add/remove events/filters or change other configurations of tracee in runtime

**Comment by mtcherni95** [comment]
Yeah, I see what you mean - sounds good to me! tracee-ebpf can simply output the events as does today (either to stdout or a channel) and then the application will read from it and if needed then flush to a server. Just note that by running tracee-ebpf alone this won't be possible and a user will have to wrap it within his app - which is ok IMO.

Regarding adding gRPC server in tracee-ebpf in order to get configurations, sounds a good idea to me.

**Comment by itaysk** [comment]
seems like you agreed to not pursue this issue. regarding configuration server - definitely something we need, but not sure we want it as GRPC server, that will limit it's accessibility. anyway, this is now probably a dup of https://github.com/aquasecurity/tracee/issues/636 so let's discuss there?
