### ISSUE TITLE
tracee-ebpf should check that /proc/sys/kernel/ftrace_enabled is '1' (enabled) 

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#1150]

**Comment by mtcherni95** [comment]
after chatting with @yanivagman and @rafaeldtinoco , maybe this issue should be in libbpfgo.

**Comment by mtcherni95** [comment]
should we enable (set it to '1') it if at start-up we see that ftrace_enabled is '0'? or just report a warning? @yanivagman

**Comment by yanivagman** [comment]
@mtcherni95 ftrace_enabled is set to 1 by default:
https://01.org/linuxgraphics/gfx-docs/drm/trace/ftrace.html#ftrace-enabled

If the user chose to set it to 0, there might be a reason for that (although I can't think of a reason why someone who is running tracing programs will ever set this value to 0) - let's warn in that case.

**Comment by mtcherni95** [comment]
> @mtcherni95 ftrace_enabled is set to 1 by default:
> 
> https://01.org/linuxgraphics/gfx-docs/drm/trace/ftrace.html#ftrace-enabled
> 
> 
> 
> If the user chose to set it to 0, there might be a reason for that (although I can't think of a reason why someone who is running tracing programs will ever set this value to 0) - let's warn in that case.

Sounds good to me.
