### ISSUE TITLE
backporting of kernel cause mismatching enums

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1151]
Ubuntu are using backporting on the linux kernel, which changes some enums (for example of the kernel_module loading).
This causes a mismatch from the expected enum (due to the kernel version) to the actual enum (which was changed in the backporting).

To overcome this issue we should use BTF in enums as well.

**Comment by yanivagman** [comment]
@rafaeldtinoco

**Comment by rafaeldtinoco** [comment]
I'm sorry, could you clarify the request.. it wasn't clear to me. Are you saying we need to support "enum based relocations" in "tailored btfs" generation ? Or is this something else ? 

Could you provide examples of the code and issues you're facing ?

**Comment by AsafEitani** [comment]
So we're trying to print the parsed id of a low level file load into the kernel (for instance kernel module, firmware, etc)
We're doing that by using the `id` parameter of the `security_kernel_read_file` function and matching it with the expected name (by kernel version) listed in this enum - https://elixir.bootlin.com/linux/v5.8/source/include/linux/fs.h#L2996
The problem occurs when there is backporting and the enum we expect doesn't match the actual enum.
For example on Ubuntu 20.10 kernel version 5.8, everytime a kernel module is loaded - the event that is generated says that a  firmware was loaded instead of kernel module.

**Comment by yanivagman** [comment]
We should avoid using internal kernel enums that are not exported to userspace, exactly for this reason.
A better approach will be to use CO-RE enum existance checks, and check for equality in bpf code:
https://nakryiko.com/posts/bpf-core-reference-guide/#bpf-core-enum-value-exists

**Comment by rafaeldtinoco** [comment]
Currently BTFGEN is capable of doing all libbpf supported relocations so this can be closed IMO. Also, what @yanivagman said makes total sense regarding using CO-RE enum helpers and check for equality.
