### ISSUE TITLE
Tracee-ebpf missing arguments

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1158]
Some events doesn't have the "syscall" and "argv" arguments (tracee was invoked with detect-syscall flag) - happens on `security_file_open` and `sched_process_exec` the invoking processes all seems to be kworkers:
![image](https://user-images.githubusercontent.com/54033369/143286560-619c74d4-289a-4c89-9cce-37e73eca3d08.png)
![image](https://user-images.githubusercontent.com/54033369/143286712-6659471c-9477-49a9-b8ac-d0d207ff313f.png)

**Comment by yanivagman** [comment]
kworkers are not started by a userspace process, thus don't have an originating syscall.
argv pointers (mm->arg_start and mm->arg_end) are also invalid for kworkers.

Closing this as invalid
