### ISSUE TITLE
tracee-ebpf: networking structs can't CO-RE

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1172]
During the development of the slim vmlinux header, we have found out that the following 2 structs can't be reduced (to take advantage of CO-RE access index feature only):

```C
// TODO: can't CO-RE __sk_buff (check)

struct __sk_buff {
        __u32 len;
        __u32 pkt_type;
        __u32 mark;
        __u32 queue_mapping;
        __u32 protocol;
        __u32 vlan_present;
        __u32 vlan_tci;
        __u32 vlan_proto;
        __u32 priority;
        __u32 ingress_ifindex;
        __u32 ifindex;
        __u32 tc_index;
        __u32 cb[5];
        __u32 hash;
        __u32 tc_classid;
        __u32 data;
        __u32 data_end;
        __u32 napi_id;
        __u32 family;
        __u32 remote_ip4;
        __u32 local_ip4;
        __u32 remote_ip6[4];
        __u32 local_ip6[4];
        __u32 remote_port;
        __u32 local_port;
        __u32 data_meta;
        union {
                struct bpf_flow_keys *flow_keys;
        };
        __u64 tstamp;
        __u32 wire_len;
        __u32 gso_segs;
        union {
                struct bpf_sock *sk;
        };
        __u32 gso_size;
};

and

struct iphdr {
        __u8 ihl: 4;
        __u8 version: 4;
        __u8 tos;
        __be16 tot_len;
        __be16 id;
        __be16 frag_off;
        __u8 ttl;
        __u8 protocol;
        __sum16 check;
        __be32 saddr;
        __be32 daddr;
};
```

That might happen because of pointer arithmetics using specific offsets (or something similar). Needs investigation.

**Comment by yanivagman** [comment]
As described in #1193 I don't think that we want to reduce struct iphdr.

I also think that the problem you encountered with __sk_buff is related to the fact that we need to bound check access to a packet, and removing fields might cause out of bounds access (this is why we use skb_revalidate_data() in our bpf code).

So, let's keep both structs with full definition?

**Comment by rafaeldtinoco** [comment]
Yes, it makes sense. I found that v4.18 CO-RE (with needed fixes) also fails because of the sizeof of incomplete BTF types. We can close this one, I'll document findings in the v4.18, v4.19 CORE issue.
