### ISSUE TITLE
Build fails due to dockerhub rate limiting

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#1188]
```
Sending build context to Docker daemon  19.58MB
Step 1/24 : ARG BASE=fat
Step 2/24 : FROM alpine:3.15 as builder
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
make: *** [Makefile:63: docker] Error 1
```

Authenticating to dockerhub might help but is still limited.

**Comment by simar7** [comment]
With Trivy we benefitted from GHCR. Could we use it in Tracee as well?

**Comment by itaysk** [comment]
can you elaborate? did you copy your base images to GHCR? how do you keep them up to date? GHCR doesn't have limits?

**Comment by rafaeldtinoco** [comment]
Closed by: https://github.com/aquasecurity/tracee/pull/2872/commits/c44947fd1000afd3291111d2da4fa3da1e9be77c
