### ISSUE TITLE
errors from security_socket_connect

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#1189]
```
failed to read argument 1 of event security_socket_connect: error parsing sockaddr_in: error reading byte array: unexpected EOF
2021/12/01 14:09:51 error handling event by signature Standard Input/Output Over Socket: argument remote_addr not found
```

**Comment by itaysk** [comment]
Thanks to @roikol for debugging, seems related to #1160 missing padding in sockaddr

**Comment by yanivagman** [comment]
> Thanks to @roikol for debugging, seems related to #1160 missing padding in sockaddr

Ok, so I think I understand what is going on here.
It is not directly related to padding but to the fact that the slim header doesn't include all the fields of a struct, but only those we access. For this reason, whenever we use the sizeof operator in the bpf code, we get the wrong size (in this case, it is the size of the socket struct). But the problem is actually not specific to sockaddr, but for every struct which we wrap with sizeof.

**Comment by rafaeldtinoco** [comment]
> > Thanks to @roikol for debugging, seems related to #1160 missing padding in sockaddr
> 
> Ok, so I think I understand what is going on here. It is not directly related to padding but to the fact that the slim header doesn't include all the fields of a struct, but only those we access. For this reason, whenever we use the sizeof operator in the bpf code, we get the wrong size (in this case, it is the size of the socket struct). But the problem is actually not specific to sockaddr, but for every struct which we wrap with sizeof.

That is actually something important for CO-RE. I wonder if there is a helper to get size of full complex BTF types if we're not declaring them entirely. OR we should avoid using sizeof() for complex types in order not to have this problem.

**Comment by yanivagman** [comment]
> That is actually something important for CO-RE. I wonder if there is a helper to get size of full complex BTF types if we're not declaring them entirely. OR we should avoid using sizeof() for complex types in order not to have this problem.

See #1193

**Comment by yanivagman** [comment]
Fixed by #1190

**Comment by itaysk** [comment]
@rafaeldtinoco remember this for the next talk about CO-RE lessons ;)

**Comment by rafaeldtinoco** [comment]
@itaysk created a CO-RE Lessons tag so we can track those cases when going to present (very valuable to keep track of those specific issues/PRs).
