### ISSUE TITLE
aio.rego is copied to the dist/rules/ directory

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/tracee#1199]
The `./tracee-rules/signatures/rego/regosig/aio.rego` is supposed to be embedded in Go binary and used internally by `aio.go`. We should not copy it to the `dist/rules/aio.rego`

**Comment by simar7** [comment]
Fixed with https://github.com/aquasecurity/tracee/commit/11c1b21e8164c8ca523ac4e17d80b442609d4666
