### ISSUE TITLE
tracee-ebpf events pid field read incorrectly

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1201]
In a recent update (changing to a slim header) the pid field of events is read incorrectly.
Tested on ubuntu 20.10 kernel version 5.8.
The change happened somewhere between commit c82f5470e71c4a077fa7273c19b2524aa16eb4ee and 74ad130a3e9f63e0500d7ea69693bfd6f07d4be1 (including both)

Attached is the ebpf events in json format of those events with pid 0:
[pid_0_bug.zip](https://github.com/aquasecurity/tracee/files/7655624/pid_0_bug.zip)

**Comment by yanivagman** [comment]
@AsafEitani can you please verify that #1203 fixes this issue for you?

**Comment by AsafEitani** [comment]
Yes, that change fixed the issue, Thanks!
