### ISSUE TITLE
Adding assignment of default values to events in tracee-ebpf

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1204]
We expect events arguments coming from tracee-ebpf to match their definitions in `consts.go`.
Sometime those arguments are not populated due to configuration or technical reasons (#1158)

This creates a state in which the received event doesn't necessarily has the expected fields, which in turn makes tracee-ebpf to be less predictable and make automations harder.
Also using those fields in tracee-rules means checking if the field exists - and to skip if it doesn't. This can cause a situation where we need a certain argument (such as syscall) and if it doesn't exists (like in events created from a kworker) we skip. If for some reason tracee-ebpf was run without the `detect-syscall` flag we would skip all the events without even knowing that they are skipped and that there is a problem.

We should add a default value for each argument type (could be 0 for `int`, empty string or "null" for `char *`, etc) and populate those missing fields automatically.

This will ensure a consistent output of tracee-ebpf.

**Comment by itaysk** [comment]
I'm afraid might be more complicated issue.. "nullable types" that is. Some things to consider:

1. how do you know if 0 int is the default or just the value zero?
2. how does this help you avoid writing code if the value is default and handle accordingly?
3. how is this going to be portable across different type systems (we currently have go/json/rego)?

**Comment by yanivagman** [comment]
This is a duplicate of #2261.
Since we continued the discussion there, I'm closing this one.
