### ISSUE TITLE
Support Apple M1

### ISSUE THREAD

**Issue by pomozoff** [aquasecurity/tracee#1208]
Please, add an ability to run tracee inside a VM based on a host with M1 chip.

**Comment by yanivagman** [comment]
Which architecture is being emulated by the VM?
By reading https://www.howtogeek.com/767684/how-to-install-linux-on-apple-silicon/, I assume it is ARM64 architecture.
If that's the case, Tracee already supports it (ARM64), but on latest version this issue still needs to be fixed: https://github.com/aquasecurity/tracee/issues/1129

**Comment by pomozoff** [comment]
Yes, it's ARM64. There are still two issues in tracee:
1. It crashes
2. It could not be built without the **binutils-gold** package in the builder image

**Comment by yanivagman** [comment]
> Yes, it's ARM64. There are still two issues in tracee:
> 
> 1. It crashes
> 2. It could not be built without the **binutils-gold** package in the builder image

1. Can you please elaborate on the crash? Is it #1129 or something else?
2. Can you please explain why do you think `binutils-gold` package is needed and to which builder image (we have two)?

**Comment by rafaeldtinoco** [comment]
Yes, we still need to fix:

https://github.com/aquasecurity/tracee/issues/1129#issuecomment-982825358

and, possibly, some other arm64 specific issues. Not a priority before 0.6.5 release though.

**Comment by pomozoff** [comment]
Yes, I can. Just give me a couple of hours to collect the data.

**Comment by pomozoff** [comment]
> Can you please explain why do you think binutils-gold package is needed and to which builder image (we have two)?

Because when I try to build v0.6.4 without the gold linker I get the next error:
```
# github.com/aquasecurity/tracee/tracee-rules
/usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
collect2: fatal error: cannot find 'ld'
compilation terminated.

make[1]: *** [Makefile:26: dist/tracee-rules] Error 2
make[1]: Leaving directory '/tracee/tracee-rules'
make: *** [Makefile:47: dist/tracee-rules] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2
```

The full log is attached: [tracee-0.6.4-build.log](https://github.com/aquasecurity/tracee/files/7663387/tracee-0.6.4-build.log)

P.S. However, when I build 0.6.5 it builds just fine. Something has been changed in the `libbpf` submodule.

**Comment by pomozoff** [comment]
```
❯ sudo docker run --rm --privileged --pid=host -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro -v /tmp/tracee:/tmp/tracee -v /home/apomozov/templates:/templates -it local/tracee:tracee --output-template /templates/rawjson.tmpl --rules-dir /tracee/rules
Segmentation fault (core dumped)
starting tracee-ebpf...
2021/12/09 22:18:47 invalid operator and/or values given to filter: =

~
❯ cat /home/apomozov/templates/rawjson.tmpl                                                                                                                                                apomozov@utracee
{{ toJson . }}

~
❯
```

**Comment by pomozoff** [comment]
I generated a log when tracee-ebpf crashes: [ebpf-arm64.log](https://github.com/aquasecurity/tracee/files/7698326/ebpf-arm64.log)

**Comment by yanivagman** [comment]
> I generated a log when tracee-ebpf crashes: ebpf-arm64.log

Indeed this is #1129

**Comment by rafaeldtinoco** [comment]
https://github.com/aquasecurity/tracee/pull/1294 enables Apple M1 for tracee-ebpf.
