### ISSUE TITLE
There is no documentation of specific flags required to run

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1211]
Currently the documentation include the [Prerequisites](https://aquasecurity.github.io/tracee/v0.6.4/install/prerequisites/) page which contains the _Permissions_ sub-chapter which advise to use the `--privileged` flag.
However, there are requirements for tracee which are not documented properly:

- `--pid=host` - for the init_namespaces event and for capturing logic
- `--cgroup=host`  - to gain information about existing cgroups at startup

There is an example running command to use, but we don't specify the specific flags anywhere.
I think it would be good to create a page about the running requirements separated from the page of the installation requirement.

**Comment by yanivagman** [comment]
Command examples given in the documentation now include these flags.
I agree it should be added to the prerequistes page as well.
