### ISSUE TITLE
Tracee-ebpf: Compilation dependencies are unclear

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1212]
Currently it is very complicated to contribute to Tracee because when first compiling there are many dependencies which should be downloaded but the error message for each one doesn't correlate to the name of the package missing.
In my opinion, we should create a doc for the packages required by Tracee OR create a simple file that contains all packages required for fast download with some API.

**Comment by itaysk** [comment]
> dependencies which should be downloaded but the error message for each one doesn't correlate to the name of the package missing

can you please give an example?

> file that contains all packages required for fast download with some API

This is supposedly answered by the dockerfile. also all makefile commands accept `DOCKER=1` so that the developer to automatically build in a container with all the dependencies.

**Comment by AlonZivony** [comment]
So when I tried compiling now tracee-ebpf on a new machine I got the messages:

- `llc tool` not found - need to install `llvm` packge
- "package libelf was not found in the pkg-config" - didn't have time to solve

In the end it is just too much trouble to compile, and though we have the option to compile using docker it doesn't work all the time (now I couldn't because something that told me I need to wait for 1h for update or something similar) and I think that helping developers to enter quickly to the project could be nice.

I opened this issue not say that there is no documentation on the dependencies, but it you think there is not need for it you can close it.

**Comment by rafaeldtinoco** [comment]
For tracee-ebpf/ directory,

Under Debian/Ubuntu environments you're supposed to:

`$ sudo apt-get install clang llvm`
`$ sudo apt-get install clang-13 llvm-13`
`$ sudo apt-get install libelf-dev zlib1g-dev`
`$ sudo apt-get install pkg-config`

And I believe you're ready to:

`$ go clean -cache`
`$ make clean `
`$ rm -rf ./dist`
`$ make bpf`
`$ STATIC=1 MAKE ALL`

And you will have a static binary capable of running CO-RE eBPF object into:

https://github.com/aquasecurity/tracee/issues/1210 

If you decide to improve instructions on how to build, I would also mention that latest Fedoras aren't able to generate statically compiled go binaries because of missing static libs.

**Comment by rafaeldtinoco** [comment]
I'm trying to address compilation dependencies through the new Makefile (being done at PR https://github.com/aquasecurity/tracee/pull/1227).

**Comment by itaysk** [comment]
closing for now. feel free to reopen if you think there's something to fix.
I think the docker builder is the answer for this

**Comment by AlonZivony** [comment]
So after some discussion with my teammates which started work with Tracee's source code in the last months, it seems that the docker solution is not enough.
People want to compile Tracee themselves, and to do so they need to know the dependencies which are unclear.
Why don't we add at least a list of the compilation dependencies (llvm etc.) to some documentation page we have?
In the future we can even maybe create a file for automatic installation in various environments like other projects do, but at least for now people should know what to install.

**Comment by yanivagman** [comment]
Documented here https://aquasecurity.github.io/tracee/v0.10/contributing/building/building/

**Comment by rafaeldtinoco** [comment]
https://github.com/aquasecurity/tracee/pull/2787 improves the building.md file and solves this issue.
