### ISSUE TITLE
Revise makefiles

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#1233]
1. Makefile should be smarted about what to build and what to reuse (correct use of targets and requirements)
2. Remove DOCKER=1 functionality in order to simplify the makefile. We can introduce a separate makefile for docker oriented workflow.
3. With the new project structure, probably we don't need 3 separate makefiles.

**Comment by rafaeldtinoco** [comment]
We need to make sure `main.go` building is 1:1 with Makefile.one as soon as Makefile.one becomes the standard.

**Comment by rafaeldtinoco** [comment]
We also need to make sure to document "bpf-noncore" building target (whenever docs/ is updated after this change).

**Comment by yanivagman** [comment]
> We need to make sure `main.go` building is 1:1 with Makefile.one as soon as Makefile.one becomes the standard.

This should be handled by #1239 



> We also need to make sure to document "bpf-noncore" building target (whenever docs/ is updated after this change).

Open an issue to track this?


@rafaeldtinoco  Can we close this now that #1227 is merged?

**Comment by itaysk** [comment]
closed by #1227
