### ISSUE TITLE
E2E sanity test

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/tracee#1234]
In scope of this we should try running existing integration tests from tests/tracee_test.go in the GitHub Actions runner as a minimal e2e quality gate.

**Comment by simar7** [comment]
See my old PR trying to work this in - https://github.com/aquasecurity/tracee/pull/1219 

From what I could gather, tracee no longer runs out of the box within GitHub Actions environment. We need to further investigate why this is the case.

**Comment by grantseltzer** [comment]
@simar7 What do you mean that it no longer runs out of the box? I can investigate, and possibly retry having selfhosted runners.

**Comment by simar7** [comment]
> @simar7 What do you mean that it no longer runs out of the box? I can investigate, and possibly retry having selfhosted runners.

Sorry I wasn't clear. What I noticed that Tracee was not running out of the box on GitHub actions with the default options. 

You can see the options I tried to run with in the sanity test PR I linked above.

**Comment by rafaeldtinoco** [comment]
as a fyio on this... the following test, suggested by Simar on Teams:

```
$ sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace comm=strace | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json
```

has been a life saver when dealing with parseArgs and similar changes.
