### ISSUE TITLE
socket_dup event wrong port under CORE

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#1237]
hey,

under CORE, socket_dup event shows wrong port number. for example:

ipv4:
15:15:04:334699  1000   python3          43338   43338   0                security_socket_connect sockfd: 3, remote_addr: map[sa_family:AF_INET sin_addr:8.8.8.8 sin_port:53]
15:15:04:378489  1000   python3          43338   43338   0                socket_dup           oldfd: 3, newfd: 0, remote_addr: map[sa_family:AF_INET sin_addr:8.8.8.8 sin_port:512]

port should be 53 - like in security_socket_connect.

ipv6:
15:15:09:925689  1000   python3          43340   43340   0                security_socket_connect sockfd: 3, remote_addr: map[sa_family:AF_INET6 sin6_addr:::1 sin6_flowinfo:1 sin6_port:8080 sin6_scopeid:16777216]
15:15:09:926380  1000   python3          43340   43340   0                socket_dup           oldfd: 3, newfd: 0, remote_addr: map[sa_family:AF_INET6 sin6_addr:::1 sin6_flowinfo:0 sin6_port:2560 sin6_scopeid:0]

port should be 8080 - like in security_socket_connect.

**Comment by yanivagman** [comment]
After me and @roikol looked at it together, we suspect that this might be a bug in clang.

1. Issue only happens in CO-RE environment
2. Inspecting the generated BTF, dport field has the correct offset (12)
3. It seems that functionality is changed when using a "volatile" variable to read the port. Might be related to compiler optimization. 
 
Further investigation is required.
@roikol can you please share here the code snippet changed to get the different behavior?

**Comment by yanivagman** [comment]
Ok, so #1281 fixed this bug, but we need to further investigate why to avoid such bugs in the future, so I'm keeping this one open

**Comment by yanivagman** [comment]
We don't support non-CORE platforms anymore, and removed the `READ_KERN` macro, so I'm not sure we can do any further investigation here. Anyway, this is not an issue anymore.
