### ISSUE TITLE
Tracee-rules: Output templates does not support multiple input sources

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1263]
I noticed that there is only 1 template which is used to process the output.
However, given that the current templates use the Context field of the finding (which currently is the Event interface) there should be a way to match between input source to the event type and signatures output type.

**Comment by AlonZivony** [comment]
I think it could be convenient to create a plug-in design for the three of those.
Maybe it will make it harder for signatures to use the types but it will be helpful to unite the 3 in the same package or file.

**Comment by itaysk** [comment]
@AlonZivony I'm sorry I don't follow your problem and suggestion. can you please try to explain again?

**Comment by AlonZivony** [comment]
Sure
We try to support multiple input sources at tracee-rules.
However, we support only one kind of template to use for the output. This template use the `types.Finding.Context` field to print the output, but this is an interface. The result is that tracee-rules can't support more than one type of context in the output, which also translates to one input source.
If our goal is to support multiple input sources stimulatingly it is not possible in the current structure.
Also, if we want to support multiple `Context`s for the same input source (I currently work on adding process tree to the `Context` but I want to support normal events simultaneously) it is also not possible.

To solve this issue, I thought that maybe we can support creation of a template for each type of `Context` which will be loaded at the same time and will be used according to the received `Context` type at the `output.go` file.

**Comment by yanivagman** [comment]
> If our goal is to support multiple input sources

This is not a goal of tracee-rules anymore.
Tracee will only support events generated by it.
