### ISSUE TITLE
extract package `config` from `tracee`

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#1264]
from https://github.com/aquasecurity/tracee/issues/960:

> configurations - create package `config` that includes filter, captureConfig ,outputConfig and related functions. (also create an interface for config and implement validators)

**Comment by yanivagman** [comment]
The following consts can also be moved into this package:
```
type bpfConfig uint32

const (
	configDetectOrigSyscall bpfConfig = iota + 1
	configExecEnv
	configCaptureFiles
	configExtractDynCode
	configTraceePid
	configStackAddresses
	configUIDFilter
	configMntNsFilter
	configPidNsFilter
	configUTSNsFilter
	configCommFilter
	configPidFilter
	configContFilter
	configFollowFilter
	configNewPidFilter
	configNewContFilter
	configDebugNet
	configProcTreeFilter
	configCaptureModules
	configCgroupV1
)
```

**Comment by yanivagman** [comment]
> The following consts can also be moved into this package:
> 
> ```
> type bpfConfig uint32
> 
> const (
> 	configDetectOrigSyscall bpfConfig = iota + 1
> 	configExecEnv
> 	configCaptureFiles
> 	configExtractDynCode
> 	configTraceePid
> 	configStackAddresses
> 	configUIDFilter
> 	configMntNsFilter
> 	configPidNsFilter
> 	configUTSNsFilter
> 	configCommFilter
> 	configPidFilter
> 	configContFilter
> 	configFollowFilter
> 	configNewPidFilter
> 	configNewContFilter
> 	configDebugNet
> 	configProcTreeFilter
> 	configCaptureModules
> 	configCgroupV1
> )
> ```

In a second thought, there are some consts here that are more related to filters and other stuff not directly related to what we might want to have in the `config` package
