### ISSUE TITLE
merge `argprinters.go` into package `eventprinter`

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#1265]
from https://github.com/aquasecurity/tracee/issues/960:

> `argprinters.go` - move to `eventprinter` package (see above). remove dependency on tracee (can be a static function). replace `parse` misnomer with `print` (as the file name suggests). 

depends on #1266

**Comment by yanivagman** [comment]
argprinters.go doesn't exist anymore, and anyway argument parsing moved to the events package, which doesn't depend on the tracee package
