### ISSUE TITLE
extract package `events`

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#1268]
from #960:

> `events_decoder.go` - create new package `events`. rename to `events_decoding.go`
`events_processor.go` - create new package `events`. rename to `event_processing.go`. `CopyFileByPath` function should move to some utlis package or duplicated.
`events.go` - create new package `events` processEvents` should be minimal as possible, there is some code here that should be in `processEvent`.

**Comment by yanivagman** [comment]
Done
