### ISSUE TITLE
Revise release script

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#1271]
#1217 together with #1227 "broke" the release script. We need to reimplement it. 

remember to consider, from #1270 :

> If we were to cut a release right now, three git tags would be created, each corresponding with a Go module that we had: https://github.com/aquasecurity/tracee/blob/main/Makefile#L14
Since the project is restructured this should be changed to only create a single git tag for our single go module.

**Comment by rafaeldtinoco** [comment]
The PR https://github.com/aquasecurity/tracee/pull/1273 is creating Makefiles for generating container images, according to the new Makefile.one. My idea is to re-create the release script after that change (so we can, finally, replace the current building scripts).

**Comment by itaysk** [comment]
ok but AFAIK @grantseltzer (which is assigned) was working to fix the release script

**Comment by rafaeldtinoco** [comment]
> ok but AFAIK @grantseltzer (which is assigned) was working to fix the release script

Grant and I synced about this Friday (fyi). He is, indeed, checking the release script out and will consider the new Makefile.one logic.
