### ISSUE TITLE
Simplify the logic of loading BPF object

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/tracee#1275]
Follow up on https://github.com/aquasecurity/tracee/pull/1226#discussion_r770392757

Regarding the BPF/BTF/BTFHUB loading algorithm:

> I think this flow can be greatly simplified as follows:
```
if bpfenv {
  config.bpf = bpfenv
} else {
  config.bpf =  unpack
}
if btfenv {
  config.btf = btfenv
} else if vmlinux {
  config.btf = vmlinux
}
```

**Comment by itaysk** [comment]
consider refactoring this decision making process, and all of the accompanying BPF/BTF loading code into a package while you're at it

**Comment by yanivagman** [comment]
This code was moved to its own package (initialize).
Closing this now.
