### ISSUE TITLE
Metadata passing protocol between tracee-ebpf to tracee-rules

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1278]
### Background
As times passes, the need to pass information from tracee-ebpf to tracee-rules about the initial state of the system is increasing.
We have the init_namespaces event which pass the init process namespaces to give information about the host namespaces. Now we need information about the process tree at the start of tracee-ebpf for the process tree feature - #1262 .

### The Problem
The current solution of using user-mode events to pass the information is problematic, because the information itself is not an event and is always received at the start of tracee-ebpf before any other event.
We need to have some protocol to pass system information between the two tools that fits the data that pass.

**Comment by AlonZivony** [comment]
### Solution Suggestion
We can use the `Printer.Preamble()` method to pass the information.
We can add to the interface that each `Printer` must receive in the `Preamble()` method a struct representing the system stats and pass it forward. This struct will be a shared package between tracee-ebpf and tracee-rules.
In tracee-rules we can expect to receive this preamble and decode it appropriately.

### Struct Structure
The question that rise is if the struct that pass in the `Preamble` should be a generic struct or not.
We can maybe create a struct similar to the signatures arguments so the receiver needs to know what he expects to receive. It will be helpful if we want a dynamic interface that enables communication of different versions of tracee-rules and tracee-ebpf.
However, if we don't need this flexibility, we can just create a fixed structed and use it in both of the tools. It will be easier to implement and use.
What do you think?

**Comment by itaysk** [comment]
> We can use the Printer.Preamble() method to pass the information.

I'm not sure that's a good place since consumers that use Tracee as a library (not CLI) won't be able to leverage it.

> if the struct that pass in the Preamble should be a generic struct or not

I suppose you mean Map vs Struct? I think we should start with a struct since the other side (tracee-rules) will anyway need to be programmed to use it specifically

**Comment by itaysk** [comment]
also we need to define the how the tracee-rules process will receive this data

**Comment by NDStrahilevitz** [comment]
I suggested this in a previous sync, we could use the new `protocol.EventHeaders` to indicate the state passing, instead of using `trace.Event` how it's done for example in #1519, WDYT?

**Comment by AlonZivony** [comment]
I support what you proposed, though I am not sure if the name `EventHeaders` will suit it (because it is not exactly an event).
If you can publish here the new structure that you proposed to us I think it would be great.

**Comment by NDStrahilevitz** [comment]
`EventHeaders` is the component that enables it. You can see #1493 for the structure itself. Basically instead of sending these `trace.Event` which are then converted to protocol, I suggest we define a `Metadata` payload which we will pass with a `ContentType` header indicating it as such. Then the engine will have a separate path for handling that ContentType (Or maybe we could add a signature which will have a callback that handles the metadata registration, but I think that would be less efficient).

**Comment by yanivagman** [comment]
Now that we have a single tracee binary, this is not needed anymore
