### ISSUE TITLE
BUG: go version of tracee always reports 0 lost events

### ISSUE THREAD

**Issue by icarus-sparry** [aquasecurity/tracee#128]
In the statsStore there is a lostEvCounter, but it is never altered. 
The code around https://github.com/aquasecurity/tracee/blob/master/tracee/tracee.go?#L432 
```
		case lost := <-t.lostEvChannel:
			t.stats.errorCounter.Increment(int(lost))
		}
	}
``` 
should probably be incrementing this counter rather than the general errorCounter.

**Comment by itaysk** [comment]
good catch! thanks for reporting. I have open #129 to fix, feel free to submit a PR next time if you would like.
