### ISSUE TITLE
Save captured files using container id

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1283]
We currently save captured (written) files into directories which name is the mount namespace id.
This is problematic as mount namespace id might be reused when a container is exited, and a new container starts.
As we now extract the container id (using the cgroup id) per event, we can use it to name the directories used to save these captured artifacts.

**Comment by itaysk** [comment]
is container ID guaranteed to be unique over time?

**Comment by itaysk** [comment]
https://github.com/opencontainers/runtime-spec/blob/main/runtime.md#state

> id (string, REQUIRED) is the container's ID. This MUST be unique across all containers on this host. There is no requirement that it be unique across hosts.

I think it's supposed to be unique between the currently active containers, but not sure about over previous containers (which I think won't solve your issue?)

**Comment by yanivagman** [comment]
> nk it's supposed to be unique between the currently active containers, but not sure about over previous containers (which I think won't solve your issue?)

In practice, every container has a unique id.

**Comment by rafaeldtinoco** [comment]
> > is container ID guaranteed to be unique over time?
> 
> With a high probability, the answer is yes. In contrast, with mount namespace id, on some systems, with a probability of 1 you will get a collision

Isn't it a SHA-1 ? It would be 1/(2^80) or something like it (if we're using the full id).

**Comment by itaysk** [comment]
It's a sha in docker maybe but other runtimes might choose otherwise.  Also people might create cgroups with any name. Just adding a consideration feel free to ignore, but maybe adding a random number or something will be safer

**Comment by mtcherni95** [comment]
Do we want to change the path by using cgroup ns ID only for capture write or also for other artifacts?
