### ISSUE TITLE
runtime engine not detected correctly

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#1302]
I am running tracee on `uname -a = 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux` and my container runtime engine is Docker version 20.10.7. 
Cgroup version is v1 (`/sys/fs/cgroup/cgroup.controllers` does not exists).
In function `tracee.getContainerIdFromCgroup`, for Docker at least,  we fetch the runtime engine by checking if 'docker-'  is a prefix of the path component which is, in my file system, the container id ( `/sys/fs/cgroup/cpuset/docker/01adbaf26db7fac62f8b7ec5b116b2e60f4abbf230e29122e667996c6b5c04d4/`) (https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/containers.go#L190). By doing so the container runtime ends up being 'unknown', as probably the if prefix condition is not matched. 

BTW, the `runtime` field of struct `CgroupInfo` is not used.

**Comment by yanivagman** [comment]
related: #884
