### ISSUE TITLE
Improve falcosidekick integration

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#1306]
The mapping between tracee Finding and falcosidekick Payload doesn't properly map the severity and key metadata items. when displayed in falcosidecick-ui the filters doesn't work

cc: @idanr1986

**Comment by vaibhavmew** [comment]
Hi, I am new to the community and would like to take up this issue.

**Comment by josedonizetti** [comment]
Falco sidekiq integration was removed from tracee, we have an issue to write a tutorial on how to do it by using the gotemplate printer https://github.com/aquasecurity/tracee/issues/2796
