### ISSUE TITLE
Add option to aggregate Tracee-Rules findings

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#1308]
We would like to give option to Tracee Rules to aggregate detection of the same type/signatures and output the findings only after a certain amount of occurrences happened or a certain time period expired.

**Comment by itaysk** [comment]
This feature is definitely necessary for real-world usage, but is out of  scope for tracee, which is supposed to just detect suspicious behavior and not be a an incident management tool. Open Source users should use Postee or falcosidekick or another tool of their choice. In your case (CNDR) I recommend implementing this in CNDR side
