### ISSUE TITLE
Incorporate tutorials into docs

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#1314]
Currently we have just one type of docs which are "reference" documentation. We should add a "how-to/tutorials" section with goal-driven content. We can start by drawing already available content:

https://blog.aquasec.com/kubernetes-runtime-security-ebpf
https://blog.aquasec.com/tracee-runtime-malware-alerts-aqua-postee
https://blog.aquasec.com/runtime-security-tracee-rules
https://github.com/krol3/workshop-cloud-native-security/blob/main/runtime.md

**Comment by yanivagman** [comment]
We can probably add these two as well:
https://blog.aquasec.com/linux-vulnerabilitie-tracee
https://blog.aquasec.com/ebpf-container-tracing-malware-detection

**Comment by krol3** [comment]
Nice issue! I would like to help!
