### ISSUE TITLE
Considering add allow filter to envp

### ISSUE THREAD

**Issue by chriskaliX** [aquasecurity/tracee#1316]
Hello, Happy new year!
When I go through the source code of `tracee.bpf,c`, I find there are lots of awesome filters for pid, path and etc. . 
**I was wondering whether it's neccessary to add envp allow filter in hook  `raw_tracepoint/execve(at)`.**
In my view, the env that we need to audit is quite limited, such as, `SSH_TTY`,`SSH_CONNECTION`, `LD_PRELOAD`, `LD_LIBRARY_PATH`. Other envs like `LS_COLORS`,`LANGUAGE` are not helpful in security situation and take up a lot of spaces

![images](https://user-images.githubusercontent.com/46471110/147850359-2867e88d-f9a1-499c-b0c8-e58067e13d2c.png)

~~I try to implement the filters by BPF_HASH, but it seems that I have to implement `strtok` in the first place...~~

**Comment by yanivagman** [comment]
> Hello, Happy new year!
> When I go through the source code of tracee.bpf,c, I find there are lots of awesome filters for pid, path and etc. .
> I was wondering whether it's neccessary to add envp allow filter in hook raw_tracepoint/execve(at).
> In my view, the env that we need to audit is quite limited, such as, SSH_TTY,SSH_CONNECTION, LD_PRELOAD, LD_LIBRARY_PATH. Other envs like LS_COLORS,LANGUAGE are not helpful in security situation and take up a lot of spaces

Hello!
The bpf filters (pid, comm, etc...) are used to filters events - if a match is found, the event is filtered in/out.
If I understand correctly, what you ask is to keep the event itself (execve/execveat), but filter SOME envrionment variables from one of the event's arguments (envp).
So, this is not exactly the same functionality - filtering an event VS filtering some of the content of one of the arguments of the event. Implementing such functionality in the bpf code is also not a trivial task. The environment variables number is unknown, so some bounded loop is required, also instruction limit might not be enough and string comparison is not an easy task as there are no bpf helpers for doing such comparisons.

A better place to implement such functionality will probably be in userspace. We currently have "argument filters" that compare an argument to some given value. It might be possible to do something similar that will only extract some chosen content of an argument, but I think that will be too specific to execve(at) event (while we prefer implementing generic filters). Another option (easier to implement) might be in the parseArgs functions (which is located in the argprinters.go file). There you can look for execve/execveat events, and change the content of a specific argument.

**Comment by chriskaliX** [comment]
Thanks for your reply! I'll look into that
