### ISSUE TITLE
Document how Tracee can be debugged using delve

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#1318]
I wanted to debug tracee-ebpf using delve, however I got error `could not launch process: could not open debug info`.
This is because tracee-ebpf is built with the `-w` flag which strips out the DWARF information from it (please see https://github.com/go-delve/delve/issues/1485). After compiling tracee-ebpf without the `-w` flag, I managed to debug it with delve. Why might consider to compile without `-w` (?)

**Comment by NDStrahilevitz** [comment]
I think adding a flag for a debug compile here seems reasonable, what do you think?

Also, i've noticed that `tracee-rules` is also compiled with a `-w` however it doesn't seem to have the same effect there.

**Comment by yanivagman** [comment]
This issue is about debugging tracee and not user facing.
We can add the above comment to the contribution section in the docs so whoever wants to debug tracee with delve can know how to do so

**Comment by yanivagman** [comment]
> @yanivagman I think this is already solved: [c83ac80](https://github.com/aquasecurity/tracee/commit/c83ac80f25f67d940d87428b6bcfdb02e548c494)

Ok good to know.
Closing this issue then
