### ISSUE TITLE
15 or 14 signatures TRC

### ISSUE THREAD

**Issue by krol3** [aquasecurity/tracee#1321]
I only see 14 signatures. in the output said 15.

Loaded 15 signature(s): [TRC-1 TRC-13  TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7]

**Comment by rafaeldtinoco** [comment]
It all looks good in last release:

```
Loaded 14 signature(s): [TRC-1 TRC-13 TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7]
```
