### ISSUE TITLE
Sub command "trace" can not work with option --trace c

### ISSUE THREAD

**Issue by vincent-pli** [aquasecurity/tracee#1338]
I try sub command `trace` with
```
docker run --name tracee --rm --pid=host --cgroupns=host --privileged -v /tmp/tracee:/tmp/tracee -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro -it aquasec/tracee:0.6.5 trace --trace c
```
But no event collected:
```
TIME             CONTAINER_ID  UID    COMM             PID/host        TID/host        RET              EVENT                ARGS
```

I expected it will be many event since I run it in a kubernetes node.
Checked some code, with option `--trace c`, `--trace container` `--trace !container` .etc,  the code will go through folders in path `/sys/fs/cgroup/cpuset`(cgroupv1) to collect `containerID`,  that's make sense, but we do not mount host's `/sys/fs/cgroup/` to the `tracee`, the code go through the file system of the tracee container rather than the host.

To change the command like this, it will work:
```
docker run --name tracee --rm --pid=host --cgroupns=host --privileged -v /tmp/tracee:/tmp/tracee -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro  -v /sys/fs/cgroup/:/sys/fs/cgroup/:ro  -it  aquasec/tracee:0.6.5 trace --trace c
```

**Comment by yanivagman** [comment]
Well that's strange.
`cgoupns=host` should have taken care of that as it then uses the same cgroupfs as the one on the host.
Can you please exec into the container after it is started and `ls /sys/fs/cgroup/cpuset`?
