### ISSUE TITLE
cap_capable doesn't monitor all capabilities with CO-RE

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1341]
After taking a look at #1340 I noticed that we don't monitor the capabilities correctly when CO-RE is enabled.
The reason for this is that CAP_OPT_NONE is not defined in CO-RE.

**Comment by rafaeldtinoco** [comment]
Despite `CAP_OPT_NONE` not being defined... the logic is unfinished (as it seems), but it is currently working:

ubuntu 5.4.0-91-generic

```
$ sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace event=cap_capable | jq -jc '"\nPID: ", .processId, " COMM: ",.processName," EVENT: ",.eventName," ARGS: ", .args, "\n"'

PID: 993 COMM: lxd-agent EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SETUID"}]
PID: 993 COMM: lxd-agent EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SYS_ADMIN"}]
PID: 993 COMM: sh EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SYS_ADMIN"}]
PID: 993 COMM: sh EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SYS_ADMIN"}]
PID: 993 COMM: sh EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SYS_ADMIN"}]
PID: 993 COMM: sh EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SYS_ADMIN"}]
PID: 993 COMM: sh EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SYS_ADMIN"}]
PID: 993 COMM: sh EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SYS_ADMIN"}]
PID: 993 COMM: sh EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SYS_ADMIN"}]
PID: 993 COMM: sh EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SYS_ADMIN"}]
PID: 993 COMM: sh EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SYS_ADMIN"}]
```

ubuntu 5.13.0-25-generic:

```
sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace event=cap_capable | jq -jc '"\nPID: ", .processId, " COMM: ",.processName," EVENT: ",.eventName," ARGS: ", .args, "\n"'

PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SETUID"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SETGID"}]
PID: 1200913 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1200913 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1200913 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1200913 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1200913 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1200913 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1200913 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1200913 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SETGID"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SETGID"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SETUID"}]
```

debian 5.15.0-3-amd64:

```
$ sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace event=cap_capable | jq -jc '"\nPID: ", .processId, " COMM: ",.processName," EVENT: ",.eventName," ARGS: ", .args, "\n"'

PID: 3365 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 3365 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 3365 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 3365 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 3365 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 3365 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 3365 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 3365 COMM: exe EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_NET_ADMIN"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SETGID"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SETGID"}]
PID: 1 COMM: runc:[2:INIT] EVENT: cap_capable ARGS: [{"name":"cap","type":"string","value":"CAP_SETUID"}]
```

With: 

```C
int cap_opt = PT_REGS_PARM4(ctx)
```

`cap_out` is, most of the times, CAP_OPT_NONE (0).

The only execution path it is not `CAP_OPT_NONE` is when being executed by `has_cap_mac_admin()`. In that case, it might either be `CAP_OPT_NONE` or `CAP_OPT_NOAUDIT` (depending if selinux is executing it with audit).

In both cases, the:

```C
#ifdef CAP_OPT_NONE
  audit = (cap_opt & 0b10) == 0;
#else
  audit = cap_opt;
#endif

  if (audit == 0)
    return 0;
```

doesn't seem right.

I suggest we always submit "cap_capable" event with the correct capability request. Will propose a PR for that.

**Comment by yanivagman** [comment]
So here is the thing...

0b10 signifies CAP_OPT_NOAUDIT. This option is being called internally (opposed from by user request of some capability), for example, from selinux and apparmor. Whenever it is set, we DON'T want to trace cap_capable.
This is why we have this line:
`audit = (cap_opt & 0b10) == 0;`
and then:
```
  if (audit == 0)
    return 0;
```

Now, the problem is that CAP_OPT_NOAUDIT (as well as CAP_OPT_NONE) was only introduced in kernel 5.1, where the following three options are defined:
```
/* Default (no) options for the capable function */
#define CAP_OPT_NONE 0x0
/* If capable should audit the security request */
#define CAP_OPT_NOAUDIT BIT(1)
/* If capable is being called by a setid function */
#define CAP_OPT_INSETID BIT(2)
```

So only when CAP_OPT_NONE is defined we want to use this logic. Otherwise, option argument has a different meaning.
In kernels 4.18-4.20, the following options are defined:
```
#define SECURITY_CAP_NOAUDIT 0
#define SECURITY_CAP_AUDIT 1
```
And as you can see, even the bits have different meaning here, which makes things more complicated.

So now that this logic is (hopefully) clear, we need to think how we solve this problem for CO-RE.
We could have remove it as you suggested in your PR, but then we will get events that not only represent the capabilities requested by user, but also some other internally required capabilities used by LSM such as apparmor and selinux

**Comment by rafaeldtinoco** [comment]
> So now that this logic is (hopefully) clear, we need to think how we can solve this problem for CO-RE.
> We could have removed it as you suggested in your PR, but then we will get events that not only represent the capabilities requested by user, but also some other internally required capabilities used by LSM such as apparmor and selinux

Thanks for clarifying. I failed to see `0b10` was a binary-literal and interpreted it in the hex format, so it made no sense when I read it. Now it does.

I'm afraid that, without an enum relocation, handling this without handling kernel version (even if comparing a totally different type so we can better identify versions) won't be possible.

Let's see... checking it out...

**Comment by rafaeldtinoco** [comment]
> I'm afraid that, without an enum relocation, handling this without handling kernel version (even if comparing a totally different type so we can better identify versions) won't be possible.

Clarifying: we can't simply rely in LINUX_VERSION_CODE (or similar kconfig logic) ksym relocation because of the dead code elimination verifier issues (thus the need to depend on another type existence)...

**Comment by rafaeldtinoco** [comment]
The change you're referring to is at:

```
commit c1a85a00ea66
Author: Micah Morton <mortonm@chromium.org>
Date:   Mon Jan 7 22:10:53 2019

    LSM: generalize flag passing to security_capable
```

and... because of the nature of this "relocation need" (based on defines with opposite meaning), my idea is that we could support:

- rh8 kernels (which are < 4.19)
- kernels bigger than 5.1

RH introduces types named "rh80" on its kernel. From the second patched version (very old) and on, they have "rh80" types, that we can use to identify if CO-RE is at a RH8 kernel. 

Example:

```
$ for file in *; do bpftool btf dump file $file format raw | grep -q rh8 && echo $file; done
4.18.0-147.0.3.el8_1.x86_64.btf
4.18.0-147.3.1.el8_1.x86_64.btf
4.18.0-147.5.1.el8_1.x86_64.btf
4.18.0-147.8.1.el8_1.x86_64.btf
4.18.0-147.el8.x86_64.btf
4.18.0-193.1.2.el8_2.x86_64.btf
4.18.0-193.14.2.el8_2.x86_64.btf
4.18.0-193.19.1.el8_2.x86_64.btf
4.18.0-193.28.1.el8_2.x86_64.btf
4.18.0-193.6.3.el8_2.x86_64.btf
4.18.0-193.el8.x86_64.btf
4.18.0-240.1.1.el8_3.x86_64.btf
4.18.0-240.10.1.el8_3.x86_64.btf
4.18.0-240.15.1.el8_3.x86_64.btf
4.18.0-240.22.1.el8_3.x86_64.btf
4.18.0-305.10.2.el8_4.x86_64.btf
4.18.0-305.12.1.el8_4.x86_64.btf
4.18.0-305.17.1.el8_4.x86_64.btf
4.18.0-305.19.1.el8_4.x86_64.btf
4.18.0-305.25.1.el8_4.x86_64.btf
4.18.0-305.3.1.el8.x86_64.btf
4.18.0-305.7.1.el8_4.x86_64.btf
4.18.0-305.el8.x86_64.btf
4.18.0-348.2.1.el8_5.x86_64.btf
4.18.0-348.7.1.el8_5.x86_64.btf
4.18.0-348.el8.x86_64.btf
```

If you don't think its too "hacky" we can use one of those types to check if we're at a RH8 kernel, if we are, then we assume its the old definition, if not, we assume its the new definition. This would cover all kernels we're currently supporting I suppose (again, from https://github.com/aquasecurity/tracee/issues/1210 list).

**Comment by yanivagman** [comment]
Actually, I see that latest updates of kernel 4.19 already backported the new defines:
https://elixir.bootlin.com/linux/v4.19.98/source/include/linux/security.h

I bet that redhat also backported these new defs.
If that's the case, maybe our best solution will be to assume that these defs exist and just:
```
    if (cap_opt & CAP_OPT_NOAUDIT)
        return 0;
```

And add these to missing_definitions.h:
```
/* Default (no) options for the capable function */
#define CAP_OPT_NONE 0x0
/* If capable should audit the security request */
#define CAP_OPT_NOAUDIT 0b10
/* If capable is being called by a setid function */
#define CAP_OPT_INSETID 0b100
```

WDYT?
