### ISSUE TITLE
Indicating events that are vulnerable to TOCTOU

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1356]
### Discussed in https://github.com/aquasecurity/tracee/discussions/1355

<div type='discussions-op-text'>

<sup>Originally posted by **OriGlassman** January 18, 2022</sup>
Users should be aware of events that are vulnerable to time of use to time of check (TOCTOU) attacks. 
I think every event in tracee-ebpf should mention whether they are vulnerable or not, instead of "forcing" the user to google the event and check whether this is a syscall, lsm hook, kernel tracepoint etc.

The event documentation should clearly state whether it's vulnerable, and the relevant vulnerable fields (arguments).</div>

**Comment by itaysk** [comment]
IMO it's sufficient to indicate which events are syscalls and which are not. non-sysscalls have different security implications (like TOCTOU), performance, API and documentation, etc

**Comment by yanivagman** [comment]
> IMO it's sufficient to indicate which events are syscalls and which are not. non-sysscalls have different security implications (like TOCTOU), performance, API and documentation, etc

Actually, we already have this: https://github.com/aquasecurity/tracee/blob/main/docs/faq.md
However, we currently don't have documentation per each event, so maybe the issue should be converted to add such a documentation, where we will also describe the arguments, and whether one of them is exposed to such an attack.

**Comment by itaysk** [comment]
What I meant is that Tracee-eBPF will make it clear with events are syscall not in the repo but in the cli, we already kind of do this in --list but we could be more clear and maybe also mention in output. Once the user knows it's a syscal they should be aware of the implications (which can be documented in docs)

**Comment by OriGlassman** [comment]
IMO, if we don't want to mention for each event whether it's vulnerable to TOCTOU, renaming all the events into categories will help users understand what to expect from each specific event they see.

For example, events that are syscalls should have a syscall prefix: 'syscall_openat'.
Events that are LSM hooks 'lsm_security_file_open'.
Events that are self made: 'custom_init_namespaces'
etc
 
And then you can generally explain that syscalls are vulnerable to toctou while other stuff aren't. It will also provide visibility to the user what is the origin of the event he sees, without googling it first, or searching it in --list.

**Comment by itaysk** [comment]
that's more along the lines of what I was thinking. do you think there's a difference between LSM and "custom" from this standpoint?

**Comment by yanivagman** [comment]
Closing this in favor of #1398
