### ISSUE TITLE
capture network icmp packets

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#1359]
hey,

right now we are only capturing packets of l4 protocols: tcp and udp.
we should add support for capturing packets of protocol: icmp.

**Comment by itaysk** [comment]
Just out of curiosity can you share the use case?

**Comment by roikol** [comment]
the use case is visibility (network wise) on the processes we monitor. right now if a process is communicating through icmp, we don't capture it in the resulted pcap.

security wise - icmp could be used to exfiltrate data between a process/malware on a victim machine to the C&C server of the attacker.
