### ISSUE TITLE
tracee-ebpf :adding support to net events as regular events

### ISSUE THREAD

**Issue by itamarmaouda101** [aquasecurity/tracee#1363]
Hey,

Right now we are only printing network events in the console by fmt.Printf() and not by the events channel ( because now they are only debug events).

We should add support for printing network events also in json and also add a support for adding more net -events like that other events.

Currently I'm working on creating that support by adding a `network_protocols` package and directory which will able us to add net events easily and also support tracing them using the command line

**Comment by itamarmaouda101** [comment]
i think you right.
i hope we will support more net events  (for example protocols like dns, http, irc, etc) in the feature .
i created a draft PR which still prints the events only in debug mode (#1364 ) but  i think that later on it will be great idea to remove it from the `--debug`

**Comment by yanivagman** [comment]
> And, IMO, we should remove the network debugging from "--debug".
> 
> @yanivagman WDYT about it ? IIRC we've discussed this in the past.
> 
> I'm doing VNC to the machine being observed/tested and its almost impossible to check "--debug" initial messages because of so many "network packets debugging" passing through my screen (even when --output none is given).

Yes, I agree. In the first place I wanted to create --debug-net flag, but @itaysk opposed to this idea, saying that --debug is enough.

In addition to this, I think this issue should be more general than just the json printer. Net events should be converted to an external.Event struct and pushed to the events channel, which then uses the regular printer interface

**Comment by itamarmaouda101** [comment]
> In addition to this, I think this issue should be more general than just the json printer. Net events should be converted to an external.Event struct and pushed to the events channel, which then uses the regular printer interface

defiantly agree , i did exactly that in my PR.
 i created a NET_PACKET event handler that assign the  first argument to be that packet data (Src and Dst Ips and Ports ).
 now in the CR with @AlonZivony we thought about how can we  will support more then just Net packets (for example IRC, DNS, ICMP ,etc protocols)

**Comment by itamarmaouda101** [comment]
I changed the issue subject to be more general because in my PR I will expend the network functionality as well

**Comment by rafaeldtinoco** [comment]
This has been implemented.
