### ISSUE TITLE
Fail to start tracee under high load

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1366]
By accident I was testing tracee-ebpf in parallel to lots of server loads I have and I saw that:

```
$ sudo ./dist/tracee-ebpf --debug -o option:parse-arguments --trace comm=ping --trace event=* --trace event!='sched*' --capture net=home
OSInfo: ID: ubuntu
OSInfo: ID_LIKE: debian
OSInfo: KERNEL_RELEASE: 5.13.0-25-generic
OSInfo: ARCH: x86_64
OSInfo: PRETTY_NAME: "Ubuntu 21.10"
OSInfo: VERSION_ID: "21.10"
OSInfo: VERSION: "21.10 (Impish Indri)"
OSInfo: VERSION_CODENAME: impish
BTF: bpfenv = false, btfenv = false, vmlinux = true
BPF: using embedded BPF object
unpacked CO:RE bpf object file into memory
libbpf: Kernel error message: Exclusivity flag on, cannot modify
2022/01/19 16:34:14 error creating Tracee: error creating process tree: readlink /proc/2562484/task/2562484/ns/mnt: no such file or directory
```

There might be a race issue because of error handling when the task exits and we're trying to read procfs during the initial load.

**Comment by yanivagman** [comment]
This error is from the new process tree pr merged earlier today.
@itamarmaouda101 can you have a look?

**Comment by itamarmaouda101** [comment]
sure , on it!

**Comment by itamarmaouda101** [comment]
i checked that  and i notice that in case that error occurs in the parsing of task file while initiate the process-tree- we return error and then it failed to create tracee. 
i created a PR that fixing that by changing the `return err' to `continue` in the task parsing phase of the process tree
