### ISSUE TITLE
Tracee not catching anti-debugging if using all events

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1370]
During development of another PR, I have noticed that if I do:

Select just the default events (except 'sched*'):

```
$ sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace event!='sched*' | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json
Loaded 14 signature(s): [TRC-1 TRC-13 TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7]
```

I'm able to get ALL signatures triggered:

```
*** Detection ***
Time: 2022-01-20T15:05:37Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: fujitsu

*** Detection ***
Time: 2022-01-20T15:05:37Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: fujitsu

*** Detection ***
Time: 2022-01-20T15:05:38Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: fujitsu
```

But if I tell tracee-ebpf to trace ALL existing events, I get one (if I'm fast enough, in the beginning of command execution, and others are not showed).

```
$ sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace event='*' --trace event!='sched*' | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json
Loaded 14 signature(s): [TRC-1 TRC-13 TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7]

*** Detection ***
Time: 2022-01-20T15:04:04Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: fujitsu
```

Sometimes I get nothing (no detection).

My machine has 24 CPUs and 200GB of RAM. 

This, for me, means that we could be dropping too many events in bigger hosts, and making signatures not to work because of that (or something alike) and might deserve a better investigation.

**Comment by rafaeldtinoco** [comment]
@mtcherni95 that might interest you ^ (to either follow or play with).

**Comment by yanivagman** [comment]
Choosing to trace all events of all the process in the system should only be done when testing for verifier issues, IMO.
Of course you will have way too many lost events as you trace the following:
- sys_enter of any syscall
- sys_exit of any syscall
- sched_switch which happens whenever there is a context_switch

Even choosing one of the above events and tracee for a few seconds you will get many lost events. These events are not meant to be used in production

**Comment by rafaeldtinoco** [comment]
@yanivagman yes, I was already ignoring sched events.. I removed 'sys_enter' and 'sys_exit' from the list of events and it got much better:

```

$ sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace event!='sched*' --trace event!='sys_enter' --trace event!='sys_exit' | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json
Loaded 14 signature(s): [TRC-1 TRC-13 TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7]

*** Detection ***
Time: 2022-01-20T15:35:26Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: fujitsu

*** Detection ***
Time: 2022-01-20T15:35:27Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: fujitsu

*** Detection ***
Time: 2022-01-20T15:35:28Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: fujitsu

*** Detection ***
Time: 2022-01-20T15:35:29Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: fujitsu
```

Nevertheless, its a good way of stressing things out (causing delays in event delivery, causing events to be lost, etc).

Thanks.

**Comment by yanivagman** [comment]
> sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace event!='sched*' --trace event!='sys_enter' --trace event!='sys_exit' | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json

@rafaeldtinoco you didn't choose `--trace e=* ` as well so `--trace event!='sys_enter' --trace event!='sys_exit'` doesn't do anything as this events are not chosen by default.

> Nevertheless, its a good way of stressing things out (causing delays in event delivery, causing events to be lost, etc).

Correct. Even choosing one of these events would have been enough for a stress test (but only of tracee-ebpf and not tracee-rules, and checking only the events pipeline, and not the parsing/processing functions which ignore these events)
