### ISSUE TITLE
/sys/kernel/security/lockdown has to be bind mounted to container so tracee-ebpf is executed

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1396]
After commit a5bc030, tracee-make stopped being able to run tracee-ebpf as it does not bind mount "/sys/kernel/security" to the container:

```
$ sudo ./dist/tracee-ebpf --debug
2022/01/24 21:08:19 open /sys/kernel/security/lockdown: no such file or directory
```

**Comment by rafaeldtinoco** [comment]
I'm fixing this soon, together with other PR I'm preparing (FYIO).

**Comment by yanivagman** [comment]
Not only that, we should also make sure that with older kernels, were `/sys/kernel/security/lockdown` doesn't exist we don't fail tracee
