### ISSUE TITLE
Document events and expose documentation using CLI

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1398]
We can use a new "Documentation" field in EventDefinition to document tracee-ebpf events.
Such a documentation can then be exposed to the user by the `help` flag followed by an event's name.
Things we can include in each event documentation:

1. General description of the event and when it is triggered
2. Event type - syscall/lsm_hook/other internal kernel function/derived event
3. Arguments description
4. Telling if the event is stable, in the sense that it won't be removed in future releases, and the existing arguments won't be changed
5. Warn if one of the arguments is exposed to TOCTTOU attack (#1356)

**Comment by itaysk** [comment]
This is good. how do we plan to maintain the events documentation across the CLI and the online docs website? https://github.com/aquasecurity/tracee/issues/436 can be of interest here
