### ISSUE TITLE
tracee-ebpf: trace 'pid>X' or 'pid<Y' does not seem to be working

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1417]
Reproducer:

```
$ sudo ./dist/tracee-ebpf --trace 'pid>0'
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
<nothing>
```

Tested with 5.13 and 5.15. Did not investigate further (yet).

**Comment by yanivagman** [comment]
Introduced in commit: https://github.com/aquasecurity/tracee/commit/b7007617228284c0043d6d7fee9e56e0cb0ecca2#diff-710a36e0ca7a07ea49cf4970d916ed0b74b1c3619920145d9db50477c4f96967

inequality_filter value is of type uint64 and we shouldn't cast to uint32
