### ISSUE TITLE
don't capture duplicated packets on loopback device 

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#1418]
currently, when capturing on loopback device, we capture each packet twice - once on the ingress on the interface, and once on the egress. this causes the pcap to be not that readable, as responses are not linked correctly to their requests.
we should probably only capture on tc_ingress, and don't capture on tc_egress (or vice versa), when the interface is a loopback device.

in tcpdump, for example, we can see in the output that it goes through X packets, but only captured X/2 packets.
```
root@ubuntu-VirtualBox:~# tcpdump -w /tmp/capture.pcap -i lo
tcpdump: listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
^C 6 packets captured
12 packets received by filter
0 packets dropped by kernel
```

**Comment by yanivagman** [comment]
Should have been closed by #1556
