### ISSUE TITLE
CPU queueing has a BUG: HEAD with next detected

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1441]
During some event loss tests, when enabling CPU queueing/sorting feature, I came across the message that @AlonZivony introduced during our CPU queueing feature review:

```
INFO: probing tracee-ebpf capabilities...
INFO: starting tracee-ebpf...
INFO: starting tracee-rules...
Loaded 14 signature(s): [TRC-1 TRC-13 TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7]

*** Detection ***
Time: 2022-02-04T19:33:42Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: focal

lost 10052 events

*** Detection ***
Time: 2022-02-04T19:34:03Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: focal

lost 6275 events
lost 27641 events
lost 116737 events
lost 8831 events

BUG: HEAD has next
BUG: HEAD has next
```

**Comment by AlonZivony** [comment]
I will take a look at it.
If you can send me how you run the test so I will be able to reproduce the bug it will be a huge help.
Thanks

**Comment by rafaeldtinoco** [comment]
> I will take a look at it.
> If you can send me how you run the test so I will be able to reproduce the bug it will be a huge help.
> Thanks

Sure Alon, please check the discussion I opened recently (about flaky tests and performance). The simple test described there, when executed with events sorting, is the one that caused this. I'm afraid it's triggered by high event loss but that is just a hunch for now.
