### ISSUE TITLE
Flaky smoke tests

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1456]
### Discussed in https://github.com/aquasecurity/tracee/discussions/1442

<div type='discussions-op-text'>

<sup>Originally posted by **rafaeldtinoco** February  5, 2022</sup>
## Performance Observations (env: 5.15 kernel, 4 cpus, 4gb)

@danielpacak and I investigated some flaky smoke tests today. Smoke tests started being VERY flaky after we caused docker daemon to download and instantiate a container image, right before the test execution, instead of pulling the image first and then initializing the container.

What happened was that the workload of the docker daemon, in the docker hub node, was enough to make a very simple test (TRC-2) to fail significantly. I'm enumerating reproducers in multiple steps, here, isolating the variables:

1. multiple events + multiple rules
2. multiple events + single rule
3. single event + single rule

The test is the following:

- Run `tracee-ebpf`
- Run `while true; do ps -ef; done` in a 4 cpu box
- Run `strace ls` multiple times (wait a bit so pipeline gets full)

The tests:

----

1. multiple events + multiple rules

```
$ sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace event=close,dup,dup2,dup3,execve,init_module,magic_write,mem_prot_alert,process_vm_writev,ptrace,sched_process_exec,sched_process_exit,security_bprm_check,security_file_open,security_kernel_read_file,security_sb_mount,security_socket_connect | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json
Loaded 12 signature(s): [TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7]

*** Detection ***
Time: 2022-02-05T05:08:23Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: debian

*** Detection ***
Time: 2022-02-05T05:08:43Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: debian

lost 5891 events
lost 100578 events
```

Executed: 5 `strace` commands
Got: 2 detections

----

2. multiple events + single rule

```
$ sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace event=close,dup,dup2,dup3,execve,init_module,magic_write,mem_prot_alert,process_vm_writev,ptrace,sched_process_exec,sched_process_exit,security_bprm_check,security_file_open,security_kernel_read_file,security_sb_mount,security_socket_connect | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json
Loaded 1 signature(s): [TRC-2]

*** Detection ***
Time: 2022-02-05T05:15:42Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: debian

*** Detection ***
Time: 2022-02-05T05:15:45Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: debian
lost 9959 events

*** Detection ***
Time: 2022-02-05T05:15:47Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: debian

lost 17789 events
lost 7556 events

*** Detection ***
Time: 2022-02-05T05:15:53Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: strace
Hostname: debian
```

Executed: 5 `strace` commands
Got: 4 detections

----

3. Same test, but now, instead of selecting all events (from all existing signatures), select only `ptrace` event. Keep the same pallalel workload (`while true; do ps -ef; done`).

Executed: 10 `strace` commands
Got: 10 detections

----

Some conclusions:

When loading all existing signatures (14), not much if we consider CNDR, we reduce the detection rate considerably (way more that if we select multiple events to be probed for a single signature). At least if that test is done in a small environment (4 cpus, 4 gb)

The fact that tracee-ebpf output is not consumed fast enough makes it to hold the pipeline, because the nature of the OS I/O handling, and then tracee-ebpf cannot consume the perf buffer fast enough. This makes ebpf programs to overwrite perf buffer events that were not consumed, causing event loss.

I do know that:

* we can raise the perf buffer size
* have a plan to have tracee-ebpf & tracee-rules part of the same process (multiple routines) and have a channel to pass over the received events.
* we can use ring buffers (in newer kernels), which could improve event delivery performance

I'm wondering if we don't also need some sort of event caching in between the tracee-ebpf and tracee-rules (not relying only in the channel buffering only, when both are part of the same proccess, as it may exhaust very fast).

Don't we need something **very fast** to remove perf buffer pressure and allow tracee-rules to be slower if it needs to ? Eventually this cache would be drained during workload relief.

</div>

**Comment by rafaeldtinoco** [comment]
Important comments about this:

https://github.com/aquasecurity/tracee/discussions/1442#discussioncomment-2122956

and

https://github.com/aquasecurity/tracee/discussions/1442#discussioncomment-2125086

**Comment by yanivagman** [comment]
> have a plan to have tracee-ebpf & tracee-rules part of the same process (multiple routines) and have a channel to pass over the received events.

We will still want those to live in two different processes for security reasons (drop caps)

**Comment by rafaeldtinoco** [comment]
* Code for the investigations is at the bottom of this comment.

**Some investigations made (@mtcherni95):**

1. **Regular pipebuf** (made in C, working as a pipe in between trace-ebpf and tracee-rules, using Glib async queue implementation)

2. **Golang pipebuf** (made in Cgo, working as a pipe in between tracee-ebpf and tracee-rules, using Glib async queue implementation with glibc malloc)

3. Same as "2" but, instead of using glibc malloc, using **jemalloc**, like described in https://dgraph.io/blog/post/manual-memory-management-golang-jemalloc/).

4. Golang **list** serving as a **FIFO queue** between 2 routines.

5. Increasing the **buffer size of the channel** responsible for the output prints.

**For the same workload, in the same environment:**

So far, (1) is winning by a big advantage. We can cache chunks of memory and allocate/release memory at will. Memory grows and shrinks as needed.

(2) and (3) did not perform well and still had event losses for the same workload (while (1) did not have). Like described in the jemalloc post, when using malloc from Cgo, we can't really control if glibc is giving back allocated memory to OS (and it holds memory even with appropriate frees()). When using jemalloc, the amount of memory allocated and released were right BUT, still, throughput of CGO calling GLIB queues was not great.

I was able to have a good throughput without too many looses with (4), but I could not control the allocated memory nor when the GC would be triggered (so the memory management seems erratic and we can't release allocated memory often, for smaller hosts). Also, the delays caused by the queueing were bigger than (1).

Michael and I tested (5) during our last talk and it caused event losses (so just increasing the channel buffer doesn't seem to be a good "caching/buffering" mechanism to reduce the ratio in between events production and consumption).

So, until now, I think we will have to implement a buffering mechanism in a fixed about of allocated memory (that won't grow or shrink) by using Go (for CNDR) AND the same (or (1)) for tracee open source (that will be the same as CNDR in near future).

CODES:

1.

```C
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include <pthread.h>

#include <glib.h>
#include <glib/gprintf.h>

#define chunk_size 1024

GAsyncQueue *queue;

void *readstdin(void *ptr) {
	gchar *entry;

	for(;;) {
		entry = g_malloc0(chunk_size);
		read(fileno(stdin), entry, chunk_size);
		g_async_queue_push(queue, entry);
	}
}

void *writestdout(void *ptr) {
	gchar *entry;

	for(;;) {
		entry = g_async_queue_pop(queue);
		g_printf("%s", (gchar *) entry);
		fflush(stdout);
		g_free(entry);
	}
}

int main(int arc, char **argv)
{
	pthread_t read_t, write_t;
	int ret = 0;

	queue = g_async_queue_new();

	ret |= pthread_create(&read_t, NULL, readstdin, NULL);
	ret |= pthread_create(&write_t, NULL, writestdout, NULL);

	if (ret != 0) {
		fprintf(stdout, "error creating threads\n");
		exit(1);
	}

	pthread_join(read_t, NULL);
	pthread_join(write_t, NULL);

	return 0;
}
```

2. and 3. (with glibc malloc and jemalloc malloc)

```go
package main

/*
#cgo CFLAGS: -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
#cgo LDFLAGS: -lglib-2.0

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <malloc.h>

#include <glib.h>
#include <glib/gasyncqueue.h>

GAsyncQueue *queue;

struct entries {
	int size;
	char *buffer;
};

int get_size(struct entries *entry) {
	return entry->size;
}

char *get_buffer(struct entries *entry) {
	return entry->buffer;
}

void init(void) {
	queue = g_async_queue_new();
}

void enqueue(void *buffer, int size) {
	struct entries *entry = calloc(sizeof(struct entries), 1);
	entry->size = size;
	entry->buffer = calloc(size, 1);
	memcpy(entry->buffer, buffer, size);
	g_async_queue_push(queue, entry);
}

struct entries *dequeue() {
	struct entries *entry = g_async_queue_pop(queue);
	return entry;
}

void release(struct entries *entry) {
	free(entry->buffer);
	free(entry);
}
*/
import "C"

import (
	"sync"
	"os"
	"io"
	"runtime"
	"log"
	"unsafe"
)

func errExit(why error) {
    _, fn, line, _ := runtime.Caller(1)
    log.Printf("error: %s:%d %v\n", fn, line, why)
    os.Exit(1)
}

func main() {
	var wg sync.WaitGroup

	C.init()

	wg.Add(1)
	go func() {
		defer wg.Done()

		bytes := make([]byte, 1024*1024)

		for {
			bytes := bytes[:cap(bytes)]
			n, e := os.Stdin.Read(bytes)
			if e != nil {
				if e == io.EOF {
					break
				}
				errExit(e)
			}
			bytes = bytes[:n]
			C.enqueue(unsafe.Pointer(&bytes[0]), C.int(n))
		}
	}()

	wg.Add(1)
	go func() {
		defer wg.Done()

		for {
			entry := C.dequeue()
			size := C.int(entry.size)
			buffer := unsafe.Pointer(entry.buffer)
			bytes := C.GoBytes(unsafe.Pointer(buffer), C.int(size))
			os.Stdout.Write(bytes)
			bytes = nil
			C.release(entry)
		}
	}()

	wg.Wait()
}
```

**Comment by rafaeldtinoco** [comment]
@mtcherni95 after investigations, I found out that the PR above is the one that dealt better with the situation (and had a satisfactory memory release). I've tested it multiple times and it seems to be working well. Let me know your feedback on that PR, please.

**Comment by yanivagman** [comment]
Currently, the tests ALWAYS fail.
This seems to be realted to the following error:
`error creating Tracee: could not read /boot/config-5.11.0-1028-azure: stat /boot/config-5.11.0-1028-azure: no such file or directory\n`

**Comment by yanivagman** [comment]
> Currently, the tests ALWAYS fail. This seems to be realted to the following error: `error creating Tracee: could not read /boot/config-5.11.0-1028-azure: stat /boot/config-5.11.0-1028-azure: no such file or directory\n`

#1532 should now resolve this

**Comment by yanivagman** [comment]
Question: can it be that the issue here is not related to lost events but to the fact that we are not waiting for tracee-ebpf to be ready correctly before starting tracee-rules?
Taking into account that we don't delete tracee.pid on exit, can it be that tracee.pid already exists in the system? Or maybe we create it twice (for when we probe for co-re), but start tracee-rules right after the probe, but not before it is REALLY ready?

**Comment by danielpacak** [comment]
@yanivagman @rafaeldtinoco Indeed, in #1540 I've added wait strategy to check if the `/tmp/tracee/out/tracee.pid` exists, but I'm not sure it's super reliable readiness check. I had to add an extra delay (of 10 seconds) to make smoke tests pass every time.

So I think we should also check that the tracee.pid file is not written too early. WDYT?

**Comment by danielpacak** [comment]
And looking into code it seems that we write `/tmp/tracee/out/tracee.pid` file before tracee.Run() is invoked. That might be a reason of lost events due to Go channel not being initialized.

**Comment by yanivagman** [comment]
> @yanivagman @rafaeldtinoco Indeed, in #1540 I've added wait strategy to check if the `/tmp/tracee/out/tracee.pid` exists, but I'm not sure it's super reliable readiness check. I had to add an extra delay (of 10 seconds) to make smoke tests pass every time.
> 
> So I think we should also check that the tracee.pid file is not written too early. WDYT?

@danielpacak @rafaeldtinoco if that's the case, then this is actually a regression. We used to do the wait in entrypoint.sh, and only start tracee-rules after tracee-ebpf is ready. If that's not the case now, then we need to fix it in entrypoint.sh, and not in the tests themselves

**Comment by danielpacak** [comment]
Indeed there was a while loop in https://github.com/aquasecurity/tracee/blob/v0.6.5/entrypoint.sh#L43 that probably caused a delay before the tracee-rules process was started.

**Comment by rafaeldtinoco** [comment]
I believe this issue is being worked in multiple pull requests: 

- #1540 (wait tracee-ebpf readiness, mitigation)
- #1527 (default caching, side effect resolution) 

And, since #1540 was just merged (and probably addressing the most common cause for flaky-ness), I'm closing this issue.
