### ISSUE TITLE
CoreOS environment support

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1457]
To check why CoreOS environment supports 0.6.0 but not 0.6.5. To check if adjustments are needed in order to get the next released supported in that environment.

**Comment by grantseltzer** [comment]
One thing I have noticed is that there isn't a retrievable kernel config available on the system.

**Comment by grantseltzer** [comment]
I've tried reproducing this again today and couldn't. I'm moving this to v0.7.1 milestone for now because i'm not yet confident enough to close it. @rafaeldtinoco can you share more details, especially the vagrant machine you're using.

**Comment by yanivagman** [comment]
Last status of this issue was "can't reproduce" almost a year ago
