### ISSUE TITLE
TRC-13: Unable to trigger

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#1459]
I was trying to execute TRC-13 with the following scenario:

```
$ KUBERNETES_SERVICE_HOST=127.0.0.1 nc -k -l -w 1 -p 10255 
$ KUBERNETES_SERVICE_HOST=127.0.0.1 curl -v http://127.0.0.1:10255/pods
$ KUBERNETES_SERVICE_HOST=127.0.0.1 curl -v http://127.0.0.1:10255/api --header "Authorization: Bearer 123" --insecure
```

But nothing was detected. Below are some logs:
```
sudo dist/tracee-ebpf -o format:gob | dist/tracee-rules --input-tracee file:stdin --input-tracee format:gob
Loaded 15 signature(s): [TRC-1 TRC-13  TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7]
```

I've tried on v0.6.5 and v0.6.4 so far. Here's a complete log of all events and actions https://gist.github.com/simar7/d6c65a1e2660bb5e558b56684330cda1

**Comment by vincent-pli** [comment]
@simar7 
See this issue: https://github.com/aquasecurity/tracee/issues/1326

**Comment by simar7** [comment]
Whoops- sorry I didn't see that. Thanks I'll close this then.
