### ISSUE TITLE
tracee-ebpf and tracee-rules events at container creation mismatch

### ISSUE THREAD

**Issue by OriGlassman** [aquasecurity/tracee#1467]
Hi,

Currently, there is no way for tracee-rules to distinguish between events that happen as part of a container creation and normal container events.

tracee-ebpf associate the events of the container creation to the host, while tracee-rules treat them as from container, since the containerId field is not empty.

For example, if one wants to create a signature, based on a certain event that happen when the container is already running, and that event also happen as part of the container creation and the containerId field is populated, has no way to tell.

Another way to look at it is if I were to set the signature to host origin, the signature won't be triggered, even though the events are  attributed to the host in tracee-ebpf (they are not shown with -t c).

**Comment by yanivagman** [comment]
Fixed by #1984
