### ISSUE TITLE
 "missing libbpf source - maybe do 'git submodule init && git submodule update

### ISSUE THREAD

**Issue by jpfreyen** [aquasecurity/tracee#1471]
I cloned v0.6.5 onto RHEL 8.2 (kernel 4.18.0-193.el8.x86_64) and typed 'make' on the top-level directory and got this error:

`[jfreyensee@rhel82 tracee]$ make
make -C tracee-ebpf mostlyclean dist/tracee-ebpf  OUT_DIR=dist && cp -r tracee-ebpf/dist/tracee-ebpf dist
make[1]: Entering directory '/home/jfreyensee/projects/tracee/tracee-ebpf'
rm -rf dist/tracee-ebpf dist/tracee.bpf dist/tracee.bpf.4_18_0-193_el8_x86_64.v0_6_5.o dist/tracee.bpf.core.o dist/tracee.bpf.tar.gz
test -d 3rdparty/libbpf/src || (echo "missing libbpf source - maybe do 'git submodule init && git submodule update'" ; false)
missing libbpf source - maybe do 'git submodule init && git submodule update'
make[1]: *** [Makefile:76: 3rdparty/libbpf/src] Error 1
make[1]: Leaving directory '/home/jfreyensee/projects/tracee/tracee-ebpf'
make: *** [Makefile:44: dist/tracee-ebpf] Error 2`

Sure enough there isn't a libbpf/src directory:

`[jfreyensee@rhel82 3rdparty]$ pwd
/home/jfreyensee/projects/tracee/tracee-ebpf/3rdparty
[jfreyensee@rhel82 3rdparty]$ ls
include  libbpf`

Is there a step I missed that should have happened before typing 'make'?  Can this step be a part of the Makefile?  Or maybe part of the README for building tracee?

Thank you!

**Comment by rafaeldtinoco** [comment]
Hello! We just changed our building schema, could you checkout HEAD and try running "make all" ? If your env does not work, you can use instructions of docs/building to get a building environment using docker (make -f builder/Makefile.tracee-make XXX).

I'll get you specific instructions soon, but checkout the HEAD documentation of how to build Tracee for now, it might help you.

**Comment by jpfreyen** [comment]
Thanks for the response!

With the new build I get the following:

`Failed to clone '3rdparty/libbpf'. Retry scheduled
Cloning into '/home/jfreyensee/projects/tracee/3rdparty/libbpf'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:libbpf/libbpf.git' into submodule path '/home/jfreyensee/projects/tracee/3rdparty/libbpf' failed`

I think it's because I don't have a public ssh key registered because I typically use https (https://github.com/libbpf/libbpf.git).  Let me set this up and try again

**Comment by rafaeldtinoco** [comment]
Right. And please check:

1. https://github.com/aquasecurity/tracee/blob/main/docs/building/environment.md
2. https://github.com/aquasecurity/tracee/blob/main/docs/building/containers.md
3. https://github.com/aquasecurity/tracee/blob/main/docs/building/packaging.md

AND, if you're using a kernel that does not support eBPF CO-RE, then you might need:

4. https://github.com/aquasecurity/tracee/blob/main/docs/building/nocore-ebpf.md

It is very likely that you will only need (1). You can compile an "alpine" based, or "ubuntu" based environment and use it to run the compiled binaries. OR you may event compile in your host (like you're trying to).

We're heading to 0.7 version and close to a freeze, so the HEAD version should be "stable enough" for you to play with. When we reach 0.7, published images will be like what you're playing now.

Let me know if you face any issues.

**Comment by jpfreyen** [comment]
Just a quick update from me, I was able to successfully compile from the recommended main/ branch on Oracle 8.5.  I'm going to review your documentation next, haven't had the time it to try running it or review the docs mentioned.  Thanks!

**Comment by yanivagman** [comment]
> question for u: I ran the example "sudo strace /bin/ls after I started trace via:
> 
> ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace comm=bash --trace follow --trace event!='sched*' | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json
> 
> Is this error something to be concerned about?:
> 
> 2022/02/15 16:59:00 error handling event by signature Standard Input/Output Over Socket: couldn't convert arg to addr

There's already an open issue for that: https://github.com/aquasecurity/tracee/issues/1260

**Comment by jpfreyen** [comment]
thank you :-)
