### ISSUE TITLE
tracee-rules - Unrecognized argument type

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1492]
When running tracee-ebpf on default settings and streaming to tracee-rules the following error is yield(attached)

[error.zip](https://github.com/aquasecurity/tracee/files/8110272/error.zip)

that's a few seconds recording - from that I derived the following list of unsupported types, but I'm sure that there are more that a quick search can find.
{'Name:parent_tid Type:int*}', 'Name:stdin_type Type:umode_t}', 'Name:dirp Type:struct linux_dirent64*}', 'Name:statbuf Type:struct stat*}'}

**Comment by yanivagman** [comment]
Seems that you didn't use the parse-arguments option.
Pointer values are printed here as raw numbers, thus the unmarshaler tries to decode them.
Is that the case?
