### ISSUE TITLE
broken pcap

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#1499]
currently captured pcap is broken: 
![image](https://user-images.githubusercontent.com/17714090/155147568-ea86a72a-db68-49cd-afc7-434257637468.png)

this is because the packets are saved from the wrong offset in `payloadBytes`, and the timestampts are wrong

**Comment by yanivagman** [comment]
@itamarmaouda101 can it be related to your latest changes?

**Comment by yanivagman** [comment]
Fixed in main
