### ISSUE TITLE
Produce `protocol.Event` in tracee-ebpf

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#1524]
Currently, `trace.Event`s are being converted to `protocol.Event` on consuming inside `tracee-rules` itself. As was already mentioned in #1482 this logic is backwards, but was a continuation of what was done before. Now this should be fixed.

Fixing this has two parts:
1. Requiring that events are already sent as `protocol.Event` on arrival to `tracee-rules` (so no conversions should be required at all).
2. Implement sending `protocol.Event`s from `tracee-ebpf`. I think this could be done with a new `output` flag, however there could other better ways which is why i'm opening the issue.

**Comment by yanivagman** [comment]
@NDStrahilevitz since #1531 has been close, can this be closed as well?

**Comment by NDStrahilevitz** [comment]
@yanivagman I think that with everything is an event we should aim to remove the `protocol.Event` and use only `trace.Event` directly. However CNDR currently relies on the protocol feature for updating signature data so #2561 is a requirement before that.

**Comment by josedonizetti** [comment]
Agree with @NDStrahilevitz, though we have an umbrella issue for everything is an event, which this is already tracked, makes sense to close this one? https://github.com/aquasecurity/tracee/issues/2355

**Comment by rafaeldtinoco** [comment]
> However CNDR currently relies on the protocol feature for updating signature data so #2561 is a requirement before that.

I would like this statement to be further explored/clarified. If that is true, maybe the protocol.Event removal could be part of #2355 and another issue just for that should be used/created.

**Comment by rafaeldtinoco** [comment]
Alright, so https://github.com/aquasecurity/tracee/issues/2561 takes care of state saving and protocol.Event removal can be part of @josedonizetti's epic. Lets close this one then (@josedonizetti as long as you have a specific note added to the single binary issue for tracking this).
