### ISSUE TITLE
magic_write: Missing hook in direct_splice_actor

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1552]
In the effort to expand the `magic_write` event to catch all file operations, the `direct_splice_actor` function is targeted as one of the functions that envelope the use of the file operation `splice_write` for kernel uses.
This function is used by the `sendfile` syscall.

This is sub-issue of the #1357 issue.

**Comment by AlonZivony** [comment]
The solution for this issue will need to use page addresses, which means it depends on #1507

**Comment by yanivagman** [comment]
Closing since it is a sub-task of #1357 and not being actively worked on
