### ISSUE TITLE
limit number of opened pcaps

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#1554]
currently the number of opened pcaps is not limited, and may be very big on high volume systems (many processes/containers that send/reveive network packets).

usually, the soft limit of opened file descriptors per process in 1024. so a situation may occur that this limit will be reached because of all the opened pcaps - this will result in tracee failing to open any new file descriptors (files, sockets, etc.).

**Comment by rafaeldtinoco** [comment]
This was closed already by commit: d3fad4df
