### ISSUE TITLE
adding uprobes to Tracee

### ISSUE THREAD

**Issue by itamarmaouda101** [aquasecurity/tracee#1573]
Hi 

We should add support to uprobes events in Tracee. in order to add the ability to trace user-space events.

Currently, I'm working on PR that adds that to Tracee (:

**Comment by itaysk** [comment]
this sounds very interesting! please describe the use case - why you need it and how you are seeing the user uses it. Also if you have a design in mind please discuss it here before you start implementing it. We also planned something similar so please coordinate with us before you start working on this, to make sure you spend your time effectively.

**Comment by itaysk** [comment]
Also it's a dup of #363 so please let's discuss is there
