### ISSUE TITLE
No documentation of events

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1579]
I noticed that there is no accessible documentation of events.
I think that at first all events were in the shape of the function the hook was on - had the same name and the same arguments.
However, today we can see more and more events with logic inside them, and I can't find a fair documentation on them.
For example, the `magic_write` event which is one of the most interesting events we have today is not documented anywhere except for the `tracee.bpf.c` file which is not where most users will search for documentation.

I suggest adding a field for each event in the `events_definitions.go` file that tells that documents what is the event, and have a way in the CLI to read the documentation of each event.

EDIT (copy from #1855):
After https://github.com/aquasecurity/tracee/pull/1808, we have to start enforcing the DocPath existence and the file format every time an event is added to tracee.

https://github.com/aquasecurity/tracee/pull/1808#issuecomment-1161755558
https://github.com/aquasecurity/tracee/pull/1808#issuecomment-1161843244

**Comment by AlonZivony** [comment]
Following other projects which do documentation better than us, me and @rafaeldtinoco thought about doing the following procedure:
* For each event / event group a "man page" will be created in the doc directory (doc/events for example)
* For each event in the `events_defenition.go` file, a link to the relevant doc page will be given.
* A CLI option will be given to read the man page of a given event

This way, the documentation will be available through the golang docs and through the CLI in the same time.
For example to a project that do this kind of style, have a look at [`systemtap`](https://www.sourceware.org/systemtap/):
* Each script has a man page associated with it.
* The man pages are available through the [online documentation](https://sourceware.org/systemtap/tapsets/).

This means we will add a mandatory step for each event to add a valid link to a documentation file.

**Comment by itaysk** [comment]
please also consider https://github.com/aquasecurity/tracee/issues/436

**Comment by yanivagman** [comment]
Events were recently exposed in the online documentation.
Closing in favor of #2809
