### ISSUE TITLE
tracee-rules fails when piping `metrics` enabled tracee-ebpf through stdin

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#1581]
First i'll note this won't affect the docker images or tests since we're using a separate named pipe in these cases.

In short the bug is reproduced as such:
```
tracee-ebpf --metrics --output gob --output option:parse-arguments | tracee-rules --input-tracee=format:gob --input-tracee file:stdin
Loaded 14 signature(s): [TRC-1 TRC-13 TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7]
2022/03/24 13:02:27 error while decoding event: gob: duplicate type received
2022/03/24 13:02:27 error while decoding event: gob: duplicate type received
2022/03/24 13:02:27 error while decoding event: gob: unknown type id or corrupted data
2022/03/24 13:02:27 error while decoding event: gob: unknown type id or corrupted data
2022/03/24 13:02:27 error while decoding event: gob: type mismatch in decoder: want struct type trace.Event; got non-struct
```

With json format this isn't crashing but a similar error occurs, I guess this is because the gob module panics on some errors. I'm not sure what's the best way to solve this and if we should at all, but we should at least document it in case someone has this problem.

**Comment by itaysk** [comment]
I suspect some errors are written to stdout when using the metrics flag, in which case it is a bug. Can you look into it?

**Comment by danielpacak** [comment]
I can reproduce and it seems that this line is causing error https://github.com/aquasecurity/tracee/blob/v0.7.0-rc-1/cmd/tracee-ebpf/main.go#L193

```go
fmt.Fprintf(os.Stdout, "Serving metrics endpoint at %s\n", metricsAddr)
```

I think @itaysk is right that we have clutter in stdout when --metrics or --debug flag is used. The stream of events should be separated somehow from debug statements.

**Comment by NDStrahilevitz** [comment]
@danielpacak Yep, this is the causing line, should've mentioned it in the original comment, I'm just not sure we can do much about it since there's no other sensible place to log it to IMO.
The solutions I see are:
1. Putting it under the debug flag (which is more like putting this issue under the rug)
2. Disabling piping tracee-ebpf through stdout (so a pipe must be provided explicitely)
3. Moving this message to stderr (except it isn't an error)

I think option 3 is the least bad one of those but I don't really like any of them.

**Comment by danielpacak** [comment]
There is one more option to remove the line I mentioned at all and only print errors to stderr if there is any problem with registering metrics handler.

**Comment by NDStrahilevitz** [comment]
When I added this I based the logging on tracee-rules's pprof server, which would always print on success (without checking for a debug flag).
Considering what you said, adding a debug flag protection for this would be the correct solution, so I'll upload a PR for that after the weekend.

**Comment by itaysk** [comment]
> When I added this I based the logging on tracee-rules's pprof server, which would always print on success (without checking for a debug flag).

tracee-rules isn't as strict as tracee-ebpf but sounds like we should fix the behavior there as well (good catch)

> debug flag with the metrics flag and gob formatting would be broken, so we might want to document that (maybe in the flag?)

yes sounds like a good clarification to make ( that using --debug is contaminating the event stream)

> Maybe we should indicate in the stream that a debug message is being sent and filter them out in tracee-rules input streaming?

IMO  it's not a good idea to couple tracee-ebpf and tracee-rules like this. Tracee-ebpf should be usable also without tracee-rules

> Maybe add a debug flag to tracee-rules to enable this behavior?

mabye, but not for this behavior rather for your first catch about pprof

> I don't think the debug flag should break working behavior.

I can relate, but lets please fix this quickly for the release so we can actually use the metrics feature, and then think about how to fix debug logging for next version.

**Comment by NDStrahilevitz** [comment]
> yes sounds like a good clarification to make ( that using --debug is contaminating the event stream)

Then I'll add that to the usage in the relevant PR.

> IMO it's not a good idea to couple tracee-ebpf and tracee-rules like this. Tracee-ebpf should be usable also without tracee-rules

You're right, I was just throwing the idea out.

> I can relate, but lets please fix this quickly for the release so we can actually use the metrics feature, and then think about how to fix debug logging for next version.

Okay, so I'll upload a PR protecting this output (and others if I catch them) and documenting it in the debug usage flag after the weekend, and then I'll open a follow up issue on this (that debug breaks behavior). Sounds good?

**Comment by itaysk** [comment]
> Okay, so I'll upload a PR protecting this output (and others if I catch them) and documenting it in the debug usage flag after the weekend, and then I'll open a follow up issue on this (that debug breaks behavior). Sounds good?

sounds good except for the timeline. We wanted to cut the release this week. so perhaps someone who does work today will pick it up if you can't

**Comment by NDStrahilevitz** [comment]
No intention to keep this up if this is a blocker, I uploaded a PR for your review @itaysk
