### ISSUE TITLE
TRC-11 triggered from runc process

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1611]
![image](https://user-images.githubusercontent.com/7395852/160599247-5475fffc-c3fa-4444-91d7-cf268b35f78a.png)

and related discussion:

![image](https://user-images.githubusercontent.com/7395852/160599291-7e5a4a04-c53c-4661-b55e-6dd089276ddb.png)

**Comment by roikol** [comment]
i think the easy aaproach which is also good is to check whether its the `runc` process, with `tid == 1`. if it is the case - do not trigger.

the other approach is to create an event of `container_start`, and only trigger after the container started. in this case, this signatures should be rewritten to go, as it becomes statefull (need to keep track of started containers).

@rafaeldtinoco @yanivagman any thoughts?

**Comment by yanivagman** [comment]
We now have the container_started flag which can be used in this rule to distinguish runc processes.
@roikol @AsafEitani I think all existing rules should be revisted and use this flag instead of excluding the runc process
