### ISSUE TITLE
Make use of BPF_PROG_TYPE_TRACING programs instead of raw tracepoints if kernel supports it

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#1623]
In kernel 5.5 BPF_PROG_TYPE_TRACING was introduced which offers better performance than raw tracepoints which we currently use for most probes such as system calls. https://github.com/aquasecurity/libbpfgo/issues/140 must be completed first.

**Comment by yanivagman** [comment]
@grantseltzer I think this is a duplication of #475 as fentry is the attach mechanism for BPF_PROG_TYPE_TRACING type as can be seen here: https://lore.kernel.org/bpf/20191102220025.2475981-5-ast@kernel.org/

And as far as I understand it should be used as a replacement for kprobes programs and not raw tracepoints, as explained here: https://lwn.net/Articles/804937/

So, if that's correct, we can close this one

**Comment by grantseltzer** [comment]
@yanivagman Can you update the contents of that issue as it contradicts what you're saying here? I do believe you're correct that fentry/fexit refers to the attachment mechanism for programs of type BPF_PROG_TYPE_TRACING. I'm currently investigating how to make the actual attachment, I'm not sure libbpf yet has an API to do so.
