### ISSUE TITLE
eBPF CO-RE functionality improvements

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#1624]
- [ ] Make use of bpf global variables for configuration and other read-only applications (#784, https://github.com/aquasecurity/libbpfgo/issues/27)
- [ ] #476
- [ ] #475 
- [ ] #474
- [ ] Remove `always_inline` attribute from functions that no longer need them based on kernel version (needs investigation)
- [ ] #1636

**Comment by yanivagman** [comment]
Regarding removing the `always_inline` attribute, please note that this doesn't play well with tail calls, as explained here: https://docs.cilium.io/en/stable/bpf/#bpf-to-bpf-calls

**Comment by yanivagman** [comment]
Also, there is this one (bounded loops since 5.3): https://github.com/aquasecurity/tracee/issues/474

**Comment by yanivagman** [comment]
No need for this epic. Let's stay with individual issues
