### ISSUE TITLE
Improve specification of events loading

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1628]
Currently tracee-ebpf uses multiple methods to save the state of a signature:
1. `EssentialEvent` of the `EventDefinition` struct
2. `eventsToTracee` of the `Tracee` struct

These methods come to imply what to do with the event:
- Load the eBPF program of the event
- Submit the event from the kernel to the user-mode
- Send the event to the user by the output events channel

The current way to monitor what to do with the events is clumsy and less readable. It is also not a good practice to change the `EventsDefinitons` global, that is supposed to be constant (because it is a kind of a configuration).
There should be a centralized way to monitor all the operations of each event that unite the two methods.

**Comment by itaysk** [comment]
Is there a PR that fixed this?

**Comment by AlonZivony** [comment]
It was fixed mainly in #1657 but it wasn't fixed specifically, so it is hard to say exactly which PR fixed it.

**Comment by itaysk** [comment]
Asking because you closed it as "completed" but no linked PR
