### ISSUE TITLE
processEvents + parseArgs: for call_usermode_helper, proc_create, debugfs_create_file, debugfs_create_dir events

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1650]
@itamarmaouda101 (this is a suggestion, check with your team if this is needed please):

After https://github.com/aquasecurity/tracee/pull/1566 and https://github.com/aquasecurity/tracee/issues/1613, it occurred to me that some of the events created to solve those issues should have their arguments parsed (`t.processEvents -> t.parseArgs()`) depending on given cmdline flag:

```
sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments -o option:detect-syscall -trace event=call_usermodehelper,proc_create,debugfs_create_file,debugfs_create_dir
```

Arguments I can clearly see would deserve some parsing are:

1. call_usermodehelper: hexa (0xfff...) for argv/envp pointers.
2. proc_create: hexa (0xfff...) for proc_ops_addr pointer.
3. debufs_create_file: mode_t parsing (S_IRUSR, S_IRWXU, ...) and hexa (0xfff...) proc_ops_addr pointer.
4. debugfs_create_dir: (N/A)

**Comment by rafaeldtinoco** [comment]
@itamarmaouda101 

You have added `DebugfsCreateDir` to events_processor in PR: #1649 , Maybe you should do the same for #1648 changes. I believe you can add all needed events_processor using this issue and a PR containing commit(s) to address the parsing.

**Comment by yanivagman** [comment]
@AsafEitani is this issue relevant or can we close it?

**Comment by AsafEitani** [comment]
1 - Resolved.
2 - We currently do not use the proc_ops_addr field, and IDK if we want to parse it... https://elixir.bootlin.com/linux/v5.15/source/include/linux/proc_fs.h#L29
3 - Same as 2, we don't use the mode but shouldn't it be converted automatically due to its type?
4 - Resolved by @rafaeldtinoco 

I don't see a need to push this.

**Comment by yanivagman** [comment]
> I don't see a need to push this.

Closing it then
