### ISSUE TITLE
missing output in docker?

### ISSUE THREAD

**Issue by falcorocks** [aquasecurity/tracee#167]
Hi, I'm trying  to deploy tracee as a docker container, I'm interested in extracting the output of tracee as a file.

According to the help manual
```
--output-path value                 set output path (default: "/tmp/tracee")
```

Expected behaviour:
The stdout should be located in `/tmp/tracee`

Actual behaviour:
no file is ever generated in `/tmp/tracee`

To reproduce:
```
# start container in detached mode
docker run -d --name tracee --rm --privileged -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro aquasec/tracee:latest

# attach to container
docker exec -ti tracee bash

ls /tmp/tracee
```

I suspect I'm misunderstanding something because the tool is great!

**Comment by falcorocks** [comment]
From re-reading your readme I think I figured it out, the --output-path is for when the --capture flag is used.

**Comment by itaysk** [comment]
Yes you figured it out. If you are looking to save the log output to a file you can use shell output redirection
```
tracee > path/to/file
```

**Comment by falcorocks** [comment]
thanks for the suggestion!
I was putting together a minimal docker-compose to easily deploy your tool, so to make things simpler I ended up relying on docker logs functionality. I look forward to share my docker-compose in a PR as soon as I have time
