### ISSUE TITLE
Decoding long as a 64bit integer

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1671]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.
- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

Currently we interpret `long` type as a 32bit variable when decoding events arguments from the kernel.
However, this is not the real definition for `long` in the kernel.
`long` type is 32bit integer, and `long long` is 64bit.

I encountered it while trying to use `loff_t` in tracee-rules, and got error that the type is not supported in `GetParamType`.
When I came to add it to the function I noticed that `off_t` is interpreted as a 64bit unsigned integer, and long is 64bit signed integer. `loff_t` is a typedef for `long long` type. I understood that we have a parsing bug here.

## Additional Information

I am not sure what are the consequences of the miss-parsing, but I guess that there might be bugs hiding here.

**Comment by AlonZivony** [comment]
After checking in the eBPF code it seems that both `long` and `long long` are 64bit in my system.
The same is for `off_t` and `loff_t`.
Anyways, I will close the issue for it doesn't matter in this case.

**Comment by rafaeldtinoco** [comment]
@AlonZivony and we are doing bitwise ops in signed variables, and u32 and ints being used in interchanged ways. Things are "working" but a review on types being passed back and forth to maps (and through perf map) could be helpful (specially and we start supporting arm64 through cross compiling and fully emulated VMs testing).
