### ISSUE TITLE
Create a signature for syscall detection in tracee-rules

### ISSUE THREAD

**Issue by itamarmaouda101** [aquasecurity/tracee#1672]
## Prerequisites

- [x] I'm going to create a PR to solve this (assign to yourself)

## Feature description
We should add to tracee-rules a signature to the detect_hooked_syscalls event.

## Context

* Linux version: Ubuntu 20.04.3 LTS
* Linux kernel version: 5.13.0-39-generic
* Tracee version (or commit id of your tree): de2749f27f2a0bf891018f547012ec2263fdf08f
* LLVM version: llc-12
* Golang version: go1.17.6

**Comment by AsafEitani** [comment]
#1705
