### ISSUE TITLE
TC error message when using net events

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1676]
## Prerequisites

- [x] I checked the documentation and found no answer.
- [x] There isn't an issue describing the bug.
- [ ] I can reproduce the issue in latest released version.
- [x] I can reproduce the issue in development version.

## Bug description

When tracing a net event, the following error is received for each interface monitored:
_libbpf: Kernel error message: Exclusivity flag on, cannot modify_

This is the normal flow of the program, so it shouldn't create any error.
This error should be suppressed. 

## Steps to reproduce

```
$ sudo ./dist/tracee-ebpf --capture net=<interface> --output none
libbpf: Kernel error message: Exclusivity flag on, cannot modify
```

## Context

* Linux version: Manjaro
* Linux kernel version: 5.10.105
* Tracee version (or commit id of your tree): de2749f2

**Comment by yanivagman** [comment]
Also see this: https://www.spinics.net/lists/bpf/msg44842.html

**Comment by rafaeldtinoco** [comment]
This has been mitigated by:

https://github.com/aquasecurity/libbpfgo/pull/174

and I'll bump libbpfgo dependency version and it will fade away.
