### ISSUE TITLE
empty process context for net_packet event

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#1688]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.
- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

When tracing net events (currently the only net event is net_packet), and not capturing net, the process context of the net_packet event is empty.

## Steps to reproduce

cmdline:
`./dist/tracee-ebpf --trace event=net_packet --capture net=enp0s3`

result:
![image](https://user-images.githubusercontent.com/17714090/165305796-419e47e9-1619-4e64-af59-36e86985ae53.png)

## Context

* Linux version: Ubuntu 20.04.2 LTS
* Linux kernel version: 5.13.0-39-generic
* Tracee version (or commit id of your tree): 2a606cbfab417942132e9dc73a146aa2ddef249e
* LLVM version: 12
* Golang version: 1.18.1

## Additional Information

When also capturing net, the process context is as expected. Also, for processes running before tracee is started, the process context is as expected.

This is because the process tree is updated only if `OPT_PROCESS_INFO` (`optProcessInfo`) is set, and it set only on this condition: 

`t.config.Capture.NetIfaces != nil || t.config.Debug` 

https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/tracee.go#L504

**Comment by rafaeldtinoco** [comment]
@roikol 

Thinking more about this one, I believe we should have checked for length instead of != nil:

```diff
commit c6f382e6 (HEAD -> int-to-trace-fix)
Author: Rafael David Tinoco <rafaeldtinoco@gmail.com>
Date:   Tue Apr 26 22:49:22 2022

    network: InterfacesToTrace should be checked by length

    Commit 82b4ec3e ("fix empty process context for net_packet event
    (#1692)") checks if InterfacesToTrace is not null but it should check
    for length being bigger than 0 instead.

diff --git a/pkg/ebpf/tracee.go b/pkg/ebpf/tracee.go
index d22222db..66d6a666 100644
--- a/pkg/ebpf/tracee.go
+++ b/pkg/ebpf/tracee.go
@@ -281,7 +281,7 @@ func New(cfg Config) (*Tracee, error) {
                t.events[MprotectEventID] = eventConfig{}
                t.events[MemProtAlertEventID] = eventConfig{}
        }
-       if t.config.Capture.NetIfaces != nil || t.config.Filter.NetFilter.InterfacesToTrace != nil || cfg.Debug {
+       if t.config.Capture.NetIfaces != nil || len(t.config.Filter.NetFilter.InterfacesToTrace) > 0 || cfg.Debug {
                t.events[SecuritySocketBindEventID] = eventConfig{}
        }

@@ -501,7 +501,7 @@ func (t *Tracee) getOptionsConfig() uint32 {
        if t.containers.IsCgroupV1() {
                cOptVal = cOptVal | optCgroupV1
        }
-       if t.config.Capture.NetIfaces != nil || t.config.Filter.NetFilter.InterfacesToTrace != nil || t.config.Debug {
+       if t.config.Capture.NetIfaces != nil || len(t.config.Filter.NetFilter.InterfacesToTrace) > 0 || t.config.Debug {
                cOptVal = cOptVal | optProcessInfo
                t.config.ProcessInfo = true
        }
```

Do you agree ? I can merge this change if you do.

**Comment by roikol** [comment]
@rafaeldtinoco 
agreed, no problem. it's better to be on the safe side. 
thanks!
