### ISSUE TITLE
Rootkit hooking detection

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1703]
## Prerequisites

- I'll create a PR to implement this feature (assign to yourself).

## Feature description

This feature is about adding rootkit hooking detection and enabling rules writing on it.
The following PR should be merged by order:

- [x] #1709
- [x] #1672
- [x] #1560
- [x] #1582 

PR numbers will be updated once they are open.

**Comment by yanivagman** [comment]
All relevant PRs were merged
