### ISSUE TITLE
PIPE_BUF_FLAG_CAN_MERGE not exists prior to kernel 5.8

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1712]
## Prerequisites

- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [x] Someone else should solve this.

## Bug description

The `PIPE_BUF_FLAG_CAN_MERGE` flag doesn't exists before kernel 5.8 (maybe earlier but no older than 5.4).
This causes a crash in tracee compilation in kernels older than and including 5.4.

This is how I'm executing tracee (cmdline):
New tests fails - https://github.com/aquasecurity/tracee/runs/6214021411?check_suite_focus=true

This is the error I'm getting:
```
llc \
	-march=bpf -mcpu=v2 \
	-filetype=obj \
	-o dist/tracee.bpf.5_4_1[66](https://github.com/aquasecurity/tracee/runs/6214021411?check_suite_focus=true#step:4:66)-ubuntu+..o \
	dist/tracee.bpf.5_4_166-ubuntu+..ll
rm dist/tracee.bpf.5_4_166-ubuntu+..ll
./pkg/ebpf/c/tracee.bpf.c:4852:39: error: use of undeclared identifier 'PIPE_BUF_FLAG_CAN_MERGE'
    if ((out_pipe_last_buffer_flags & PIPE_BUF_FLAG_CAN_MERGE) == 0) {
                                      ^
1 error generated.
llc: error: llc: dist/tracee.bpf.5_4_166-ubuntu+..ll: error: Could not open input file: No such file or directory
rm: cannot remove 'dist/tracee.bpf.5_4_166-ubuntu+..ll': No such file or directory
make: *** [Makefile:338: dist/tracee.bpf.5_4_166-ubuntu+..o] Error 1
[  127.594821][    T1] reboot: Power down
TEST: FAILED
Error: Process completed with exit code 1.
````
## Steps to reproduce

Steps to reproduce the issue:

1. run tracee new tests (NON-CO-RE)

## Context

Relevant information about my setup:

* Linux version: ubuntu
* Linux kernel version: 5.4
* Tracee version (or commit id of your tree): b69403034eb96285bfa56ab161b975d487f9b602
* LLVM version: 12
* Golang version: 1.17

**Comment by AlonZivony** [comment]
This is duplicate of #1659
