### ISSUE TITLE
trace_tcp_connect event raise error on CO-RE 4.19 test compilation

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1713]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.
- [x] Someone else should solve this.

## Bug description

Tracee CO-RE 4.19 test fails for `trace_tcp_connect` event for `Invalid argument`

This is how I'm executing tracee (cmdline):
Tracee CO-RE tests 

This is the error I'm getting:
https://github.com/aquasecurity/tracee/runs/6214057909?check_suite_focus=true
```
[377] TYPEDEF trace_security_socket_bind type_id=376
[378] Invalid btf_info:8400000a
-- END BTF LOAD LOG --
Loaded 1 signature(s): [TRC-2]
libbpf: Error loading .BTF into kernel: -22. BTF is optional, ignoring.
libbpf: prog 'trace_tcp_connect': BPF program load failed: Invalid argument
libbpf: failed to load program 'trace_tcp_connect'
libbpf: failed to load object 'embedded-core'
2022/04/28 15:39:37 error creating Tracee: failed to load BPF object
VM ERROR: time out waiting for tracee initialization
[  162.021142] reboot: Power down
TEST: FAILED
```

## Steps to reproduce

Steps to reproduce the issue:

1. run tracee tests

## Context

Relevant information about my setup:

* Linux version: stable
* Linux kernel version: 4.19
* Tracee version (or commit id of your tree): 
* LLVM version: 12
* Golang version: 1.17

**Comment by rafaeldtinoco** [comment]
This is a duplicate of: https://github.com/aquasecurity/tracee/issues/1670

**Comment by rafaeldtinoco** [comment]
@AsafEitani

I'm closing this one and assigning @roikol to that one.
