### ISSUE TITLE
Tracee-Rules filter mediation

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#1729]
## Prerequisites

- [ ] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [x] I'll create a PR to implement this feature (assign to yourself).

## Feature description

In order to configure tracee-ebpf filters during runtime according to signature needs, the metadata described in #1728 should be used to send requests to the API in #1726.
This request mediation should happen in the tracee-rules `cmd`, in order to decouple from the engine itself.

## Additional Information (feature drawings, files, logs, etc)

<img width="656" alt="image" src="https://user-images.githubusercontent.com/22661609/166468493-a8a9ebf7-2b3a-423d-8ef9-c34fe3c475b5.png">

**Comment by yanivagman** [comment]
With the new tracee binary, this becomes irrelevant
