### ISSUE TITLE
Arg names should not be parsed within the event processing loop

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#173]
https://github.com/aquasecurity/tracee/pull/165 added arg names which are encoded into a uint8, and decoded when reading the event fro the buffer. When reading the event, and also while processing it, theres no need for the arg name, the tag (uint8 encoding) suffice. the name decoding code should be moved out of the event loop and into a printing related region, presumably the `newEvent` function.

Mentioned in review: https://github.com/aquasecurity/tracee/pull/165#discussion_r464038945

**Comment by yanivagman** [comment]
Resolved in #176
