### ISSUE TITLE
Create an event for collision of SO symbols

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1753]
One known way to create hook and running malicious code is using the LD_PRELOAD method.
In this way, an attacker can export the same function as `libc` or other used shared library, and by loading the malicious shared object before the known one the loader will resolve the imported symbol to be of the malicious shared object instead of the normal one.
To locate this issue, we need event that can check if a shared object loaded to a process has the same symbols as another one.

**Comment by rafaeldtinoco** [comment]
Solved by https://github.com/aquasecurity/tracee/pull/2053 and https://github.com/aquasecurity/tracee/pull/2740
