### ISSUE TITLE
Does compile a eBPF CO-RE program need kernel open with CONFIG_DEBUG_INFO_BTF=y?

### ISSUE THREAD

**Issue by jerryhanhuan** [aquasecurity/tracee#1760]
I'm confused about eBPF CO-RE，I think the eBPF CO-RE program need the target kernel with CONFIG_DEBUG_INFO_BTF=y, but not the compiler enviroment, the compiler enviroment just need the clang 10 + and vmlinux.h， is that correct?

**Comment by yanivagman** [comment]
CO-RE bpf objects can run on kernels with CONFIG_DEBUG_INFO_BTF=y,
OR if you have the BTF of the running kernel, which can be provided when loading the program (for Tracee, this can be provided using TRACEE_BTF_FILE environment varialble).
To compile tracee, clang 12 is required (clang 10 misses some features required by Tracee, but can be used in other project to compile CO-RE object, I guess)
vmlinux.h is used as the header in the bpf file to get the relevant kernel types when compiling it as CO-RE.

**Comment by jerryhanhuan** [comment]
I have some tests on the  ubuntu 18.04  that not have CONFIG_DEBUG_INFO_BTF，I can complie CO-RE in ubuntu 18.04, with clang 13 and vmlinux.h，But the eBPF program can not run，it occurs with error:libbpf: failed to find valid kernel BTF， but can running on the machine with CONFIG_DEBUG_INFO_BTF=y. So, I think that is correct: CO-RE complie just need vmlinux.h and clang and libbpf， only running need the BTF.

**Comment by yanivagman** [comment]
Does your question refer to compiling Tracee or compiling CO-RE bpf in general?
If a general question, let's move this to a discussion

**Comment by jerryhanhuan** [comment]
> Does your question refer to compiling Tracee or compiling CO-RE bpf in general? If a general question, let's move this to a discussion

I want to know exactly can I compiling Tracee with CO-RE without CONFIG_DEBUG_INFO_BTF=y，but run the Tracee  with CONFIG_DEBUG_INFO_BTF=y. Is the clang record the relocation information using the vmlinux.h and co-re function，not using BTF on the compiling ?

**Comment by yanivagman** [comment]
Your understanding is correct.
To compile tracee, you need vmlinux.h (which is provided in this repo for the specific structures used by tracee) and libbpf (which is also provided as a submodule of this project). CONFIG_DEBUG_INFO_BTF=y is not required to compile CO-RE objects. In fact, you can use the makefile of tracee to compile it inside a docker container, without any further requirement.

To run Tracee, you either need a kernel with CONFIG_DEBUG_INFO_BTF=y or to provide the BTF file of your kernel (which must be >= 4.18). That's it.

**Comment by jerryhanhuan** [comment]
> Your understanding is correct. To compile tracee, you need vmlinux.h (which is provided in this repo for the specific structures used by tracee) and libbpf (which is also provided as a submodule of this project). CONFIG_DEBUG_INFO_BTF=y is not required to compile CO-RE objects. In fact, you can use the makefile of tracee to compile it inside a docker container, without any further requirement.
> 
> To run Tracee, you either need a kernel with CONFIG_DEBUG_INFO_BTF=y or to provide the BTF file of your kernel (which must be >= 4.18). That's it.

Thanks a lot.
