### ISSUE TITLE
[BUG] Probing tracee-ebpf capabilities is not required when using the trace subcommand

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1765]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description
When running tracee with the trace subcommand, a few seconds are wasted while probing for tracee-ebpf capabilities. This is not required when the user is about to run tracee-ebpf anyway.

This is how I'm executing tracee (cmdline):
docker run   --name tracee --rm -it   --pid=host --cgroupns=host --privileged   -v /etc/os-release:/etc/os-release-host:ro   -e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host   aquasec/tracee:dev trace

This is the error I'm getting:
INFO: probing tracee-ebpf capabilities...

## Steps to reproduce

Steps to reproduce the issue:

1. step 1
2. step 2

## Context

Relevant information about my setup:

* Linux version:
* Linux kernel version:
* Tracee version (or commit id of your tree):
* LLVM version:
* Golang version:

**Comment by cdelzotti** [comment]
Hello ! Can I work on that ? :)

**Comment by rafaeldtinoco** [comment]
@cdelzotti it is yours, it might be as simple as:

```
$ git diff -- builder/entrypoint.sh
diff --git a/builder/entrypoint.sh b/builder/entrypoint.sh
index afd75a9c..7f2fb2c3 100755
--- a/builder/entrypoint.sh
+++ b/builder/entrypoint.sh
@@ -45,11 +45,6 @@ probe_tracee_ebpf() {
 }

 run_tracee_ebpf() {
-    probe_tracee_ebpf
-    if [ ${TRACEE_RET} -eq 2 ]; then
-        return
-    fi
-
     ${TRACEE_EBPF_EXE} $@
     TRACEE_RET=$?
 }
```

But you will have to make sure the container generation (through correct makefile build targets) are good after that change (and you can execute the generated container as tracee AND tracee-ebpf only).
