### ISSUE TITLE
[BUG] Output is cluttered with "unknown runtime" messages

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/tracee#1789]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [ ] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

The output of Tracee is cluttered with "unknown runtime" messages so it's hard to see detections.

## Steps to reproduce

I'm just compiling Tracee and running it in the Vagrant machine:

```console
$ sudo ./dist/tracee-ebpf --output=format:gob --output=option:parse-arguments | ./dist/tracee-rules --input-tracee=file:stdin --input-tracee=format:gob
Loaded 15 signature(s): [TRC-1 TRC-13 TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-8 TRC-6 TRC-10 TRC-7 TRC-15]
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
unknown runtime
```

## Context

Relevant information about my setup:

* Linux version: Ubuntu 21.10 (Impish Indri)
* Linux kernel version: 5.13.0-44-generic
* Tracee version (or commit id of your tree): 3e1990b17dfecde6daa0378abfc7a0f47e71fafb
* LLVM version: 12.0.1
* Golang version: go1.17 linux/amd64

## Additional Information (files, logs, etc)

N/A

**Comment by NDStrahilevitz** [comment]
So i'm not sure how this is replicated - since these should be relevant to some container spawning (otherwise the earlier error of `"no containerId"` would be returned), but regardless of that - in hindsight maybe those error messages would be more relevant under a debug flag condition, instead of being piped to the error channel.
Would that solution be fine?

**Comment by danielpacak** [comment]
Currently it's making stdout unreadable. I'm afraid that if we do the same behind the debug flag we'll make debug output unreadable. If we used structured logger such as Zap this would probably be go under the trace log level.

**Comment by NDStrahilevitz** [comment]
We could add the cgroup id to the error and improve it's context, but it would still make a lot of noise in affected envs.
So the question remains, do we just remove the error logging for this feature, or move it down to debug (until we can add logging levels)?
