### ISSUE TITLE
[BUG] Capabilities enforcement apply only for 1 thread

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1813]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

This bug was discovered while investigating #1803 
We noticed that the error message we received isn't received on each run, only for part of them.
When forcing only 1 goroutine, the error occurs in much more runs.
@yanivagman suggested that the current capabilities package change only thread's capabilities, which might not be the thread with reduced capabilities. See the discussion in #1803 for more details.

This is how I'm executing tracee (cmdline):
`sudo ./dist/tracee-ebpf -o none -o option:parse-arguments -o option:detect-syscall-trace comm-bash -trace follow`

This is the error I'm getting:
Inconsistently, get the following error message:
![image](https://user-images.githubusercontent.com/87267148/172633837-2cf7ca58-f772-4358-8e00-ec758f9edf27.png)

## Context

Relevant information about my setup:

* Linux version: Ubuntu
* Linux kernel version: 5.13
* Tracee version (or commit id of your tree):  727e6

**Comment by rafaeldtinoco** [comment]
I believe we've dropped this from this milestone, right ? Just wanted to make sure @AlonZivony (based on our previous meeting).

**Comment by yanivagman** [comment]
> I believe we've dropped this from this milestone, right ? Just wanted to make sure @AlonZivony (based on our previous meeting).

I think we should keep it as part of the milestone as we already merged the dropped capabilities PR, but it's implementation is incorrect, which might cause hard to debug issues on some environments due to it being statistically working.

**Comment by rafaeldtinoco** [comment]
Sure, no objections. I just wanted to confirm that is what we wanted! Thanks.
