### ISSUE TITLE
Catch LD_PRELOAD hooking

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1823]
## Prerequisites

- [ ] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [x] I'll create a PR to implement this feature (assign to yourself).
- [ ] Someone else should implement this (describe it well).

## Feature description

We want to be able to use tracee to catch hooking of libraries functions, using symbols overriding.
To do so we need the following roadmap:
1. #1821 
2. #1655 
3. #1753 
4. #2013

**Comment by yanivagman** [comment]
Closing this one as all items in the list were merged.
