### ISSUE TITLE
[BUG] containerName field starts with a '/'

### ISSUE THREAD

**Issue by OriGlassman** [aquasecurity/tracee#1825]
## Prerequisites

- [] I can reproduce the issue in latest released version.
- [] I can reproduce the issue in development version (from source tree).
- [] I checked the documentation and found no answer.
- [] There isn't an issue describing the bug.

## Bug description

This is how I'm executing tracee (cmdline):tracee-ebpf -t c -t e=execve

This is the error I'm getting: "containerName": "/focused_engelbart"
(the containerName field in tracee-ebpf event contains a '/')

## Steps to reproduce

Steps to reproduce the issue:

1. run a container
2. watch the containerName field from an event originated from the container

## Context

Relevant information about my setup:

* Linux version: 21.04 (Hirsute Hippo)
* Linux kernel version: 5.11.0-49-generic
* Tracee version (or commit id of your tree): Tracee version "v0.7.0-152-g22e2ec7"
* LLVM version:
* Golang version:

**Comment by rafaeldtinoco** [comment]
@NDStrahilevitz I remember I saw this during the PR review for the enrichment and I did some digging back then and realized that the / was part of the answer from the docker API. Should we remove it ?

**Comment by NDStrahilevitz** [comment]
> @NDStrahilevitz I remember I saw this during the PR review for the enrichment and I did some digging back then and realized that the / was part of the answer from the docker API. Should we remove it ?

It is a docker thing and not a bug in the enrichment. 
I think we should document this somewhere at the very least (maybe in a comment at some level of the enrichment) so users will know to expect it. But i'm not in favor of removing the '/'.

**Comment by OriGlassman** [comment]
The docker cli removes it when presenting the name to the user though..
![image](https://user-images.githubusercontent.com/39296766/173827324-d067e173-1e16-4907-8b8d-5a9e0859c987.png)

**Comment by NDStrahilevitz** [comment]
So the relevant issue to this is moby/moby#6705. 
The '/' does relay relevant info about the container, but maybe there's a better way to inform it for tracee (event argument?).

In terms of usability, I checked and doing something like `docker stop /focused_engelbart` should work in current versions of docker, so this is purely cosmetic and shouldn't impede usability, which is what I would be worried about.

**Comment by rafaeldtinoco** [comment]
I checked the same thing back then and docker understands the "/" (likely part of an hierarchy of nested containers ?). I confess I'm in doubt of having it by default if there is a single prefix "/" in container name (just like docker is doing in "ps" command).

**Comment by NDStrahilevitz** [comment]
I'll defer to you for that decision. 
But having thought of it more, if we don't take out the /,  we need to document it somewhere. And even then, we may get more issues on this matter in the future. So maybe removing is the right call.

**Comment by rafaeldtinoco** [comment]
Yep, lets remove it. Does not make any sense for a regular user IMO.
