### ISSUE TITLE
[FEAT] Event Context Filter

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#1830]
## Prerequisites

- [x] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [x] I'll create a PR to implement this feature (assign to yourself).
- [ ] Someone else should implement this (describe it well).

## Feature description

This feature will add the capability to filter Context fields (fields defined in trace.Event) per event.
This filter will be initially implemented in userspace. It can later be translated to ebpf.

## Additional Information (feature drawings, files, logs, etc)

CLI Input:
`-t security_file_open.context.comm=ls`: For security_file_open events only those with a comm of ls will be emitted, all other events will work the same.
For the sake of comparison this is different from `-t event=security_file_open -t comm=ls`: Only trace events of type `security_file_open` and only if they have a comm of ls. 

Struct outline:
```
type ContextFilter struct {
    Filters    map[int32]*internalContextFilter
    Enabled bool
}

type internalContextFilter struct {
    //corresponding filter for each field of `trace.Event`
    Enabled bool
}
```

**Comment by yanivagman** [comment]
> In the CLI it would look like `-t security_file_open.comm=ls`

To avoid collision with argument filters, I would go for something like `-t security_file_open.context.comm=ls`

**Comment by itaysk** [comment]
how is this different from `-t event=security_file_open -t comm=ls`?

**Comment by NDStrahilevitz** [comment]
> how is this different from `-t event=security_file_open -t comm=ls`?

So the CLI input you used translates to this sentence: 
Only trace events of type `security_file_open` that were spawned from the process `ls`.

But this input `-t security_file_open.context.comm=ls` would be equivalent to this sentence:
For events of type `security_file_open` only trace them if they were spawned from the process `ls`.

So in the second type of input, other events are still traced as usual, regardless of their spawning process.

**Comment by rafaeldtinoco** [comment]
> > In the CLI it would look like `-t security_file_open.comm=ls`
> 
> To avoid collisions with argument filters, I would go for something like `-t security_file_open.context.comm=ls`

Yep, I thought the same, or else it will become very confusing.
