### ISSUE TITLE
[BUG] can't find DNS layer in packet for DNS resolution for ICMP packets

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1834]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

When capturing `dns_request` events, if I `ping <hostname>` from within a docker container, I get: `couldn't find the DNS layer in packet`:

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/7395852/174153265-1c97550b-89ca-4980-84bf-9fada09ee487.png">

This is how I'm executing tracee (cmdline):
```
$ sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments -o option:detect-syscall -trace comm=bash -trace follow -trace event=dns_request -trace net=docker0 -capture net=docker0
```
This is the error I'm getting:
```
{"timestamp":1655409115931386278,"processorId":0,"processId":479,"cgroupId":0,"threadId":479,"parentProcessId":1,"hostProcessId":3653606,"hostThreadId":3653606,"hostParentProcessId":481797,"userId":0,"mountNamespace":4026533727,"pidNamespace":4026533730,"processName":"ping","hostName":"","containerId":"ce113a7f50960197c260fa4fbe4dbabd90adb9fc6d72bf208152a6bb99d7cd09","containerImage":"","containerName":"","podName":"","podNamespace":"","podUID":"","eventId":"4001","eventName":"dns_request","argsNum":2,"returnValue":0,"stackAddresses":null,"args":[{"name":"metadata","type":"trace.PktMeta","value":{"src_ip":"172.17.0.2","dst_ip":"1.1.1.1","src_port":35379,"dst_port":53,"protocol":17,"packet_len":86,"iface":"docker0"}},{"name":"dns_questions","type":"[]bufferdecoder.DnsQueryData","value":[{"query":"199.3.147.200.in-addr.arpa","queryType":"PTR","queryClass":"IN"}]}]}
couldn't find the DNS layer in packet
couldn't find the DNS layer in packet
couldn't find the DNS layer in packet
couldn't find the DNS layer in packet
couldn't find the DNS layer in packet
couldn't find the DNS layer in packet
couldn't find the DNS layer in packet
couldn't find the DNS layer in packet
```
## Steps to reproduce

Steps to reproduce the issue:

1. Start tracee with given cmdline
2. From inside an existing docker container: `ping www.zip.net` 

## Context

Relevant information about my setup:

* Linux version: any
* Linux kernel version: any
* Tracee version (or commit id of your tree): commit 6499f067
* LLVM version: any
* Golang version: any

## Additional Information (files, logs, etc)

FYI @roikol @yanivagman

**Comment by mtcherni95** [comment]
I cannot reproduce the error message described above. Instead I get: `libbpf: Kernel error message: Exclusivity flag on, cannot modify`, not sure if related though.

**Comment by rafaeldtinoco** [comment]
This error message will be solved as soon as we bump libbpfgo to next version (about to happen). https://github.com/aquasecurity/libbpfgo/pull/174

**Comment by roikol** [comment]
@rafaeldtinoco 

i was able to reproduce these errors. it happens here because DNS is used over TCP. in this case, we see packets on port 53, which are not DNS, but TCP messages (syn, ack, etc.). we try to get DNS layer from these packets because they are on port 53, and we fail.

possible solution: if we fail to get DNS layer, check if the packet contains TCP layer - if so, don't return the error.

WDYT?
