### ISSUE TITLE
[BUG] Tracee crash on kernel module load error

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1843]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [x] I'm going to create a PR to solve this (assign to yourself).

## Bug description

Tracee-ebpf crash when a kernel module is loaded using `finit_module`.

This is how I'm executing tracee (cmdline):
`./tracee-ebpf -t e=finit_module`
This is the error I'm getting:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9ed287]

goroutine 13 [running]:
github.com/aquasecurity/libbpfgo/helpers.(*KernelSymbolTable).GetSymbolByName(0x0, {0x14cf83b, 0x0}, {0x14e0cd4, 0xc})
	/home/eitani/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/helpers/kernel_symbols.go:90 +0x107
github.com/aquasecurity/tracee/pkg/ebpf/initialization.ValidateKsymbolsTable(0x30b2465e7753dab)
	/home/eitani/projects/tracee/pkg/ebpf/initialization/ksymbols.go:40 +0x33
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).updateKallsyms(0xc000290000)
	/home/eitani/projects/tracee/pkg/ebpf/tracee.go:1319 +0x3b
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).processEvent(0xc000290000, 0xc0000fea00)
	/home/eitani/projects/tracee/pkg/ebpf/events_processor.go:349 +0x71
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).processEvents.func1()
	/home/eitani/projects/tracee/pkg/ebpf/events_pipeline.go:231 +0x11a
created by github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).processEvents
	/home/eitani/projects/tracee/pkg/ebpf/events_pipeline.go:227 +0x11a

```

## Steps to reproduce

Steps to reproduce the issue:

1. use `finit_module` on a memfd/ non existing fd.

## Context

Relevant information about my setup:

* Linux version: ubuntu 20.04
* Linux kernel version: 5.13
* Tracee version (or commit id of your tree): latest main
* LLVM version: 12
* Golang version: 1.17

**Comment by rafaeldtinoco** [comment]
@grantseltzer hey this might be a bug in libbpfgo, lets make sure the "bump" includes a fix for this one (before next release). Added this to the next milestone.

**Comment by grantseltzer** [comment]
@rafaeldtinoco sounds good, ill look to triage today
