### ISSUE TITLE
Enforce DocPath and Markdown Document to each added event

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1855]
## Bug description

After https://github.com/aquasecurity/tracee/pull/1808, we have to start enforcing the DocPath existence and the file format every time an event is added to tracee.

https://github.com/aquasecurity/tracee/pull/1808#issuecomment-1161755558
https://github.com/aquasecurity/tracee/pull/1808#issuecomment-1161843244

**Comment by yanivagman** [comment]
Closing since we already have #1579 to track this
