### ISSUE TITLE
ARM64: docker image artifact

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1913]
Tracee supports arm64 for some time now, we should cross-build docker images for arm64 architecture and publish them together with the release images.

List of issues for ARM64:

https://github.com/aquasecurity/tracee/issues/2832
https://github.com/aquasecurity/tracee/issues/2821
https://github.com/aquasecurity/tracee/issues/2594
https://github.com/aquasecurity/tracee/issues/1129

----

Updates:

After PR: #2849 is merged, there will still be missing some TODOS:

- [x] Create a single "latest" multi-architecture image.
- [x] Create a single "full" multi-architecture image.

Can be covered by: https://github.com/aquasecurity/tracee/issues/2866

- [x] Add the arm64 artifacts to the release artifacts (commit: 4d6e5d56)
- [x] Update documentation to reflect architecture images (commit: 974bc33f)
- [x] Enable BTFHUB for Release Snapshot and Release (and add latest images) (commit 3432ad31)

to be done soon.

**Comment by rafaeldtinoco** [comment]
FTR: That is exactly why i changed the "distro test" image recently. It is able to generate other architecture's compilations/docker images/packages.

**Comment by shitou12345678** [comment]
hello,  i compiled the tracee image of the ARM version according to x86 dockerfile successfully. I want to know how do i submit this image?

**Comment by yanivagman** [comment]
> hello, i compiled the tracee image of the ARM version according to x86 dockerfile successfully. I want to know how do i submit this image?

Hi @shitou12345678 , we need to add this to be part of the release process, so image will be updated on every release automatically

**Comment by yanivagman** [comment]
Depends on #2542
