### ISSUE TITLE
Network events should also be enriched

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1922]
## Bug description

Enrichment works with:

![image](https://user-images.githubusercontent.com/7395852/177399077-99a4c4b1-dc54-4737-9f30-68e03ad3d3c1.png)

But fails to work when picking "net_packet" only event:

![image](https://user-images.githubusercontent.com/7395852/177399349-7d277098-735b-4c71-9c12-7dbfaccc6297.png)

## Context

Relevant information about my setup:

* Linux version: any
* Linux kernel version: any
* Tracee version (or commit id of your tree): e1a28fe
* LLVM version: any
* Golang version: any

**Comment by NDStrahilevitz** [comment]
I'm not sure this is because of the enrichment events not being enabled (cgroup_mkdir etc should be enabled by default). I think net events just aren't getting enriched since they don't go through the enrichment pipeline. Can you maybe confirm with another singular event.

**Comment by rafaeldtinoco** [comment]
> I'm not sure this is because of the enrichment events not being enabled (cgroup_mkdir etc should be enabled by default). I think net events just aren't getting enriched since they don't go through the enrichment pipeline. Can you maybe confirm with another singular event.
> 
> We can try and add enrichment to the network events for next release, but it's a bit messy because it has its own separate "pipeline".

You're right.

**Comment by yanivagman** [comment]
IMO solution should be to use the same pipeline as a regular event.
We should send network events through the events perf buffer, and modify the pipeline to handle them (need to build the proper context from procinfo, then use the regular pipeline)

**Comment by yanivagman** [comment]
I just want to be clear that when I suggest to use the same perf buffer for network events, I only refer to events, and not the full net packets (pcap) which will continue to use the net perf buffer.

> The advantage to your would be less memory taken for another buffer, but we would have a smaller buffer for more events, so (correct me if i'm wrong) it might cause more event loss.

Another benefit for using the events buffer is event ordering. Different perf buffers (events VS net-events) might have a big offset in their timestamp if there is a big load in one of them. Now we also have different buffers for each CPU, so it's not that big advantage, but as we will move to use ring-buffer, this advantage will become more relevant.

About lost events - there can be more lost events in the events buffer, but then we can just make the buffer bigger. If we keep having two different buffers for network events and "regular" events, then if the rate at which events are produced is too high events will be lost anyway (either network events or "regular" events).

**Comment by rafaeldtinoco** [comment]
This is solved for the new network events (coming in the same pipeline as all other events). We will have to migrate other network events (using PktMeta) to the new events and then this will be done.

@roikol ^ FYIO

**Comment by rafaeldtinoco** [comment]
Solved by:


commit 4e9b50e5
Author: Rafael David Tinoco <rafaeldtinoco@gmail.com>
Date:   Tue Sep 27 04:04:00 2022

    events: add network protocol events
