### ISSUE TITLE
[FEAT] add suffix and contains argument filters options

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1925]
## Prerequisites

- [ ] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [x] I'll create a PR to implement this feature (assign to yourself).
- [ ] Someone else should implement this (describe it well).

## Feature description

This feature is about adding suffix and contains filter options to argument filters.

The feature is needed because it will allow us to reduce overhead between tracee-ebpf to tracee-rules

**Comment by NDStrahilevitz** [comment]
Just to note that I have this implemented in #1750 as well (not that it should affect this issue) but just wanted to say that I was sure we had this before as well. 😮
