### ISSUE TITLE
[BUG] tracee-ebpf not capturing events from existing containers when using container filter

### ISSUE THREAD

**Issue by OriGlassman** [aquasecurity/tracee#1933]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

tracee-ebpf doesn't capture the container events when running with -t c and the container was already alive when tracee began running.

This is how I'm executing tracee (cmdline):
tracee-ebpf -t c

This is the error I'm getting:
no events

## Context

Relevant information about my setup:

* Linux version:
* Linux kernel version:
* Tracee version (or commit id of your tree):
* LLVM version:
* Golang version:

**Comment by NDStrahilevitz** [comment]
Solved in #1935
