### ISSUE TITLE
[BUG] Clean up the manual cpuset mount in cgroupv1 environments

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1945]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

![Screen Shot 2022-07-07 at 16 11 16](https://user-images.githubusercontent.com/7395852/177855549-c8e1b1f6-9298-4df6-a582-c64505664272.png)

1. The cpuset diretory is mounted in the same directory as the tracee-ebpf binary.

2. The cpuset directory is never unmounted and/or cleaned up.

![Screen Shot 2022-07-07 at 16 15 31](https://user-images.githubusercontent.com/7395852/177855484-da439c1d-cb37-42bb-aee7-16776307f183.png)

3. The syscall.Mount() call fails because of missing ./cpuset directory in some cases.

![Screen Shot 2022-07-07 at 16 20 43](https://user-images.githubusercontent.com/7395852/177855240-cd8c63b1-243c-4143-a446-631634d67af4.png)

## Steps to reproduce

See pictures above.

```
$ make -f builder/Makefile.tracee-make alpine-prepare

$ make -f builder/Makefile.tracee-make alpine-shell
...

tracee@54ab0cbb4872[/tracee]$ make all
...

$ sudo ./dist/tracee-ebpf -o none
containers: failed to mount cgroupv1 controller: failed to mount no such file or directory
```

## Context

Relevant information about my setup:

* Linux version: Ubuntu Jammy
* Linux kernel version: 5.15.0-33-generic
* Tracee version (or commit id of your tree): v0.8.0-rc-1-24-g07c8af7
* LLVM version: 13
* Golang version: 1.17

**Comment by rafaeldtinoco** [comment]
This is the result of dropping capabilities before the attempt of creating and mounting the cgroupfs cpuset directory (which is needed in the alpine environment created by the Makefile).

**Comment by yanivagman** [comment]
> This is the result of dropping capabilities before the attempt of creating and mounting the cgroupfs cpuset directory (which is needed in the alpine environment created by the Makefile).

I see three problems here:
1. The one you listed above
2. We don't check for error when calling `os.Mkdir("./cpuset", 0644)` (should return an error if err!=nil && err==path exists)
3. We identify the host as a container because /sys/fs/cgroup/cpuset/release_agent doesn't exist although we assumed that it should (this turns out to be a wrong assumption)

**Comment by rafaeldtinoco** [comment]
I see the same problems =D

![image](https://user-images.githubusercontent.com/7395852/177869138-9f45d865-fe79-4915-9278-224659c28251.png)

**Comment by yanivagman** [comment]
Can you please list the dir content of /sys/fs/cgroup/cpuset on the host?
I wonder if there's another way we can distinguish a container from the host, e.g. the existance of sub-directories

**Comment by rafaeldtinoco** [comment]
Host:

![image](https://user-images.githubusercontent.com/7395852/177872303-120bed42-75bb-4080-afe7-4629204734b7.png)

Container

![image](https://user-images.githubusercontent.com/7395852/177872405-59bea86b-de62-4158-9940-f2bb1ec3da1d.png)

**Comment by rafaeldtinoco** [comment]
I believe `/sys/fs/cgroup/misc/release_agent` exists in all containers.

About dropping privileges, do we HAVE to drop privileges before `New()` ? If I drop them later (which would be also after `initBPF()` as well), then we have no problems (or we will have to think of a way to create a temp dir to mount cgroup on it before.

**Comment by yanivagman** [comment]
> 3\. We identify the host as a container because /sys/fs/cgroup/cpuset/release_agent doesn't exist although we assumed that it should (this turns out to be a wrong assumption)

Oh so this does work - I can see that you do have it on your host

**Comment by rafaeldtinoco** [comment]
> > 3. We identify the host as a container because /sys/fs/cgroup/cpuset/release_agent doesn't exist although we assumed that it should (this turns out to be a wrong assumption)
> 
> Oh so this does work - I can see that you do have it on your host

It does, we're doing things right (mounting a cpuset cgroup directory). We have problems on "WHEN" we are doing it (and I would also change the place where to mount).

**Comment by yanivagman** [comment]
> I believe `/sys/fs/cgroup/misc/release_agent` exists in all containers.
> 
> About dropping privileges, do we HAVE to drop privileges before `New()` ? If I drop them later (which would be also after `initBPF()` as well), then we have no permission problems (or we will have to think of a way to create a temp dir to mount cgroup on it before `initContainers`).

I don't see a problem with dropping the capabilities after New() (but beofre Run()), maybe @AlonZivony can confirm that?

**Comment by rafaeldtinoco** [comment]
If `ensureCapabilities` is placed after `tracee.New()` it works like expected. But I'm not sure dropping capabilities after the `initBPF()` logic would be problematic. Yep, lets confirm with @AlonZivony. I'll release it tomorrow anyway, I'll continue fixing some minor documentation issues.

**Comment by yanivagman** [comment]
Not related to this bug, but this made me thought that maybe we should also change the user of tracee to a non-root user (in addition to dropping capabilties), WDYT?

**Comment by geyslan** [comment]
I know that Arch based isn't market target but registering that this is not reproducible in my host setup:

- Linux version: Manjaro
- Linux kernel version: 5.17.15-1-MANJARO
- Tracee version (or commit id of your tree): 72e0d024547
- LLVM version: 13.0.1
- Golang version: 1.18.3

```shell
$ sudo make -f builder/Makefile.tracee-make alpine-prepare

$ sudo make -f builder/Makefile.tracee-make alpine-shell
...

root@a74ba3814963[/tracee]$ make all
...

$ sudo ./dist/tracee-ebpf -o none
```

**Comment by yanivagman** [comment]
> I know that Arch based isn't market target but registering that this is not reproducible in my host setup:
> 
> * Linux version: Manjaro
> * Linux kernel version: 5.17.15-1-MANJARO

That's because your'e running cgroup v2 and not v1 (BTW, I'm also a Manjaro user :-) )

**Comment by geyslan** [comment]
> That's because your'e running cgroup v2 and not v1 (BTW, I'm also a Manjaro user :-) )

Indeed.

```bash
$ grep cgroup /proc/filesystems
nodev	cgroup
nodev	cgroup2

$ mount | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)
```

And yeah, Manjaro is smooth ;-)

**Comment by AlonZivony** [comment]
> If `ensureCapabilities` is placed after `tracee.New()` it works like expected. But I'm not sure dropping capabilities after the `initBPF()` logic would be problematic. Yep, lets confirm with @AlonZivony. I'll release it tomorrow anyway, I'll continue fixing some minor documentation issues.

There is a problem with doing it inside of tracee, because dropping capabilities is not a thing you expect from a package.
The `main` package should drop the capabilities, so if we drop the capabilities after the `initBPF` it will be after the whole `New` function.
We can do it for now if you think this is the best course, but it may result problems - we need to ensure that there are **enough** capabilities to run before the `New` function and drop what needs dropping afterwards. However, this seems to me as just playing it weird - we can just drop capabilities 2 times, before `New` and after. That way we use the lowest capabilities we need in each step, and providing the best security measures.
BTW, we might even be able to reduce the `CAP_SYS_ADMIN` this way, if we make sure to do all BPF operations in `New` (I am not sure if we do it right now).

**Comment by rafaeldtinoco** [comment]
Yes, let's do something easy now for the release (finishing documentation). Then we can think of a better way of solving the issue (executing everything depending on higher privileges first). Remember that, eventually, we will have a routine running with high privileges (for capture data, bpf commands, etc).

**Comment by rafaeldtinoco** [comment]
@yanivagman mind tackling this one this Sunday ? I'll be finishing documentation updates to release Tracee on Monday with the new documentation in place AND this fix.

**Comment by yanivagman** [comment]
@rafaeldtinoco I saw this change in your documentation PR, is it there by mistake?

**Comment by rafaeldtinoco** [comment]
> @rafaeldtinoco I saw this change in your documentation PR, is it there by mistake?

Yep, I included it during tests but wasn't sure about our approach. I think we should do what you said to address for this release and fix it in the next.

**Comment by AlonZivony** [comment]
> As we only introduce drop-capabilities in this release, I thing that it will be ok to drop them after calling New(), and fixing it for the next release (moving it back before calling New()). WDYT @rafaeldtinoco @AlonZivony ?

I am OK with it as a temporary solution, but it will be problematic to let it stay this way.
Anyways, we do need to check that all needed capabilities are available before the `New` method, so we need to understand the capabilities issues here to give the right error message to the user so he would be able to fix it.

**Comment by grantseltzer** [comment]
I've opened #1958 to handle this, but I want to open another issue describing why this is only a temporary solution, what is problematic about the ordering here?

**Comment by yanivagman** [comment]
> I've opened #1958 to handle this, but I want to open another issue describing why this is only a temporary solution, what is problematic about the ordering here?

Dropping the capabilities after calling New means that initBPF was already called, the hooks are already attached and events started to flow. So better do it before.

**Comment by AlonZivony** [comment]
@rafaeldtinoco did you find the lacking  capability which results this error?

**Comment by yanivagman** [comment]
> @rafaeldtinoco did you find the lacking capability which results this error?

It was CAP_DAC_OVERRIDE.
see https://github.com/aquasecurity/tracee/pull/1958#issuecomment-1183551015

**Comment by rafaeldtinoco** [comment]
Yep, sorry for the delay here, thanks Yaniv.
