### ISSUE TITLE
implementation of get_task_ns_pid

### ISSUE THREAD

**Issue by xjas** [aquasecurity/tracee#1950]
sorry to disturb, but after reading some kernel code about pid, I can't understand the implementation

```
    context->task.tid = get_task_ns_pid(task);
    context->task.pid = get_task_ns_tgid(task);
```

The name`get_task_ns_tgid `(same with `get_task_ns_pid `), I think it's a ns tgid which should be fetched from the initial namespace, namely the pid_namespace when the process is created,  which is permanent; but task->nsproxy->pid_ns_for_children can changed when it switched to its children pid_namespace, which is used in tracee.

the kernel implementation use current->ns->level, namely pid->level to fetch the real pid. 
```
pid_t pid_nr_ns(struct pid *pid, struct pid_namespace *ns)
{
	struct upid *upid;
	pid_t nr = 0;

	if (pid && ns->level <= pid->level) {
		upid = &pid->numbers[ns->level];
		if (upid->ns == ns)
			nr = upid->nr;
	}
	return nr;
}

pid_t pid_vnr(struct pid *pid)
{
	return pid_nr_ns(pid, task_active_pid_ns(current));
}
```

**Comment by xjas** [comment]
> Hello @xjas , Yes, I think you are right. I opened #1957 to fix this, and simplify the code as well. Can you have a look?

sorry to occupy your time, I want to open a PR before, but I'm not sure whether I understand it right. 😂

and yeah, it's the implementation I expected, thanks.

**Comment by yanivagman** [comment]
> > Hello @xjas , Yes, I think you are right. I opened #1957 to fix this, and simplify the code as well. Can you have a look?
> 
> sorry to occupy your time, I want to open a PR before, but I'm not sure whether I understand it right. joy
> 
> and yeah, it's the implementation I expected, thanks.

Great. Thanks for reporting this.
