### ISSUE TITLE
[BUG] tracee-ebpf and tracee-rules mismatch of interpreting which events belong to container/host

### ISSUE THREAD

**Issue by OriGlassman** [aquasecurity/tracee#1967]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

tracee-ebpf may regard events that contain containerId to the **host** (upon creation of a new container), while tracee-rules will regard them to a **container** (since the event has a containerId). 

## Context

Relevant information about my setup:

* Linux version:
* Linux kernel version:
* Tracee version (or commit id of your tree):
* LLVM version:
* Golang version:

**Comment by NDStrahilevitz** [comment]
Can you please elaborate with an example? Are you talking about `container_create` events or any event with a containerId?

**Comment by rafaeldtinoco** [comment]
Yes @OriGlassman, please try to always provide us a reproducer and the output of the effects you're observing, so we can reproduce and fix ourselves. Thank you!

**Comment by OriGlassman** [comment]
When container is created, at some point tracee-ebpf will populate the containerId field but still treat these events as host events (with container filter on, you won't see those events) as tracee-ebpf waits for the first execve insde the container and then attributes all the events afterwards to the container.
tracee-rules attribution to host or container is based on containerId field. If the field is populated, it attributes the event to container.
So what do we have? we have a few events with containerId populated, where tracee-ebpf relates them to the host, while tracee-rules relates those same events to a container. Mismatch.

**Comment by AlonZivony** [comment]
The bugfix implementation:
* Modify the `padding` member of the `context_t` to be a flags bitfield, with flag for `container_started`
* When doing `sched_process_exec` change the state of the container to started.
* Create in `trace.Event` a member for flags received from the kernel, and pass it on as bools.
* Change check in tracee-rules to check the new flag instead the `ContainerID`

**Comment by NDStrahilevitz** [comment]
Could you provide an effective example of a problem this bug creates? As far as I can tell what was described here is more of a "semantic" difference between the programs, but not a behavioral one. 
The only possible problem I understand may occur is that we may miss submission of some early container events from the kernel? If so maybe we should try to mark them as container events earlier, that's a tracee-ebpf only problem though.

**Comment by AlonZivony** [comment]
The problem here is that tracee-rules and tracee-ebpf are not matching in their definition of when a container really starts.
From the user point of view, the `runc` process events before executing the entry-point are not considered container events, because they are not effected from the image.
Tracee-ebpf is currently fulfilling it in the right way, waiting for the first execution after `runc` to pass it through the container filter. We just want to copy this logic to tracee-rules.
This is the bug, because when you write rules for containers you don't expect the high-privileges behavior of `runc` before container entry-point.

**Comment by rafaeldtinoco** [comment]
Im reopening this because of https://github.com/aquasecurity/tracee/pull/2029 and regressions observed when we added more tests to each PR. I have reverted the following PRs:

https://github.com/aquasecurity/tracee/pull/1984
https://github.com/aquasecurity/tracee/pull/2007

**Comment by AlonZivony** [comment]
Opened again 2 PRs for closing this:
types - #2041 (instead of #2007)
flag code - #2032 (instead of 1984)
