### ISSUE TITLE
[BUG] get wrong old pid_ns for hook switch_task_namespaces

### ISSUE THREAD

**Issue by xjas** [aquasecurity/tracee#1972]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.
- [x] I'm going to create a PR to solve this (assign to yourself).

## Bug description

@yanivagman 
I  noticed the commit is amended: https://github.com/aquasecurity/tracee/commit/db4caec3df2788239127af1f4594c21d5a4410aa

the former implementation get pid_ns_id from `task->nsproxy->pid_ns_for_children->ns.inum`
now the implemenatation use the data of `task->pids[PIDTYPE_PID].pid`

I thought the modify maybe not proper for the hook point`SEC("kprobe/switch_task_namespaces")`

```
void switch_task_namespaces(struct task_struct *p, struct nsproxy *new)
{
	struct nsproxy *ns;

	might_sleep();

	task_lock(p);
	ns = p->nsproxy;
	p->nsproxy = new;
	task_unlock(p);

	if (ns && atomic_dec_and_test(&ns->count))
		free_nsproxy(ns);
}
```

when `switch_task_namespaces` is executed, the nsproxy is switched, just as the `task->nsproxy` denoted

just as [man pid_namespace](https://man7.org/linux/man-pages/man7/pid_namespaces.7.html) described:
`task->nsproxy->pid_ns_for_children` is a ns which the children of the process will be in. 

> Calls to [setns(2)](https://man7.org/linux/man-pages/man2/setns.2.html) that specify a PID namespace file descriptor
and calls to [unshare(2)](https://man7.org/linux/man-pages/man2/unshare.2.html) with the CLONE_NEWPID flag cause children
subsequently created by the caller to be placed in a different
PID namespace from the caller. (Since Linux 4.12, that PID
namespace is shown via the /proc/[pid]/ns/pid_for_children file,
as described in [namespaces(7)](https://man7.org/linux/man-pages/man7/namespaces.7.html).) These calls do not, however,
change the PID namespace of the calling process

so `task->nsproxy->pid_ns_for_children` could be any of the descendants of the pid_ns when the proc is created.
for example: there is a nested pid_ns, such as `pid_ns0 -> pid_ns1->pid_ns2`, proc A is created in pid_ns0, then it 

proc A's original pid_ns is pid_ns0, which is steady when proc A is created, and can't be changed, proc A can swith to pid_ns1, then to pid_ns2, it's just the task->nsproxy changed, only change the pid_ns_for_children.

when proc A swtich from pid_ns1 to pid_ns2, the new modify just record the old_pid_ is pid_ns0, which is not correct.

**Comment by xjas** [comment]
Or may I add some code to denote the original pid_ns which is the pid_ns when the proc is created?
However, they are the same in most situations.

**Comment by yanivagman** [comment]
Thanks @xjas , yes, you are right.
Anyway the comparison is incorrect because wer'e now comparing pid ns with pid_for_children ns.

**Comment by xjas** [comment]
> Thanks @xjas , yes, you are right.
> 
> Anyway the comparison is incorrect because wer'e now comparing pid ns with pid_for_children ns.

Yes, you are correct. I mistook that it's only used in the hook switch_namespaces, so I didn't mention it in the previous issue.

**Comment by xjas** [comment]
> Or may I add some code to denote the original pid_ns which is the pid_ns when the proc is created?
> 
> However, they are the same in most situations.

@yanivagman Is it necessary to add a new field in task_context, such as pid_id_children? A process do have 2 pid_id, ls -l /proc/1/ns show this, while they are the same mostly.

**Comment by yanivagman** [comment]
> > Or may I add some code to denote the original pid_ns which is the pid_ns when the proc is created?
> > However, they are the same in most situations.
> 
> @yanivagman Is it necessary to add a new field in `struct task_context`, such as `u32 pid_id_children;`? A process do have 2 pid_id, `ls -l /proc/1/ns` show this, whereas they are the same mostly.

I don't see any special use for this, do you? I think we should prefer to keep the context small, unless really necessary

**Comment by xjas** [comment]
> > > Or may I add some code to denote the original pid_ns which is the pid_ns when the proc is created?
> 
> > > However, they are the same in most situations.
> 
> > 
> 
> > @yanivagman Is it necessary to add a new field in `struct task_context`, such as `u32 pid_id_children;`? A process do have 2 pid_id, `ls -l /proc/1/ns` show this, whereas they are the same mostly.
> 
> 
> 
> I don't see any special use for this, do you? I think we should prefer to keep the context small, unless really necessary

Yes, I don't see any use cases either.

I agree with your idea to keep the context as small as possible.
