### ISSUE TITLE
Move capability requirement logic into tracee

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#1990]
## Prerequisites

Select one OR another:

- [ ] I have discussed the refactoring idea with one (or another) maintainer.
- [x] I'll create a PR to implement this refactoring idea (assign to yourself).
- [ ] Someone else should implement this (describe it well).

## Refactoring description

tracee-ebpf includes many different subsystems that may require their own set of capabilities in additional to event and ebpf capabilties. In order to allow easy maintenance of these capabilities, calculation logic should be moved inside tracee.

However in order to drop before running effects we must split side effects from `New()` (#1989)

**Comment by NDStrahilevitz** [comment]
@rafaeldtinoco I think this is solved in your new `capabiltiies` package by now right?

**Comment by rafaeldtinoco** [comment]
Yes I believe so. Closing.
