### ISSUE TITLE
[BUG] Matrix tests have fail-fast

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#2020]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

Currently, when the CORE and NONCORE tests run, when a test in the array fails, for example if stream9 test fails, all following tests will be cancelled, even if they passed.
This is because of a property `fail-fast` documented [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast).

**Comment by rafaeldtinoco** [comment]
That is by design @NDStrahilevitz. There was no point in continuing tests (in my point of view) as most of the runs were because of PRs. Maybe we can have a non fail-fast daily test running instead of making all PRs not to fail fast ?

**Comment by NDStrahilevitz** [comment]
> That is by design @NDStrahilevitz. There was no point in continuing tests (in my point of view) as most of the runs were because of PRs. Maybe we can have a non fail-fast daily test running instead of making all PRs not to fail fast ?

In the PRs I disagree, because it might be that a test is simply flaky (see alon's PRs now), and then we lose the rest of the tests mark, so we lose the bigger picture of what broke.
