### ISSUE TITLE
[BUG] Matrix tests fail on stream9

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#2022]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [ ] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

As can be seen from #2021 and some PRs we have on right now, we have a regression, both in CORE and NONCORE in most signature tests of stream9.

**Comment by NDStrahilevitz** [comment]
So luckily I have an open PR (#2017) which is one commit behind HEAD right now, where the stream9 tests do pass. That means the last commit [d6de9ef](https://github.com/aquasecurity/tracee/commit/d6de9ef1e5e369933a9bb7729145ea1a60c65dcc) is probably the responsible one. 
From checking the relevant PR (#1984) - it seems it ran with the old SMOKE tests and not the new matrix tests, which is why this wasn't caught at the time. 
@AlonZivony assigning you to check.

**Comment by NDStrahilevitz** [comment]
#2025 confirms that #1984 is the cause.

**Comment by itaysk** [comment]
what is stream9?

**Comment by NDStrahilevitz** [comment]
> what is stream9?

centos 9, had to google it though, @rafaeldtinoco why are we using that name though? Also we have focal instead of ubuntu for example.

**Comment by yanivagman** [comment]
Fixed in #2029
