### ISSUE TITLE
Convert BCC to libbpf+CO-RE

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#209]
All the reasons why and a practical guide for how to do that: https://facebookmicrosites.github.io/bpf/blog/2020/02/20/bcc-to-libbpf-howto-guide.html

Work in progress in the branch `libbpf` https://github.com/aquasecurity/tracee/tree/libbpf

**Comment by pathtofile** [comment]
Donig this would make tracee much more portable, very much in favour of this

**Comment by yanivagman** [comment]
First part of this task is now done.
We opened a branch named libbpf, where we moved from bcc to libbpf.
You are more than encouraged to use this branch and report any problems you encounter.

**Comment by pathtofile** [comment]
Hey @yanivagman, super keen to check this out, I'm having dependency issues when attempting to run `make build-docker`, as the builder docker container is missing clang and a few other deps.

But the regular `make build` works on Ubuntu 20.04, kernel 5.4 and clang 11 👍

**Comment by pathtofile** [comment]
How long are you thinking of keeping this branch separate before merging it into main? Should we be targeting new PRs to this branch or main?

**Comment by yanivagman** [comment]
Hi @pathtofile , there are few small todos left in this branch, which you can see in tracee.go file, initBPF function.
One of these things is adding support to build docker image.
After we will complete these todos - we can merge this branch into master

**Comment by pathtofile** [comment]
awesome, thanks!

**Comment by yanivagman** [comment]
Libbpf branch is now merged to master.
Our next step will be adding support for CO-RE

**Comment by yanivagman** [comment]
initial CO-RE support was added in #759 
Other CO-RE related tasks should be handled in a new issue
