### ISSUE TITLE
Don't require specifying a device for network pcap

### ISSUE THREAD

**Issue by OriGlassman** [aquasecurity/tracee#2096]
As of today tracee-ebpf has two pcap related arguments: '-c net=<interface> and -c pcap:<host|per-container>'.
This puts the burden of capturing pcaps on the user to supply an interface..
I suggest to have a 'pcap:<host,containers,all>' (default all) option, and leave tracee to detect the relevant network interface.

**Comment by rafaeldtinoco** [comment]
The `-c net=` will vanish as soon as we drop tc progs attached to interfaces (being currently worked on). I'm about to create all issues for the network improvements about to come. Will label this as "networking" (and all subsequent/related ones).
