### ISSUE TITLE
[BUG] documentation for 0.8.1 not published?

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#2098]
## Prerequisites

- [x] This affects latest released version.
- [x] There isn't an issue describing the bug.

## Bug description

There's no documentation published for the latest version. Is that expected? 

Steps to reproduce the issue:

https://aquasecurity.github.io/tracee/v0.8.1/

**Comment by josedonizetti** [comment]
@rafaeldtinoco ^^

**Comment by rafaeldtinoco** [comment]
@grantseltzer trigger did not occur automatically like last time with 0.8.0. I wonder why, remember you investigated this.

**Comment by rafaeldtinoco** [comment]
![image](https://user-images.githubusercontent.com/7395852/186914035-f8869488-27ce-4b6e-a88d-5f29e5f361f6.png)

**Comment by rafaeldtinoco** [comment]
> ![image](https://user-images.githubusercontent.com/7395852/186914035-f8869488-27ce-4b6e-a88d-5f29e5f361f6.png)

The trigger couldn´t run, and there is a "rc1" version released. Checking...

**Comment by rafaeldtinoco** [comment]
I have removed v0.7.0-rc1 wrong uploaded tag + removed the mkdocs structure using it as latest: https://github.com/aquasecurity/tracee/pull/2105. Now I'll update for doc site to be updated and try to generate 0.8.1 AND dev to see if it is good enough to fix broken release action scripts.

**Comment by rafaeldtinoco** [comment]
Was able to run the documentation generation now: https://github.com/aquasecurity/tracee/actions/runs/2934281650 (v0.8.1).

**Comment by rafaeldtinoco** [comment]
Seems fixed now. Thanks.
