### ISSUE TITLE
[BUG] uprobe based events need DAC_OVERRIDE cap

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2117]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [ ] There isn't an issue describing the bug.

Select one OR another:

- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

This is how I'm executing tracee (cmdline):

    $ sudo ./dist/tracee-ebpf -t e=hooked_syscalls

This is the error I'm getting:

    ...
    /08/28 01:46:07 error initializing Tracee: failed to attach required probe:
    error finding github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).
    triggerSyscallsIntegrityCheckCall function offset: could not open elf file
    to resolve symbol offset: open .../dist/tracee-ebpf: permission denied

**Comment by yanivagman** [comment]
So tracee fails to open its own binary?
This can probably be fixed by setting correct permissions on the file, or maybe by accessing the binary using /proc/self/exe instead of the binary path.
I don't think we should add the CAP_DAC_OVERRIDE permission because of this

**Comment by rafaeldtinoco** [comment]
Yep, much better approach. Changing it.
