### ISSUE TITLE
[BUG] golang different calling conventions make uprobe arguments incorrectly parsed

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2124]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [ ] There isn't an issue describing the bug.

Select one OR another:

- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

The following error (in ARM64):

```
$ sudo ./dist/tracee-ebpf -t e=hooked_syscalls
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
failed to apply invoke context on print_syscall_table event: no event context with id 0

End of events stream
Stats: {EventCount:0 NetEvCount:0 ErrorCount:1 LostEvCount:0 LostWrCount:0 LostNtCount:0}
```

Happens because differences in golang calling convention among different golang versions (and architectures). The following code (and similar uprobe handlers):

```C
SEC("uprobe/trigger_syscall_event")
int uprobe_syscall_trigger(struct pt_regs *ctx)
{
    u64 caller_ctx_id;
#if defined(bpf_target_x86)
    caller_ctx_id = ctx->bx;
#elif defined(bpf_target_arm64)
    bpf_probe_read(&caller_ctx_id, 8, ((void *) ctx->sp) + 16);
#else
    return 0;
#endif
```

Are wrong if we compile tracee with 1.18 and 1.19 golang version, when we would have to use:

```C
caller_ctx_id = ctx->user_regs.regs[1];
```
to get arguments for the functions being uprobed.

## Steps to reproduce

The following error (in ARM64):

```
$ sudo ./dist/tracee-ebpf -t e=hooked_syscalls
```

## Context

Relevant information about my setup:

* Linux version: Ubuntu Jammy
* Linux kernel version: 5.15.0-1017-aws
* Tracee version (or commit id of your tree): latest (22-08-28)
* LLVM version: 
* Golang version: multiple

**Comment by rafaeldtinoco** [comment]
**golang 1.17:**

![image](https://user-images.githubusercontent.com/7395852/187264799-181000ef-1167-4cc5-ac90-e28c779d3a8a.png)

    bpf_probe_read(&three, 8, ((void *) ctx->sp)+16);

**golang 1.18** and on:

![image](https://user-images.githubusercontent.com/7395852/187266209-0201e8cc-6e61-4f97-ac3e-f125eaddb13b.png)

@AsafEitani alright, golang 1.17 uses stack based argument passing convention, golang 1.18 and 1.19 uses register based argument passing convention to make "our lives easy". 

> Good readings about it:
> 1. https://blog.0x74696d.com/posts/challenges-of-bpf-tracing-go/
> 2. https://go.googlesource.com/proposal/+/refs/changes/78/248178/1/design/40724-register-calling.md

and I believe the convention change is being tracked at:

* https://github.com/golang/go/issues/40724

and we can see:

![image](https://user-images.githubusercontent.com/7395852/187264591-5bdc5d5d-67d7-4e0f-996c-506c9465585c.png)

meaning arm64 has been "ported" for the new convention. We can either have a "magic number" as the first argument (so we can always check if we have the rest of arguments in the stack or in registers) OR just rely in GO 1.18 entirely for tracee from now on.

**Comment by rafaeldtinoco** [comment]
I believe the best approach would be:

```go
const uProbesMagicNumber uint64 = 20220829

// triggerSyscallsIntegrityCheck is used by a Uprobe to trigger an eBPF program
// that prints the syscall table
//go:noinline
func (t *Tracee) triggerSyscallsIntegrityCheckCall(
	magicNumber uint64, // allow uprobe handler to understand calling convention
	eventHandle uint64, // 1st argument to uprobe handler
	) {
}
```
this way we can check for the calling convention by checking stack for a known value (the magic number) and allow Tracee to work with uprobes in golang 1.17, 1.18 and 1.19.

**Comment by AsafEitani** [comment]
Are there any drawbacks to upgrading to golang 18?

**Comment by yanivagman** [comment]
> Are there any drawbacks to upgrading to golang 18?

I think they use an older version for CNDR

**Comment by grantseltzer** [comment]
There are nuances to the Go 1.18+ calling convention described here: https://go.googlesource.com/go/+/refs/heads/dev.regabi/src/cmd/compile/internal-abi.md

I have experience around so would like to help. Lets discuss during our meeting tomorrow

**Comment by rafaeldtinoco** [comment]
I think I got it covered for both: amd64 (go 1.17, 1.18 and 1.19) and arm64 (go 1.17, 1.18 and 1.19) at https://github.com/aquasecurity/tracee/pull/2103, AT LEAST for the cases we use: we control the function we're uprobe hooking into, so its easier for me to make sure the calling convention works as expected.

If we were hooking into 3rd party software, random functions, etc, then I suppose we would have a REAL headache trying to figure out all those nuances.

**Comment by rafaeldtinoco** [comment]
> > Are there any drawbacks to upgrading to golang 18?
> 
> I think they use an older version for CNDR

And I also thought about enabling go1.17 users in arm64 (and also thought that, if we expand architecture support (ppc, s390, armhf) we might still have the same need.
