### ISSUE TITLE
index capture written files 

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#213]
add a file to the output directory that indexes the written files by their paths. for example:
`/path/to/file -> write.dev-1.inode-33`

**Comment by yanivagman** [comment]
By monitoring vfs_write and vfs_writev - this data can be easilly extracted and written to a file

**Comment by ng29** [comment]
Heya @itaysk 

More info on this will be highly appreciated , so that i can pick this up .

Cheers

**Comment by yanivagman** [comment]
Hi @ng29 ,

One of Tracee's features is capturing files written by the traced processes.
To enable file capture, one should provide "--capture write" as part of the arguments to Tracee, optionally with 1-3 filters, given by "--filter-file-write".
File writes are then saved to the output directory (defaults to /tmp/tracee), with a name constructed from the device id and inode number of the file.
The reason why these files are not saved by using the name of the original file path, is that the same file can be written from different paths (e.g. when a hard link is used), and we want to represent the real data that was eventually written to the file. Device id and inode number uniquely represent a file in the system, however, it is somewhat cryptic when trying to figure out from the file name, what is the original file that was written.

In order to properly map between (dev id, inode) to file path, it is necessary to save this data in a map one one of "vfs_write" or "vfs_writev" events happen. These events contain both the path and the dev_id+inode nubmer of the written file. So what is needed to be done, is saving this data (the mapping) to a file in the output directory when one of these events happen.

**Comment by ng29** [comment]
> Hi @ng29 ,
> 
> One of Tracee's features is capturing files written by the traced processes.
> To enable file capture, one should provide "--capture write" as part of the arguments to Tracee, optionally with 1-3 filters, given by "--filter-file-write".
> File writes are then saved to the output directory (defaults to /tmp/tracee), with a name constructed from the device id and inode number of the file.
> The reason why these files are not saved by using the name of the original file path, is that the same file can be written from different paths (e.g. when a hard link is used), and we want to represent the real data that was eventually written to the file. Device id and inode number uniquely represent a file in the system, however, it is somewhat cryptic when trying to figure out from the file name, what is the original file that was written.
> 
> In order to properly map between dev id+inode number to file path, it is necessary to save this data in a map when one of "vfs_write" or "vfs_writev" events happen. These events contain both the path and the dev_id+inode nubmer of the written file. So what is needed to be done, is saving this mapping to a file in the output directory.

Hey @yanivagman , thanks for providing information... but as far as i understood this seems to be quite tricky (Contradicting to label good-first-issue) from my perspective..

So i think its not my cup of tea(Will be exploring other issues within repo)

Cheers

**Comment by yanivagman** [comment]
Hi @ng29 , no problem!
Just note that this may sound trickier than what it actually is, as I tried to describe the whole picture.
Eventually, all the data is given in the events (vfs_write + vfs_writev), and all that is needed is to record it to a file.

**Comment by pathtofile** [comment]
De we currently send down the original filename with the vfs_write events? Relevant code is in `processFileWrites` around https://github.com/aquasecurity/tracee/blob/master/tracee/tracee.go#L928 right?

**Comment by yanivagman** [comment]
Hi @pathtofile ,

We do send the original filename with thevfs_write events.
The code in processFileWrites is not related, as it is used to capture the files, and not show the events.
The vfs_write(v) events are shown as any other event in tracee's output, and can be processed in the function processEvent https://github.com/aquasecurity/tracee/blob/42cd0b70d39ae8bc0b41cb452fe6702f8d07b005/tracee/tracee.go#L664

**Comment by pathtofile** [comment]
ok cool, so if someone were to pick this up, they would start at that `processEvent` function, and if we end up capturing/copying a file, they should also get the original filename from the event and write that to an index file. And that index file should be in the folder specified by `t.config.OutputPath`. Is that correct?

**Comment by itaysk** [comment]
@pathtofile it's actually simpler than that: the `//capture executed files` section in `processEvent` function has all the needed information: in `filePath` and `destinationFilePath` vars. You just need to collect and print them out into a file at the end of the run.

**Comment by yanivagman** [comment]
@itaysk your last comment may be misleading.
The original intent was to map between written files filenames ("write.dev-%d.inode-%d") to original filename.
The data avialable in captured execued files section in `processEvent` is about "exec.%d.%s" files.

**Comment by itaysk** [comment]
yes, sorry my bad. When writing the comment I thought about executed files but this is about written files. 
maybe it would be nice to also have an index of executed files. not necessary cause the file names are more meaningful but might be good for consistency, that every capture option will produce a file with all the files. wdyt @yanivagman ?

@jan0ski - if you want to take another stab at the original intent, please ignore my previous comment (which i'll edit), and instead take a look at the `processFileWrites` function, where the "written" files are really created.

**Comment by yanivagman** [comment]
@itaysk `processFileWrites` will not be a good place to implement this. See my previous comment:

> We do send the original filename with the vfs_write events.
> The code in processFileWrites is not related, as it is used to capture the files, and not show the events.
> The vfs_write(v) events are shown as any other event in tracee's output, and can be processed in the function processEvent

Having an index of executed files (and memory written files?) can be nice to have, but as you said, is not a must.

**Comment by itaysk** [comment]
yes, we don't have the file names there..

**Comment by jan0ski** [comment]
Thanks, both for the feedback.  Had a few confusions I raised in the PR but I think studying the codebase a bit more and reading your comments have helped.  I'll work to update this.
