### ISSUE TITLE
executed files are sometimes missed

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#215]
(reported by Idan)
probably because the container exists quickly

**Comment by rafaeldtinoco** [comment]
I believe this issue could be closed now as it could be pretty much anything. We're currently in much better shape regarding missed events now that we're discussing performance improvements AND we have a default caching mechanism that can be enabled on execution.

**Comment by yanivagman** [comment]
I don't think we should close this yet.
The current implementation of this feature has race conditions that should be addressed, or at least documented

**Comment by yanivagman** [comment]
#226 can be used to track this as well
