### ISSUE TITLE
CWD is sometimes changed to kernel headers directory

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#216]
(reported by Idan)
In a go program that loads tracee as a library and writes to a file simultaneously, meaning there are 2 goroutins, one that runs tracee, another that writes files to a relative path. Some files are being written to the kernel headers directory, instead of the directory where this program runs. The hunch is it's related to ebpf compilation, probably something there is `cd`ing around, and the process is affected.

**Comment by yanivagman** [comment]
Which files exactly are written to the kernel headers directory? And where do we use relative paths?

**Comment by itaysk** [comment]
another program that uses tracee as a library, not tracee itself. but the fact that tracee was loaded seems to have affected the host program.

**Comment by yanivagman** [comment]
Ok, now it's clearer.
So why "some files"? we're not changing dir while running tracee, and compilation only happens on start - so it should have been permanent (always writing to kernel headers dir) according to the ebpf compilation theory.

If indeed BCC does a directory change on compilation, then the solution is to chdir back after bpf initialization is completed.

**Comment by itaysk** [comment]
Maybe they cd into headers and then back, and code that happens to run
while ebpf compiles is written to the wrong place. In that case the
workaround is to just wait until initbpf is finished.

**Comment by yanivagman** [comment]
Why workaround? As I said, the solution is to chdir back after init bpf is finished -
We can add one line to save current working dir in init_bpf function start and add one other line to change dir back in init_bpf function end

**Comment by itaysk** [comment]
Cd *after* initbpf doesn’t fix because while initbpf is running the problem
remains. If you wait till after initbpf to cd then The cd is not needed.
 Of course we first need to repro and validate the hypothesis for the root
cause

**Comment by yanivagman** [comment]
If the problem *only* exists during the bpf init phase, this is not an issue, and can be marked as a limitation, that the calling process should not perform any file writes during bpf init.

I thought that the problem persists after bpf init is finished (and the current dir is kept set to the kernel headers dir) - and in that case, the above solution works

**Comment by yanivagman** [comment]
This should not happen now, as BPF code compilation is now done by tracee or in the makefile, and not by BCC.
