### ISSUE TITLE
Wait for perf buffer to empty before exiting tracee-ebpf

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#2171]
## Prerequisites

- [x] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [ ] I'll create a PR to implement this feature (assign to yourself).
- [x] Someone else should implement this (describe it well).

## Feature description

After sending a termination signal to tracee-ebpf (Ctrl+C), tracee-ebpf should first kill the bpf programs, and continue to consume events from the perf buffer in the go userspace. This will empty the perf buffer and no event will be lost due to premature exit.

**Comment by danielciuraru86** [comment]
We noticed this issue when running tracee in CI.
We created a workflow where we generate a few system events (network, process_exec, filesystem) and the last one before the tracee termination signal was not always present in the output. (the type of the last event did not matter)

Snippet from our workflow

```
      - name: Start Tracee public
        uses: aquasecurity/tracee-action@v0.3.0-start

      - name: Create Profile Data
        run: |

          echo "Creating detection data"
          date
          nmap -sV -p 80 localhost

          echo "Creating container data"
          sudo docker run -d alpine:3.17.1 sleep 1

          echo "Creating filesystem data"
          echo "console.log('Addition');" > testdata/files/to-add.js
          echo "console.log('Modification');" >> testdata/files/to-modify.js
          rm -f testdata/files/to-delete.js

          echo "Creating network call data"
          curl -sL https://facebook.com > /dev/null
          
      - name: Stop Tracee
        uses: aquasecurity/tracee-action@v0.3.0-stop
```

The last curl to facebook.com sometimes is missed

**Comment by rafaeldtinoco** [comment]
@danielciuraru86 and @tamirkiviti13 be aware that the network code needs the work being done at https://github.com/aquasecurity/tracee/pull/2716 to be WAY more reliable (and don't miss network flows).

For your awareness, you might be experiencing the results of that bug (and not this one).

**Comment by yanivagman** [comment]
> @danielciuraru86 and @tamirkiviti13 be aware that the network code needs the work being done at #2716 to be WAY more reliable (and don't miss network flows).
> 
> For your awareness, you might be experiencing the results of that bug (and not this one).

They mentioned to me that adding delay at the end of the run resolved the problem, so I think it is indeed related to this one.

**Comment by danielciuraru86** [comment]
@rafaeldtinoco we noticed the same behavior regardless of the type of command that was run last on the "Create Profile Data" step. (we tried a few combinations of that step, always the last command is missed)
We will take into account issue #2716 as it may affect us in other cases. @tamirkiviti13 FYI

**Comment by geyslan** [comment]
@AsafEitani @danielciuraru86 do you have any reproducer for this? Could you please test it against https://github.com/aquasecurity/tracee/pull/2969? Thanks.

**Comment by AsafEitani** [comment]
Sadly we don't have a stable reproducer
