### ISSUE TITLE
Multi scopes (set) of filters

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2176]
Currently Tracee only supports one set of filters (in the CLI) given by the user to decide about the scope of events to emit as part of the output. 

In some cases, the user might want to be able to have different “streams” of events. Each stream can be described by a different scope, which is in fact a different set of filters.

# Technicalities

Covered issues:

- https://github.com/aquasecurity/tracee/issues/2301
- https://github.com/aquasecurity/tracee/issues/2337

**Comment by rafaeldtinoco** [comment]
Closed by https://github.com/aquasecurity/tracee/pull/2626
