### ISSUE TITLE
Remove `$` from code examples

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#2184]
Let's remove `$` from code examples on the documentation, when one clicks to copy it, it always add the `$` failing the command once you past it on the terminal.

Eg:

```
$ helm repo add aqua-charts https://aquasecurity.github.io/helm-charts
$ helm dependency update ./deploy/helm/tracee
$ helm install tracee ./deploy/helm/tracee \
    --namespace tracee-system --create-namespace \
    --set hostPID=true \
    --set postee.enabled=true
```

should be 

```
helm repo add aqua-charts https://aquasecurity.github.io/helm-charts
helm dependency update ./deploy/helm/tracee
helm install tracee ./deploy/helm/tracee \
    --namespace tracee-system --create-namespace \
    --set hostPID=true \
    --set postee.enabled=true
```

**Comment by sassukeuchiha** [comment]
Hey @josedonizetti is this issue resolved or can I take up this ?

**Comment by josedonizetti** [comment]
@sassukeuchiha I would love some help to do this. Let me know if you still interested.

**Comment by sassukeuchiha** [comment]
yes @josedonizetti would love to work on this , will read the docs once and get in to resolve the issue

**Comment by sassukeuchiha** [comment]
Hey @josedonizetti should I make changes just on the Install Tracee on Kubernetes page or this needs to be done whole document wide

**Comment by sassukeuchiha** [comment]
Hello, @yanivagman, @josedonizetti, Actually, I was working on another issue when I made an unintentional sync fork. 😅 
I didn't know how to revert back, so I raised a new PR https://github.com/aquasecurity/tracee/pull/2694

**Comment by yanivagman** [comment]
Done
