### ISSUE TITLE
[REFAC] Change all log calls to logger package ones

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2207]
## Prerequisites

Select one OR another:

- [ ] I have discussed the refactoring idea with one (or another) maintainer.
- [ ] I'll create a PR to implement this refactoring idea (assign to yourself).
- [x] Someone else should implement this (describe it well).

## Refactoring description

Refactoring is needed to standardize the use of logging interface across the project. 

(Edit from @NDStrahilevitz: `tracee-bench` is an exception to this issue and should be left as is).

## Additional Information

The use of the new logger API can be checked in:
- https://github.com/aquasecurity/tracee/pull/2110
- https://github.com/aquasecurity/tracee/pull/2208

**Comment by ShubhamPalriwala** [comment]
Hey @geyslan Can I take this up?

**Comment by geyslan** [comment]
Hi @ShubhamPalriwala. For sure. Anything please ask.

**Comment by ShubhamPalriwala** [comment]
Hey, would like to know what format are we following when logging for an error:

Currently:
```go
log.Printf("error while decoding event: %v", err)
```

With the new logger:
```go
logger.Error("error while decoding event:" + err.Error(), "error", err)
logger.Error("error while decoding event", "error", err)
```

I think the second line makes more sense as we have the generalised error in the message and the detailed error with the "error" key,
Let me know if this makes sense, as this would also require changing a few test cases

**Comment by geyslan** [comment]
> Hey, would like to know what format are we following when logging for an error:

The Error API already makes it clear that it's an error, so I would remove redundant information from the message `"decoding event"` and for the key value pair I would stick with the type (or name of the info) and value `"error", err`:

```go
logger.Error("decoding event", "error", err)
```

@yanivagman @rafaeldtinoco @NDStrahilevitz @josedonizetti WDYT?

**Comment by geyslan** [comment]
> @geyslan Could even remove the "error" argument I believe since log level should take care of it but looks right.

In that case, in order not to lose the `err` information, this can be a option:

```go
logger.Error("decoding event: " + err.Error())
```

**Comment by ShubhamPalriwala** [comment]
> > @geyslan Could even remove the "error" argument I believe since log level should take care of it but looks right.
> 
> In that case, in order not to lose the `err` information, this can be a option:
> 
> ```go
> logger.Error("decoding event: " + err.Error())
> ```

This makes the most sense to me and is pretty clean as well + uniform in the context of its parsing as there's one string that contains everything about the error.
Let me know if I can proceed further with the same

**Comment by geyslan** [comment]
> > > @geyslan Could even remove the "error" argument I believe since log level should take care of it but looks right.
> > 
> > In that case, in order not to lose the `err` information, this can be a option:
> > 
> > ```go
> > logger.Error("decoding event: " + err.Error())
> > ```
> 
> This makes the most sense to me and is pretty clean as well + uniform in the context of its parsing as there's one string that contains everything about the error.
> Let me know if I can proceed further with the same

From my end it's ok. Let's just hear again from @NDStrahilevitz and @yanivagman.

**Comment by ShubhamPalriwala** [comment]
Hey, so I implemented the logger [here on my fork](https://github.com/ShubhamPalriwala/tracee/tree/shubham/refactor-logger) and as expected, the tests under **TestEngine_ConsumeSources** in [`pkg/rules/engine/engine_test.go`](https://github.com/ShubhamPalriwala/tracee/blob/shubham/refactor-logger/pkg/rules/engine/engine_test.go) are failing for those where the test cases are listening for errors.

```sh
{"level":"error","ts":1665221925.2151358,"msg":"signature Fake Signature doesn't declare an input source"}
{"level":"error","ts":1665221925.2164664,"msg":"Ignored key without a value.","ignored":"error initializing signature Fake Signature: init failed"}
{"level":"error","ts":1665221925.216454,"msg":"loading signature: %v"}
{"level":"error","ts":1665221925.2177777,"msg":"Ignored key without a value.","ignored":"error getting selected events for signature Fake Signature: getSelectedEvents error"}
{"level":"error","ts":1665221925.2177703,"msg":"loading signature: %v"}
{"level":"error","ts":1665221925.2190068,"msg":"Ignored key without a value.","ignored":"error getting metadata: getMetadata error"}
{"level":"error","ts":1665221925.2189963,"msg":"loading signature: %v"}
--- FAIL: TestEngine_ConsumeSources (0.02s)
    --- FAIL: TestEngine_ConsumeSources/sad_path_-_with_all_events_selector,_no_source (0.00s)
        /home/shubham/Desktop/tracee/pkg/rules/engine/engine_test.go:460: 
            	Error Trace:	/home/shubham/Desktop/tracee/pkg/rules/engine/engine_test.go:460
            	Error:      	"" does not contain "signature Fake Signature doesn't declare an input source\n"
            	Test:       	TestEngine_ConsumeSources/sad_path_-_with_all_events_selector,_no_source
            	Messages:   	sad path - with all events selector, no source
    --- FAIL: TestEngine_ConsumeSources/sad_path_-_signature_init_fails (0.00s)
        /home/shubham/Desktop/tracee/pkg/rules/engine/engine_test.go:460: 
            	Error Trace:	/home/shubham/Desktop/tracee/pkg/rules/engine/engine_test.go:460
            	Error:      	"" does not contain "error initializing signature Fake Signature: init failed\n"
            	Test:       	TestEngine_ConsumeSources/sad_path_-_signature_init_fails
            	Messages:   	sad path - signature init fails
    --- FAIL: TestEngine_ConsumeSources/sad_path_-_getSelectedEvents_returns_an_error (0.00s)
        /home/shubham/Desktop/tracee/pkg/rules/engine/engine_test.go:460: 
            	Error Trace:	/home/shubham/Desktop/tracee/pkg/rules/engine/engine_test.go:460
            	Error:      	"" does not contain "error getting selected events for signature Fake Signature: getSelectedEvents error\n"
            	Test:       	TestEngine_ConsumeSources/sad_path_-_getSelectedEvents_returns_an_error
            	Messages:   	sad path - getSelectedEvents returns an error
    --- FAIL: TestEngine_ConsumeSources/sad_path_-_getMetadata_returns_an_error (0.00s)
        /home/shubham/Desktop/tracee/pkg/rules/engine/engine_test.go:460: 
            	Error Trace:	/home/shubham/Desktop/tracee/pkg/rules/engine/engine_test.go:460
            	Error:      	"" does not contain "error getting metadata: getMetadata error\n"
            	Test:       	TestEngine_ConsumeSources/sad_path_-_getMetadata_returns_an_error
            	Messages:   	sad path - getMetadata returns an error
FAIL
FAIL	github.com/aquasecurity/tracee/pkg/rules/engine	0.019s
FAIL
```

I debugged it for a while and understood that it is unable to read the errors our package logger is throwing and has something to do with:
https://github.com/ShubhamPalriwala/tracee/blob/shubham/refactor-logger/pkg/rules/engine/engine_test.go#L410 and https://github.com/ShubhamPalriwala/tracee/blob/shubham/refactor-logger/pkg/rules/engine/engine_test.go#L438

Can you please help here if possible?

For reference, these are the changes I made in the `engine.go` file: https://github.com/ShubhamPalriwala/tracee/commit/e8aa6b789247d1e293e792ae22569444f6153d4b

**Comment by geyslan** [comment]
Hey @ShubhamPalriwala. Sorry for the delay in responding.

Firstly, I ask you to send a draft PR with your current work. This would facilitate discussions over the current proposal.

Before tackling the `_test.go` error I suggest you take a look at how we (for now) decided to initialize the logger in the `cmd/tracee-{ebpf,rules}/main.go` files.

https://github.com/aquasecurity/tracee/blob/main/cmd/tracee-ebpf/main.go#L57-L69

https://github.com/aquasecurity/tracee/blob/main/cmd/tracee-rules/main.go#L39-L51

This logger is automatically initialized when the package is imported, but its settings can be overridden by environment variables at this point: https://github.com/aquasecurity/tracee/blob/main/pkg/logger/logger.go#L394-L396

So if the package it's not a tool start like tracee-ebpf, tracee-rules, tracee-bench (main package) I suppose you can forget about initialization once these other packages will inherit the logger settings through the pkg/logger import.

Returning to the [pkg/rules/engine/engine_test.go](https://github.com/ShubhamPalriwala/tracee/blob/shubham/refactor-logger/pkg/rules/engine/engine_test.go) shown issue. I think it can be related to the io.writer set. In the test this writer is saving in logBuf while the pkg/logger is writing to the stderr:

https://github.com/ShubhamPalriwala/tracee/blob/shubham/refactor-logger/pkg/rules/engine/engine.go#L55
https://github.com/ShubhamPalriwala/tracee/blob/shubham/refactor-logger/pkg/logger/logger.go#L87-L89

So this' the case where we need to take care of the logger initialization. Try resetting the logger settings to use the local logBuf as the output with `Init()`: https://github.com/aquasecurity/tracee/blob/main/pkg/logger/logger.go#L423-L431

Thank you again for taking care of this. 🚀
