### ISSUE TITLE
Additional tracing modes

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#221]
We currently support three modes of operation. It may be useful to add three more.
As we don't want to have a flag for each of these modes, we better change the UX to use "--trace-target" as suggested below by @itaysk 

trace target | trace mode | status (issue)
--- | --- | ---
process | all | TODO
process | new | implemented, migrate UX
process | specific | implemented, migrate UX
container | all | TODO
container | new | implemented, migrate UX
container | specific | TODO https://github.com/aquasecurity/tracee/issues/255

**Comment by itaysk** [comment]
for interactive, exploratory use, I often want to trace everything that happens in a specific terminal. if I use option 3 - trace specific pid of the shell, the shell itself is traced as well which can generate some noise. it would be nice if we could be able to trace a pid's children, without the pid itself.

**Comment by siddharths2710** [comment]
Hey @yanivagman I'm interested in tackling these different modes of operation. 

Could edit the description by adding the points as a checklist instead?

Thanks!

**Comment by itaysk** [comment]
So we have a few options for what is the trace target: container, process, system. and for each trace target we have a few modes: all, new, specific. 
I would not want to see flag for each option, and propose to simplify the ux by one of the following:
1. `--trace-target container/process/system --trace-mode all/new/id`
2. combine both settings into one flag like `--trace-target container:id`
@yanivagman wdyt?

**Comment by yanivagman** [comment]
@itaysk 

Good idea adding these flags.
Then we can remove the "-c" "--pid", and maybe add "-t" as a shortcut to "--trace-target".

**Comment by itaysk** [comment]
Great so can you please edit the issue description accordingly. I would put it in a matrix:

trace target | trace mode | status (issue)
--- | --- | ---
process | all | TODO
process | new | implemented, migrate UX
process | specific | N/A (this is remote tracing I suppose)
container | all | TODO
container | new | implemented, migrate UX
container | specific | TODO https://github.com/aquasecurity/tracee/issues/255

**Comment by pathtofile** [comment]
hey @itaysk , could you provide an example for how you think `--trace-target` could work if you wanted a specfic contain *and* a specific pid? or perhaps with the idea of tracing only children of a PID inside a container? I have no idea how likley or needed that would be, but as an alternative, what if you kept the process filtering and container filtering as seperate flags, but insted enabled special keywords, e.g.:

Command | Meaning
--- | ---
`--pid all` | All PIDs
`--pid new` | Only new PIDs (default)
`--pid id:<number>` | Only this pid and children
`--pid children:<number>` | Only this pid's children
--- | ---
`--container system` | Trace entire system and not just containers (default)
`--container all` | Trace Containers only
`--container id:name` | Trace specific container or pod

**Comment by yanivagman** [comment]
Hi @pathtofile ,

I like your suggested direction as well.
I would just remove "--container system" as this is the default behavior, and also confusing, as system mode is not related to containers, but traces all the processes in the system.
Instead, I would put "--container new" to trace newly created containers (which we already support today using "-c" flag).

**Comment by pathtofile** [comment]
Opened a PR with suggested alterations: https://github.com/aquasecurity/tracee/pull/265

**Comment by itaysk** [comment]
@pathtofile thanks for collaborating with us on this!

I'm not a big fan of splitting into flags for two reasons:
1. It's not scalable, UX wise, if we need to add new flag for every mode we'll want to support. I would prefer to find a way to use a fixed number of flags.
2. it implies that all the combinations of modes are supported as well, which puts us in a difficult spot. If we add kubernetes mode, and it's a new flag, do we allow to use it with the other flags? it would become difficult to implement or enforce.

So I suggest we stick with the original plan, or add maybe another fixed flag if needed. IMO we don't have to support tracing specific pid in specific container at this point (we didn't support it before). If someone really needs it they can trace the host pid.

WDYT?

**Comment by pathtofile** [comment]
So I’m happy to take your leads on this, when you say original do you mean having just `—trace-target` or `—trace-target` and `—trace-mode`?

My only thoughts are we will also need to make sure there is documentation to accompany this, as I fell it will be hard to clearly explain what combinations of what `target` and `mode` are supported in single-line the cli help for the options.

**Comment by yanivagman** [comment]
@itaysk I tend to disagree with you on this one.
The possible traced entities in "our world" are:
1. Processes
2. Containers
3. Pods
Did I miss anything?
I think that using a flag for each of these entities is clearer, and will feel more natural to the user.

Regarding your second point - how is what you suggested doesn't suffer from this as well? 
If we use "--trace-target container/process/system --trace-mode all/new/id" as you suggested - it has the exact same problem of not knowing which combinations are valid. Of course, this can be solved by telling the user that the mode is not supported, but it can be done either way.

I think that what @pathtofile suggested is good, with minor modifications:

trace target | trace mode | UX | status (issue)
--- | --- | --- | ---
process | all | --pid all | TODO
process | new | --pid new | implemented, migrate UX
process | specific | --pid _pid_ | implemented, migrate UX
container | all | --container all | TODO
container | new | --container new | implemented, migrate UX
container | specific | --container _cid_ | TODO https://github.com/aquasecurity/tracee/issues/255

This also has the advantage that we don't have to make changes in the current ux.
We can keep --pid id as we have today, and we can keep --container, which when used without extra command will default to --container new as we have today.

**Comment by itaysk** [comment]
> how is what you suggested doesn't suffer from this as well?

my suggestion is to not support mixed modes, simple as that. we don't support it today and I don't think it's an important use case. But I'm not entrenched in this so we can go with @pathtofile 's suggestion if you prefer

**Comment by yanivagman** [comment]
What exactly do you mean by mixed modes? I thought that we were referring to how the flags should look like. If you suggest not mixing, for example, tracing container with a given pid (this is my understanding for what you call mixed mode) - so we can still do that with  what @pathtofile suggested.

**Comment by itaysk** [comment]
Yes this is what I meant. of course we can do that with any UX paradigm, the questions is which one is clearer. I didn't think that providing multiple flags each with a diverse set of options and then expecting the user to understand how the different flags and options work or doesn't work together, is a good approach, so I proposed to make this a single flag which naturally reflects that the user need to choose one option, and makes extending this flag in the future simpler.
FWIW the proposed PR internally chose a single `TraceMode` configuration (rather than multiple configs) which maybe signals that we internally think of this feature as a single choice rather then disjoint options.

Anyway, I really didn't mean to be a blocker here, just to offer my perspective. If you both like the other approach please go ahead with it.

**Comment by yanivagman** [comment]
Agreed.
So, we will make the modes mutually exclusive, while keeping the flags we have today (--container and --pid).
For any of (container/pid) we will have three possible modes:  all/new/specific - and these modes will be mutually exclusive as well.

**Comment by yanivagman** [comment]
Actually, we can keep the modes mutually exclusive by having a mode flag, with the above ux:

trace target | trace mode | UX | status (issue)
--- | --- | --- | ---
process | all | --mode pid all | TODO
process | new | --mode pid [optional: new] | implemented as default behavior, add "new" command
process | specific | --mode pid _pid_ | implemented
container | all | --mode container all | TODO
container | new | --mode container [optional: new] | implemented when using --container, add "new" command
container | specific | --mdoe container _cid_ | TODO https://github.com/aquasecurity/tracee/issues/255

This approach, however, has the disadvantage of adding an extra "mode" word that the user will have to write as part of the command.

WDYT?

**Comment by pathtofile** [comment]
I’m good with that, not familiar with the cli library tracee uses, is double/sub keywords possible?

**Comment by yanivagman** [comment]
Didn't try this as well (using double words in the cli) - need to look at the docs.
If not, we can use what Itay suggested before:
--mode pid:all(/new/_pid_)
--mode container:all(/new/_cid_)

I'm just not sure about the extra "mode" here - it requires the user to type more.
On the other hand, using "-m" as a shortcut can help...
WDYT @itaysk @pathtofile ?

**Comment by itaysk** [comment]
@yanivagman this is exactly what I suggested...

**Comment by itaysk** [comment]
> I'm just not sure about the extra "mode" here

why is "mode" an extra? it's the only flag that the user provides no?

**Comment by itaysk** [comment]
@pathtofile 
> not familiar with the cli library tracee uses, is double/sub keywords possible?

you would parse the arg value as a string

**Comment by yanivagman** [comment]
> @yanivagman this is exactly what I suggested
like I said:
> we can use what Itay suggested before

I still think that scalability is not an issue here, and that we can prohibit mode mixing either way (your original arguments).
The thing that I want us to think about now is only the UX - what will be easier for the user?
I think that it is more natural for the user to just use --pid and --container with one of all/new/id, and give an error message if mode mixing happens. Do you think that using "mode" is better (from UX standpoint)?

> why is "mode" an extra? it's the only flag that the user provides no?
--mode pid all VS --pid all

**Comment by itaysk** [comment]
> I want us to think about now is only the UX - what will be easier for the user

When I say UX this is exactly what I mean - what will be easier for the user. I had no other meaning

>  Do you think that using "mode" is better (from UX standpoint)?

Yes. I think it's easier to remember that there is one flag that controls the scope of the trace rather then having multiple flags. Also it's easier to discover all the scope related options in one place (when browsing the --help). Also I think it's intuitively conveying the exclusivity rules, without having to read the docs or to encounter a validation error.
That's just my hunch. If you think otherwise that's fine with me, this is not the hill I'll die on :)

**Comment by yanivagman** [comment]
Ok, these are good arguments to use "mode" flag.
Let's just consider one more case - tracing multiple (specific) pids or multiple (specific) containers.
In that case, today, the user needs to specify the flag --pid multiple times.
I think that if we want to keep things simple with one flag, we should support providing a list of pids with this "mode" flag.
Maybe something like --mode pid:pid1:pid2:....
Then, we can allow only one occurance of "mode" flag, and ignore the others (and we can remove all the code that checks for mutual exclusiveness)

One more thing. "mode" flag or "target" flag? I think that mode is more of an internal tracee term, and maybe for the user it will be more natural to user "target".

WDYT?

To conclude, this is how the UX may look like with "target" (or just "-t") flag:

trace target | trace mode | UX | status (issue)
--- | --- | --- | ---
process | all | --target process:all | TODO
process | new | --target process [_optional_: process:new] | implemented, migrate UX
process | specific | --target process:_pid1_:_pid2_:... | implemented, migrate UX
container | all | --target container:all | TODO
container | new | --target container [_optional_: container:new] | implemented, migrate UX
container | specific | --target container:_cid1_:_cid2_:... | TODO https://github.com/aquasecurity/tracee/issues/255

We can also support shortcuts for "container" ("c") and "process" ("p"), and then tracing a specific mode becomes short:

`tracee -t p:all` or `tracee -t c:new`

**Comment by itaysk** [comment]
sounds good to me. 
BTW - for kubernetes tracing, I thought about it more and I think we should defer those configurations to the kubectl plugin which we already had planned for. The Tracee binary should cover all the OS level tracing modes, and other integrations can be implemented by configuring the integration (kubernetes) and to use those core tracing modes. for example, the plugin should be able to trace a pod/node/deployment/etc - that is out of scope for core Tracee.

**Comment by yanivagman** [comment]
Good.
@pathtofile what do you think?
If you also agree, we can continue with #265 with this UX

**Comment by pathtofile** [comment]
@yanivagman Yep, fine with me! I'll make the changes to the PR

**Comment by yanivagman** [comment]
> for interactive, exploratory use, I often want to trace everything that happens in a specific terminal. if I use option 3 - trace specific pid of the shell, the shell itself is traced as well which can generate some noise. it would be nice if we could be able to trace a pid's children, without the pid itself.

@itaysk here is the thing...
If we will not trace the parent pid itself, then when it will fork and execute a new binary, you will not be able to capture it (as the parent pid is not traced). 
What we can do, however, is to keep using pid mode like we have today for this use case, and enable the user not to output events of a specific pid.
This can be done in one of two ways:
1. Exclude the parent pid in shouldPrint() function in userspace
2. Use a new map, which tells the kernel not to send events of specific pids (these pids will still be traced, but will not send events from the kernel)

Either way - we can open a new issue for this if you think this is usefull, as I don't think we should consider this as a new mode

**Comment by itaysk** [comment]
@yanivagman  I didn't understand how the implementation details affect the decision to include this feature. why does it matter if the filtering is done in user/kernel or requires a new map? for the user it's just a flag option. Why don't you think we should consider this as a new tracing mode?

**Comment by pathtofile** [comment]
For interactive, exploratory situations, if it’s just the single PID you’d wish to not see, would piping it through a a grep or jq to remove the unwanted events be enough?

I’m not sure how it fits in UX wise, but I think the idea of being able specify a list arbitrary pids to ignore a potentially good new feature. And I think for that use case filtering in the kernel at the ‘earliest’ point would be the most efficient, right?

**Comment by yanivagman** [comment]
@itaysk it's more than just implementation details.

Do you think this feature deserves its own mode?
From the way I see it, it's just another feature, but not a mode.
What you are asking is exactly the same thing as specific pid mode, with the request to hide one of the pids (to be generic).
I think it is cleaner (both from UX perspective and implementation) to implement this as a different feature, where the user can exclude pids from the output.
To be even more generic, we can have both "exclude-process" and "exclude-container" feature flags, which will allow the user to exclude these from the output if not necessary.
In your specific use case, the parent pid have to still be traced as I explained above. You just ask to hide it's output.

@pathtofile indeed, filtering in the kernel will be most efficient

**Comment by yanivagman** [comment]
I would even suggest having "--no-trace" which has the same syntax as "--trace", where you can exclude traced entities.

**Comment by itaysk** [comment]
ok, that can work as well

**Comment by yanivagman** [comment]
PR #268 adds new container and new process modes.
Issue #255 will track progress in specific container mode.
For additional tracing capabilities - e.g. "--no-trace" as discussed above - we can open a new issue
