### ISSUE TITLE
Support multiple outputs for tracee-ebpf

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#2231]
## Prerequisites

- [x] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [ ] I'll create a PR to implement this feature (assign to yourself).
- [x] Someone else should implement this (describe it well).

## Feature description

This feature is about adding support for multiple outputs of tracee-ebpf.
An example use case is if someone wants to display the table output on screen but save the json output to disk for later investigation.
Another use case is outputting both json and gob formats for signature testing purposes.

**Comment by patrick-stephens** [comment]
I've submitted a PR to integrate with Fluent Bit which potentially also resolves this: #2155 
You can use Fluent Bit then to send to one/many differing endpoints including a file, S3, etc. without any change to Tracee required: https://docs.fluentbit.io/manual/pipeline/outputs
