### ISSUE TITLE
[REFAC] improve help handling

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#2240]
## Prerequisites

Select one OR another:

- [ ] I have discussed the refactoring idea with one (or another) maintainer.
- [x] I'll create a PR to implement this refactoring idea (assign to yourself).
- [ ] Someone else should implement this (describe it well).

## Refactoring description

There is a lot of repetition to handle and print when of flags with its own help (eg: `--capture help`). Let's improve this, because we also need to handle and print help commands on new subcommand of the one binary to boot collection and rules at the same time.

**Comment by itaysk** [comment]
related (but not required): #436
