### ISSUE TITLE
[FEAT] logger: output origin as key/value

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2248]
- [x] I'll create a PR to implement this feature (assign to yourself).

## Feature description

Implement logic to automagically output debug logs containing origin information (package, file, line) as key/values, e.g.:

```go
logger.Debug("my log", "somekey", "somevalue")
```

```
{"level":"debug","ts":1666125863.3628938,"msg":"my log","pkg":"main","somekey":"somevalue"}
```

**Comment by geyslan** [comment]
@rafaeldtinoco @josedonizetti @NDStrahilevitz 

We can make the debug level even more verbose, besides the package name we can output like:

```
{"level":"debug","ts":1666125863.3628938,"msg":"my log","pkg":"main","file":"main.go","line":"42","somekey":"somevalue"}
```

WDYT?

P.S.:
If the logger is being already consumed it can be a breaking change.

**Comment by rafaeldtinoco** [comment]
I want that. I started using logger for my capabilities package and understand there is a real need to have such information (in order to filter debug messages when all code uses the logger).
