### ISSUE TITLE
[BUG] No syscall_pathname when compiling a kernel module 

### ISSUE THREAD

**Issue by TalLessin** [aquasecurity/tracee#2260]
## Prerequisites

- [ ] I can reproduce the issue in latest released version.
- [ ] I can reproduce the issue in development version (from source tree).
- [X ] I checked the documentation and found no answer.
- [X] There isn't an issue describing the bug.

## Bug description
When running tracee while tracking only security_file_open no syscall_pathname appears when preforming a "make" command

This is how I'm executing tracee (cmdline):

This is the error I'm getting:

> [2022-10-20T12:17:34.684Z] 2022/10/20 12:17:31 error handling event by signature ReadWrite to fd: argument syscall_pathname not found in {Timestamp:1666268178217886884 ThreadStartTime:411848324866 ProcessorID:0 ProcessID:765 CgroupID:832 ThreadID:765 ParentProcessID:403 HostProcessID:24246 HostThreadID:24246 HostParentProcessID:23873 UserID:0 MountNS:4026532537 PIDNS:4026532540 ProcessName:make HostName:e5eb166db751 ContainerID:e5eb166db7512a86c71395a4cd25ce33ccb73763d8d664d565cd5b65f7edd5a0 ContainerImage: ContainerName: PodName: PodNamespace: PodUID: EventID:722 EventName:security_file_open ArgsNum:6 ReturnValue:0 StackAddresses:[] ContextFlags:{ContainerStarted:true} Args:[{ArgMeta:{Name:pathname Type:const char*} Value:/home/Diamorphine} {ArgMeta:{Name:flags Type:string} Value:O_RDONLY|O_LARGEFILE|O_NOATIME} {ArgMeta:{Name:dev Type:dev_t} Value:271581185} {ArgMeta:{Name:inode Type:unsigned long} Value:1800204} {ArgMeta:{Name:ctime Type:unsigned long} Value:1666268178156159541} {ArgMeta:{Name:syscall Type:string} Value:openat}]} 

## Steps to reproduce

Steps to reproduce the issue:

1. run tracee while filtering for security_file_open only
2. make a kernel driver

## Context

Relevant information about my setup:

* Linux version: ubuntu focal
* Linux kernel version: 22.04
* Tracee version (or commit id of your tree): any 
* LLVM version:
* Golang version:

**Comment by NDStrahilevitz** [comment]
Hi, opened the general case bug in #2261, let's track there.
