### ISSUE TITLE
[BUG] Arguments may be missing if submission fails

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#2261]
## Bug description

This is the general case of #2260.
In the bpf helper functions `save_to_submit_buf`, `save_bytes_to_buf`, `save_str_to_buf`, etc. the field `data->context.argnum` is not incremented on failure cases.
As such arguments can fail to be submitted and will be overriden, causing them to not exist in the event itself.

## Steps to reproduce

Simple reproduction can be done by doing this modificaiton
<img width="532" alt="image" src="https://user-images.githubusercontent.com/22661609/196957641-58c4ede6-2d66-4020-8f6d-ff2d68edfc81.png">
Then run `tracee-ebpf -t e=security_file_open -o option:detect-syscall` and note how both `pathname` and `syscall_pathname` are entirely missing from the arguments.

## Context

Relevant information about my setup:

* Linux version:
* Linux kernel version:
* Tracee version (or commit id of your tree):
* LLVM version:
* Golang version:

**Comment by NDStrahilevitz** [comment]
@AsafEitani @yanivagman @rafaeldtinoco I think we need this before our CNDR release as it's causing issues with signature testing.

**Comment by NDStrahilevitz** [comment]
> Do you know the sentence "it's not a bug, it's a feature"? So this is the case here :-)

Definitely not an intuitive reasoning here, since the event "contract" is broken. while I understand the reasoning, i'd say this is more a designed bug than a feature.

> We don't want to increment the argument number if we failed to save them in bpf code for any reason. This helps us to send the event to userspace even in cases where something fails (e.g. when failing to read some string from userspace memory, which is controllable by the userspace, thus can be made to fail on purpose).

If we fail to save something that means we need to treat a failure not ignore that it happened. wether that's by marking the argument for fixing or setting a default value then and there, it's a "breach of contract" of the event.

> Anyway, we may consider adding some default value to these arguments instead of simply removing them, but this will probably need to happen in userspace and not in the bpf code.

I think we will need to do this, AND mark optional arguments as such, for example the "syscall" arguments which are appended only for some CLI settings.

> Rules need to be ready to expect a non existing argument, and not fail tracee-rules in any case.
I don't really agree here, but we already have this issue with the optional "detect-syscall" which is practically required in our signatures. This expects rules to be aware of how tracee-ebpf may internally fail or succeed in argument logic.

Overall I think this issue exposes a design fault in how we treat sending incomplete events.

**Comment by yanivagman** [comment]
> Definitely not an intuitive reasoning here, since the event "contract" is broken. I'd say this is more a "purposefully designed" bug than a feature.

We never said that there is an "event contract" which assures that all the arguments will exist.
We do have plans to introduce this contract for "user friendly" (aka higher level) events though (but definitely not for all the events, which arguments may change from time to time.)

> If we fail to save something that means we need to treat a failure not ignore that it happened. wether that's by marking the argument for fixing or setting a default value then and there, it's otherwise a "breach of contract" of the event.

On the contrary. Instead of ignoring the error and not sending the event at all, we still send the event and not ignoring it. This is why we encapsulate the type of each argument and not simply count on the argument position to decode the type in userspace - so this design is fault tolerant.

> I think we will need to do this, AND mark optional arguments as such, for example the "syscall" arguments which are appended only for some CLI settings.

Yes, this should be part of the solution, and this is why I think it won't be a "quick fix"

**Comment by NDStrahilevitz** [comment]
> We never said that there is an "event contract" which assures that all the arguments will exist. We do have plans to introduce this contract for "user friendly" (aka higher level) events though (but definitely not for all the events, which arguments may change from time to time.)

For better or worse, the event definitions we give in `events.go` are a contract, at least the closest thing we have to one, as that's the only reference a user will have for an event, and will be listed in the event list of `tracee-ebpf --list`.
If an event can miss an argument, that's not documented anywhere, and I don't think it's good UX to make a consumer need to be concerned with that.

> On the contrary. Instead of ignoring the error and not sending the event at all, we still send the event and not ignoring it. This is why we encapsulate the type of each argument and not simply count on the argument position to decode the type in userspace - so this design is fault tolerant.

I didn't claim we need to not submit the event, but rather than simply ignoring the failure in order to move forward isn't the right call for behavior either.

I want to be clear, I don't think it was wrong to fault tolerate the argument submission, but I do think it counts as a bug as long as no fix is given for that failure at any other point in the event's flow.

Fixing in eBPF is not necessarily the right approach because the "default value" submit may also fail right?
As you said then, userspace would be the place to do this fix, probably adding a `FixArguments` function in the decode stage after filtering.

**Comment by yanivagman** [comment]
> Fixing in eBPF is not necessarily the right approach because the "default value" submit may also fail right?
> As you said then, userspace would be the place to do this fix, probably adding a FixArguments function in the decode stage after filtering.

Yes, I think this should be done in userspace, by looking at the missing argument indexes, checking if they are optional or not, and filling a default value according to the argument type

**Comment by yanivagman** [comment]
Copying two comments from #1204 which also discuss this issue:

@AsafEitani says:

> We expect events arguments coming from tracee-ebpf to match their definitions in consts.go.
> Sometime those arguments are not populated due to configuration or technical reasons (https://github.com/aquasecurity/tracee/issues/1158)
> 
> This creates a state in which the received event doesn't necessarily has the expected fields, which in turn makes tracee-ebpf to be less predictable and make automations harder.
> Also using those fields in tracee-rules means checking if the field exists - and to skip if it doesn't. This can cause a situation where we need a certain argument (such as syscall) and if it doesn't exists (like in events created from a kworker) we skip. If for some reason tracee-ebpf was run without the detect-syscall flag we would skip all the events without even knowing that they are skipped and that there is a problem.
> 
> We should add a default value for each argument type (could be 0 for int, empty string or "null" for char *, etc) and populate those missing fields automatically.
> 
> This will ensure a consistent output of tracee-ebpf.

@itaysk replied:

> I'm afraid this might be more complicated issue.. "nullable types"/"optional types" that is. Some things to consider:
> how do you know if 0 int is the default or just the value zero?
> how does this help you avoid writing code in the consumer that checks if the value is default and handle accordingly?
> how is this going to be portable across different type systems (we currently have go/json/rego)?

**Comment by yanivagman** [comment]
Quoting @AlonZivony from dup issue #2390:

> When an event has a missing argument, it should be filled and get a nil value.
> To make it more efficient from performance perspective, this should only be done during the parsing stage. This will make sure that we will filters events and remove events that should not be emitted before adding it, reducing processing time.

**Comment by NDStrahilevitz** [comment]
I've had some thoughts about the `nil` value. If we go with this approach then every argument check (in a helper or directly in signature) will need to include some `arg == nil` check. This can get rather cumbersome and may not be intuitive.
It may be more appropriate to go for a strategy like the `io.EOF` error we have in `Read` methods, rather than trying to define some alternative value, we should have an explicit method at the struct receiver level that attempts to:
1. Query the argument
2. Parse it to the correct type (we can use generics for this I believe)

Then we define a constant error that signifies a missing argument which we document near the function so users will know to check for it. This is more explicit and likely to be simpler as users will already check for an error value anyway when extracting an argument from an event.

**Comment by AlonZivony** [comment]
I agree that exposing an helper function which return error if the argument is missing is a very good API to deal with this problem.
However, not all of the events consumers are rules and written in Golang.
We should still give the argument a `nil` value so that static DB tables would be able to contain the values and that query's will be simplified.
I can assume that there are more case scenarios for consuming events, and I think giving default `nil` value is still the requirement to support all consumers.

**Comment by NDStrahilevitz** [comment]
I see your point. How about we have `GetArg` and `GetArgNullable`, we can expose the former for golang consumers and the latter in external consumers.
