### ISSUE TITLE
Tracee container on debian buster fails to run

### ISSUE THREAD

**Issue by neutrinoguy** [aquasecurity/tracee#2266]
## Prerequisites

- [x] I can reproduce the issue in latest released version.
- [ ] I can reproduce the issue in development version (from source tree).
- [x] I checked the documentation and found no answer.
- [x] There isn't an issue describing the bug.

## Bug description

Below is the docker command I am running after installing all prerequisites mentioned in the docs. 

`sudo docker run --name tracee --rm -it --pid=host --cgroupns=host --privileged -v /etc/os-release:/etc/os-release-host:ro -e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host -v /boot:/boot:ro -v /usr/src:/usr/src:ro -v /lib/modules:/lib/modules:ro -v /tmp/tracee:/tmp/tracee:rw aquasec/tracee:full ` 

This is the error I'm getting:

`INFO: probing tracee-ebpf capabilities... 
rm -rf ./dist rm -f .*.md5 rm -f .check* rm -f .*-pkgs* CC="clang" \ CFLAGS=""-fPIC"" \ LD_FLAGS="" \ make \ -C ./3rdparty/libbpf/src \ BUILD_STATIC_ONLY=1 \ DESTDIR=/tracee/src/dist/libbpf \ OBJDIR=/tracee/src/dist/libbpf/obj \ INCLUDEDIR= LIBDIR= UAPIDIR= prefix= libdir= \ install install_uapi_headers MKDIR /tracee/src/dist/libbpf/obj/staticobjs CC /tracee/src/dist/libbpf/obj/staticobjs/bpf.o CC /tracee/src/dist/libbpf/obj/staticobjs/btf.o CC /tracee/src/dist/libbpf/obj/staticobjs/libbpf.o CC /tracee/src/dist/libbpf/obj/staticobjs/libbpf_errno.o CC /tracee/src/dist/libbpf/obj/staticobjs/netlink.o CC /tracee/src/dist/libbpf/obj/staticobjs/nlattr.o CC /tracee/src/dist/libbpf/obj/staticobjs/str_error.o CC /tracee/src/dist/libbpf/obj/staticobjs/libbpf_probes.o CC /tracee/src/dist/libbpf/obj/staticobjs/bpf_prog_linfo.o CC /tracee/src/dist/libbpf/obj/staticobjs/xsk.o CC /tracee/src/dist/libbpf/obj/staticobjs/btf_dump.o CC /tracee/src/dist/libbpf/obj/staticobjs/hashmap.o CC /tracee/src/dist/libbpf/obj/staticobjs/ringbuf.o CC /tracee/src/dist/libbpf/obj/staticobjs/strset.o CC /tracee/src/dist/libbpf/obj/staticobjs/linker.o CC /tracee/src/dist/libbpf/obj/staticobjs/gen_loader.o CC /tracee/src/dist/libbpf/obj/staticobjs/relo_core.o CC /tracee/src/dist/libbpf/obj/staticobjs/usdt.o AR /tracee/src/dist/libbpf/obj/libbpf.a INSTALL bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h xsk.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h usdt.bpf.h INSTALL /tracee/src/dist/libbpf/obj/libbpf.pc INSTALL /tracee/src/dist/libbpf/obj/libbpf.a INSTALL ../include/uapi/linux/bpf.h ../include/uapi/linux/bpf_common.h ../include/uapi/linux/btf.h MAKEFLAGS="--no-print-directory" clang -S -nostdinc \ -D__TARGET_ARCH_x86 \ -D__BPF_TRACING__ \ -D__KERNEL__ \ -include /lib/modules/4.19.0-21-amd64/source/include/linux/kconfig.h \ -I /lib/modules/4.19.0-21-amd64/source/arch/x86/include \ -I /lib/modules/4.19.0-21-amd64/source/arch/x86/include/uapi \ -I /lib/modules/4.19.0-21-amd64/build/arch/x86/include/generated \ -I /lib/modules/4.19.0-21-amd64/build/arch/x86/include/generated/uapi \ -I /lib/modules/4.19.0-21-amd64/source/include \ -I /lib/modules/4.19.0-21-amd64/build/include \ -I /lib/modules/4.19.0-21-amd64/source/include/uapi \ -I /lib/modules/4.19.0-21-amd64/build/include/generated \ -I /lib/modules/4.19.0-21-amd64/build/include/generated/uapi \ -I ./dist/libbpf \ -I ./3rdparty/include \ -Wunused \ -Wall \ -Wno-frame-address \ -Wno-unused-value \ -Wno-unknown-warning-option \ -Wno-pragma-once-outside-header \ -Wno-pointer-sign \ -Wno-gnu-variable-sized-type-not-at-end \ -Wno-deprecated-declarations \ -Wno-compare-distinct-pointer-types \ -Wno-address-of-packed-member \ -fno-stack-protector \ -fno-jump-tables \ -fno-unwind-tables \ -fno-asynchronous-unwind-tables \ -xc -O2 -g -emit-llvm \ -c ./pkg/ebpf/c/tracee.bpf.c \ -o dist/tracee.bpf.4_19_0-21-amd64.v0_8_3.ll llc \ -march=bpf -mcpu=v2 \ -filetype=obj \ -o dist/tracee.bpf.4_19_0-21-amd64.v0_8_3.o \ dist/tracee.bpf.4_19_0-21-amd64.v0_8_3.ll rm dist/tracee.bpf.4_19_0-21-amd64.v0_8_3.ll ./pkg/ebpf/c/tracee.bpf.c:98:9: warning: 'likely' macro redefined [-Wmacro-redefined] #define likely(x) __builtin_expect((x), 1) ^ /lib/modules/4.19.0-21-amd64/source/include/linux/compiler.h:76:10: note: previous definition is here # define likely(x) __builtin_expect(!!(x), 1) ^ ./pkg/ebpf/c/tracee.bpf.c:99:9: warning: 'unlikely' macro redefined [-Wmacro-redefined] #define unlikely(x) __builtin_expect((x), 0) ^ /lib/modules/4.19.0-21-amd64/source/include/linux/compiler.h:77:10: note: previous definition is here # define unlikely(x) __builtin_expect(!!(x), 0) ^ ./pkg/ebpf/c/tracee.bpf.c:1788:13: warning: unused variable 'cgroup_id_lsb' [-Wunused-variable] u32 cgroup_id_lsb = context->cgroup_id; ^ ./pkg/ebpf/c/tracee.bpf.c:1799:13: warning: unused variable 'cgroup_id_lsb' [-Wunused-variable] u32 cgroup_id_lsb = context->cgroup_id; ^ ./pkg/ebpf/c/tracee.bpf.c:4610:9: warning: unused variable 'old_state' [-Wunused-variable] int old_state = ctx->args[1]; ^ 5 warnings generated. INFO: starting tracee-ebpf... 
INFO: starting tracee-rules... 
Loaded 15 signature(s): [TRC-1 TRC-13 TRC-2 TRC-14 TRC-3 TRC-11 TRC-9 TRC-4 TRC-5 TRC-12 TRC-6 TRC-10 TRC-7 TRC-16 TRC-15] 
libbpf: Error in bpf_create_map_xattr(sys_enter_init_tail):No error information(-524). Retrying without BTF. 
libbpf: Error in bpf_create_map_xattr(sys_enter_submit_tail):No error information(-524). Retrying without BTF. 
libbpf: Error in bpf_create_map_xattr(sys_enter_tails):No error information(-524). Retrying without BTF. 
libbpf: Error in bpf_create_map_xattr(sys_exit_init_tail):No error information(-524). Retrying without BTF. 
libbpf: Error in bpf_create_map_xattr(sys_exit_submit_tail):No error information(-524). Retrying without BTF. 
libbpf: Error in bpf_create_map_xattr(sys_exit_tails):No error information(-524). Retrying without BTF. 
libbpf: Error in bpf_create_map_xattr(prog_array_tp):No error information(-524). Retrying without BTF. 
libbpf: Error in bpf_create_map_xattr(prog_array):No error information(-524). Retrying without BTF. 
libbpf: prog 'uprobe_syscall_trigger': BPF program load failed: Invalid argument 
libbpf: prog 'uprobe_syscall_trigger': -- BEGIN PROG LOAD LOG -- 0: (bf) r7 = r1 1: (79) r1 = *(u64 *)(r7 +88) 2: (7b) *(u64 *)(r10 -16) = r1 3: (b7) r6 = 0 4: (7b) *(u64 *)(r10 -24) = r6 5: (7b) *(u64 *)(r10 -32) = r6 6: (7b) *(u64 *)(r10 -40) = r6 7: (7b) *(u64 *)(r10 -48) = r6 8: (7b) *(u64 *)(r10 -56) = r6 9: (7b) *(u64 *)(r10 -64) = r6 10: (7b) *(u64 *)(r10 -72) = r6 11: (7b) *(u64 *)(r10 -80) = r6 12: (7b) *(u64 *)(r10 -88) = r6 13: (7b) *(u64 *)(r10 -96) = r6 14: (7b) *(u64 *)(r10 -104) = r6 15: (7b) *(u64 *)(r10 -112) = r6 16: (7b) *(u64 *)(r10 -120) = r6 17: (7b) *(u64 *)(r10 -128) = r6 18: (7b) *(u64 *)(r10 -136) = r6 19: (7b) *(u64 *)(r10 -144) = r6 20: (7b) *(u64 *)(r10 -152) = r6 21: (7b) *(u64 *)(r10 -160) = r6 22: (7b) *(u64 *)(r10 -168) = r6 23: (7b) *(u64 *)(r10 -176) = r6 24: (7b) *(u64 *)(r10 -184) = r6 25: (63) *(u32 *)(r10 -360) = r6 26: (bf) r2 = r10 27: (07) r2 += -360 28: (18) r1 = 0xffff9f2a3536c000 30: (85) call bpf_map_lookup_elem#1 31: (7b) *(u64 *)(r10 -40) = r0 32: (55) if r0 != 0x0 goto pc+1 R0=inv0 R6=inv0 R7=ctx(id=0,off=0,imm=0) R10=fp0,call_-1 fp-24=0 fp-32=0 fp-40=inv fp-48=0 fp-56=0 fp-64=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-104=0 fp-112=0 fp-120=0 fp-128=0 fp-136=0 fp-144=0 fp-152=0 fp-160=0 fp-168=0 fp-176=0 fp-184=0 33: (05) goto pc+418 452: (bf) r0 = r6 453: (95) exit from 32 to 34: R0=map_value(id=0,off=0,ks=4,vs=208,imm=0) R6=inv0 R7=ctx(id=0,off=0,imm=0) R10=fp0,call_-1 fp-24=0 fp-32=0 fp-40=map_value fp-48=0 fp-56=0 fp-64=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-104=0 fp-112=0 fp-120=0 fp-128=0 fp-136=0 fp-144=0 fp-152=0 fp-160=0 fp-168=0 fp-176=0 fp-184=0 34: (7b) *(u64 *)(r10 -368) = r7 35: (85) call bpf_get_current_task#35 36: (bf) r9 = r0 37: (7b) *(u64 *)(r10 -64) = r9 38: (79) r1 = *(u64 *)(r10 -40) 39: (61) r1 = *(u32 *)(r1 +4) R0=inv(id=0) R1_w=map_value(id=0,off=0,ks=4,vs=208,imm=0) R6=inv0 R7=ctx(id=0,off=0,imm=0) R9_w=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=0 fp-40=map_value fp-48=0 fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-104=0 fp-112=0 fp-120=0 fp-128=0 fp-136=0 fp-144=0 fp-152=0 fp-160=0 fp-168=0 fp-176=0 fp-184=0 fp-368=ctx 40: (7b) *(u64 *)(r10 -376) = r1 41: (85) call bpf_get_current_pid_tgid#14 42: (bf) r8 = r0 43: (7b) *(u64 *)(r10 -352) = r6 44: (bf) r3 = r9 45: (07) r3 += 1520 46: (bf) r1 = r10 47: (07) r1 += -352 48: (b7) r2 = 8 49: (85) call bpf_probe_read#4 50: (63) *(u32 *)(r10 -144) = r8 51: (77) r8 >>= 32 52: (63) *(u32 *)(r10 -148) = r8 53: (79) r1 = *(u64 *)(r10 -352) 54: (7b) *(u64 *)(r10 -176) = r1 55: (7b) *(u64 *)(r10 -352) = r6 56: (bf) r8 = r9 57: (07) r8 += 1240 58: (bf) r1 = r10 59: (07) r1 += -352 60: (b7) r2 = 8 61: (bf) r3 = r8 62: (85) call bpf_probe_read#4 63: (79) r3 = *(u64 *)(r10 -352) 64: (63) *(u32 *)(r10 -352) = r6 65: (07) r3 += 1228 66: (bf) r1 = r10 67: (07) r1 += -352 68: (b7) r2 = 4 69: (85) call bpf_probe_read#4 70: (61) r1 = *(u32 *)(r10 -352) 71: (63) *(u32 *)(r10 -140) = r1 72: (7b) *(u64 *)(r10 -352) = r6 73: (bf) r3 = r9 74: (07) r3 += 1328 75: (7b) *(u64 *)(r10 -384) = r3 76: (bf) r1 = r10 77: (07) r1 += -352 78: (b7) r2 = 8 79: (85) call bpf_probe_read#4 80: (79) r7 = *(u64 *)(r10 -352) 81: (63) *(u32 *)(r10 -352) = r6 82: (bf) r1 = r10 83: (07) r1 += -352 84: (bf) r3 = r7 85: (07) r3 += 4 86: (b7) r2 = 4 87: (85) call bpf_probe_read#4 88: (61) r1 = *(u32 *)(r10 -352) 89: (67) r1 <<= 4 90: (0f) r7 += r1 91: (63) *(u32 *)(r10 -352) = r6 92: (07) r7 += 56 93: (bf) r1 = r10 94: (07) r1 += -352 95: (b7) r2 = 4 96: (bf) r3 = r7 97: (85) call bpf_probe_read#4 98: (61) r1 = *(u32 *)(r10 -352) 99: (63) *(u32 *)(r10 -156) = r1 100: (7b) *(u64 *)(r10 -352) = r6 101: (bf) r3 = r9 102: (07) r3 += 1288 103: (bf) r1 = r10 104: (07) r1 += -352 105: (b7) r2 = 8 106: (85) call bpf_probe_read#4 107: (79) r3 = *(u64 *)(r10 -352) 108: (7b) *(u64 *)(r10 -352) = r6 109: (07) r3 += 1328 110: (bf) r1 = r10 111: (07) r1 += -352 112: (b7) r2 = 8 113: (85) call bpf_probe_read#4 114: (79) r7 = *(u64 *)(r10 -352) 115: (63) *(u32 *)(r10 -352) = r6 116: (bf) r1 = r10 117: (07) r1 += -352 118: (bf) r3 = r7 119: (07) r3 += 4 120: (b7) r2 = 4 121: (85) call bpf_probe_read#4 122: (61) r1 = *(u32 *)(r10 -352) 123: (67) r1 <<= 4 124: (0f) r7 += r1 125: (63) *(u32 *)(r10 -352) = r6 126: (07) r7 += 56 127: (bf) r1 = r10 128: (07) r1 += -352 129: (b7) r2 = 4 130: (bf) r3 = r7 131: (85) call bpf_probe_read#4 132: (61) r1 = *(u32 *)(r10 -352) 133: (63) *(u32 *)(r10 -160) = r1 134: (7b) *(u64 *)(r10 -352) = r6 135: (bf) r1 = r10 136: (07) r1 += -352 137: (b7) r2 = 8 138: (bf) r3 = r8 139: (85) call bpf_probe_read#4 140: (79) r3 = *(u64 *)(r10 -352) 141: (7b) *(u64 *)(r10 -352) = r6 142: (07) r3 += 1328 143: (bf) r1 = r10 144: (07) r1 += -352 145: (b7) r2 = 8 146: (85) call bpf_probe_read#4 147: (79) r7 = *(u64 *)(r10 -352) 148: (63) *(u32 *)(r10 -352) = r6 149: (bf) r1 = r10 150: (07) r1 += -352 151: (bf) r3 = r7 152: (07) r3 += 4 153: (b7) r2 = 4 154: (85) call bpf_probe_read#4 155: (61) r1 = *(u32 *)(r10 -352) 156: (67) r1 <<= 4 157: (0f) r7 += r1 158: (63) *(u32 *)(r10 -352) = r6 159: (07) r7 += 56 160: (bf) r1 = r10 161: (07) r1 += -352 162: (b7) r2 = 4 163: (bf) r3 = r7 164: (85) call bpf_probe_read#4 165: (61) r1 = *(u32 *)(r10 -352) 166: (63) *(u32 *)(r10 -152) = r1 167: (7b) *(u64 *)(r10 -352) = r6 168: (7b) *(u64 *)(r10 -392) = r9 169: (07) r9 += 1728 170: (bf) r1 = r10 171: (07) r1 += -352 172: (b7) r2 = 8 173: (bf) r3 = r9 174: (85) call bpf_probe_read#4 175: (79) r3 = *(u64 *)(r10 -352) 176: (7b) *(u64 *)(r10 -352) = r6 177: (07) r3 += 24 178: (bf) r1 = r10 179: (07) r1 += -352 180: (b7) r2 = 8 181: (85) call bpf_probe_read#4 182: (79) r3 = *(u64 *)(r10 -352) 183: (63) *(u32 *)(r10 -352) = r6 184: (07) r3 += 24 185: (bf) r1 = r10 186: (07) r1 += -352 187: (b7) r2 = 4 188: (85) call bpf_probe_read#4 189: (61) r1 = *(u32 *)(r10 -352) 190: (63) *(u32 *)(r10 -132) = r1 191: (7b) *(u64 *)(r10 -352) = r6 192: (bf) r1 = r10 193: (07) r1 += -352 194: (b7) r2 = 8 195: (79) r3 = *(u64 *)(r10 -384) 196: (85) call bpf_probe_read#4 197: (79) r7 = *(u64 *)(r10 -352) 198: (63) *(u32 *)(r10 -352) = r6 199: (bf) r1 = r10 200: (07) r1 += -352 201: (bf) r3 = r7 202: (07) r3 += 4 203: (b7) r2 = 4 204: (85) call bpf_probe_read#4 205: (61) r1 = *(u32 *)(r10 -352) 206: (67) r1 <<= 4 207: (0f) r7 += r1 208: (7b) *(u64 *)(r10 -352) = r6 209: (07) r7 += 64 210: (bf) r1 = r10 211: (07) r1 += -352 212: (b7) r2 = 8 213: (bf) r3 = r7 214: (85) call bpf_probe_read#4 215: (79) r3 = *(u64 *)(r10 -352) 216: (63) *(u32 *)(r10 -352) = r6 217: (07) r3 += 200 218: (bf) r1 = r10 219: (07) r1 += -352 220: (b7) r2 = 4 221: (85) call bpf_probe_read#4 222: (61) r1 = *(u32 *)(r10 -352) 223: (63) *(u32 *)(r10 -128) = r1 224: (85) call bpf_get_current_uid_gid#15 225: (63) *(u32 *)(r10 -136) = r0 226: (63) *(u32 *)(r10 -92) = r6 227: (bf) r1 = r10 228: (07) r1 += -124 229: (b7) r2 = 16 230: (85) call bpf_get_current_comm#16 231: (7b) *(u64 *)(r10 -352) = r6 232: (bf) r1 = r10 233: (07) r1 += -352 234: (b7) r2 = 8 235: (bf) r3 = r9 236: (85) call bpf_probe_read#4 237: (79) r3 = *(u64 *)(r10 -352) 238: (7b) *(u64 *)(r10 -352) = r6 239: (07) r3 += 8 240: (bf) r1 = r10 241: (07) r1 += -352 242: (b7) r2 = 8 243: (85) call bpf_probe_read#4 244: (79) r3 = *(u64 *)(r10 -352) 245: (73) *(u8 *)(r10 -288) = r6 246: (7b) *(u64 *)(r10 -296) = r6 247: (7b) *(u64 *)(r10 -304) = r6 248: (7b) *(u64 *)(r10 -312) = r6 249: (7b) *(u64 *)(r10 -320) = r6 250: (7b) *(u64 *)(r10 -328) = r6 251: (7b) *(u64 *)(r10 -336) = r6 252: (7b) *(u64 *)(r10 -344) = r6 253: (7b) *(u64 *)(r10 -352) = r6 254: (07) r3 += 69 255: (bf) r6 = r10 256: (07) r6 += -352 257: (bf) r1 = r6 258: (b7) r2 = 65 259: (85) call bpf_probe_read#4 260: (bf) r1 = r10 261: (07) r1 += -108 262: (b7) r2 = 16 263: (bf) r3 = r6 264: (85) call bpf_probe_read_str#45 265: (79) r1 = *(u64 *)(r10 -376) 266: (57) r1 &= 64 267: (15) if r1 == 0x0 goto pc+37 R0=inv(id=0,umax_value=16,var_off=(0x0; 0x1f)) R1=inv(id=0,umax_value=64,var_off=(0x0; 0x40)) R6=fp-352,call_-1 R7=inv(id=0) R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=0 fp-40=map_value fp-48=0 fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-168=0 fp-184=0 fp-368=ctx 268: (b7) r6 = 0 269: (7b) *(u64 *)(r10 -352) = r6 270: (79) r3 = *(u64 *)(r10 -392) 271: (07) r3 += 2096 272: (bf) r1 = r10 273: (07) r1 += -352 274: (b7) r2 = 8 275: (85) call bpf_probe_read#4 276: (79) r3 = *(u64 *)(r10 -352) 277: (7b) *(u64 *)(r10 -352) = r6 278: (bf) r1 = r10 279: (07) r1 += -352 280: (b7) r2 = 8 281: (85) call bpf_probe_read#4 282: (79) r3 = *(u64 *)(r10 -352) 283: (7b) *(u64 *)(r10 -352) = r6 284: (bf) r1 = r10 285: (07) r1 += -352 286: (b7) r2 = 8 287: (85) call bpf_probe_read#4 288: (79) r3 = *(u64 *)(r10 -352) 289: (7b) *(u64 *)(r10 -352) = r6 290: (07) r3 += 288 291: (bf) r1 = r10 292: (07) r1 += -352 293: (b7) r2 = 8 294: (85) call bpf_probe_read#4 295: (79) r3 = *(u64 *)(r10 -352) 296: (79) r7 = *(u64 *)(r10 -368) 297: (15) if r3 == 0x0 goto pc+10 R0=inv(id=0) R3=inv(id=0) R6=inv0 R7=ctx(id=0,off=0,imm=0) R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=0 fp-40=map_value fp-48=0 fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-168=0 fp-184=0 fp-368=ctx 298: (07) r3 += 104 299: (bf) r1 = r10 300: (07) r1 += -352 301: (b7) r2 = 8 302: (85) call bpf_probe_read#4 303: (79) r6 = *(u64 *)(r10 -352) 304: (05) goto pc+3 308: (7b) *(u64 *)(r10 -168) = r6 309: (85) call bpf_ktime_get_ns#5 310: (7b) *(u64 *)(r10 -184) = r0 311: (b7) r6 = 0 312: (73) *(u8 *)(r10 -66) = r6 313: (63) *(u32 *)(r10 -72) = r6 314: (85) call bpf_get_smp_processor_id#8 315: (b7) r1 = 120 316: (63) *(u32 *)(r10 -24) = r1 317: (7b) *(u64 *)(r10 -48) = r7 318: (6b) *(u16 *)(r10 -68) = r0 319: (63) *(u32 *)(r10 -4) = r6 320: (bf) r2 = r10 321: (07) r2 += -4 322: (18) r1 = 0xffff9f2a2f0c8800 324: (85) call bpf_map_lookup_elem#1 325: (7b) *(u64 *)(r10 -32) = r0 326: (15) if r0 == 0x0 goto pc+125 R0=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R6=inv0 R7=ctx(id=0,off=0,imm=0) R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 327: (61) r1 = *(u32 *)(r10 -144) 328: (63) *(u32 *)(r10 -352) = r1 329: (bf) r2 = r10 330: (07) r2 += -352 331: (18) r1 = 0xffff9f2a0bd2bc00 333: (85) call bpf_map_lookup_elem#1 334: (55) if r0 != 0x0 goto pc+22 R0=inv0 R6=inv0 R7=ctx(id=0,off=0,imm=0) R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 335: (b7) r1 = 0 336: (63) *(u32 *)(r10 -200) = r1 337: (bf) r2 = r10 338: (07) r2 += -200 339: (18) r1 = 0xffff9f2a2f0c8800 341: (85) call bpf_map_lookup_elem#1 342: (15) if r0 == 0x0 goto pc+13 R0=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R6=inv0 R7=ctx(id=0,off=0,imm=0) R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 343: (bf) r7 = r10 344: (07) r7 += -352 345: (18) r1 = 0xffff9f2a0bd2bc00 347: (bf) r2 = r7 348: (bf) r3 = r0 349: (b7) r4 = 1 350: (85) call bpf_map_update_elem#2 R0=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R1_w=map_ptr(id=0,off=0,ks=4,vs=176) R2_w=fp-352,call_-1 R3_w=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R4_w=inv1 R6=inv0 R7_w=fp-352,call_-1 R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 351: (18) r1 = 0xffff9f2a0bd2bc00 353: (bf) r2 = r7 354: (85) call bpf_map_lookup_elem#1 355: (55) if r0 != 0x0 goto pc+610 R0=inv0 R6=inv0 R7=fp-352,call_-1 R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 356: (05) goto pc+95 452: safe from 355 to 966: R0=map_value(id=0,off=0,ks=4,vs=176,imm=0) R6=inv0 R7=fp-352,call_-1 R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 966: (b7) r1 = 256 967: (63) *(u32 *)(r0 +160) = r1 R0=map_value(id=0,off=0,ks=4,vs=176,imm=0) R1_w=inv256 R6=inv0 R7=fp-352,call_-1 R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 968: (b7) r1 = 0 969: (73) *(u8 *)(r0 +168) = r1 R0=map_value(id=0,off=0,ks=4,vs=176,imm=0) R1_w=inv0 R6=inv0 R7=fp-352,call_-1 R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=0 fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 970: (7b) *(u64 *)(r10 -56) = r0 971: (bf) r6 = r10 972: (07) r6 += -56 973: (79) r1 = *(u64 *)(r10 -168) 974: (63) *(u32 *)(r10 -352) = r1 975: (bf) r2 = r10 976: (07) r2 += -352 977: (18) r1 = 0xffff9f29fb0fb800 979: (85) call bpf_map_lookup_elem#1 980: (bf) r1 = r0 981: (55) if r1 != 0x0 goto pc+2 R0=inv0 R1=inv0 R6=fp-56,call_-1 R7=fp-352,call_-1 R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=map_value fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 982: (79) r0 = *(u64 *)(r6 +0) 983: (05) goto pc-566 418: (bf) r3 = r10 419: (07) r3 += -176 420: (bf) r1 = r0 421: (b7) r2 = 88 422: (85) call bpf_probe_read#4 R0_w=map_value(id=0,off=0,ks=4,vs=176,imm=0) R1_w=map_value(id=0,off=0,ks=4,vs=176,imm=0) R2_w=inv88 R3_w=fp-176,call_-1 R6=fp-56,call_-1 R7=fp-352,call_-1 R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=map_value fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 423: (b7) r6 = 0 424: (63) *(u32 *)(r10 -188) = r6 425: (bf) r2 = r10 426: (07) r2 += -188 427: (18) r1 = 0xffff9f29fb0f8000 429: (85) call bpf_map_lookup_elem#1 430: (15) if r0 == 0x0 goto pc+21 R0=map_value(id=0,off=0,ks=4,vs=8,imm=0) R6=inv0 R7=fp-352,call_-1 R8=inv(id=0) R9=inv(id=0) R10=fp0,call_-1 fp-24=0 fp-32=map_value fp-40=map_value fp-48=ctx fp-56=map_value fp-72=0 fp-80=0 fp-88=0 fp-96=0 fp-368=ctx 431: (b7) r6 = 0 432: (7b) *(u64 *)(r10 -296) = r6 433: (7b) *(u64 *)(r10 -304) = r6 434: (7b) *(u64 *)(r10 -312) = r6 435: (7b) *(u64 *)(r10 -320) = r6 436: (7b) *(u64 *)(r10 -328) = r6 437: (7b) *(u64 *)(r10 -336) = r6 438: (7b) *(u64 *)(r10 -344) = r6 439: (7b) *(u64 *)(r10 -352) = r6 440: (bf) r7 = r10 441: (07) r7 += -352 442: (bf) r1 = r7 443: (b7) r2 = 64 444: <invalid BPF map reference>BPF map '.rodata.str1.1' is referenced but wasn't created -- END PROG LOAD LOG -- 
libbpf: failed to load program 'uprobe_syscall_trigger' libbpf: failed to load object '/tmp/tracee/tracee.bpf.4_19_0-21-amd64.v0_8_3.o' 2022/10/20 11:05:28 error initializing Tracee: failed to load BPF object`

## Context

I think this kernel version is supported through BTFHUB but doesn't seem to be working. 

Relevant information about my setup:

* Linux version: Debian GNU/Linux (Buster)
* Linux kernel version: 4.19.0-21-amd64 
* Tracee version (or commit id of your tree): latest docker full version image. 
* LLVM version:  7.0.1
* Golang version: 1.17
* Arch: x86_64

**Comment by rafaeldtinoco** [comment]
Well, kernel Linux kernel version: 4.19.0-21-amd64 isn't supported. We do support 4.18 RHEL8 and >= 5.2 kernels (that is what we currently test and prepare for). I think we can close this because of that.
