### ISSUE TITLE
[FEAT] Stop creating a documentation version for every patch version

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#2273]
stop creating a documentation version for every patch version
keep triggering the workflow, and regenerating docs on every push including patch versions, BUT when pushing to mkdocs omit the patch version, meaning minor version will be overridden.

Based on https://github.com/aquasecurity/trivy/pull/2824

**Comment by rafaeldtinoco** [comment]
Closed by https://github.com/aquasecurity/tracee/pull/2274
