### ISSUE TITLE
Move event filtering for events requiring processing

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#2286]
## Prerequisites

Select one OR another:

- [ ] I have discussed the refactoring idea with one (or another) maintainer.
- [x] I'll create a PR to implement this refactoring idea (assign to yourself).
- [ ] Someone else should implement this (describe it well).

## Refactoring description

Since filtering is done as early as possible, userland filtered events (those that match the ebpf filtering context), may skip being processed despite being relevant for populating tracee's caches (for example the "sched_process" event family).
As such we need to extract the events which require processing (currently in a switch case in `event_processor.go`) and according to the registered events, skip their filtering in `decodeEvents` and do it later after processing is done.

Alternatively, if not all events which can be processed require it, we can  add a field to the event definition marking it as `RequiresProcessing`.

**Comment by yanivagman** [comment]
@NDStrahilevitz I think this will be solved by #3086 so it can be closed, right?

**Comment by NDStrahilevitz** [comment]
I think so as "control plane" events are the target of both PRs in scope.

**Comment by yanivagman** [comment]
Closing in favor of #3086
