### ISSUE TITLE
Add ignore list

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#2291]
Running tracee on GKE, or DO kubernetes and there are some signatures getting triggered in a loop. 

GKE:

```
*** Detection ***
Time: 2022-10-23T23:17:44Z
Signature ID: TRC-1020
Signature: File operations hooking on proc filesystem detected
Data: map[Hooked proc file operations:[{struct file_operations pointer hidden} {iterate hidden}]]
Command: kubelet
Hostname: gke-cluster-1-d

```

DO: 
```
*** Detection ***
Time: 2022-10-23T23:26:02Z
Signature ID: TRC-108
Signature: K8s service account token file read
Data: map[]
Command: cilium-operator
Hostname: pool-xoticiv9p-

*** Detection ***
Time: 2022-10-23T23:26:04Z
Signature ID: TRC-108
Signature: K8s service account token file read
Data: map[]
Command: arp-flusher
Hostname: pool-xoticiv9p-
``` 

Tracee should support a way to ignore those specific events.

**Comment by josedonizetti** [comment]
@yanivagman would it make sense to think of a solution for this soonish, or this would be built on top o multi-scope, a scope to negate a set of events that are allowed?

**Comment by yanivagman** [comment]
The first detection "File operations hooking on proc filesystem detected" is very intersting - it means that procfs operations are not performed from kernel text, but probably from a kernel module. The question is if GKE indeed adds such operations override by default...

The second detection "K8s service account token file read" was actually disabled when it was a rego signature. Why did we enable it again @rafaeldtinoco? (@roikol says that in his PR it was also disabled)

**Comment by yanivagman** [comment]
@josedonizetti I think the first issue was a bug already fixed in main.
The second is (should be?) disabled.

**Comment by josedonizetti** [comment]
@yanivagman just looked into it, both issues fixed, closing!

**Comment by itaysk** [comment]
Since we didn't actually add ignore list feature and the issue is closed as completed, I updated the title to avoid future confusion
