### ISSUE TITLE
[BUG]  deadlock in event sorter

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#2314]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

Deadlock in event sorting feature:
```
[16:59] Nadav Strahilevitz
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 2289722 lock 0xc005dda1f8
pkg/events/sorting/sorting.go:191 sorting.(*EventsChronologicalSorter).sendEvents { sorter.outputChanMutex.Lock() } <<<<<
pkg/events/sorting/sorting.go:190 sorting.(*EventsChronologicalSorter).sendEvents { func (sorter *EventsChronologicalSorter) sendEvents(outputChan chan<- *trace.Event, extractionMaxTimestamp int) { }

Have been trying to lock it again for more than 30s
goroutine 2299710 lock 0xc005dda1f8
pkg/events/sorting/sorting.go:191 sorting.(*EventsChronologicalSorter).sendEvents { sorter.outputChanMutex.Lock() } <<<<<
pkg/events/sorting/sorting.go:190 sorting.(*EventsChronologicalSorter).sendEvents { func (sorter *EventsChronologicalSorter) sendEvents(outputChan chan<- *trace.Event, extractionMaxTimestamp int) { }

Here is what goroutine 2289722 doing now
goroutine 2289722 [chan send]:
github.com/aquasecurity/tracee/pkg/events/sorting.(*EventsChronologicalSorter).sendEvents(0xc005dda1e0, 0x0?, 0x1721f1b347c87135)    /home/ubuntu/tracee/pkg/events/sorting/sorting.go:206 +0x17e
created by github.com/aquasecurity/tracee/pkg/events/sorting.(*EventsChronologicalSorter).Start    /home/ubuntu/tracee/pkg/events/sorting/sorting.go:169 +0x2a5

```

## Steps to reproduce

Run `tracee-ebpf -o option:sort-events`
otherwise intermittent.

## Context

Relevant information about my setup:

* Linux version:
* Linux kernel version:
* Tracee version (or commit id of your tree):
* LLVM version:
* Golang version:

**Comment by AlonZivony** [comment]
Need to look into it, but what is written here is not a real indication of a deadlock.
All it says is that this function uses lock, and it took long for it to finish. It might be possible with a huge load, which we know other parts of Tracee also have issue dealing with (but don't use locks so it doesn't count by this test as a "deadlock"). It just seems not very logical that we had a deadlock here, because we use this feature for a year now and it hasn't been changed. So we should have seen problems here already.
Anyways I will need more information on what you have run to get this result to examine it more deeply.

**Comment by NDStrahilevitz** [comment]
Lock happens due to a high load, or lags later in the pipeline, that's accurate, so any high load generation can cause this (I reproduced it with the cndr signature e2e tests).
One way to solve it would be to send the events out in a goroutine but that may just cause an overflow of many goroutines. This issue likely will also exist in container enrichment as well when enabled @rafaeldtinoco.

**Comment by AlonZivony** [comment]
Just saw that the line that the first thread is on is the channel send line, which means this is defiantly not a deadlock or even a problem with the sorting feature (but a problem with the speed Tracee read from the channel).
Unless you think that the fact that many threads might end up stacking in waiting for the lock of the `SendEvents` function, I think this matter is closed.
