### ISSUE TITLE
[BUG] Integration test script doesn't have access to parent proc environment variables

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#2331]
## Prerequisites

- [ ] This affects latest released version.
- [ ] This affects current development tree (origin/HEAD).
- [ ] There isn't an issue describing the bug.

Select one OR another:

- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

When running integration tests, the tester.sh script doesn't honor the parent proc's environment variables. This can be solved simply by using `os.Environ` in the Env field of syscall.ProcAttr [here](https://github.com/aquasecurity/tracee/blob/main/tests/integration/integration_test.go#L284).

**Comment by yanivagman** [comment]
Closed by #2366
