### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#234]
Tracee currently doesn't work on ARM architecture. If you are interested in this, please add the 👍 reaction to this issue, and optionally add a comment to describe your use case.

From: https://github.com/aquasecurity/tracee/discussions/231#discussioncomment-89249
> The reason why Tracee will not work on arm devices is that the event ids numbers match the x86_64 syscalls numbers.
I recently added a table that maps x86_64 syscalls to x86_32 syscalls to support 32bit applications running in compat mode.
We can do something similar for arm, but some other changes are also required, like reading the arguments to different registers in pt_regs struct in the bpf code.

**Comment by sswarnas1** [comment]
Trying to sandbox applications like netflix, youtube in crun based containers. To harden the container configuration, currently using strace, Looking in to the tracee features, interested to try out and get the exact container config to use it for hardening on ARM based device.

**Comment by pathtofile** [comment]
My main focus in Tracee is to help in dynamic reverse engineering of malware.

Tracee working on AMR64, plus the efforts to seperate it from bcc and make it CO-RE, would make it possible to get Tracee working on physical Android devices, which could help observe malware that employs anti-virtual and anti-observanility techniques.
