### ISSUE TITLE
[BUG] container_remove is not emitted when --containers flag is on

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#2347]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

This is how I'm executing tracee (cmdline):
`sudo dist/tracee-ebpf -t e=container_create,container_remove --containers`
This is the error I'm getting:
```
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
20:01:40:349740  0      runc             114595  114619  0                container_create     runtime: docker, container_id: ae562587e5af89de324b70d8573428fc45309dd22f906326f2a9fc515d29f0d7, ctime: 1668016900346134477, container_image: ubuntu:latest, container_name: keen_hugle, pod_name: , pod_namespace: , pod_uid: 
```

without `--containers`:
```
sudo dist/tracee-ebpf -t e=container_create,container_remove
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
19:47:01:905111  0      runc             114008  114014  0                container_create     runtime: docker, container_id: 3ec938f5554b9093ac0152fc34969230e2c34def9f42d62afe9e4eb0164b9643, ctime: 1668016021900326202, container_image: , container_name: , pod_name: , pod_namespace: , pod_uid: 
19:47:05:395458  0      runc             114069  114069  0                container_remove     runtime: docker, container_id: 3ec938f5554b9093ac0152fc34969230e2c34def9f42d62afe9e4eb0164b9643, ctime: 1668016021900326202, container_image: , container_name: , pod_name: , pod_namespace: , pod_uid: 
```

## Context

Relevant information about my setup:

* Linux version: ubuntu focal
* Linux kernel version: 5.15.0
* Tracee version (or commit id of your tree):main
* LLVM version:12
* Golang version:17

**Comment by NDStrahilevitz** [comment]
Cgroup_rmdir was triggering cleanup logic in that pipeline stage but I forgot to add an `out <- event` at the end there, oops.
Uploading a fix now.
