### ISSUE TITLE
Update rules examples

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#2353]
We currently give gdb (which uses ptrace) as an example to trigger the Anti Debugging rule. This example doesn't represent the real use of Tracee to detect attacks and we should replace it with a real attack scenario. A good example can be the detection of fileless execution.

**Comment by josedonizetti** [comment]
This was implemented on the PR https://github.com/aquasecurity/tracee/pull/2797

-> https://aquasecurity.github.io/tracee/v0.16/getting-started/kubernetes-quickstart/#exercising-a-security-event
