### ISSUE TITLE
Header file for C functions declarations

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#2359]
## Prerequisites

- [ ] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [ ] I'll create a PR to implement this feature (assign to yourself).
- [x] Someone else should implement this (describe it well).

## Feature description

Currently each developer in tracee who touch the `tracee.bpf.c` file needs to deal with order issues when creating helper functions or internal functions.
We should divide the file to many subfiles, but it is very difficult and will take a long time to really happen.
For now, we should at least create a new header file for functions declarations and include it in the main file, to make the ordering inside the C file irrelevant.

**Comment by NDStrahilevitz** [comment]
I've proposed a refactor solution in #2545.

**Comment by rafaeldtinoco** [comment]
Opened a discussion there if we should do it now (the pros seem bigger than the cons, lets see).

**Comment by AlonZivony** [comment]
I reopen it as the problem is still there, now just a bit less severe.

# The Issue
We only have header files currently, without C file.
This means all the code is in header files, so the order of functions is still mandatory for them to know each other.
The current file system is not maintainable, as the ordering is hard when files are divided by logic and not necessary by their order in which the functions use each other.

# Proposed Solution
We still need declaration for all the functions.
As the creation of C files is hard to do with the eBPF code, we can do the following thing:
* For each file we have currently, we will have 2 files
* One file will include all current functions, and will function as a "C" file (even though it will be imported, not linked)
* Another file will function as the real header file, including all functions declarations.
* Each "C" file will import at first its header file, and then all its dependencies of "C" files.
* This way, all header files will be imported first as they are the first include of each "C" file, and all needed functions will have their declarations before the using function is implemented.

**Comment by rafaeldtinoco** [comment]
This is going to be solved by something I discussed with Yaniv recently (having multiple eBPF objects and the capability to load them as dependency to selected events). 

Your solution "could be" an intermediary step to it, but I'm not sure its worth having "2 steps" for the change. Also, I'm dropping non CORE code as we speak, things will be simplified a lot.

Note that having multiple objects, instead of multiple header files, will also help in compilation time (as currently we either cache the entire object or nothing).

**Comment by AlonZivony** [comment]
Agree, if this change will be in the next version we don't have to make any change.
However, I will say that my proposition is very simple to implement, so it might still worth considering for the time being until the multiple object files feature is implemented (in case it is delayed for long, etc.).

**Comment by rafaeldtinoco** [comment]
> so it might still worth considering for the time being until the multiple object files feature is implemented (in case it is delayed for long, etc.).

Alright, will try to address in the same (or close) PR as the one dropping non CORE code.

**Comment by yanivagman** [comment]
> I didn't really understand your statement here. You include an header file which implements all the functions in it, instead of just declarations. The implementation may use functions from other files. However, what if 2 files are dependent on each other? Might not even be directly - file A can use B, B use C, and C use A. Normally, its not such a big issue as the declarations are added in the header files, and the functions are filled only upon linking. However, here it is not possible. Even in the files, a function can't use a function that comes after it in the file. So the file has to be ordered by usage. I think the best order of files in every language is order by relevance - exported and high level functions above local and small ones.
>
> All mentioned problems are passable, but they make the programing a lot clumsier. I think we should have a file system structure matching the normal conventions of C language, to enable more efficient coding.

There is no such case in Tracee that 2 header files are dependent on each other. This is why I asked you to give an example for that. Each header file declares and implements the relevant functions, and all its dependencies should be included in it. Unlike "regular C programming", eBPF programming is different since we have many BPF programs and not just one program, each in its own section. So it is easier to have the header files contain the implementation of the relevant functions, and then simply include it in the relevant C file (today its just one, but in the future we will seperate the different programs to their own C files).

**Comment by AlonZivony** [comment]
> There is no such case in Tracee that 2 header files are dependent on each other. This is why I asked you to give an example for that. Each header file declares and implements the relevant functions, and all its dependencies should be included in it. Unlike "regular C programming", eBPF programming is different since we have many BPF programs and not just one program, each in its own section. So it is easier to have the header files contain the implementation of the relevant functions, and then simply include it in the relevant C file (today its just one, but in the future we will seperate the different programs to their own C files).

You can take for example the `filesystem.h` file, which include the following:
```c
#include "common/buffer.h"
#include "common/common.h"
#include "consts.h"
#include "memory.h"
#include "maps.h"
```
Almost all header files include other header files.
It is very hard to maintain it this way.
And again, you have to maintain in-file order.

**Comment by yanivagman** [comment]
> You can take for example the `filesystem.h` file, which include the following:
> 
> ```c
> #include "common/buffer.h"
> #include "common/common.h"
> #include "consts.h"
> #include "memory.h"
> #include "maps.h"
> ```
> 
> Almost all header files include other header files. It is very hard to maintain it this way. And again, you have to maintain in-file order.

If every header includes its dependencies, you don't need to keep the order, and no issues arise.

**Comment by AlonZivony** [comment]
> If every header includes its dependencies, you don't need to keep the order, and no issues arise.

Between the files there is no order issue unless there is a circular dependency.
Circular dependency is OK with normal C files and headers, but we can't do it here.

However, my complaint here is that it is hard to maintain the dependencies so there won't be a circular one, because we group files by logic and not by which functions they use.
And again, in each file you do need to keep the order.

**Comment by rafaeldtinoco** [comment]
@AlonZivony I had started doing an initial step: 

https://github.com/aquasecurity/tracee/pull/3015/commits/2e26de37de3b39ac2fe1905aa66c9e4a06f70a3c

Only so I could move into something being discussed at this Issue. Currently the include directory search ordering is broken, some files include "XXX.h" others <XXX.h> and it works "by accident".

With that proposal, I could fix that, divide headers into "kernel" type accessing macros, or related, and "internal to tracee" headers. But I also think we should discuss what you're proposing here.

Should we have function prototypes in specific per file (and how should we split those files), etc.

Also bear in mind that I'll have to have multiple ".c" files for multiple eBPF objects to be generated (And prototypes, constants and macros will have to take that into account).

**Comment by rafaeldtinoco** [comment]
Either way Im removing that commit from that PR for this milestone.

**Comment by rafaeldtinoco** [comment]
Closed by https://github.com/aquasecurity/tracee/pull/3133.
