### ISSUE TITLE
[BUG] Usage of prints instead of logger

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#2368]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

We have now a logger, so there is no reason to really print any message to the user not through it (aside from the events table).
However, it seems that currently we do it.

This is how I'm executing tracee (cmdline):
`sudo ./dist/tracee-ebpf -t e=dirty_pipe_splice --debug`

This is the error I'm getting:
```RuntimeSockets: failed to register default containerd socket:
failed to register runtime socket stat /var/run/containerd/containerd.sock: no such file or directory
RuntimeSockets: failed to register default docker socket:
failed to register runtime socket stat /var/run/docker.sock: no such file or directory
RuntimeSockets: failed to register default crio socket:
failed to register runtime socket stat /var/run/crio/crio.sock: no such file or directory
RuntimeSockets: failed to register default podman socket:
failed to register runtime socket stat /var/run/podman/podman.sock: no such file or directory
BTF: bpfenv = false, btfenv = false, vmlinux = true
BPF: using embedded BPF object
unpacked CO:RE bpf object file into memory```

**Comment by geyslan** [comment]
Moved this to v0.11, working on https://github.com/aquasecurity/tracee/pull/2352 for v0.10.
