### ISSUE TITLE
[BUG] Use debug variable instead of logger

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#2369]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

Today we have a logger which support logging levels.
Because of it, there is no real reason to use the `debug` variable used in multiple places.
It should be expected that running in `debug` mode will just change the logging level to include low logging levels like `debug` and `inform`.

**Comment by geyslan** [comment]
Moved this to v0.11, working on https://github.com/aquasecurity/tracee/pull/2352 for v0.10.
