### ISSUE TITLE
[BUG] tracee-ebpf hangs on start - not creating pid file

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#2377]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

When running tracee-ebpf in tests, sometimes (couldn't figure when) tracee-ebpf hangs and is not creating the pid file (that's how we know that tracee is started)
events are not being outputted and tracee-ebpf is killed after 20 minutes like that.

**Comment by rafaeldtinoco** [comment]
I'm afraid we will need a runtime stack trace for this one (at least) or a dump.

**Comment by AsafEitani** [comment]
I have a reproducer I sent Yaniv, sending it to you as well

**Comment by yanivagman** [comment]
We didn't see this for a while, and it was probably fixed by the capabilities change introduced by @rafaeldtinoco .
Closing it for now. Please reopen if needed.
