### ISSUE TITLE
Change missing arguments in events to default values

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#2389]
Currently, when an event has a missing argument for some reason (error while getting it, configuration, etc.), we pass it without the argument. This cause inconsistency in the event structure, and also make it harder to store the events in DBs.
To fix it, we decided to pass a default value in the argument instead of passing the event without it.
This change will require the following changes:
* https://github.com/aquasecurity/tracee/issues/2261#issuecomment-1369143881
* #2391
* #2392

**Comment by NDStrahilevitz** [comment]
Copying my comment from #2390

> I've had some thoughts about the nil value. If we go with this approach then every argument check (in a helper or directly in 
> signature) will need to include some arg == nil check. This can get rather cumbersome and may not be intuitive.
> It may be more appropriate to go for a strategy like the io.EOF error we have in Read methods, rather than trying to define some alternative value, we should have an explicit method at the struct receiver level that attempts to:
> 
> 1. Query the argument
> 2. Parse it to the correct type (we can use generics for this I believe)
>
> Then we define a constant error that signifies a missing argument which we document near the function so users will know to check for it. This is more explicit and likely to be simpler as users will already check for an error value anyway when extracting an argument from an event.
