### ISSUE TITLE
Tracee should drop capabilities by default and all signatures should work

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2397]
Tracee should be able to drop capabilities and have all its signatures fully working.

> By the time the feature was added, the E2E tests still failed because of some signatures not having proper capabilities in the pipeline event processing phases.

**Comment by rafaeldtinoco** [comment]
We agreed to move this one to the next milestone.

**Comment by rafaeldtinoco** [comment]
I closed https://github.com/aquasecurity/tracee/issues/2637#issue-1560438400 as a duplicate of this one (but it is actually one of the possible errors).

**Comment by NDStrahilevitz** [comment]
Should we drop the bypass in integration tests as well?
