### ISSUE TITLE
Integrating tracee in Yocto build

### ISSUE THREAD

**Issue by mieupro18** [aquasecurity/tracee#241]
Please guide me with the steps to integrate tracee in yocto build

**Comment by itaysk** [comment]
Hi @mieupro18, I am not familiar with Yocto, but we have an existing discussion about it here https://github.com/aquasecurity/tracee/discussions/231, so I'm closing this issue.
If anyone wants to contribute a blog post about how to use tracee with yocto, that can be a good hacktoberfest contribution
