### ISSUE TITLE
Print libbpf and libbpfgo logs to logger

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#2417]
As part of our effort to get all output of Tracee to be through the new logger,
we also need to think about logs received from the `libbpfgo` library we use, which in turn use `libbpf`.
This library prints its output to `stdout` currently, meaning we miss them when reading the log file of the logger.
There should be a callback to handle `libbpf` prints, so we should probably do the following:
1. Use logger in `libbpfgo`
2. Add callback to `libbpf` that pass logs to the logger

**Comment by geyslan** [comment]
@AlonZivony as soon as I get info about the involved logic I'll return to this.

**Comment by geyslan** [comment]
Deferring this to v0.12.0 as, as discussed, it would be better to change pkg/logger to be a standalone project under tracee or to be a project repository.

- https://github.com/aquasecurity/libbpfgo/pull/284#discussion_r1068238401
