### ISSUE TITLE
make install-bpf-nocore in arm64 has an unused variable warning

### ISSUE THREAD

**Issue by shitou12345678** [aquasecurity/tracee#2467]
## Prerequisites
Tracee executing install-bpf-nocore in arm64 has a warning
## Feature description
```
[root@ecs-5017 tracee]# make install-bpf-nocore
./pkg/ebpf/c/tracee.bpf.c:4663:10: warning: unused variable 'addr_len' [-Wunused-variable]
    uint addr_len = (uint) PT_REGS_PARM3(ctx);
         ^
./pkg/ebpf/c/tracee.bpf.c:4743:10: warning: unused variable 'addr_len' [-Wunused-variable]
    uint addr_len = (uint) PT_REGS_PARM3(ctx);
         ^
2 warnings generated.
```
## Context
My current environment, where I would like the feature to work, is:
* Linux kernel version:5.10.0
* Golang version:1.19.4

**Comment by rafaeldtinoco** [comment]
Alright. Thanks for letting us know @shitou12345678. For your awareness only, 5.10 kernels support CO-RE and you don't need bpf-nocore (although it will work). I'm checking the unused variables now.
