### ISSUE TITLE
Logger refactors

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2475]
Some of the implemented functionality of the logger is not required anymore, therefore needs to be removed for clarity:

- [x] logger pkg was implemented to provide a base logger package as default. But it also provides a mechanism to instantiate new loggers. The latter wasn't used and won't be.

- [x] logger pkg was initially implemented to provide setup through env vars. It wasn't used and won't be, specially after the [creation](https://github.com/aquasecurity/tracee/commit/7fe1f4cfaa052e087ee79608112503ff28365a77) of the --output log-file flag which can work in conjunction with the new SetWrite() and SetLevel().

- [x] logger lacks a mechanism to allow external loggers to be injected instead of it. This is relevant for consumers of tracee as a library which have their own loggers.

- [x] Logger must comply with common logging interfaces, `zap` being ideal here (since we already use it as well and it's common in other aqua products).

**Comment by geyslan** [comment]
As we're having a lot of changes with the everything is an event and `tracee-rules` requires the use of env vars to get around this https://github.com/aquasecurity/tracee/issues/2532, I am deferring this to v0.12.0.

**Comment by NDStrahilevitz** [comment]
There are some changes I need to do in the logger which will fit right in so assigned to myself.
