### ISSUE TITLE
pkg/logger has unused env vars mechanism

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2476]
logger pkg was initially implemented to provide setup through env vars. It wasn't used and won't be, specially after the [creation](https://github.com/aquasecurity/tracee/commit/7fe1f4cfaa052e087ee79608112503ff28365a77) of the `--output log-file` flag which can work in conjunction with the new `SetWrite()` and `SetLevel()`, therefore needs to be removed for clarity.

**Comment by yanivagman** [comment]
Will be done as part of #2475
