### ISSUE TITLE
[UX] Break first paragraph in README further down into lists etc.

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#2490]
Link to the section:
https://github.com/aquasecurity/tracee/blob/main/Readme.md

The first paragraph describing Tracee

Problem:
- There is a lot of information in the first two paragraphs

Result:
- People might not read the paragraph or have problems grasping all the information presented 

Suggestion
- Breaking it down into multiple sections and focusing on the advantages 

First Paragraph: Overview of Tracee
Easy to run in your cloud native environment: Bullet points 
Research based: Paragraph on in-Aqua research feeding into Tracee

**Comment by rafaeldtinoco** [comment]
hey @AnaisUrlichs WDYT about keeping an "EPIC"-like issue for all related issues in documentation (this way we won't have 1 bug to each thing to fix) ? then you can make PRs always referring to the same bug (to keep a link between the PR and an issue).

**Comment by AnaisUrlichs** [comment]
Yes that makes more sense
