### ISSUE TITLE
DNS e2e tests are flaky

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#2491]
## Bug description

DNS signature test in the network e2e stage tends to be flaky and fail sometimes when running PR workflows. This might be because DNS responses are delayed.

**Comment by rafaeldtinoco** [comment]
Yes, I believe that querying an external DNS multiple times, each query of a different type, and making sure the 4 responses arrive to each detection might be a little too much (or I need to try more and raise a timeout). Will figure that out for the next milestone, for now RETRY is our friend.
