### ISSUE TITLE
Adding Table of Content to Readme.md

### ISSUE THREAD

**Issue by ng29** [aquasecurity/tracee#251]
Hey @itaysk / @yanivagman 

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

I would like to work on this issue.

**Comment by itaysk** [comment]
https://github.com/aquasecurity/tracee/issues/244
in the future please search for existing issues before opening a new one. dup of #244

**Comment by ng29** [comment]
> thanks for the suggestion but we are not looking to add a TOC to the readme.
> in the future please search for existing issues before opening a new one. dup of #244

Mah bad @itaysk , somehow missed finding same issue..
