### ISSUE TITLE
[BUG] tracee everything is an event feature only works with -t event=

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#2510]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

This is how I'm executing tracee (cmdline):
`sudo dist/tracee --trace e=anti_debugging`

This is the error I'm getting:
`{"level":"fatal","ts":1671472509.7401283,"msg":"app","error":"invalid event to trace: anti_debugging"}`

if I run `sudo dist/tracee --trace event=anti_debugging` it works

**Comment by yanivagman** [comment]
This feature is still experimental.
Shortcuts are planned for the next release.
See here for other known issues: https://github.com/aquasecurity/tracee/issues/2355
For any feedback on this feature, please post in the above thread.
