### ISSUE TITLE
Tests are failing on master

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#252]
`make test` fails on master

**Comment by neha-viswanathan** [comment]
@itaysk It looks like a known issue: https://github.com/iovisor/gobpf/issues/214
```
# github.com/iovisor/gobpf/bcc
../go/pkg/mod/github.com/iovisor/gobpf@v0.0.0-20200529092446-49b58e11a4b5/bcc/module.go:32:10: fatal error: bcc/bcc_common.h: No such file or directory
   32 | #include <bcc/bcc_common.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
github.com/cpuguy83/go-md2man/v2/md2man
github.com/urfave/cli/v2
make: *** [Makefile:15: dist/tracee] Error 2
```
One of their suggestions is to build bcc from the source: https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source

**Comment by sudiptog81** [comment]
@neha-viswanathan upon building `bcc` from source, I struck this error on my [`test`](https://github.com/sudiptog81/tracee/runs/1251932887) workflow: `tracee/tracee_test.go:189:15: assignment mismatch: 2 variables but readArgFromBuff returns 3 values`.

**Comment by itaysk** [comment]
@neha-viswanathan you seem to have an issue with BCC on you machine. This is not what this issue discusses: after you solve the issue you have with bcc, you can run `make test` and see some tests failing. 

Regarding your error: There's a known issue if you use ubuntu and obtain bcc from official repo you will get an older version of bcc which is not compatible with Tracee. One solution is to build from source as you suggest.

**Comment by itaysk** [comment]
@sudiptog81 yes this sounds more like what I was referring to

**Comment by ronaudinho** [comment]
it looks like this change in function signature in https://github.com/aquasecurity/tracee/commit/50a7e1734b2856ebd53c330d53d8fcaaf4d6af73 is the cause, now
https://github.com/aquasecurity/tracee/blob/d0fe845c21b7d6613216ae1f4ea37d88b54bb155/tracee/tracee.go#L1148
but previously it only returns 2 values
https://github.com/aquasecurity/tracee/blob/378263e8ac10fc643dd1c2d2e28c237c17b2dfcb/tracee/tracee.go#L871

looking at the commits history, it seems that there are a lot of changes on this part. I manage to make the test passes in my branch but had to remove a lot of tests, not sure how to work with the current `argTag` and what to do with `argType` that are previously explicitly handled but are not there at the moment.

feel free to to look at draft work at https://github.com/ronaudinho/tracee/pull/1, I've included things I have yet to figure out as comments there.
