### ISSUE TITLE
[BUG] empty strings are not submitted to userspace, resulting in missing args in events

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#2520]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

This is how I'm executing tracee (cmdline): 
`./dist/tracee-ebpf -t e=execve -o option:detect-syscall -o option:exec-env`

These are the events i'm getting:
```
14:05:25:679896  1000   amicontained-li  34097   34099   0                execve               argv: [], envp: []
14:05:25:679890  1000   amicontained-li  34097   34099   -14              execve               
```

This is the error I'm getting:  
in the rules i get `argument pathname not found in event execve`.

The desired result in order to not break the signatures is:
```
14:38:08:953856  1000   amicontained-li  36226   36228   0                execve               pathname: , argv: [], envp: []
14:38:08:953853  1000   amicontained-li  36226   36228   -14              execve               pathname: , argv: [], envp: []
```

## Steps to reproduce

Steps to reproduce the issue:

1. step 1: call execve with no args

## Context

Relevant information about my setup:

* Linux version:
* Linux kernel version:
* Tracee version (or commit id of your tree):
* LLVM version:
* Golang version:

**Comment by yanivagman** [comment]
Dup of #2261
