### ISSUE TITLE
e2e sanity test

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#253]
This issue is for discussing and tracking Tracee's tests posture.
We need to start testing the core functionality of Tracee (at least). This is not an easy task may involve refactoring of the codebase to improve testability (i.e break into modules, DI, etc), think of a way to simulate system events.
Part of this effort should include basic sanity tests across different runtime configurations.
Currently Tracee has minimal tests just for the functions that prints encoded structs in a human readable format.

**Comment by yanivagman** [comment]
As part of the tests, I think we should have a "simple" unit-test program that works as follows:
1. Initialize itself (whatever that will be)
2. Start tracee
3. Generate one event (e.g. call one syscall)
4. Stop tracee
5. Check output matches expectation
6. Check no errors occured.

As we have ~350 events - we need the test to be able to generate each of these events.
After we finish writing this test, we can build on it for generating more complex scenarios (e.g. generating multiple events with different arguments), and test it with different arguments given to tracee CLI (e.g. in container mode, specific process, etc...)

**Comment by yanivagman** [comment]
Another kind of test will be checking for different environments to run tracee.
As small changes to the bpf code of Tracee can make it fail passing the verifier of a given kernel, we need to run a test every time that the bpf code is changed, that will try to run tracee on VMs with different kernel versions installed.
We can then test that no verifier errors occured, meaning tracee successfully initialized itself.

**Comment by itaysk** [comment]
> As we have ~350 events - we need the test to be able to generate each of these events. 

This is the challenge here. A while back I searched for something like this, hoping someone had already done this. Didn't find anything

**Comment by yanivagman** [comment]
For many syscalls, this should be trivial.
There are some syscalls that it will be more challenging to have a VALID call,
but even then, we can supply dummy arguments that the syscall will fail, and yet tracee will trace it and we will be able to validate basic functionality.
This doesn't sound too challenging to me, but a lot of work, as the number of events is big.
We can start from a small set of events, and expand as we go

**Comment by itaysk** [comment]
Do you think we can use this tool? https://github.com/google/syzkaller
I have discovered it a while back but didn't have time to explore yet

**Comment by yanivagman** [comment]
I think that using this tool is like taking a machine gun for a task which requires a small knife.
We need something much simpler.
For each syscall, we need to write one line that calls that specific syscall.
That should be it for a basic test.

**Comment by itaysk** [comment]
I'm redefining this issue to be about e2e sanity tracing test rather than generally "tests". We do still desperately need unit tests throughout the code, but this is no longer a single issue task, it should be an ongoing effort. Also, including unit tests in this issue makes this issue impossible to assign and complete. By "e2e sanity tracing test", I mean something that exercises Tracee, make sure that it builds and loads on the given system, and checks that *something* can be traced. 
In the future we can expand this to cover more (all?) syscalls, or simulating different scenarios what not. but for now, let's make this actionable and focus on a single sanity test.

**Comment by itaysk** [comment]
another related tool https://github.com/falcosecurity/event-generator

**Comment by itaysk** [comment]
We recently discussed having a "demo" image, that will demonstrate some tracee-rules signatures by simulating the appropriate events. I think this can be the same thing.
cc: @roikol

**Comment by itaysk** [comment]
Another good reference https://github.com/linux-test-project/lot

**Comment by itaysk** [comment]
closing in favor of more specific issues:
https://github.com/aquasecurity/tracee/issues/1234
https://github.com/aquasecurity/tracee/issues/1406
https://github.com/aquasecurity/tracee/issues/1191
