### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#254]
It would be nice to add some Automated build, tests, and release. Currently most of the build/test/release logic is in the Makefile, which should be used as the basis for any work that is done on this issue.

**Comment by sudiptog81** [comment]
I apologise for making #247, can I try this one with GitHub actions? We can include jobs for tests and coverage once those are implemented.

**Comment by itaysk** [comment]
Yes, please feel free to work on this. Just exclude the test coverage for now. For the rest you can look at the makefile to see what jobs we need (build/test/release). Thank you

**Comment by itaysk** [comment]
@sudiptog81 apologies for delaying this review. I will be able to attend to this first thing next week.
