### ISSUE TITLE
Move self hosted runners of github actions

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#2542]
Use our new framework of self hosted runners to run github actions

**Comment by rafaeldtinoco** [comment]
We agreed to move this one to the next milestone.

**Comment by rafaeldtinoco** [comment]
![image](https://user-images.githubusercontent.com/7395852/217119920-bb3863d9-cc19-4519-be20-61e04b74f19e.png)

AMIs are ready, will grant access to the DevOps team, and start integrating GitHub actions with our CI soon.

**Comment by rafaeldtinoco** [comment]
Missing the CI webhook only and the workflow file changes.
