### ISSUE TITLE
Trace specific container

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#255]
Add option to trace a specific container. This should be agnostic to container runtime, and probably use Container Runtime Interface. User experience need to be defined as per https://github.com/aquasecurity/tracee/issues/221

From https://github.com/aquasecurity/tracee/pull/249: 

> CRI, which is implemented by all container runtimes working with kubernetes (including docker, containerd and cri-o). A tool that uses this interface is crictl: https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md

> start with a much simpler case before diving into any of these approaches. Assuming the user can provide the pid of the container entrypoint (by inspecting the container to get this pid) - Tracee can go to procfs to get its pid ns inode number, and use it to trace all of the container pids (by adding the pid ns id to pids_map). This should be a good starting point, from where we will be able to automate more things in the future, like getting the container entrypoint pid from a container id for a given container runtime.

**Comment by yanivagman** [comment]
Now that we added filters for UTS name, mount namespace id, and pid namespace id, it is possible to use these filters to trace a specific container(s).
We would like to have the ability to trace using the container id given by the container runtime, which is unknown to Tracee. The uts name is usually the same as the container id, and can be used for that purpose, but that cannot be trusted to always be the case.
Using cgroups is another filtering option, which we should add in the future to support container tracing.
Yet, we will probably have to implement some kind of interaction with the container runtime if we want to filter by container id correctly.

**Comment by simar7** [comment]
> The uts name is usually the same as the container id, and can be used for that purpose, but that cannot be trusted to always be the case.

Just for my understanding, why it cannot be trusted to always be the case? What would be such a situation?

**Comment by simar7** [comment]
I think I have found one case at least for that to happen. Running pods in k8s seem to have a different UTS name than what the CRI sees.

**Comment by yanivagman** [comment]
UTS name is namespaced. As such, the hostname (uts name) can be changed from within the container

**Comment by yanivagman** [comment]
For example, try to run a privileged container while tracee runs, then execute (in the container):
`hostname foobar`

**Comment by yanivagman** [comment]
Now that we have container id as part of the context (#749) we can implement a filter by container id to complete this task.
Interaction with the container runtime through CRI should be handled in #430
