### ISSUE TITLE
Add state saving mechanism to tracee-rules

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#2561]
# The problem:
Rules which are based on state saving needs to manage their own state - this can lead to duplication in state saving for similar rules.
If a global is used there are no duplicates but because rules aren't ordered we can't know which rules will get the event first and save it to the global.

# The solution:
A state saving mechanism which will be first in the event consumption pipeline of tracee-rules - and will later be relocated to the single binary to the end of the ebpf pipeline.

current state:
tracee-ebpf ---pipe---> tracee-rules parse event ----> send to each rule if was selected

suggested state:
tracee-ebpf ---pipe---> tracee-rules parse event ----> run state saving functions if defined for this event ----> send to each rule if was selected

This way tracee itself maintains a single copy of any LRU for state saving and updates it prior to the event getting to any rule.
The proposed addition to a rule will be adding function:
```
func (sig *<signame>) GetStateSavingFunc() (string, func(string, trace.Event)) {
	return "sched_process_exec", "process_executed", helpers.ProcessCreatedStateSaving
}
```

In this example:
- "sched_process_exec" is the event to be sent to the helper function
- "process_executed" is the LRU name
- `helpers.ProcessCreatedStateSaving` function is a shared function that does some logic and saves to the LRU name provided to it according to the logic

Tracee-rules will iterate over all the rules before starting them and will create a map of unique functions to be run and LRUs to be created, so if multiple rules use the same LRU name and run the same function - only one instance of it will run.

**Comment by geyslan** [comment]
@josedonizetti is ["everything is an event"](https://github.com/aquasecurity/tracee/issues/2355) effort changing this, right?

**Comment by NDStrahilevitz** [comment]
This doesn't take into account external data to configure signature behavior (for example a DNS blacklist).
Is this solution purposfully not taking this case into account?
Also, especially if we plan on deprecating the two process approach, the LRUs can be kept on tracees object in the "everything is an event" mode. Then the "on event data storage" solution presented here is simply another processor function (see #2514), so there would be no need of a new pipeline stage.

**Comment by AlonZivony** [comment]
I have a matching solution to this problem:
We save a map of LRUs, and load a new plugin for the states.
Each state should export the following functions:
``` golang
type StateSaver interface {
    GetLRUs() map[string]lru.Cache
    UpdateState(trace.Event) error
}
``` 
Then, each signature can validate that its dependent LRU is existing upon initialization by checking the map.
WDYT?

**Comment by yanivagman** [comment]
related: #1423

**Comment by NDStrahilevitz** [comment]
> I have a matching solution to this problem: We save a map of LRUs, and load a new plugin for the states. Each state should export the following functions:
> 
> ```go
> type StateSaver interface {
>     GetLRUs() map[string]lru.Cache
>     UpdateState(trace.Event) error
> }
> ```
> 
> Then, each signature can validate that its dependent LRU is existing upon initialization by checking the map. WDYT?
> 
> EDIT: We will probably want to have to these also a selected events feature to reduce load.

This solution still doesn't consider an update that doesn't come from an event - which is a requirement for CNDR signatures. As such `UpdateState` should not be event dependent.
