### ISSUE TITLE
Process Tree: Create a process tree fed by events that works as a datasource

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2586]
Process tree

1. Populated by Fork, Exec and Exit within the controller events
2. Should provide a datasource to signatures about processes/threads status.
3. Should also be populated by regular events
4. Should

Information that should be available:

1. Process related information (pid, ppid, tid, nspid, nstid, ...)
2. Information about the binary being executed
3. Information about the binary interpreter
4. Information about any real interpreter (shell, python, perl, ...)

## Issues that still need work (updates go here as they are done)

1. Process Tree should parse the signal events arguments in a generic way (issue: #3477)

2. Process Tree needs to deal with exec() called by non leader threads (issue: #3478)

3. Process Tree allows regular SchedFork,Exec,Exit events to be disabled (issue: #3479)

4. Signal events should be spinned out of regular events definitions (issue: #3480)

5. Control Plane needs refactoring for initialization arguments (issue: #3481)

6. There are some useful values that are missing from the current process tree Process struct (issue #3489):

 Execution time - the executable file information is changed in the change log during execution feed, but the time of the change is impossible to get in the current API
 Container ID
 Execution CMD
Maybe we even want the environment variables?
 Files hashes in the FileInfo struct

## PRs (related to process tree)

- https://github.com/aquasecurity/tracee/pull/3364
- https://github.com/aquasecurity/tracee/pull/3468

## Old Description (of this issue)

- A referece implementation of the process tree in tracee-rules can be found here: #1330
- Also consider the comments in #1374 for the implementation

**Comment by NDStrahilevitz** [comment]
The package should take care of coordinating between tracee procfs and the proc_info_map as well (https://github.com/aquasecurity/tracee/pull/2564#issuecomment-1406677995)

**Comment by yanivagman** [comment]
#1330 can be refactored and used, although it was intended for tracee-rules.
@AlonZivony did some good work there, but it never got merged.

**Comment by yanivagman** [comment]
Also related #1262
