### ISSUE TITLE
licencing question

### ISSUE THREAD

**Issue by 06kellyjac** [aquasecurity/tracee#2588]
tracee is marked as Apache 2.0 at the root of the repo however in [packaging/fedora/tracee.spec](https://github.com/aquasecurity/tracee/blob/main/packaging/fedora/tracee.spec#L4) it's marked as GPLv2 only and in [packaging/ubuntu/copyright](https://github.com/aquasecurity/tracee/blob/main/packaging/ubuntu/copyright#L3) it's marked Apache 2.0 generally and GPLv2+ for `pkg/ebpf/c/*`

Since ubuntu/copyright is most granular I'm thinking this is most accurate?

Maybe `reuse` might be of use?

https://github.com/fsfe/reuse-tool/

configuration:
https://github.com/fsfe/reuse-tool/blob/main/.reuse/dep5

**Comment by rafaeldtinoco** [comment]
@06kellyjac I believe the fedora package SPEC file has the wrong license. We have to fix that. Both Ubuntu and Fedora packages have dual licensing, just like you stated from https://github.com/aquasecurity/tracee/blob/main/packaging/ubuntu/copyright#L3.

**Comment by rafaeldtinoco** [comment]
Fixed by commit 276ad2fc
