### ISSUE TITLE
Tracee Image CrashLoopBackOff on Raspberry Pi Cluster

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#2595]
## Description

I tried to install Tracee on my microk8s Raspberry Pi Kubernetes cluster, following the Helm Chart installation in the tutorial: https://aquasecurity.github.io/tracee/v0.10/tutorials/everything-is-an-event/

Error: All pods are in CrashLoopBackOff

Logs of the pod:
> exec /tracee/tracee: exec format error  

Also:
> uname -m
aarch64

Events of one of the pods however, seem okish:

│   ----     ------     ----                ----               -------                                                                                                                                               │
│   Normal   Scheduled  3m30s               default-scheduler  Successfully assigned tracee-system/tracee-2nnpt to pi1                                                                                               │
│   Normal   Pulling    3m29s               kubelet            Pulling image "docker.io/aquasec/tracee:0.10.0"                                                                                                       │
│   Normal   Pulled     2m36s               kubelet            Successfully pulled image "docker.io/aquasec/tracee:0.10.0" in 53.72067991s (53.720697521s including waiting)                                         │
│   Warning  BackOff    12s (x7 over 118s)  kubelet            Back-off restarting failed container tracee in pod tracee-2nnpt_tracee-system(205d0ec6-09e5-4155-8c98-eb342e898872)                                   │
│   Normal   Pulled     1s (x4 over 2m6s)   kubelet            Container image "docker.io/aquasec/tracee:0.10.0" already present on machine                                                                          │
│   Normal   Created    1s (x5 over 2m36s)  kubelet            Created container tracee                                                                                                                              │
│   Normal   Started    0s (x5 over 2m35s)  kubelet            Started container tracee 

## Output of `tracee -v`:

I used the latest Helm Chart with this command:
```
helm install tracee aqua/tracee  --namespace tracee-system --create-namespace  -set everythingIsAnEvent=true
```

## Output of `uname -a`:

```
Linux pi0 5.19.0-1009-raspi #16-Ubuntu SMP PREEMPT Thu Nov 24 13:38:20 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

```

## Additional details 

Anais is very sad 😢

**Comment by yanivagman** [comment]
The image you use is compiled for x86 architecture and not for ARM64.
We already have an issue to handle that in the next milestone: #1913 
Closing this one as a dup.
