### ISSUE TITLE
Add IP and Port to IO operations on sockets

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#2597]
When we use events like `vfs_write` to catch writing into a socket,
the path parsed of the socket is only the protocol (for example, "TCP").
Here is a screenshot for such an event:
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAt4AAAAbCAYAAABLLohxAAABV2lDQ1BJQ0MgUHJvZmlsZQAAKJF1kM8rg3Ecx19jWvk5cVCUKQmNeObHyWF2YCXWRn7k8uzZDM08Pc9k/gc5Oju5uK52ceAmV8VSzk5Osoj1+DyGGfnUu8+rd+++vb8fqHKqup50AluptBGemvQsLa94XPc4aKaJLjpVzdT9odCMRPjalVO4lrTM1YD91mC/0nZ+sBnM5+cyl08tw3/zFVMbi5ua7DdRv6YbaXD0Cod207rNGeFWQ0oJ79ucKPGRzdESZz8y8+GA8IWwW1tXY8J5YW/0h5/4wVvJHe2zg92+Pp5aiMhuFHUQQWGcacYYRRr8kx35yAbYRmcPgw0SrJPGg18cnSRx4SApNAbxCisMiXz2jX/fruyZdzDhhqrusrd6Atln+WZ72euZhYYXOH3QVUP9vqij4DTXfEqJ63JQc2hZj4vg6oPijWW95iyreAzVt3BWeAfkW2I6JJIKtgAAAFZlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA5KGAAcAAAASAAAARKACAAQAAAABAAAC3qADAAQAAAABAAAAGwAAAABBU0NJSQAAAFNjcmVlbnNob3RAjmERAAAB1WlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNi4wLjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDxleGlmOlBpeGVsWURpbWVuc2lvbj4yNzwvZXhpZjpQaXhlbFlEaW1lbnNpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj43MzQ8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpVc2VyQ29tbWVudD5TY3JlZW5zaG90PC9leGlmOlVzZXJDb21tZW50PgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4Ko3ZN2AAAIddJREFUeAHtXQd8FUUTH4IiovTem6AICIoRUJFIR3rooRfpHRJCU1BQMHQBKYJ0QaoU6R2EBAIiKBK6EkDIR5WEJn77n2SPe4/kbl/evRDCze/33rWts7O7s7OzM8kKv1XmPzKBlClT0uLliyhr1qx0/dp12rplK8fwqeBDp06cou5delDBVwrSgsXz+f3ZM2dpz+49VKNmDUqXPh2NGz2eFn+/mF588UVasWY5pUuXjn7e8zOd/+s81fOtR8+neJ4G9h9EWzdHpyuLU+T1IvTdvFn04MED2r1zN92+fZuCRo6mO3fuyCCkEkYL7HSjUmaUbeuOLVzG+XMX0Lq167R6Dh0yjNb/tJ5KvlmSpn77DeNm546dVMq7FOXMmZNz27JpCw0KHMz3TfwaU8aMGSlb9mxUuWplioiIoHVr1vG3Des30skTJ/m+eIniNGPWdLp/7z4F7wum8+fDuf4H9h/g7/af5zFgFc3rS7pt11a6du0a+daur39NmTJl4n7x/PPP00+CHlKmfIEqVKrAYebNmU+TJ07Wwjds0pD6+vfh59j6jBZQ8aZQ4UI07/u59MuhX6hT+84OsSpWrkgjRg7nd2OCxtKSRUscvps9qOBQptG0eVPq2bsHP54IO0EtmraUnwQ+zMefXLlz0dKVS2j71u0U6D+A48p+tHL5Sho5YpSWnnwfW//y8vKin/fvocO/HKaDBw5ShowZqEq1KvTCCy9Qq2atCWWTYEVbzJo7i14vWoT7/pXLV6jse2Xp4cOH1Kxxczpz+gx5v/M2TZg8ge7evUst/VrxmDlRPHuX9qbVP66hEZ+N4OLU9a1LgYP681i5ZtUaunnzJpX7oBxhLB4QMJDDmOWFQAkZhgsV82dEhwgSV98p9XYpmjxtEqdy5PARunzlCr0rcIi5Rs47MVlol7jyUqk7EnG3X2Bsz5MvD1WtUI2Gfv4pVfuoGlX+sAo1aNSAOnbuQO1atSeMBWZzigptqPQdiZhntQ+i73xY0YcwhmDeBn+B/v/PP7dpkOBLGjZuQH0D+jKafv/tGN3+5x+JMgoNPUizZ84mV+jQXfqRmRuNYwhjxm/0HxBgSoenTp4y5f1U+bo161dTpsyZ6Njvx3iMK1qsKFflxxU/0pfDR8pqkVm9ENCKsVfLUNzENSZ8v2QhRVyJoEuX/hZ8XgnKnSc38231azfgMVmFNtp3aEctWregfXuD6Z4Yx8u8W5a89JnHdQ9C7NGlJ2FgAyPt28CXf+jUR48cdYgGJhnE26xFMw4LRmL50uUcJioqigaISfHy35fF4PguNWrSiLySe9HMGbNo25ZtDung4Y9jfxAmfDDoYPKrVK1C//3nuE5QCfNYwk4vjMqMyfnYsWMcY++evQRCRPkBvx7+la9gWkA8KV5IQbXr1qZs2bLR/uD9/O0fXSetWKkiNwCYbgAYLjQIfpmzZOZ3+AOeZ0ydQTdu3qD3yr3HHShP3tzad/vG8xiwiuZVSooF2NDBQwn946Oa1ZnpvnXzFkfVD/J4AXpMKChQsICW1cXwC9q96o0rONy8cTMPxkh7o1iE6kElnajIKI6PxbkzOL8z6l8YX8DwlihZgtq0b0N16tWhv8WgO2HsRAemG3lY0RaB/oGc7iuFXmGmOzIykoYM/ITLgDwCxOSIxcCYr8bSX3/+xePfsE8+o+vXr1OtOjWpWPFiCEarVq6iieO+pvv37xMYiZatW/IkcSIsejGPMGZ5JXQY5OcuhB4IpbFB41gogwm7oliwghHAfAKcuAIq+EF67vYLpHFbMHVxAehVZU5RoQ2VviPL8az2wfwF8lHpMqU1YRn4Gjy/9tqrjBosuiVgkYxFr/xlF0I0gCt0aAX9IE+jcQzfVfgNMzpUoR9Vvm7i+IksGICwFL/ff/sdxRQLnEcLGTyb1QthrBh7kY4ZXLhwgdsaYy0WZlh4dWjbkZluxFWhjRtCCIIxvLzPByxwTZ36ZUqmIvHWFw6RcgjGGoPDpYuXGJH4LqXHG9dvouHDhlO+/Pn4OyQvzpAsWTLKniM7pUqVis6dO2c5El9M9aIDQpzzx/PDfx8yswspvUqZY0vD+R0aIW++vHTu7DmtYZzD2M9PHwasoHmVWj/33HPcb67+7ypdvXpVJYpHw0Diht2c438cp9bN2zy26HUl87hw6EoaCGtVOmb5pk2blrJkzUK3xPgFaYenAQvvNKlT0xkhoYbEO76AAT5HzhzMfF4QiyXnRQfSVckrIcPEt676eJAQY07BbtGF8IuPTeb6sGb3ZnW3sl+YlcXKOcWqvmNVOmZ1T+g+aFYele8qdJiQ9KNSZtUwZu2uwte99NJLzMBCmBrb2KRaloQMh3EFtBh+/jzduuW4SFAtBxZz0HRIJXjTiIj/0XOqEWU4ZIyJ2Aju3btHYcfD4gwCqRImBU9Bl66deSvCKH3k798nQAtiVmYtoMENtoON6m0Q1f6UiDFgBc2rVA87L1LdSCW8J8NgoJBbgdOmTHeL6UY5VXCoUh+r0jHL68aNG4RfQgHUTPBzF8C0Y1IzApW8EjKMUVlVv0HS/+e5P1WDG4YzqrvV/cKwIOKjlXOKVX3HqnTM6p7QfdCsPCrfzegwoelHpcyqYczaXYWvA7Ntxj+qliehwl28cJHwcwewcwC1PwkuM94yovMVjCvg3r27zp8S/DkkZD+9LCTzRhAu9KYTU5mNymp/S5wYSMr0g7qNFWpeXl7J+TxG4mwBu1Q2BhIWA3a/SFh8J7XcbPpJai0av/q4rGpilA0OX966dYugp/i0wNNY5qcFt89COW36eRZa2a6jjQEbAzYGbAzYGLAGA5Yy3tYUyU7FxoCNgWcNA/P6RR+08US9W4x+3RPJ2mnaGLAxYGPAxoCNAZcxYJmqics52xFsDNgYsDEgMACm25PMsafTtxvRxoCNARsDNgZsDKhiwCMSb9hq9G1Qj94vV45efvklCgkOcbCjq1q4xBqu8KuFaWTQl7RC2AeeN3teYi2mXa5EhgGc+nY2h4ki4rTzlGmT2c7nV19+lchK7bni4JT8gqBiNHtz9jgzOX3qDJtWQwDY1Idt6teKvMoWkcLFAeltm7ey1RF8q1mrBgHHgH+F1aLLly+zuVOYZvQ08/20jAl58uah8h+Wpwzp07Pu/sHQQwJX/zLOPPGHuQB2x7cK837fTvvWE1k8luaTbAscnntb2F6HKboMwmdDVFQkHybbvHGLZq3mVfGtaLHYd2GuX7/h4M9Cpb3gGwJmZ2GLmA9oh52g9es2PNaub3u/LXxxZKEw8V1vj16PQJUw+vBJ6T6u8dlTdYT5y0LCjOi5s3+yOUJ9PqDh0mVLk5cYz2AlbeeOXRr9IFzy5MmpavUqos0LiznlIZu5gx8UZ4tIqrShz/tZujfDs6dw4RGJdythQxYGzmESDVYaQDhJCTJmysgmu9KkSZOUqmXXxYMYgHOMfv37so3mTRs2OeQEM4IwAZchQ3qH90n9ASZHs3iPowDvuGu6bMkyZrzBwH01ZpRwNuPIsPgIJrJju05sE7//wP6PJQQbsV98/qV47zlVFmT6NIwJgz8dRDVr19RwBIcpcIj2cdsObCNc+2DhzUvCZCzsFsNMYkLBk2wLMNWjxwU9VtXGTRtT54+78IH+atWrEnAfG8C2sXQkp9JesIc8enwQO2aT6WFxf/DgIbbEAGbyw4ofUqs2LQllA2wQTPmng4fyPf5UwmiBk+iN0fjsiSqnF2M96ARm6mCzPbR9qJZNpSqVaNjwocxcy5egicEDhjBjDZOhcBoFU6962P1RNerft7+24DKjDX3cZ/HeDM+exIlHGO9y5cvxAONbq76Dl0lPVsRO28bA04AB2DG1IRoDYcdPUPi2evTV0rz8om9AH4KED14mpfmmc2fP8rdAwVSD6T7y61GCI4ZI4YDk/Q/eF066HBcr165eo4GBgyhXrpzsERAe5YZ8OpgurJ0Vnekz+g8/CzXEjgAcTwwIGED/E7bie/TqTm+WepOaNmtKntppuSDMcPXr1Y9t1z4LqIdn2oXzF9KBkFDheOkSFSxUkHr17cWmOavXqM6O1n5YvIR3t/T46NqjKxV+tZDYhdjLr1XaCwzzkKGDmemGR+VlS5YzY1ZO9AvpYCTliynpi1HR3k1hng+MnuC09VmTShiHCEn4IaHG5959e0e3hRMusXMXMMCfme7xY8YTdvxGjR7JTtU+EI7Ftm/bIca1qsx0w5Hf+LETeBe1W8+uQsPgPQLvBe+9KrThlPUz9aiCZ08iRInxhiSpyOuvsetzmOGTMGzEMMorJsrePfpQiudT0Kgx0W4/sXUOgKF4wCGxnTlh3ES+h+SqiV8T4RnqHcqXLx/byg0Wqiiff/o5f3fl7+spE9mKyiGxYqxVuxbly59XGDkPp89EWnBLCg9mXbp1Fi46y1DWbFnpL2HfdqkY9FYsW6ll08e/N71T+h2xBZeVt+nOCun8nFmzafeuPVoYSGz8+/cTW9yv0dVrV4V06Lz2zb5JmhiAl6rhX37OtpXB3GFShMOoRQsXuUQ/8M4Kb5SQcAAwwdb1rcP3Pyz6gV3E84P4k1IQeE28/+A+rV39k+YuHvSJ/nXq1GlKK3ZaYguDdMzoGUwAJG53hM15GPPfvXMPu8JNmy4tfb9gkaYOoNJ3kN8HwhtX67atcUtBI4O43/GDwh9sFEde2krB+6Kl2HDRDIBH2NOinhLg1RFMNsL37t5bc44CXDjDVcH4YLzBD5PU+s3rCA61UqQtIoJGOQeP97PKmGCGQ5VxFQsJgDt4RnwsaDAZwxObHNu2CCkaGO9MYgfPagB+BgwK1JLdsX0HeyKWL1TpGVvlfcSCrETJNzgqvIjOECor+37eJ5NiibrZ+GzWFjIxd/EMW+LwICoBNFqmbFkeA3LmysGvne0Cw0kOnHRAUr129VoOo9Je3u94c91/O/obwZupBOkREM9379yl+XMXsCdPMN1jJ46RwbSrShgtsEU3b5R4gz7u9DG9IhaEYPxhe37Od3MJ3jMBZu0O51ZQ9wzdH0qTv57CccB3YJGxfesOmjt7Ls/pZmOmK+Ozu7TBhRR/8NpdpVpl7g/gKfTw3vvvEXbSIQVftHAxzzvwiA2oXvMjHtNknC2btmi7I7lz56Yu3TsL796VmfFWoQ19vu7cq86VZm2KMqjyh+62hQqe3cGJWVwvswD4Dj01NHZlsQUiIZtgZNHIQNQNoZeGLV3oUsJAOvSMYK8S9/jBU4+EHr16UPOWwp18unQUGnqQJ9MagqCwAnEVCglmqIJwEdzXvw/BdSsGNHiOxBY2JhnoFkLlJaeQfkVciaCCYjLAZFe7bi0tq4aNG7InN7iehxvm4m8UoyCxBQRJGQAD9pTpk3mCgs4oCY/1ZYTulQ1JGwOYDEHzkCAUfKUAhf0Rxh63QD9w/SrBjH7gyQx9AFcA1K9kv7gmtvn1AGYaDCZ0bjNkyEAtWjVn18UIg/6B8qCvxBUG4czKU1RIjdOlT8dnLzDA86JALCxA51ARQ71V+w7yw4IWbpTxA/PgCcCiB7BXSAOd3Qsb5ZeMdJK9ZEpDnVFy2jeVMUEFhyrjqszUXTyDQQFdoY3AbEO1yadCeU4+eF+IzMby6wvCkyR0WYs4qQip0LPcUocbeJT99u1IlhyPmzhWUzmyqi1kxd3Fs0wHOrip06QWOPYRjFZZfn3wwEH52eEKVRCcd4DbcbnTo9Je+Qvk53TgmGPIsCE0e/53NGLkcHqr1Fta+piLJ02YRGDOQZOxgUqY2OLF9x3crUMo5y104TEe/nHsOC8M0c4AlXZPkSIF00DuPLm1YsDjKHbFcuSMHodUaMyV8dkK2oAQIGBgAPNKcsGgVUDcYKcOAMEB8BAoFq+gJYD8JqXyl688crj199/R3nWl0FOFNjhRC/5U5kqVNkVRVPlDd9tC4tIIzxagJs4klGYjuFQHQCdGQsXKlbgjY9WFjgtmonuXHtS1YzdeZYPRxT1+C+YtkNHowwo+fN+yWSvq1a0XNajbkDq170z/Poj/AR9MyDWr1aLG9ZtQS79WFLw3mA8QYcDHdkydGnXJt3Z9ChD6TwApocN9t07dOW7nDl2oYb1GNG/OfK7XBz7l8Jm3dbBIOHrkKPk1akZNG/o5eCDiQPZfksZAT0Gn0IOVkqzGfo21+prRD2gffWDWjO84zvfzv9f6BejWGbp37k7VKlUX28bL+FOJN6MlffpwRmHMyoN0IFmrW6MeHTr4CycL2l+1chUz9xjQcPhOpe/oy+TJ++zZoydSyZQY5ZVCLHAgbYXu92dffMaT1jkhhbwTccAomkvfsNVrNiao4FBlXHWpYAaBb968KXYkRhMYlm+mT6Hlq5YRDtJhdwE6v1YDdizQZ4YIvVQziIuewbBCiHJJSLn9Gjajxr6NacnipTw+N2vhx8la1RZmZXT1OxjgTds2slQWC90NQk1gf0jsNFinXvQO2JpV0dJu5KXSXlmyZuZiQYUIC3IszCtWrkiTpn5NYG4TK3QTu35gxCCJb9a4udB978xzK1RwACrt7mrd4qIxV8dnV/N1Dt+5ayeC0HLqlGl8vsL5e4aMGfgVdu7qN/TlhcTqH9fwO0iMARfFzivgjTeK8xV/UlCYPkb17knRRlxzpWqbeoI/1JCku1HBsy645bdKqiaQBmMLDVu+kCjjsGTlqtFM+IZ1G10q1MmTJ4XaShHehsRW5yFxCATbKu7AsqXLWXKONKTL7WLFi3GS2JIaNGRgdPIxK35IeyBhgAtUbHFB0oetPXi7zJMnD4dlXThxJ1eOkApB6oLf/uD9PCFEJ2r/J2UMYBfnyOEjXMWf9/xMvfv1ogIFCmhVNqMfLaDCDRaJcnIGvdVvWJ/Sp48eiGV0szAq5bkTdYclx5A2AeAiW6o0pEqVilT7DuLu2bWH9a1xr9/ixrNVkFJI4wF3xS6aGUACtvCHRwt9CAVmz5xNfkXEVpVFoDImqODQlXHVXTyD4a5dtzZjADgB4wPInDkzj+mQiD4JMKJniWdIiiHYAezcsVPs6jSgfDHSXhnGaHxWaQvMBQB38cyJiL8QMUdgPsEuFqSqUKnAovaCsMSjB6hqvvlWSa4fdHMlqLQXLKhICPQfQId/OUw9e/fgsw0txZyGeSqxAXAB6yuAFctWaMWDiqhUY5VtatTuWkSFGyMaU4iuBXGXNooWK0o4xBl2PIzrDj1+Z4D0GACrQ42aNmL1xslfT6ZadWqSVDnZJSyctPu4LR+anT5rmliIevFOPeJJzYEnQRtGc6Vqm6ryh+62hQqegU9PgRLjjcw3ihV7+47tWd0EpoqwukZHcXWynTljFjPC0NHBD4zsmlVr+EBVbKbWzCp+//591vNyDodVJSAqMorAfEuAJAZ5PhA/bNlge07q34aHh7M0EGGlaoBcZYI5kXD69OO6pfKbfU1aGDhz5oxWITC1AEiwwLhgm9uMfrTICjfH/ziuhcIhLYDz7rBRGBV6RprQH+drDCN77/49un//Ab/DtqZK3+HA4g+MhDMzIb9ZdWUVL5FYeoF3M4A5NejOYwcN8cAAQVDgBxVvi0BlTFDFoeq46i6eId2GOhDUErp06MoSVeiE+jX3E4crm7DFBIvQ41IyRvQMc3yA06dOaWlKM3gZYySDVrYFMnEXz7Kgy4UwCD/0SUi/cc6oZu0aNP2bGTIIX2vFLIag23znzh3tm0p74bAkALsWkmn/YdESZrzz588nviQ+gDoIxk5Y05GMtnMpVdrdOY7RsxGNGcVz/uYubXTr2Y3rDmEj1Ivy5s3LWeTMmZN3KrBQgjlJQJv2bfj6ycBPKblXtKoJcAZAfSaKM3M4LwRdeQDmJuhaXxWHpgFPgjaM5krVNlXlD91tCxU8MyI99KfOeG/YxIw31E3AtAIwabgKu3fuZrWPUt6lmPiqVKlM2Gr7ac06XrG7mh5c1EdFRT0WTerPjh41mtau+emx73gB4gbTHbwvmIYOGcZSP0hT+gb01cLfuHGT72GPXEK2mK1v+Wxfky4GsmXLplVOTvKRkZGsXgWJhBn9aJFjbry8YtezxGcsCM3AKIxqeWJb4P6HwwsxoNJ3ZFjoLObIkYMfsSuGhbDVgAN1AGfzWbHlA7USqRIU23e8w6I6h9B1BkCNAYc2XQGVMUEVhxsVx1V38Vy67DtcxT2797BeLR7WCtUGMN6ly5R2qL67+HFIzOTBiJ4hQQPozw7kypWL38lvVrYFEnYXz1w43R8k9RBUgfH29vZ2YLxhRhQqIgAIn/Sg0l5yl0oyW4gvd7FwYNET4C5tSIECDnNDgCGZSX1ZZdsatXuk0PfHzg3aS4LcrXbWZTeiMRlXXo3GZ3dpI43Q+QfAtCR+ErAYweKsbct2GuOMb9AIQH/FIgwg2xb3OAi/auVq3pHHuRfodo//ehyr1uK7K7ThbpsiP4DRXKnSpkhDlT90ty30fcYIzyiTJ0BJxxsZY1LF1ih07jp16chlgd6aqwA1DzDKQDAsmezauYuTgNUUK0FKSarXrE4Y4CSAyAoWjFYVSCc6PyB0/0EmVKzEoZupB7kqLx6zssQ3ecJeH86+T5oYwG6JlF5C7xkgaUKFfiRW7t2LZu5eKRS9zSrfW3l1pTxG+ar0HRkfdqEXLJ7PPzAXnoD9IftZQgs1N1gDkIAdBxyGdhVwYHbx8sX8g4k3V0G2v9GYoIpD1XHVXTzLxQXUBSXIe+cDq+7iR6bv7hU7kACoa0hmCmoZADhP4muMlS0r2gLpuYtnHKgEQ6mHt4WQCSClkPIb8IyFO3Zkjvx6VL7mq0p7SfWgkgInco4rFXOwUuU8hEOGig/u0gZ2oLHYRXuW93k012JehsQWoNLuYKYxX79etChfEc95AYl3qqAyPrtLG99M+oatz8ACDX7Q8wZAWIBn7Obo1W5nTp/J3+WY98uhw/yMPzCeWNTh7BmsbbWNkZCDUQe4QhvutilnKP6M5kqVNkU6qvyhu22himdZN6uvjzhShZTBaEPFBAAiwbalK4COgkM90EWD/hYU3MuKAzRYuYbGceLblfT1YdetXU+t27Xm1eKa9auF57St/Nmngg+dOnGKD4Ju27KdV55+zZuKTp+TIIXHto8ecPCoU9eObMnik2GfUEpxSl9F8qZPw75/ujEwftJ4ljzUqFmDKyIPQanQj6z5mZi+UkswqlmEhOO8YBiw+DywP/YDVzKeK1dXymOUrkrfiS0+Jk9PACZrHHru2r0LDf18qFgc+9A/Yqer7LtlxUGji+xAx5V8JROHOFIn0pX4KmOCKzh0dVyND56D94YQ9H7BnMyYNZ1gEUFa24DZMj24ix+k1cSvMZuEk1YWIKxA+wFQX71aBb+M5W/n9p1saQoLhDETRvN2ej3fehwSh4EBVrcFJxrzFx88t23XhhqIXdMDIQeE6dlrVFIsGmBVCzDnuzkxKUdftEOVq9c6vMeDSnv9/tsxNi8KQdKyVUvZ8pJc/EKKJ6Gub12xu+yjMbawyjRh8nhxzuM2Deo/iIOphEFAK2gDZy4CB/Un/8B+bKYYB0nhkRb8xICAgaTS7ljEwIADrKrNnPMt8xDQoY4vuDo+x4c2pBlPWUboukOIeU2ctYEddsCpk6fYCyXUwj4bMYzP30geSZqaRLhZc2Zy/bGIKflmCcLZloiICM08rSptIC0r2hTpAOKaK1XaNL78YXzaQhXP0bWy/l9Z4o2soYcGJhkQHzUTbHGfOX2GJRhQ88DAg23kCWMnxunCljOL4+92jN3f2D5jYO/RpScfjIMEwreBL/9w6ACrRABWPT+u+JEPLeDgEbZK5IEUKQUCMQ8dPJSl9DC9BvOFctvkttjisSFpYwA6w1iMNWshTGAKOoJKFHQ3ASr0I7GDA5ozps6gGzdvsHtnMCZ58ubmz2As0a/kATIZB1f5TiWManmM+g3yU+k7sozSUYd89tR13ux5NG70eIGPSILZMYwdmHSlzi/aCeMLHOuYAayeSLjodNhNvje6qowJruBQZVx1F88wVTc2aBzTE3ZugEPsGGzbso0t2ujr6y5+kFbFShWpResW4hB+9A5FpkyZ+BnvsLWuQs/YGR0gDg3icBxsH8PmsldyL4IeKMoNsLot3MUz7KTfEbazwSxBjQRMN+o6dfJUB6k2DndBEo5+v06MKc6g2l7+vf2ZWYNddEguwYSAQVs4b6GWZP4C+XjBJYVKmAOxAINbewkqYRDWCtrAognqYFBLA8OPBSEYxxNhJ7k4Ku2OgHCkhX4PYw34yfNmcu5WoTHOUPwZjc8yjLu0IdMxuwb6B/K4hgUn6AiqjUMGfsK8k4wLOoPlGhy6xE4BGO0ObTs6qM2p0AbSs6JNkY7RXKnSpq7wh1a0hQqeUS9PQLLCb5V5pNzpiRxiSRMWQ7AtcUusdLFik4DtE3naVL5zvj789yFvOzu/N3qGBZMcgnkCU4FtGRCIHpCntNYit/j033GPrTyo2UA3SK9r5RzOfk4aGMCJc6hQwOTb8GHDue1BO5DOOIMK/TjH8eSzleUx6zvu1mNev9+pxejXlZOBdAY65aleSiX68kW2TKQSWZ8PbAhj1wqHlFo3b6MdqFZJRx9GdUzwNA71ZTK7B2MG3Vns3F0IvxirXXSr8GNWFtXvaHOUGRZ3zp07p3ll1MdPTG0ByR12teB4C0xgbHOOvuxG9yrthfiw+4+FKNSg5GLdKN34frOSNoAnqBZgAYjDcs7lVml3HF4F44nDhc7x41vHxBIPC9Q0qVMTpPFS4KkvG/oEeKnw8+cNx0Ez2nC3TV2ZK1XaNC7+UF93K+/N8GxlXjItl1RNZCR3r9gmctZ3Q5pdunZmhzdG6aODwia3KwBTUfqTzc5xwWzDxI8RgFmXpgqNwtnfkh4G4AzKiD5U6CchsWJlecz6TkLWC3lBKiL1BeOTN6R9ckt62pTp8Wa6kbfqmJCYcAgpI/TK4wIr8RNXHq6+R5tj3DeCxNQWYJIgUNILlYzKbvTNrL1kXAiDPC0Qspo2gCdpKUrWQ39VaXcw20Zzuz69p+0eltT01tScyw89fhVdfiPasLpNzeZKlTaNiz90rr9Vz2Z4tioffTpPhPHWF0B/HyIOUcH2qRHIg01GYexvNgbcxQAGEIA8dONuenb8xIEBtOvYoLHiQFZygl12GxwxYOPHER/20yMM2LTxCBdJ5c6KNkUaAHuuVKeKJ6Jqol48O6SNgSeHAehNwlwldOxs8BwG9GognsjF0+l7osx2mjYGbAzYGHhaMGDPla61lM14u4YvO7SNARsDHsAAmGNPgSs65J4qg52ujQEbAzYGbAzYGAAGbMbbpgMbAzYGbAzYGLAxYGPAxoCNARsDCYCBRKXjbXV9J0+bJJzlFORkodTfrnV700M6VpfBTs/GQEJjoPCrhal02dLkJaxBwDnHzh27Yj0Vb0W5VPJKyDCyTjCZV0iY4zp39k/hIyBUvn7sirKNDPqSVixfSTBZqAdYifBtUI/eL1eO4Lk2JDiERo4YpQ/CfgKyCgtNYWEnNNOG+gAqddeHf9burcKPVek8a/i362tjwMZAwmPg/4BVEmE4LqsRAAAAAElFTkSuQmCC">

It would make it much more valuable if we would have added information about the IP and port of the socket written to or read from.
For example, `pathname: 8.8.8.8:tcp:8080` or some other format.

**Comment by geyslan** [comment]
Yes, we have, it's stalled for a long time.

- https://github.com/aquasecurity/tracee/issues/2087.

**Comment by rafaeldtinoco** [comment]
@AlonZivony should we close this and consider that one (even update its description if needed since its older).
