### ISSUE TITLE
Empty arguments events

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#2598]
## Description

In the e2e tests we noticed that we receive empty events sometimes - events without any arguments.
We get errors for rules trying to process it, but nothing from the eBPF part.

**Comment by NDStrahilevitz** [comment]
This sounds like an extreme case of the missing arguments issue (#2261) right? Or is this something else (if so please provide an event sample)?

**Comment by AlonZivony** [comment]
So the problem here is not the fact that the arguments are missing by itself.
In this I mean that having default value will not solve this.
We have a bug in Tracee that cause some events to pass without any argument value.
@roikol if you have an example for when we saw it it would be great to add here.

**Comment by roikol** [comment]
hey,
we see it happen quite a lot in the e2e tests. 
each time its a different event or different argument.

the latest fail was for two events:

`{"level":"error","ts":1674034790.394005,"msg":"error processing event","event":"sched_process_exec","error":"error parsing sched_process_exec args: argument pathname not found"}
{"level":"error","ts":1674034794.3129768,"msg":"error processing event","event":"sched_process_fork","error":"couldn't find argument start_time of event sched_process_fork"}`

(in this case its errors from `tracee-ebpf`, but in other cases the error happens in `tracee-rules` signatures which expect an argument that doesn't exist).

in all cases - all the other events are fine (e.g. if there was a problem here with `sched_process_exec`, all other `sched_process_exec` events in the same run are OK).

**Comment by AlonZivony** [comment]
When I checked this error,
it wasn't just the `pathname` missing or other argument,
all the arguments were missing from the event that caused the error.

**Comment by yanivagman** [comment]
@AlonZivony is this still an issue? 
I didn't see this behavior...

**Comment by yanivagman** [comment]
We recently implemented the addition of nil values by default, so I think we can close this one.
Please reopen if reproduced with a recent version.
