### ISSUE TITLE
change pkg/logger to be a standalone package  

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2599]
Being a standalone package, logger can be used by libbpfgo.

Context:
- https://github.com/aquasecurity/libbpfgo/pull/284#discussion_r1068238401

**Comment by yanivagman** [comment]
@geyslan I believe this is part of the effort for #2417 , right?
If so, no need for a new issue

**Comment by geyslan** [comment]
Could #2417 be an EPIC?

**Comment by yanivagman** [comment]
You mean that you want to keep this issue and link #2417 back here?
I don't think #2417 is that big to make it an epic, but if you prefer keeping this issue, we shuold remove the kind/feature label

**Comment by geyslan** [comment]
Yes, I do prefer to keep this, since after this merge I need to raise other PR to remove the replace in go.mod.

**Comment by rafaeldtinoco** [comment]
> Yes, I do prefer to keep this, since after this merge I need to raise other PR to remove the replace in go.mod.

IMO we should avoid so many issues for so simple things (like replacing go.mod) if you don't mind. We're trying to reduce maintainership burden. Would that be ok ?

**Comment by geyslan** [comment]
> 

Ok, no worries. Let's close this.
