### ISSUE TITLE
cgroup_mkdir: error on processing event cgroup_mkdir: operation not permitted

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2637]
## Description

```
$ sudo rm -rf /tmp/tracee/out/pcap && sudo ./dist/tracee-ebpf --install-path /tmp/tracee --output option:parse-arguments --capabilities bypass=false --trace 1:event=net_packet_ipv4 --output none --metrics --pprof 
```

{"level":"error","ts":1674853714.6939313,"msg":"error processing event","event":"cgroup_mkdir","error":"failed to get lookup key 824652646800 from map containers_map: operation not permitted"}
{"level":"error","ts":1674853714.6941552,"msg":"tracee encountered an error","error":"failed to get lookup key 824652646800 from map containers_map: operation not permitted"}

## Output of `tracee -v`:

```
v0.10.0-102-g13364719
```

## Output of `uname -a`:

```
5.15.0-60-generic
```

## Additional details 

We're preparing for release, so I thought it would be good to report to @NDStrahilevitz and @yanivagman before the release (I'll be off next week).

**Comment by NDStrahilevitz** [comment]
This is running without bypass so I wonder if we're there's some other capability besides `BPF` and `PERFMON` required for some operations.

**Comment by yanivagman** [comment]
> This is running without bypass

So this should be handled as part of #2397 then. Moving to v0.12.0.

**Comment by rafaeldtinoco** [comment]
Considering as a duplicate of https://github.com/aquasecurity/tracee/issues/2397 (its actually one of the possible errors).
