### ISSUE TITLE
bpf_attach more than one instance of argument

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#2649]
Internal e2e tests give many repeated errors of this kind after merging #2617:
`{"level":"error","ts":1675101039.4204788,"msg":"tracee encountered an error","error":"read more than one instance of argument prog_type of event bpf_attach. Saved value: 28. New value: 2"}`
It's likely that this issue existed before but we only now see it.

**Comment by yanivagman** [comment]
Actually #2617 added a test which exposed this decoder bug. The index 0 is saved two times on the buffer. This is the first time: https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/c/tracee.bpf.c#L6225 and this is the second: https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/c/tracee.bpf.c#L4668 . Event args count and index should have been reset between these two events. @roikol  FYI

**Comment by NDStrahilevitz** [comment]
Closed in #2652
