### ISSUE TITLE
Tracee Policies

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#2665]
- [x] Implementing policies in Tracee, as discussed in #2640
    - [x] https://github.com/aquasecurity/tracee/pull/2892
    - [x] https://github.com/aquasecurity/tracee/pull/2922
    - [x] https://github.com/aquasecurity/tracee/pull/2923
    - [x] https://github.com/aquasecurity/tracee/pull/2845
    - [x] https://github.com/aquasecurity/tracee/pull/2927 
    - [ ] work on docs

Since policies are based on multi-scopes, a few extra changes to the UX and internal meaning are required:

- [x] https://github.com/aquasecurity/tracee/issues/2751 
- [x] https://github.com/aquasecurity/tracee/pull/2919 ~Multiscopes~ policies numbers feature won't be available through the CLI anymore (adding a number to filters will be removed), and it will become the infrastructure for policies. A user that wants to use it, will need to define a policy. 
- [x] remove policies table column as discussed in https://github.com/aquasecurity/tracee/pull/2923#issuecomment-1485965210

**Comment by geyslan** [comment]
I tested this on an ongoing PR and it worked great.

![image](https://user-images.githubusercontent.com/3372117/226683347-a0618a34-f66f-43b2-98ec-405cb089b0fb.png)
