### ISSUE TITLE
Precompiled eBPF program

### ISSUE THREAD

**Issue by danmx** [aquasecurity/tracee#267]
Did you consider loading/supporting a precompiled eBPF program?

Potential use case:
When using tracee as a library to build a (contenerized) monitoring tool an init script/container with higher permissions could load a precompiled eBPF program and later the actual monitoring tool (with less permissions) would read the data.

**Comment by itaysk** [comment]
Just to make sure I understand, you are want Tracee to load a user provided compiled BPF program?

**Comment by danmx** [comment]
@itaysk yes

**Comment by itaysk** [comment]
Thanks. I would separate this into 2 different issues:
1. Using precompiled ebpf programs - this is already under work. see https://github.com/aquasecurity/tracee/issues/209
2. Accepting user provided ebpf programs - we have this somewhat further on our roadmap.

**Comment by itaysk** [comment]
I'm going to close this issue as it is not so actionable. could open a new issue for the "plugins" suggestion but this will be further down the road
