### ISSUE TITLE
cgroup is not mounted correctly in the container

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#2680]
## Description

cgroup is not mounted correctly in a container, causing network events (and container enrichment as well) not to function correctly. The issue is due to not mounting the cgroup if it is already mounted:
https://github.com/aquasecurity/tracee/blob/main/pkg/mount/mount.go#L49
However, the cgroup directory mounted is only of the relevant container, and not the host root cgroup.

## Output of `tracee -v`:

```
v0.11.0
```

## Output of `uname -a`:

```
(paste your output here)
```

## Additional details 

Related issue reported by Rohit in the slack channel

**Comment by rohitburke007** [comment]
I faced this issue in the docker container but as per @yanivagman I tried it to run in Tracee binary and it also faces the same issue.

**Comment by rafaeldtinoco** [comment]
Okay, so I went on slack to get more information about this. The original command line was:

```
$ docker run --rm --pid=host --privileged  -v /etc/os-release:/etc/os-release-host:ro -e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host -v /tmp/tracee:/tmp/tracee -v /boot/config-$(uname -r):/boot/config-$(uname -r) -e LIBBPFGO_KCONFIG_FILE=/boot/config-$(uname -r) -it aquasec/tracee:0.11.0 trace --trace comm=ping --trace event=net_packet_ipv4
```

and it is missing the `--cgroupns=host` as documented in the README.md file at https://github.com/aquasecurity/tracee/. The reason why the first command did not pick any event is likely the missing docker command line argument (please confirm

cgroupns parameter behaves differently between cgroupv1 and cgroupv2 hosts, and `-v /sys/fs/cgroup:/sys/fs/cgroup` might not be accurate as cgroupfs, is v1, is a tmpfs (with other mounts inside it) and if v2 is a cgroupfs (with no other mounts inside it), and hybrid cgroup systems (v1 and v2 enabled) might be a different combination.

also, even with the correct cgroupfs, I believe the cgroup namespace has to be set to the same as the host.

Example: a regular container using its own cgroupns:

```
$ sudo lsns -t cgroup
        NS TYPE   NPROCS    PID USER          COMMAND
4026531835 cgroup    585      1 root          /sbin/init
4026535045 cgroup      1 478767 rafaeldtinoco /bin/bash
```

versus the same container using cgroupns from the host:

```
$ sudo lsns -t cgroup
        NS TYPE   NPROCS PID USER COMMAND
4026531835 cgroup    645   1 root /sbin/init
```

Mounting `/sys/fs/cgroup` only won't do the job of having a container inside the cgroup namespace from the host (needed for cgroup ebpf programs to be correctly attached).

> It is not the first time I have had to explain this (had the same issue with the tracee GitHub actions repository and needed to correct the missing argument for them as well). Maybe we should "document this better" somehow.

**Comment by rafaeldtinoco** [comment]
@rohitburke if this is actually true for you, then we can close this and keep the issue documenting the need for now (if others face the same issue).

**Comment by rohitburke** [comment]
Yes, by adding `--crgroupns=host` it works but what about this error `{"level":"error","ts":1675673780.162476,"msg":"osinfo","error":"open /sys/kernel/security/lockdown: no such file or directory"}`

**Comment by rafaeldtinoco** [comment]
@rohitburke being treated at https://github.com/aquasecurity/tracee/issues/2660 and fixed by PR https://github.com/aquasecurity/tracee/pull/2684. Soon it is merged, it will solve the issue (but you will have to use the dev version until v0.11.1 is released).

Thanks for reporting the issue! I believe it should be better documented so will keep this opened until that happens.

**Comment by rohitburke** [comment]
Okay, thanks for resolving this!!! @rafaeldtinoco

**Comment by yanivagman** [comment]
> I believe it should be better documented so will keep this opened until that happens.

Where? Don't we already have --cgroupns=host in all of our examples?

**Comment by rafaeldtinoco** [comment]
We do. If you think that is enough I can close this then! Cheers!
