### ISSUE TITLE
make integration tests more robust

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2681]
## Description

- We only have a few tests for multi-scope. Since it touches many layers, we need to create a robust test suite.
- Integration tests lack support for testing more event filter types. Building a more specialized test suite is a must.

**Comment by rafaeldtinoco** [comment]
For the integration tests, please be aware of: https://github.com/aquasecurity/tracee/issues/1681#issuecomment-1495598079 when adding tests that rely in PID=1. Cheers!

**Comment by geyslan** [comment]
> For the integration tests, please be aware of: [#1681 (comment)](https://github.com/aquasecurity/tracee/issues/1681#issuecomment-1495598079) when adding tests that rely in PID=1. Cheers!

OK. But if we run the integration test in a container just to not touch the host pid 1, that process will be a shell (for example)... so I think running tests just to filter the pid 1 that way doesn't make sense. It's the same of test against pid=whatever.

**Comment by rafaeldtinoco** [comment]
> so I think running tests just to filter the pid 1 that way doesn't make sense. It's the same of test against pid=whatever.

Sorry, I did not make myself clear, I just wanted to bring awareness to the issue, not to run tests inside a container as a suggestion!
