### ISSUE TITLE
add file modification event

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#2728]
adding an event indicating a file modification

**Comment by rafaeldtinoco** [comment]
1. There are the following PRs linked to this issue:

https://github.com/aquasecurity/tracee/pull/2608
https://github.com/aquasecurity/tracee/pull/2780

The PR #2780 will close this issue but we should re-open it to address:

- https://github.com/aquasecurity/tracee/pull/2608#discussion_r1112574608

, the fact that not all execution paths are covered by the event. This has been discussed with Roi already.

---

2. Relying in some probes that don't exist in all kernel versions will trigger error messages by default. The issue:

https://github.com/aquasecurity/tracee/pull/2608#discussion_r1112574608

is about that AND the PR:

https://github.com/aquasecurity/tracee/pull/2761

added a feature so tracee can add proper filters for those error messages.
