### ISSUE TITLE
Add Stack Traces to calls

### ISSUE THREAD

**Issue by pathtofile** [aquasecurity/tracee#273]
BPF has the ability to log/print the stacktrace for a call, which can be useful for Reverse Engineering.

I have a working-but-WIP branch here: https://github.com/pathtofile/tracee/tree/feature/stacktraces, but in case this has already been discussed and rejected in the past, or if it's already in the works, I'd be interested to hear about it.

I think it should be an optional thing, and probably only really useful in the JSON output.

**Comment by yanivagman** [comment]
Hi @pathtofile 
Looks interesting - this hasn't been already discussed.
I will take a look at your branch (probably not before tomorrow) - thanks for sharing this!

**Comment by pathtofile** [comment]
I've created a PR as an initial attempt to add this: https://github.com/aquasecurity/tracee/pull/375 

As stated in the PR, I've put it behind a `--capture-stack-traces` flag to ensure performance isn't impacted if not wanted.

**Comment by yanivagman** [comment]
@pathtofile that's great! I can't wait to try this out.
I hope I'll have the time to do this tomorrow
