### ISSUE TITLE
not finding containers_map entry from cgroup_mkdir event

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2734]
## Description

Running proposed integration tests PR https://github.com/aquasecurity/tracee/pull/2688, I've faced these errors:

```
=== RUN   Test_EventFilters/pid:_event:_args:_trace_event_sched_switch_with_args_from_pid_0
    tracee.go:81: started tracee...
	executing: /usr/bin/kill [kill -SIGHUP 1]
    tracee.go:118: timed out on output
=== RUN   Test_EventFilters/pid:_trace_events_from_pid_1
{"level":"error","ts":1676561576.2194765,"msg":"error processing event","event":"cgroup_mkdir","error":"failed to get lookup key 824719350456 from map containers_map: no such file or directory"}
{"level":"error","ts":1676561576.2195385,"msg":"tracee encountered an error","error":"failed to get lookup key 824719350456 from map containers_map: no such file or directory"}
    tracee.go:81: started tracee...
	executing: /usr/bin/kill [kill -SIGHUP 1]
{"level":"error","ts":1676561578.1471684,"msg":"error processing event","event":"cgroup_mkdir","error":"failed to get lookup key 824722541736 from map containers_map: no such file or directory"}
{"level":"error","ts":1676561578.1472602,"msg":"tracee encountered an error","error":"failed to get lookup key 824722541736 from map containers_map: no such file or directory"}
{"level":"error","ts":1676561578.3838687,"msg":"error processing event","event":"cgroup_mkdir","error":"failed to get lookup key 824722969368 from map containers_map: no such file or directory"}
{"level":"error","ts":1676561578.3838956,"msg":"tracee encountered an error","error":"failed to get lookup key 824722969368 from map containers_map: no such file or directory"}
```

https://github.com/aquasecurity/tracee/actions/runs/4195470616/jobs/7275189121

**Comment by yanivagman** [comment]
Ok, looking at the code - this means that a cgroup was created in the system, but it is not a container's cgroup (can be systemd cgroup or something like that). Then, we try to delete it from the containers_map which is a bpf map, but the entry doesn't exist so we fail here: https://github.com/aquasecurity/libbpfgo/blob/15ae9ff99817997b95110096eda30c4d3824c948/libbpfgo.go#L926

This can happen if a cgroup was created and removed very quickly and it is not part of a container.
Not sure we have something to do with it.

maybe we should not return this error here: https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_processor.go#L273
instead we can just log it with info level

**Comment by geyslan** [comment]
> but it is not a container's cgroup (can be systemd cgroup or something like that)

Certainly is a systemd cgroup, since I'm running a `kill -SIGHUP 1` in above tests to collect some events:

![image](https://user-images.githubusercontent.com/3372117/219432668-d6b005ea-56f1-4db9-8c54-98958affa19d.png)

> maybe we should not return this error here: https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_processor.go#L273
instead we can just log it with info level

Info level is the default level, so it would print anyway. WDYT of Debug level for this matter?

**Comment by yanivagman** [comment]
> Info level is the default level, so it would print anyway. WDYT of Debug level for this matter?

Fine with me
