### ISSUE TITLE
tracee: add subcomand to analyze events in a file

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#2736]
A user should be able to store events in a file, and then run the signatures events on this data to see if trigger any signature.

eg:
```
tracee --output json:/events.json
tracee --trace event=anti_debugging --input json:/events.json
```

This is supported by the binaries `tracee-ebpf` and `tracee-rules`.

**Comment by itaysk** [comment]
tracee-rules was just a rule engine so giving it input had a clear meaning - this is the input for the rules.
tracee now is not a rules engine, it's a runtime security tool that generates security observability events for the user. the primary use case of tracee now is more about generating events than consuming events, so I'm not sure `tracee --input` is the best option.

**Comment by itaysk** [comment]
I would be interested to hear more about the use case of this requirement. I am guessing it comes from researchers wanting to reproduce/test signature events?

**Comment by yanivagman** [comment]
> I would be interested to hear more about the use case of this requirement. I am guessing it comes from researchers wanting to reproduce/test signature events?

With the current architecture of two binaries, it was possible to generate the events using tracee-ebpf in one node, and analyze it with tracee-rules in another. It was also possible to keep the events in a log file for later analysis on the same node. Moving to one binary architecture, we need to keep this option viable.

**Comment by josedonizetti** [comment]
> the primary use case of tracee now is more about generating events than consuming events, so I'm not sure `tracee --input` is the best option.

Agree, `--input` is not the best option, my plan was more aligned with the issue description, a specific subcommand for it, or maybe even a different binary.  
```
tracee analyze
#or
tracee-analyze 
```

The use case might be worthwhile for users outside of research too, with policies and an API the user will be able to enable/disable the collection of specific events, one might be debugging a specific incident, and enable a specific collection, which he can write some quick rego and see if it triggers outside of the main cluster, without the need to deploy anything.

Though he could also do it in the cluster, add a yaml with rego, and enable the event for just a context.

**Comment by itaysk** [comment]
ok go it. it's not in any milestone so I presume it's just a reminder, not a immediate work item right?

**Comment by josedonizetti** [comment]
@itaysk Yes, I have extracted issues from #2355 that aren't expected to be on this milestone, for this milestone we aim to finish all TODOS, and close #2355.
