### ISSUE TITLE
event only printed in one scope

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#2745]
## Description

When using more than one scope for the same event, the event is only matched in one scope. 

Eg: 
```
 sudo ./dist/tracee 
--trace 1:event=security_file_open --trace 1:security_file_open.args.pathname=/tmp/jose/*
--trace 2:event=security_file_open --trace 2:security_file_open.args.pathname=/tmp/jose/* 
--output json
```

prints only once when the event happens:

```
{"timestamp":1676837244709400958,"threadStartTime":1676836871528867344,"processorId":6,"processId":273464,"cgroupId":566734,"threadId":273464,"parentProcessId":4027050,"hostProcessId":273464,"hostThreadId":273464,"hostParentProcessId":4027050,"userId":1000,"mountNamespace":4026531841,"pidNamespace":4026531836,"processName":"bash","hostName":"josedonizetti-x","containerId":"","containerImage":"","containerName":"","podName":"","podNamespace":"","podUID":"","podSandbox":false,"eventId":"730","eventName":"security_file_open","matchedScopes":3,"argsNum":6,"returnValue":0,"syscall":"openat","stackAddresses":null,"contextFlags":{"containerStarted":false,"isCompat":false},"args":[{"name":"pathname","type":"const char*","value":"/tmp/jose/oi.txt"},{"name":"flags","type":"string","value":"O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE"},{"name":"dev","type":"dev_t","value":271581186},{"name":"inode","type":"unsigned long","value":31339067},{"name":"ctime","type":"unsigned long","value":1676837244701855144},{"name":"syscall_pathname","type":"const char*","value":"/tmp/jose/oi.txt"}]}
```

I've tested with other events, for example:
```
 sudo ./dist/tracee 
--trace 1:event=ptrace
--trace 2:event=ptrace 
--output json
```

And if I do an `strace` there is output only for one scope.

**Comment by josedonizetti** [comment]
@yanivagman @geyslan @NDStrahilevitz is this expected? Because while debugging the same issue for signatures, what happens is that we only trigger one signature, for example, `anti_debugging` because the signature pipeline only see one `ptrace` event, not two.

**Comment by josedonizetti** [comment]
Btw, I've released this is the bug blocking `tracee-action` of using multiscopes. The `sched_process_exec` is only printed matched in one scope.

**Comment by rafaeldtinoco** [comment]
The "only once printed" event contains: "matchedScopes":3, which is `0x1 | 0x2`, meaning it was matched in both scopes, no? Not sure what you mean by matched in one scope only.

---

About "seeing the event only once". If you take a look at "deriveEvents" function, you will see 2 things:

1. the event is copied and sent out the pipeline (the original one)

2. "derivatives" array of events will be sent to the channel right after (after running the derive functions from the derivation table).

So, if you have 2 or 3 events to be generated from the same "ptrace" event, for example, you will have to have 3 entries in the derivation table for the "ptrace event".

> You can pick as example the "DNS" event (which has 3 deriveEvents functions for the original DNSBASE event). It might generate DNS, DNSRequest, DNSResponse events together or not.

**Comment by josedonizetti** [comment]
@rafaeldtinoco AH, perfect, I thought it would print one per scope, but it prints once with all the matched scopes. Thanks
