### ISSUE TITLE
Some events rely in non-existing probes (to handle multiple kernel versions).

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2754]
Some events rely in non-existing probes (to handle multiple kernel versions). This is problematic because when running tracee in other kernel versions (other than the recent ones, or vice-versa) we may see errors such as:

```
$ sudo ./dist/tracee-ebpf --trace event=vfs_utimes
libbpf: prog 'trace_utimes_common': failed to create kprobe 'utimes_common+0x0' perf event: No such file or directory
```

Like explained at:
https://github.com/aquasecurity/tracee/pull/2690#pullrequestreview-1306542463

The solution for this is brought by the libbpfgo logging callback mechanism recently merged there and being worked at https://github.com/aquasecurity/tracee/pull/2663 for tracee.

Action: we should filter out error messages regarding probes that might not exist in some kernel versions.

**Comment by rafaeldtinoco** [comment]
@geyslan FYIO

**Comment by geyslan** [comment]
closed this as [completed](https://github.com/aquasecurity/tracee/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/aquasecurity/tracee/pull/2761

**Comment by rafaeldtinoco** [comment]
@roikol whenever you have a kprobe that might not exist in a kernel version, take a look at:

https://github.com/aquasecurity/tracee/pull/2761/commits/0a83bf085508b3a58abad01723ae77d9fe506816#diff-b232e4d52e183625dc4475a35a33ddbda84421c132f501d1c1f7856d9daa1b73

and you can filter it out from the error messages (in the error callback funcion). Thanks @geyslan!
