### ISSUE TITLE
Pods in CrashLoopBackoff with exec format error

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#2757]
## Description

I installed the Tracee Helm Chart on my Kubernetes cluster using the following commands:
```
helm repo add aqua https://aquasecurity.github.io/helm-charts/
helm repo update
helm install tracee aqua/tracee \
        --namespace tracee-system --create-namespace \
        --set hostPID=true
```

This install tracee version: tracee-0.11.1

However, the pods are in CrashLoopBackoff:
Logs:
> exec /tracee/entrypoint.sh: exec format error

## Output of `uname -a`:

Ran the command on the master node of my cluster:

```
Linux pi0 5.19.0-1012-raspi #19-Ubuntu SMP PREEMPT Thu Jan 5 12:15:37 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

I am installing the Helm Chart on my Raspberry Pi Kubernetes cluster, running microk8s, Kubernetes version 1.26.1
```
microk8s version
MicroK8s v1.26.1
```

**Comment by yanivagman** [comment]
> Ran the command on the master node of my cluster:
> 
> ```
> Linux pi0 5.19.0-1012-raspi #19-Ubuntu SMP PREEMPT Thu Jan 5 12:15:37 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
> ```

you have an ARM64 environment, but we don't yet have a docker image for this platform.
There is another issue opened for this #1913 

Closing as dup
