### ISSUE TITLE
v4.19 non-core eBPF object is broken when compiled with clang-14

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2772]
## Description

v4.19 non-core eBPF object is broken when compiled with clang-14:

![image](https://user-images.githubusercontent.com/7395852/221579128-66c88f50-9dc0-4c7a-b349-58140b390308.png)

As described at https://github.com/aquasecurity/tracee/pull/2771.

## Output of `tracee -v`:

```
Tracee version "v0.11.1-37-g0906f7d0"
```

## Output of `uname -a`:

```
Linux focal419 4.19.265-0419265-generic #202211101739 SMP Thu Nov 10 20:23:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yanivagman** [comment]
Dropped support for non-CORE
