### ISSUE TITLE
Tracee 0.12 docs restucture

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#2788]
Since this release makes "everything is an event" default, which is a major UX update, the docs needs an major update as well. which is a After syncing with @josedonizetti this is our recommendation.
cc: @AnaisUrlichs @yanivagman 

## General 
1. take a snapshot of current docs and put it under directory `classic docs`
2. update all mentions of tracee-ebpf and tracee-rules to just tracee
3. update project readme
4. remove videos which are outdated

## New TOC
1. Overview
2. Events
	1. Built-in events
		1. Syscalls
		2. Security events
			1. kprobes from contributing
			2. signatures from rules
		3. AVD
	2. Custom events
		1. Go
		2. Rego
3. Filters
4. Outputs
5. Forensics
7. Integrations
8. Deep dive
	1. Secure tracing
	2. caching
	3. ordering
	4. capabilities (from [here](https://aquasecurity.github.io/tracee/v0.11/docs/deep-dive/dropping-capabilities/))

### quickstarts
1. update code snippets
2. maybe take the "everything is an event" tutorial

### tutorials
1. everything is an event -> quickstart?
2. setup vagrant -> contributing

### docs
1. overview - rewrite
2. integration
	1. templates - wasn't in tracee-ebpf, just in tracee-rules. now it's available in tracee, but not in webhook
	2. webhook - only json supported. no templates or content type. usage is now through output flag, not a dedicated flag/
	4. falcosidekick - remove
	5. prometheus - now just one port like tracee-ebpf
3. tracing
	1. output - multiple outputs instead of output files. output options are: json, gotemplate, gob, forward, webhook
	2. scopes: remove!
	3. filtering: renamed `--trace` to `--filter`
	4. network events -> tutorial/events
4. Detecting
	1. `--list-events`: removed
	2. CEL: remove
	3. rules, avd -> see new events section
6. Deep dive
	1. architecture -> contributing
	2. performance: remove
	3. healtz -> integrating
	4. override os files -> under installation

**Comment by itaysk** [comment]
we reviewed all the existing docs are collected action items, this is the "docs" title. and then created a new toc that will better suit the new UX, this is the "new toc" title. I've updated the description to clarify this

**Comment by itaysk** [comment]
yeah makes sense

**Comment by AnaisUrlichs** [comment]
Intro's that have to be rewritten
- Overview: /docs/overview.md 
- getting-started: docs/events/index.md
- Should `available rules` say `available events` instead? docs/events/events.md

**Comment by itaysk** [comment]
closed by https://github.com/aquasecurity/tracee/pull/2797 and https://github.com/aquasecurity/tracee/pull/2802
