### ISSUE TITLE
Rename start.py to tracee.py 

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/tracee#28]
So that it's more obvious that Tracee is what we are running, if we show it in a demo

**Comment by yanivagman** [comment]
That's a good idea, but then we have a conflict with tracee folder and tracee.py -
start.py imports tracee, which will then be duplicated.

**Comment by iYehuda** [comment]
Maybe we should consider one of the following:
* Move `start.py` to `tracee/tracee.py`
* Move `start.py` to `tracee/__main__.py`. That way we can run `python tracee` to invoke `__main__.py`

**Comment by itaysk** [comment]
@lizrice can we close this given the move to go?

**Comment by lizrice** [comment]
sgtm
