### ISSUE TITLE
Take event and set flags out of filter

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#2810]
Currently `event` and `set` are located under the `--filter` flag. However, there are a few good reasons to take them out and introduce dedicated flags for them:
- Event is a basic concept of Tracee, and deserves its own flag
- Tracee uses a default set when no event/set filter is chosen and it can be confusing to understand the semantics of filtering when placed under the `--filter` flag.
- It will be good to make a distinction between filtering workloads and selecting events

Given the third point, we should also consider moving the event argument filters (e.g. `openat.pathname=/tmp/*`) to be under the `--event` flag.

**Comment by geyslan** [comment]
> Given the third point, we should also consider moving the event argument filters (e.g. openat.pathname=/tmp/*) to be under the --event flag.

Should for event the `.args` be implicit? My thought is that it shouldn't - what about context and retval? - it would make it confuse.

Based on the issue and effort I'm considering the following cli as valid:

`-e openat,close` which sets only the event without filtering

`-e openat.args.pathname=/tmp/*` which sets the event openat and its argument filter in one shot. 

I could consider `-e openat.args.pathname=/tmp/*,othersycall.args.xxx=something` as well, but I think it would complicate (convolute) the understanding.

**Comment by yanivagman** [comment]
> Should for event the `.args` be implicit? My thought is that it shouldn't - what about context and retval? - it would make it confuse.

You are right. It should be explicit.

> Based on the issue and effort I'm considering the following cli as valid:
> 
> `-e openat,close` which sets only the event without filtering
> 
> `-e openat.args.pathname=/tmp/*` which sets the event openat and its argument filter in one shot.
> 
> I could consider `-e openat.args.pathname=/tmp/*,othersycall.args.xxx=something` as well, but I think it would complicate (convolute) the understanding.

Agree with all these points.

**Comment by rafaeldtinoco** [comment]
> Based on the issue and effort I'm considering the following cli as valid:
> 
> `-e openat,close` which sets only the event without filtering
> 
> `-e openat.args.pathname=/tmp/*` which sets the event openat and its argument filter in one shot.

I like this approach.

**Comment by NDStrahilevitz** [comment]
> > Given the third point, we should also consider moving the event argument filters (e.g. openat.pathname=/tmp/*) to be under the --event flag.
> 
> Should for event the `.args` be implicit? My thought is that it shouldn't - what about context and retval? - it would make it confuse.
> 
> Based on the issue and effort I'm considering the following cli as valid:
> 
> `-e openat,close` which sets only the event without filtering
> 
> `-e openat.args.pathname=/tmp/*` which sets the event openat and its argument filter in one shot.
> 
> I could consider `-e openat.args.pathname=/tmp/*,othersycall.args.xxx=something` as well, but I think it would complicate (convolute) the understanding.

Ditto on liking the short hand of declaring event and filters at the same time.
The problem with multiple event filters separated by commas (like your last example) is mainly because the comma is already the separator for filter values. We would need another separator for filters as a whole if we wish to add that option.

On a separate note, for the same reason we plan on keeping a printer to the old event format, I suggest we keep the old filtering format that we have in `--filter` right now (maybe back under the `--trace` flag, since `--filter` will be used as part of this change if I understand the original issue post right), deprecating it with a warning log when used, and removing in a few versions from now.

**Comment by yanivagman** [comment]
> On a separate note, for the same reason we plan on keeping a printer to the old event format, I suggest we keep the old filtering format that we have in `--filter` right now (maybe back under the `--trace` flag, since `--filter` will be used as part of this change if I understand the original issue post right), deprecating it with a warning log when used, and removing in a few versions from now.

Unlike a printer to the old event format (which is yet to be discussed if we are going in that direction), these flags are the input/configuration of tracee and are only given when starting tracee. Adding backward compatibility for flags is not something we want to do in the current phase of the project (we broke and still break them too frequently to be able to maintain such support).
