### ISSUE TITLE
ARM64: tracee-tester should include tests depending on binaries

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2821]
## Description

Some tests had to be disabled in arm64 runners because tracee-tester (https://github.com/aquasecurity/tracee-tester/) does not have arm64 binaries.

This issue is about improving tracee-tester so it has binaries for both architectures so the same tests can run during the workflows.

- [x] TRC-103: missing arm64 injector (amd64 binary only)
- [x] TRC-104: https://github.com/aquasecurity/tracee/issues/2821
  context: https://github.com/upx/upx/issues/446 (arm64 wrong binary)
- [x] TRC-105: https://github.com/aquasecurity/tracee/pull/2863 fileless.py has an embedded amd64 binary (needs aarch64)
- [x] TRC-1022: https://github.com/aquasecurity/tracee/pull/2863 missing load.so arm64 binary (amd64 binary only)
  - [ ] https://github.com/aquasecurity/tracee/issues/2904
- [x] TRC-1010: cdk_linux_amd64 only (missing aarch64 version)

Notes:

1. TRC-104 is seg-faulting in RHEL8 [aarch64 only](https://github.com/aquasecurity/tracee/actions/runs/4360191513/jobs/7623252895). Looks like the binary that upx puts together after compression has issues leading to seg fault. You can use public AMI `ami-06bf1de0491bed185` and run `docker run --privileged --entrypoint=/bin/bash -it aquasec/tracee-tester:latest`, enter `aarch64` directory and check trc104.sh to reproduce the issue.

### Resolutions:

- https://github.com/aquasecurity/tracee-tester/pull/1
- https://github.com/aquasecurity/tracee-tester/pull/2
- https://github.com/aquasecurity/tracee-tester/pull/4
- https://github.com/aquasecurity/tracee-tester/pull/5

**Comment by rafaeldtinoco** [comment]
@geyslan I updated the description with all missing tests and root cause so you can see what can be done, if can be done.

**Comment by geyslan** [comment]
Close since it was resolved. The remaining of this has its own issue https://github.com/aquasecurity/tracee/issues/2904.
