### ISSUE TITLE
"docker rmi" requires at least 1 argument.

### ISSUE THREAD

**Issue by pomozoff** [aquasecurity/tracee#2822]
## Description

Build Trace for the first time on a clean clone:
`BTFHUB=0 make -f builder/Makefile.tracee-container build-tracee`

## Output of `tracee -v`:

```
zsh: command not found: tracee
```

Tracee git-tag is `v0.12.0`

## Output of `uname -a`:

```
Linux adnako 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

## Additional details 

[Tracee.log](https://github.com/aquasecurity/tracee/files/10906111/Tracee.log)
<img width="386" alt="image" src="https://user-images.githubusercontent.com/839094/223339968-3bc3347d-611d-4249-a7ed-d8a23ebdbdbb.png">

**Comment by rafaeldtinoco** [comment]
Thanks for your report!

This issue should fix the `docker rmi` line in the `Makefile.tracee-container`.

**Comment by rafaeldtinoco** [comment]
Closing this due to closure of PR: #2824. (Fixed by https://github.com/aquasecurity/tracee/commit/3442a928f629a67d98bd33af40e3ee571e7f8270).
