### ISSUE TITLE
Tracee should have a logging option for libbpf relocation debug log

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2823]
Today when executing tracee we can't see the relocation messaged done by libbpf when loading the eBPF object. This was reported by @OriGlassman and it is an important feature for when someone is developing eBPF code and needs to know libbpf errors directly.

Currently a workaround is to return false in the SetLibbpfgoCallbacks() function, but we should have an official way of doing that.

Workaround:

![image](https://user-images.githubusercontent.com/7395852/223429941-34abef5d-cf67-467e-8ba6-df30f1c09f55.png)

**Comment by geyslan** [comment]
Perhaps to raise a flag like `-log libbpf` which overrides all `LogFilters`. WDYT?

**Comment by geyslan** [comment]
Currently we're using only single logger at package level, so a libbpf output level option should force/override the logger level as well. Remember that we're passing libbpf output directly to logger.Log().

So, `-log libbpf:debug` would implicitly be the same as `-log debug`. What can be a bit confuse.

Considering that we want to output all to the same logger end, I assume that we don't need a `-log libbpf<warn,info,debug>` option.

Moreover, I suppose that the exposed issue

> Today when executing tracee we can't see the relocation messaged done by libbpf when loading the eBPF object.


is being resolved via https://github.com/aquasecurity/libbpfgo/pull/312.

**Comment by geyslan** [comment]
As the team discussed today, we agreed to use a single base logger, as it already is, but implement --log filter options, such as for packages or raw strings. It would answer all needs. 

So, I'm going to close this and open a proper issue soon.

**Comment by rafaeldtinoco** [comment]
Should this be closed by now ?
