### ISSUE TITLE
KConfig: could not check enabled kconfig features

### ISSUE THREAD

**Issue by pomozoff** [aquasecurity/tracee#2829]
## Description

The error appears every time on tracee-ebpf start:
```
{"level":"warn","ts":1678216546.3585808,"msg":"KConfig: could not check enabled kconfig features","error":"could not read /boot/config-5.15.0-67-generic: stat /boot/config-5.15.0-67-generic: no such file or directory"}
{"level":"warn","ts":1678216546.359375,"msg":"KConfig: assuming kconfig values, might have unexpected behavior"}
```
However, the config file is present:
```
$ stat /boot/config-5.15.0-67-generic
  File: /boot/config-5.15.0-67-generic
  Size: 300279    	Blocks: 592        IO Block: 4096   regular file
Device: fc02h/64514d	Inode: 15          Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-03-06 06:56:37.215929644 +0000
Modify: 2023-02-22 14:01:11.000000000 +0000
Change: 2023-03-06 06:56:10.564486882 +0000
 Birth: 2023-03-06 06:56:10.068383982 +0000
```

Is there any other reason to show this warning?

## Output of `tracee -v`:

```
zsh: command not found: tracee
```
I cloned v0.12.0

## Output of `uname -a`:

```
Linux tracee 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by rafaeldtinoco** [comment]
This is "a feature". You can execute docker with "-v /boot/kconfig-$(uname-r):/boot/kconfig-$(uname -r)" to get rid of that message.

Still, keeping the issue opened as I believe we can do better for the docker command examples (and perhaps for that message as default).

**Comment by pomozoff** [comment]
Got it. Thank you.

**Comment by rafaeldtinoco** [comment]
I have updated README file:

![image](https://user-images.githubusercontent.com/7395852/229863888-ce7daaa2-2bdf-42c9-98e8-51a7eac5786e.png)

And I believe that is "the best we can do" about this right now. So I'm closing this as it is documented how to properly run tracee not to get this error. We might improve the need for kconfig file settings in the future.
