### ISSUE TITLE
TRC-103 should also check PTRACE_POKEDATA

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2841]
## Description

TRC-103 signature is checking only PTRACE_POKETEXT. Since ptrace man stands

       PTRACE_POKETEXT, PTRACE_POKEDATA
              Copy  the  word data to the address addr in the tracee's memory.
              As for PTRACE_PEEKTEXT and PTRACE_PEEKDATA, these  two  requests
              are currently equivalent.

       PTRACE_PEEKTEXT, PTRACE_PEEKDATA
              ...
              Linux does not have separate text and data address spaces,
              so these two requests are currently equivalent.

the signature should also check for PTRACE_POKEDATA.

**Comment by yanivagman** [comment]
Fixed by #2846
