### ISSUE TITLE
Drop unnecessary capabilities on start

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#286]
As a security best practice, we should drop all unnecessary capabilities on start.
For now, this means ALL but CAP_SYS_ADMIN (need to verify this).
Starting from kernel 5.8, there are new CAP_BPF+CAP_PERFMON which should be used instead. (https://lwn.net/Articles/822362/)

Update: Also see required capabilties at https://aquasecurity.github.io/tracee/v0.6.4/install/prerequisites/
Update2: CAP_NET_ADMIN is also required for tc programs (packet capture feature in tracee)

**Comment by yanivagman** [comment]
We should also c

**Comment by AlonZivony** [comment]
For receiving the namespaces of the host (the init_namespaces event) tracee also should have the CAP_PTRACE capability.
