### ISSUE TITLE
Create a single "full" multi-architecture docker image (amd64/arm64)

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2866]
After PR: #2849 was merged, I saw that we could, in theory, create a multi architecture docker image putting together multiple manifests (https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/). This means that the second architecture container image builder (arm64) would have to pull the just built (in one step earlier) container image (amd64) from docker hub, create the multi architecture image and push it again to docker hub. 

TODO: Check if this is worth as well.

**Comment by prabhatsharma** [comment]
We have (in AWA) intel and graviton based instances in the same kubernetes cluster and this is pretty much a must if we were to run it in the cluster. Currently it just runs on the intel nodes and fails to run in graviton nodes;

**Comment by rafaeldtinoco** [comment]
> Currently it just runs on the intel nodes and fails to run in graviton nodes;

Hello @prabhatsharma, could you clarify this a bit further ? You're running tracee (deplying w/ helm I suppose ?) and can't have your arm64 nodes to run tracee because image is not multi-architecture, is that it ?

**Comment by rafaeldtinoco** [comment]
Partially done by:

- https://github.com/aquasecurity/tracee/pull/3582
- https://github.com/aquasecurity/tracee/pull/3581

For the "development" image (daily builds). Once the workflow finishes generating a dev snapshot I'll configure the release workflow to do the same (and probably release v0.18.1 with the new workflow to make sure it works).

**Comment by rafaeldtinoco** [comment]
Alright @hangrymuppet, the fix release:

https://github.com/aquasecurity/tracee/releases/tag/v0.18.1

Has been released and has a single manifest for both arches. Let me know if you face any issues. Closing this one for now. Thanks for the contribution and discussion.
