### ISSUE TITLE
Additional filtering

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/tracee#29]
I'd like to be able to filter by UTS name field. 

Option 1: add `--u <uts_name>[,<uts_name2>...]` / `--uts-name <uts_name1>[,<uts_name2>...]` option which would only output a line if it matches one of the specified UTS names

Option 2: add `-f <field name>=<value1>[,<value2>...]` / `--filter <field name>=<value>[,<value2>...]` which would only output a line if the field matches the specified values. If multiple filters are specified, they are ANDed together (so the line only gets matched if all filters have a match). 

Option 1 is easier to both implement and use, and we already have `--event` for filtering on particular events, so I'm leaning towards that. It wouldn't rule out option 2 for the future. Wdyt?

**Comment by icarus-sparry** [comment]
I would use `awk` (for table output) or `jq` (for json output) to post-process the output. Not quite as efficient but then you have a full programming language available so you can say "if it is for this utsname or this utsname then do this, else if it is for this utsname and it is an openat system call do this else ...". Whilst `find` has proved you can write arbitrary complex expressions on the command line, no one actually wants to do it.

If this enhancement is accepted then I suggest using `find` as a model and allowing both `and` and `or` operators together with grouping. Having -f name=value1,value2 as an abbreviation for `\( -f name=value1 --or -f name=value2 \)` would be nice but then the rules for escaping commas might get non obvious.

**Comment by itaysk** [comment]
I think tracee should just collect/generate events, and not process them which better be done with specialized tools like you mentioned @icarus-sparry. But I do think that @lizrice has a point specifically about hostname filtering, or if can generalize - container filtering, which I think is n important use case (I want to trace only container X) and can also be filtered in kernel. Container filtering is also discussed in https://github.com/aquasecurity/tracee/issues/21.
