### ISSUE TITLE
print_mem_dump not working

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#2902]
## Description

run `tracee-ebpf -f e=print_mem_dump -e print_mem_dump.args.symbol_name=system:security_file_open
nothing pops up

The cause is this commit:
https://github.com/aquasecurity/tracee/commit/0459ae5f937628f4d4749fc3b40a83ffff9a561a

## Output of `tracee -v`:

```
v0.10.0-73-gc8850253
```

## Output of `uname -a`:

```
Linux ubuntu 5.15.0-50-generic #56~20.04.1-Ubuntu SMP Tue Sep 27 15:51:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

## Additional details 
The `print_mem_dump` has a workaround to allow it to be submitted although the filter doesn't match:
https://github.com/aquasecurity/tracee/blob/main/pkg/filters/args.go#L50

Something happened when the multiscope was introduced that causes the event to not be printed.
The BPF code that is submitting the event is running.
The event is received by the user land process.

**Comment by rafaeldtinoco** [comment]
@geyslan u think u can check this one ?

**Comment by AsafEitani** [comment]
> There is also a special case for uprobe-related events at:
> 
> ![image](https://user-images.githubusercontent.com/7395852/226924372-715c6b36-1cb5-4d45-a2fe-3091daf24997.png)
> 
> Because the `shouldProcess()` logic could not deal with them correctly, but it makes derivative events to be sent down the pipeline (instead of trying to filter them).
> 

The print memory event is not derived, could that be the reason for the bug?

**Comment by geyslan** [comment]
Testing c88502537b3ecbf7e72069e91e97d2126a2b57eb, we have the right result:

![image](https://user-images.githubusercontent.com/3372117/227057059-0a51e1aa-be91-45f3-a274-69de602232a6.png)

In main, commenting out the args filter check, I made it print:

![image](https://user-images.githubusercontent.com/3372117/227057774-ced544d1-dedd-4f2d-b160-57d50127197e.png)

As you can see, the arguments are duplicated and the first ones are nil. It's the cause of filter failure.

**Comment by geyslan** [comment]
![image](https://user-images.githubusercontent.com/3372117/227059134-9268d6d1-29b7-48b2-8189-84581b241083.png)

For testing:

```diff
diff --git a/pkg/ebpf/events_pipeline.go b/pkg/ebpf/events_pipeline.go
index 164105ac..0ae6b06a 100644
--- a/pkg/ebpf/events_pipeline.go
+++ b/pkg/ebpf/events_pipeline.go
@@ -4,6 +4,7 @@ import (
        "bytes"
        "context"
        "encoding/binary"
+       "fmt"
        "strconv"
        "sync"
        "unsafe"
@@ -279,6 +280,8 @@ func (t *Tracee) computePolicies(event *trace.Event) uint64 {
        origMatchedPolicies := event.MatchedPolicies
        matchedPolicies := event.MatchedPolicies
 
+       fmt.Printf("event.Args: %+v\n\n", event.Args)
+
        for p := range t.config.Policies.Map() {
                bitOffset := uint(p.ID)
 
@@ -298,10 +301,10 @@ func (t *Tracee) computePolicies(event *trace.Event) uint64 {
                        continue
                }
 
-               if !p.ArgFilter.Filter(eventID, event.Args) {
-                       utils.ClearBit(&matchedPolicies, bitOffset)
-                       continue
-               }
+               // if !p.ArgFilter.Filter(eventID, event.Args) {
+               //      utils.ClearBit(&matchedPolicies, bitOffset)
+               //      continue
+               // }
```

**Comment by geyslan** [comment]
Based on the commit msg:

```
...
Now we always pass all arguments, with default `nil` value if they are
missing.
```

it can be the origin: https://github.com/aquasecurity/tracee/commit/45dd5cc0b8558c1133f617b3cf71213fda75873e#diff-243833522f012bc561e9dbe8ae288fbde4f4a41fe65c52cfba6973cf56813bacR161-R181

**Comment by geyslan** [comment]
> 	event.Args[4].Value = arch
> 	event.Args[5].Value = symbol.Name
> 	event.Args[6].Value = symbol.Owner

Even with this the bit is being cleared and when we get in sinkEvents we have:

```
event.MatchedPolicies &= t.events[id].emit
```

```shell
tracee on  main [$!] via 🐹 v1.19.7 via ⍱ v2.3.4 took 5s 
❯  cd /home/gg/code/tracee ; /usr/bin/env GOPATH=/home/gg/go/1.19.7 /usr/bin/sudo /home/gg/go/1.19.7/bin/dlv dap --client-addr=:39761 
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
event.MatchedPolicies fffffffffffffffe
t.events[id].emit 1
```

It seems an args filtering issue. I'll check it out.

**Comment by geyslan** [comment]
> It seems an args filtering issue. I'll check it out.

It's not.

We're reaching `processPrintMemDump()` at a late stage, so the filtering is being done using nil args values.

![image](https://user-images.githubusercontent.com/3372117/227206146-84fd699e-a65c-4c03-85f6-ef68acae7a26.png)

`processEvents()` must run first.

**Comment by yanivagman** [comment]
We should simply ignore argument filters for print_mem_dump.
The reason we don't need argument filter for this event is because the event itself is configured as a filter - you give it the symbol name or address, and when the event is triggered it is using these values, and only them.
Argument filter is being abused as a way to pass parameters to the event. This is why we need a new mechanism to pass parameters to events (#2576), then we will be able to do something like `print_mem_dump.**params**.symbol_name=system:security_file_open`

@AsafEitani FYI

**Comment by yanivagman** [comment]
> There is also a special case for uprobe-related events at:
> 
> ![image](https://user-images.githubusercontent.com/7395852/226924372-715c6b36-1cb5-4d45-a2fe-3091daf24997.png)
> 
> Because the `shouldProcess()` logic could not deal with them correctly, but it makes derivative events to be sent down the pipeline (instead of trying to filter them).

PrintMemDump event is not a derived event. It should be removed from this list.
