### ISSUE TITLE
feat: Improvement in release workflows 

### ISSUE THREAD

**Issue by kranurag7** [aquasecurity/tracee#2907]
With Reference to this https://github.com/aquasecurity/tracee/issues/2804 and after discussion with @developer-guy I'm opening this issue.  
As of now, We are using `crane` for getting the digest of the Image and afterwards we are using that digest for signing the image. This requires a network call to the registry. 

Here's the comment by Jon Johnson on trusting registry clients. 

> By using crane or imagetools inspect to get the digest of the image you pushed, you have to trust the registry because you pushed it by tag and are requesting it by tag. If you are man-in-the-middled or someone is able to overwrite the tag between when you pushed it and pulled it, they could serve you the digest of a malicious image.

Read more about it [here](https://sigstore.slack.com/archives/C01PZKDL4DP/p1672710585396579?thread_ts=1666895101.659899&cid=C01PZKDL4DP) in Sigstore slack. 

We should get the digest of the image without a network call to the registry. 

### Alternatives

We can use buildx for building the Image with `--metadata-file` flag and save the corresponding file on the disk and later query the digest using `jq -r '.["containerimage.digest"]' filename.json`

We can discuss other approaches as well.

**Comment by developer-guy** [comment]
you can assign it to us, we with @kranurag7 can work on this 😇 

PTAL @itaysk @rafaeldtinoco

**Comment by developer-guy** [comment]
yeah, it can work with your plans, this is just all about outputting the metadata file includes a bunch of build information as described [here](https://www.docker.com/blog/capturing-build-information-buildkit/) it helps us not to trust the network operations as we did for finding the digest instead we are going to rely on filesystem operations on disk.

**Comment by developer-guy** [comment]
as tracee builds container image locally then retag images and then push them to the registry, if we use `docker buildx` instead, the workflow has to change from beginning to end as it depends on `docker` commands heavily which means that if we use `docker buildx` we should reorganize the cycle of building, retagging and pushing stages defined in Makefiles which also means a lot of work to do because the build-push workflow will be redesigned. 

I don't think that @rafaeldtinoco is going to accept this for now. PTAL @kranurag7

**Comment by rafaeldtinoco** [comment]
@developer-guy I'd rather wait for this release (happening this week) and tackle the fixes that the current schema might need. In the next release my idea described at: https://github.com/aquasecurity/tracee/issues/2907#issuecomment-1482922243 should be "improved/developed" IMO. WDYT about that ?

I don't think we can use build for the multi-architecture build, as we need arm64 environment to build the eBPF objects etc. With that said, my idea was to build both: x64 and arm64 images and then create a multi-arch image based on the two. We could temporarily upload the images to github container repository and then upload the last image to docker hub, etc.. 

Let me know your thoughts!

**Comment by yanivagman** [comment]
Closing in favor of #2804 - let's first fix signing, then consider improvements (it is possible that improvements will be included in the fix)

**Comment by itaysk** [comment]
I'm not sure that one is in favor of the other in this case. The other issue is a bug report in image signing, this one is about security considerations in the signing process. Yes it might be that both will be closed in the same PR if that's what you meant, but should we close this issue as not planned so soon?

**Comment by yanivagman** [comment]
> I'm not sure that one is in favor of the other in this case. The other issue is a bug report in image signing, this one is about security considerations in the signing process. Yes it might be that both will be closed in the same PR if that's what you meant, but should we close this issue as not planned so soon?

I thought that the solution of using the image digest given by docker instead of using crane will resolve both issues, but I get your point for keeping this one open as well. Reopening then.
