### ISSUE TITLE
Add Amazon2 5.4 Kernel to PR workflows

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#2915]
Just as we did with Amazon2 5.10 and gke, we should add this missing kernel to our workflows to ensure no regression happens in AWS.

**Comment by rafaeldtinoco** [comment]
@NDStrahilevitz could you point me out the AMI containing the 5.4 kernel you would like to be tested ? I could not find an AMZN2 image with 5.4 kernel, the default ones are all 5.10 and in the community workspace I couldn't find a specific 5.4 HVM AMI.

**Comment by yanivagman** [comment]
These AMIs are not supported anymore
