### ISSUE TITLE
Docs: List supported OS

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#2929]
It would be great to have a list of OS and environments e.g. Kubernetes clusters listed in the Prerequisites section
https://aquasecurity.github.io/tracee/v0.12/getting-started/installing/prerequisites/

**Comment by yanivagman** [comment]
@AnaisUrlichs I think this was already done?
https://aquasecurity.github.io/tracee/dev/docs/install/prerequisites/
