### ISSUE TITLE
libbpf print output is raw and escaped

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2950]
## Description

As reported in aquasecurity/libbpfgo#313 and discussed in aquasecurity/libbpfgo#312, the output of libbpf is an escaped string.

Tracee logger is based on zap which uses a json structure format which cannot interpret escaped strings uber-go/zap#963.

After discussion we raised the issue https://github.com/aquasecurity/tracee/issues/3035 to be the focal point of the new logger feature `--log filter`.

For now, as we have bumped the libbpfgo to `v0.4.8-libbpf-1.2.0`, this issue can be solved with:

- [x] remove suffix "\n" from libbpf msg before logging.

## Output of `tracee -v`:

```
Tracee version "v0.8.3-596-ge1018ba3"
```

## Output of `uname -a`:

```
Linux hb 6.2.7-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Mar 18 17:15:16 UTC 2023 x86_64 GNU/Linux
```

## Additional details 

Next step is https://github.com/aquasecurity/tracee/issues/3035.

**Comment by rafaeldtinoco** [comment]
Couldn't play with this one before the release. Maybe we can include it in the buf fix release right after (1st week).
