### ISSUE TITLE
tracee cmdline output (help, list events, list signatures) should have tabled output

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2972]
Instead of having very long lines when using the cmdline, Tracee should use tables (https://github.com/aquasecurity/table) and have line breaks inside a box for the option, so the output is readable.

Example. Instead of:

![image](https://user-images.githubusercontent.com/7395852/229629118-2071d90a-09a0-4645-82f9-ac5d35a28889.png)

Something like:

![image](https://user-images.githubusercontent.com/7395852/229629153-a7fcc585-8083-447d-ac45-fb64b74cd5fa.png)

**Comment by yanivagman** [comment]
This output is of urfave, not sure we can (and want?) to do such a change to table output.
Maybe there is an option to align long lines with the start of the first line so that only the flags are in the left part and explanation in the right?

**Comment by rafaeldtinoco** [comment]
About "can do it".. maybe my example wasn't so good, but the same applies to the event listing, for example, which is a string that we control.

About "want to do it", then it is up to you, I think it is a good idea if someone wants to implement (thus the "good first issue" label). Feel free to close this if you think its not worth.

**Comment by itaysk** [comment]
some thoughts:
1. I think virtually every cli tool I know uses this help format so I don't think it's was hurdle for adoption
2. tables are hard to maintain in different terminal sizes. we are having these issues in trivy all the time (the trivy help is still line-oriented but the result output is table).
3. online docs might be better place to experiment with creative layouts of docs

**Comment by yanivagman** [comment]
> 1. I think virtually every cli tool I know uses this help format so I don't think it's was hurdle for adoption

+1
Also, we just switched to cobra, which is used by many CLI tools written in go.

> Feel free to close this if you think its not worth.

So if you don't mind, will do.
