### ISSUE TITLE
Tracee for ARM32 

### ISSUE THREAD

**Issue by rohitburke** [aquasecurity/tracee#2990]
Like, For now, we know Tracee start supporting ARM64 architecture but will it update to ARM32 because most of the IoT devices have ARM32 architecture. So, it will be great if Tracee gets support for ARM32 in an upcoming version.

**Comment by rohitburke** [comment]
Like, For now, the latest version of Tracee supports ARM64. But as you know that most IoT devices support ARM32. So, will Tracee in the upcoming version start supporting ARM32. That will be great if it gets done

**Comment by yanivagman** [comment]
There are currently no plans to add support for ARM32, unless there will be such contribution from the community
