### ISSUE TITLE
errfmt: prefixFunc only need to prefix at debug level

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2992]
`prefixFunc` always prefix the msg error with the function name, but it's an information required only for debug level.

https://github.com/aquasecurity/tracee/blob/90f56d07ee7e6bb17acf861997aefe2dc327985c/pkg/errfmt/errfmt.go#L22-L26

**Comment by rafaeldtinoco** [comment]
> but it's an information required only for debug level.

Is it ? What about an error you can't reproduce and user is willing to help by saying "I got this error" and you don't have a clue where the origin is (this is what was happening).

Maybe we can have smaller, but, still, position informative information. Software vendors use error codes usually (Error: XXXXXX (Code: 432432)). Maybe we can have something like that so users, who don't run tracee in debug mode, that can't reproduce an issue at will, are still able to inform us where the error came from.

Just thinking out loud. I think the change of having the error origin is very good to get rid of it (even in non debug mode). For me, debug is for "tracing purposes" as well. Errors should always be informative about what it means and its origins.

**Comment by geyslan** [comment]
Sorry, I didn't make the issue so clear. The intent is to prefix the function name with whatever `logger.{Debug,Error,Warn}w` helper is used, but only when the `LoggerConfig.Level` is Debug. So, in default level - Info, for instance, any log output, even if the errfmt is used, won't prefix anything. But any use of the errfmt helpers will behave like it behaves today only when debug level is set.

See my current implementation (with a false additional logger.Warnw to exemplify):

```shell
tracee on  2992-prefix-debug [$!] via 🐹 v1.19.7 via ⍱ v2.3.4 took 39s 
❯ sudo ./dist/tracee -f comm=uname --log warn 
{"level":"warn","ts":1681144933.57907,"msg":"Enricher","error":"error registering enricher: unsupported runtime crio"}
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
```

```shell

tracee on  2992-prefix-debug [$!] via 🐹 v1.19.7 via ⍱ v2.3.4 took 4s 
❯ sudo ./dist/tracee -f comm=uname --log debug
Place your finger on the fingerprint reader
{"L":"DEBUG","T":"2023-04-10T13:41:32.175-0300","M":"OSInfo","PRETTY_NAME":"\"Manjaro Linux\"","ID":"manjaro","ID_LIKE":"arch","BUILD_ID":"rolling","KERNEL_RELEASE":"6.2.9-1-MANJARO","ARCH":"x86_64","origin":"urfave:pkg/cmd/urfave/urfave.go:69","calls":"GetTraceeRunner() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
...
{"L":"WARN","T":"2023-04-10T13:41:32.382-0300","M":"Enricher","error":"containers.(*runtimeInfoService).Register: error registering enricher: unsupported runtime crio"}
{"L":"DEBUG","T":"2023-04-10T13:41:32.382-0300","M":"Enricher","error":"containers.(*runtimeInfoService).Register: error registering enricher: unsupported runtime crio","origin":"containers:pkg/containers/containers.go:72","calls":"New() < (*Tracee).Init() < Runner.Run() < main.func1() < (*App).RunContext() < (*App).Run() < main()"}
```

You can see that even any logger helper will continue to provide the metadata when the level is set to Debug but will have a clean output on the other hand.

So the user would have an clean output in general use and when helping/trying to solve the problem should run with debug level set. WDYT?

**Comment by rafaeldtinoco** [comment]
Yep, I got that from the issue description also. My point is that super clear error messages are good for nothing if we don't know its origin (when having an issue opened by someone not willing to test things with debug option enabled or incapable of reproducing the issue again). 

So, maybe add an error code to the messages with filename and number ? Something we can identify the error origin even without all the debug level messages.

**Comment by geyslan** [comment]
As discussed, not planned.
