### ISSUE TITLE
Complete before release

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#300]
Before we can release 0.3.0, we need to address the following:

- [x] Fix compilation in ubuntu 16.04: Need to add "-I 3rdparty/libbpf/include/uapi" to the go build command (libbpf is trying to find "enum bpf_attach_type" which is defined there) 
- [x]  Fix compilation in ubuntu 20.04: Workaround "asm_inline" error from kernel 5.4.
- [x]  Warn user and don't compile if llvm version < 7.0
- [x]  Add output when "make build-docker" is used, otherwise, it seems that the command is hanged
- [x]  Build BPF object when using "make build-docker". This is needed, as tracee will try to call clang if bpf object is not compiled, and that might not work if the user doesn't have clang installed, or has an old clang version
- [x]  Set libbpfgo as a go module
- [x]  Set bpf filename to include kernel version and matching tracee version, and check for a match on start
- [x]  Fix bpf build on arch based distros

**Comment by itaysk** [comment]
hope you don't mind, I've turned this into a checklist

**Comment by itaysk** [comment]
actualy, it would have been better to create each item as an issue, and then associate them with a milestone v0.3.0. that way we can discuss each item and maybe remove from the milestone without losing the item. No need to add unnecessary formality now, just making a note for next time

**Comment by itaysk** [comment]
I don't think this is required for release, right?
> Add output when "make build-docker" is used, otherwise, it seems that the command is hanged

**Comment by itaysk** [comment]
> Build BPF object when using "make build-docker"

I think it will be confusing if `make build` and `make build-docker` will produce different results. if the user can't build using `make bpf`, then we can add a `make bpf-docker` to follow the same convention. alternatively we can change the `make build-docker` step to be more like `make all-docker`. wdyt?

**Comment by yanivagman** [comment]
> I don't think this is required for release, right?

I think it is.
If people are going to build from source, the best way to do that is using build-docker, which has a reproducible environment for the build. When using it now, it seems that its just stuck. I think we should change it before the release

**Comment by yanivagman** [comment]
> I think it will be confusing if `make build` and `make build-docker` will produce different results. if the user can't build using `make bpf`, then we can add a `make bpf-docker` to follow the same convention. alternatively we can change the `make build-docker` step to be more like `make all-docker`. wdyt?

I agree these two should be the same.
I think that by default, both "make" and "make build-docker" should build both tracee binary and the bpf object.

The reason why we build the bpf object in the tracee binary is for us to be able to release a standalone binary.
On the otherhand, If building from source, there are 3 reasons to build bpf code using make:
1. Users will be able to build it inside the docker container in a reproducible way
2. No clang will be required at runtime, meaning less dependencies and less security risks
3. Cross compilation environments (android), where clang is not available at runtime
