### ISSUE TITLE
golang updates: updating dependencies to latest brakes --filter event=aaa,bbb (comma usage)

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3033]
## Description

```
$ go get -u ./...
```
then
```
$ sudo ./dist/tracee-ebpf --filter event=$(./dist/tracee-rules --list-events TRC-107)
{"level":"fatal","ts":1683088413.7106009,"msg":"App","error":"invalid filter option specified (hooked_syscalls), use '--filter help' for more info"}
```

I'm currently releasing v0.14.0 (was trying to update dependencies but couldn't because of this).

**Comment by yanivagman** [comment]
Not sure it's related to the golang deps. I'm seeing this issue in main while using the unified binary

**Comment by rafaeldtinoco** [comment]
There might be two issues, as I was able to reproduce that issue by using `tracee-ebpf` and you just reported a similar (or the same) issue for `tracee` single binary.

For the `trace` single binary situation, it happens because of cobra. Check the difference for the cmdline parsing:

![image](https://user-images.githubusercontent.com/7395852/236379622-14372766-3a17-48fc-8a95-ec0fdbd30483.png)

I'm checking a "good" way to keep things working as well as keeping compatibility with existing urfave code.

**Comment by rafaeldtinoco** [comment]
@josedonizetti and/or @geyslan, what did you have in mind when doing the cobra filter parsing ? I can see that if you give the following command line:

```
--filter event=one,two
```

It won't concatenate `one,two` but it will have two strings: `event=one,two`. Did you expect the user to set one filter per operator and per event ? Something like:

```
--filter event=one --filter event=two --filter event!=three
```

Is that it ? Because I can "concatenate" the next arguments into the previous event + operator, but I'm not sure that is what you had planned.

**Comment by rafaeldtinoco** [comment]
Also, I'm not sure the single binary is behaving like it should for filters... I created a function to deal with the issue I described above.. but the filters don't look like they're being applied correctly:

tracee-ebpf: no events (comm=cmd01 does not exist)

```
$ sudo ./dist/tracee-ebpf --filter event=openat --filt
er comm=cmd01
filter: event=openat
filter: comm=cmd01
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
```

tracee: events (comm=cmd01 is ignored ?)

```
$ sudo ./dist/tracee --filter event=openat --filter co
mm=cmd01
filter: event=openat
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
03:02:37:546371  1000   node             976478  976478  24               openat                    dirfd: -100, pathname: /proc/1012358/cmdline, flags: , mode: 0
03:02:37:546484  1000   node             976478  976478  24               openat    
```

**Comment by rafaeldtinoco** [comment]
Proposed https://github.com/aquasecurity/tracee/pull/3057 to address this issue (of having multiple slice items in string arrays when using comma).

**Comment by rafaeldtinoco** [comment]
So, this wasn't solved for "tracee-ebpf". After updating the packages, right after the #3058 was merged, I still get:

```
$ sudo ./dist/tracee-ebpf --filter event=getuid,umount,net
_packet_dns --filter event!=openat,readdir --filter event=net_packet_http --filter comm=sh --fi
lter comm=ping
{"level":"fatal","ts":1683313055.2694995,"msg":"App","error":"invalid filter option specified (umount), use '--filter help' for more info"}
```

Investigating...

**Comment by rafaeldtinoco** [comment]
Alrignt, urfave has included an option for parsing the separator. I was able to make it work like it should with a simple change:

```
rafaeldtinoco@fujitsu:tracee-libbpfgo$ sudo ./dist/tracee --filter event=getuid,umount,net_pack
et_dns --filter event!=openat,readdir --filter event=net_packet_http --filter comm=sh --filter 
comm=ping
filtersArr: [event=getuid,umount,net_packet_dns event!=openat,readdir event=net_packet_http comm=sh comm=ping]
Killed
rafaeldtinoco@fujitsu:tracee-libbpfgo$ 
rafaeldtinoco@fujitsu:tracee-libbpfgo$ sudo ./dist/tracee-ebpf --filter event=getuid,umount,net
_packet_dns --filter event!=openat,readdir --filter event=net_packet_http --filter comm=sh --fi
lter comm=ping
filtersArr: [event=getuid,umount,net_packet_dns event!=openat,readdir event=net_packet_http comm=sh comm=ping]
Killed
```

Sending a PR.

**Comment by rafaeldtinoco** [comment]
https://github.com/aquasecurity/tracee/pull/3067
