### ISSUE TITLE
Create `--log filter`, `--log filter-out` options

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#3035]
> As the team discussed today, we agreed to use a single base logger, as it already is, but implement --log filter options, such as for packages or raw strings. It would answer all needs.

Possible options:

- `--log filter:msg=somemsg1` (outputs logs containing somemsg1)
- `--log filter:msg=somemsg1,somemsg2` (outputs logs _containing_ somemsg1 or somemsg2)
- `--log filter:pkg=somepkg2,somepkg2` (outputs logs originated in somepkg1 or somepkg2)
- `--log filter:file=somefile1,somefile2` (outputs logs originated in somefile1 or somefile2)
- `--log filter:libbpf` (outputs logs originated in libbpf - tackle verifier formatted output as well)

`filter-out` should have the same options. 

Context: https://github.com/aquasecurity/tracee/issues/2823 #2950

**Comment by geyslan** [comment]
@yanivagman @rafaeldtinoco @josedonizetti What do you think of the options proposed above?

**Comment by rafaeldtinoco** [comment]
Do we have to pick one ? Or you want to implement all of them ? I would go for "all of them" then I consider it very very cool.

**Comment by rafaeldtinoco** [comment]
I like the syntax. Can I mix things ?

--log filter:pkg=somepkg1,msg=somemsg1 ?

**Comment by geyslan** [comment]
> I like the syntax. Can I mix things ?
> 
> --log filter:pkg=somepkg1,msg=somemsg1 ?

Yep. Mixing is doable.

**Comment by rafaeldtinoco** [comment]
I am +1 then, looks very helpful IMO.

**Comment by geyslan** [comment]
> Am I correct in understanding that the filters declare which logs _will_ appear and not which will be filtered out? If so then I think it should be the opposite. Simply put, currently I have to know which logs I want _ahead_ of time, which is odd since logs are usually discovered and not known ahead. Let's say I run in some log level, it's reasonable to assume that I would like to see all messages of that level and not have to know which to select and which not to select. If there is some message in particular that spams my system for example I would like to filter out only that one in particular.

`"filter:pkg=somepkg1,pkg3;msg=somemsg1,msg2;file=ola,ole;libbpf;file=oie,oia;pkg=pkg5"`

would show only what is set.

`"filter-out:pkg=somepkg1,pkg3;msg=somemsg1,msg2;file=ola,ole;libbpf;file=oie,oia;pkg=pkg5"`

would show all but what is set.

**Comment by rafaeldtinoco** [comment]
>  If so then I think it should be the opposite. Simply put, currently I have to know which logs I want ahead of time, which is odd since logs are usually discovered and not known ahead.

Yep, usually for "DEBUG" this is true but not for INFO or ERRORS. A good example of the same functionality is libvirt (https://libvirt.org/kbase/debuglogs.html) and, as you can see there:

![image](https://github.com/aquasecurity/tracee/assets/7395852/12ed5764-380a-480b-84be-f7937e48cdf1)

you can include something like "pkg" and then "pkg.area", you can select files and also the log level you want. And they're all interdependent (info:pkg01, debug:pkg03, ...). Now saying we should do that, just showing knowing what you want in advance is a known and used use case as well.

So, filter and filter-out might be a nice way of achieving that.

**Comment by NDStrahilevitz** [comment]
As long as we don't specify filters everything passes right? If that stays the same i'm okayish with this.
@rafaeldtinoco  the example seems relevant for component filtering which would be known ahead of time usually but the qEMU example you've shown if I understand correctly filters by components and not by message which is the case we have here with the filter.
filter in for package does seems reasonable, but filtering in messages by default, which have much more variety, less so.

**Comment by geyslan** [comment]
> As long as we don't specify filters everything passes right? If that stays the same i'm okayish with this.

Yep.
