### ISSUE TITLE
Tracee doesn't exit when using syscalls set

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#3039]
## Description

When using the syscalls set and trying to terminate tracee with CTRL+C it never terminates
Command used:
`sudo ./dist/tracee -f set=syscalls`

## Output of `tracee -v`:

```
v0.14.0
```

## Output of `uname -a`:

```
(paste your output here)
```

## Additional details 

Potentially related (didn't test): https://github.com/aquasecurity/tracee/pull/2969

**Comment by geyslan** [comment]
Tested with `-f set=fs`, `--metrics --pprof` and after flagging the cancellation, both metrics and pprof are unavailable, which indicates that the hang is after these terminations.

**Comment by geyslan** [comment]
Most significant goroutines still running after cancel signal:

```
  Goroutine 1 - User: ./pkg/cmd/printer/broadcast.go:34 github.com/aquasecurity/tracee/pkg/cmd.Runner.Run (0x1a24de5) [chan send]
  Goroutine 16 - User: ./pkg/ebpf/events_pipeline.go:564 github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).WaitForPipeline (0x1998705) [chan receive 90186207389350]
  Goroutine 26 - User: /home/gg/.goenv/versions/1.19.7/src/net/fd_posix.go:55 net.(*netFD).Read (0xe96ee9) [IO wait 90185493148528]
  Goroutine 49 - User: /home/gg/.goenv/versions/1.19.7/src/net/fd_posix.go:55 net.(*netFD).Read (0xe96ee9) [IO wait 90185493148528]
  Goroutine 69 - User: ./pkg/ebpf/events_pipeline.go:455 github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).deriveEvents.func1 (0x1997db6) [chan send]
  Goroutine 87 - User: ./pkg/ebpf/signature_engine.go:63 github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).engineEvents.func1 (0x199f5ce) [chan send]
  Goroutine 92 - User: ./pkg/ebpf/events_pipeline.go:582 github.com/aquasecurity/tracee/pkg/ebpf.MergeErrors.func1 (0x1998a54) [chan receive 90186207389350]
  Goroutine 93 - User: ./pkg/ebpf/events_pipeline.go:582 github.com/aquasecurity/tracee/pkg/ebpf.MergeErrors.func1 (0x1998a54) [chan receive 90186207389350]
```

I'll dive into that TOM.

**Comment by rafaeldtinoco** [comment]
> Using the regular stack trace output and chatGPT:

Based on the given stack trace, the deadlock seems to be occurring in the goroutine 1 and goroutine 6, which are both trying to send data to the same channel, `c00072b500`. The `runtime.chansend` function is blocking both goroutines because they're both trying to send data to the same channel at the same time, and there's no available receiver for the channel.

Here are the relevant parts of the stack trace:

Goroutine 1:
```
goroutine 1 [chan send]:
runtime.chansend(0xc00072b500, 0xc002a876e0, 0x1, 0x0?)/usr/lib/go-1.20/src/runtime/chan.go:259 +0x42e fp=0xc002a87558 sp=0xc002a874d0 pc=0xbca5ae
runtime.chansend1(0xc0001cc500?, 0x2b32798?)/usr/lib/go-1.20/src/runtime/chan.go:145 +0x1d fp=0xc002a87588 sp=0xc002a87558 pc=0xbca15d
```

Goroutine 6:
```
goroutine 6 [chan send]:
runtime.chansend(0xc00072b500, 0xc000a75ca0, 0x1, 0x2?)/usr/lib/go-1.20/src/runtime/chan.go:259 +0x42e fp=0xc000a75bd8 sp=0xc000a75b50 pc=0xbca5ae
runtime.chansend1(0xc000a75c80?, 0xc000a75c40?)/usr/lib/go-1.20/src/runtime/chan.go:145 +0x1d fp=0xc000a75c08 sp=0xc000a75bd8 pc=0xbca15d
```

To resolve this deadlock, you might consider using a buffered channel with a capacity greater than 1, or introduce another goroutine that listens on the channel and processes the received data, so that the senders are not blocked.

**Comment by geyslan** [comment]
@rafaeldtinoco huge thanks for you analysis. I've detected the offending commit via bisect: (1b5abef fix go routines leaks).

**Comment by rafaeldtinoco** [comment]
We discussed it offline, and just updating my last comment: it just changes the behavior, and the lock still happens after some time of Tracee running. We identified a blocked wg.Done() and Geyslan is investigating and fixing it. Sorry for the noise Geyslan =D

**Comment by geyslan** [comment]
Not at all @rafaeldtinoco. Tks for your help. I was rubber ducking with @josedonizetti and we possibly identified a part of the problem. When broadcast was created we didn't drain yet the channel, so using context was safe. But now we need it until the last breath (last event drained/printed).

This is a test that didn't solve the blocking but reduced the go routines trying to send/receive to the same channel. I'm still investigating.

```diff 
diff --git a/pkg/cmd/printer/broadcast.go b/pkg/cmd/printer/broadcast.go
index f2f11f65..16c7f1be 100644
--- a/pkg/cmd/printer/broadcast.go
+++ b/pkg/cmd/printer/broadcast.go
@@ -1,19 +1,19 @@
 package printer
 
 import (
-	"context"
-
 	"github.com/aquasecurity/tracee/types/trace"
 )
 
 // Broadcast is a printer that broadcasts events to multiple printers
 type Broadcast struct {
 	eventsChan []chan trace.Event
+	done       chan struct{}
 }
 
 // NewBroadcast creates a new Broadcast printer
-func NewBroadcast(ctx context.Context, printers []EventPrinter) *Broadcast {
+func NewBroadcast(printers []EventPrinter) *Broadcast {
 	eventsChan := make([]chan trace.Event, 0, len(printers))
+	done := make(chan struct{})
 
 	for _, printer := range printers {
 		// we use a buffered channel to avoid blocking the event channel,
@@ -21,10 +21,13 @@ func NewBroadcast(ctx context.Context, printers []EventPrinter) *Broadcast {
 		eventChan := make(chan trace.Event, 1000)
 		eventsChan = append(eventsChan, eventChan)
 
-		go startPrinter(ctx, eventChan, printer)
+		go startPrinter(done, eventChan, printer)
 	}
 
-	return &Broadcast{eventsChan: eventsChan}
+	return &Broadcast{
+		eventsChan: eventsChan,
+		done:       done,
+	}
 }
 
 // Print broadcasts the event to all printers
@@ -35,16 +38,20 @@ func (b *Broadcast) Print(event trace.Event) {
 	}
 }
 
-func startPrinter(ctx context.Context, c chan trace.Event, p EventPrinter) {
+func (b *Broadcast) Close() {
+	close(b.done)
+}
+
+func startPrinter(done chan struct{}, c chan trace.Event, p EventPrinter) {
 	// Print the preamble and start event channel reception
 	p.Preamble()
 
 	for {
 		select {
+		case <-done:
+			return
 		case event := <-c:
 			p.Print(event)
-		case <-ctx.Done():
-			return
 		}
 	}
 }
diff --git a/pkg/cmd/tracee.go b/pkg/cmd/tracee.go
index e3403ed9..d1b1e802 100644
--- a/pkg/cmd/tracee.go
+++ b/pkg/cmd/tracee.go
@@ -57,7 +57,7 @@ func (r Runner) Run(ctx context.Context) error {
 		return errfmt.Errorf("error initializing Tracee: %v", err)
 	}
 
-	broadcast := printer.NewBroadcast(ctx, r.Printers)
+	broadcast := printer.NewBroadcast(r.Printers)
 
 	// Start event channel reception
 	go func() {
@@ -80,6 +80,7 @@ func (r Runner) Run(ctx context.Context) error {
 		case event := <-r.TraceeConfig.ChanEvents:
 			broadcast.Print(event)
 		default:
+			broadcast.Close()
 			return err
 		}
 	}
```

**Comment by geyslan** [comment]
Ok, let gpt help us.

Providing delve output to gpt it tolds us:

> From the stack trace, we can see that Goroutine 1 is waiting to acquire a semaphore, which is causing the application to block. This can happen if the semaphore is held by another Goroutine and hasn't been released yet. The other Goroutines seem to be in various states, waiting for garbage collection, finalization, or idle, so they are not directly causing the application to block.

> Goroutines 20 and 22 seem to be executing user code and are not in a blocked state. These could be potential areas of focus for further investigation.

> Additionally, Goroutines 25, 28, 30, and 32 seem to be executing system code related to perfbuf, which could also be potential areas of focus for further investigation.

This is a summarised delve output:

```
  Goroutine 1 - User: /home/gg/.goenv/versions/1.19.7/src/runtime/sema.go:62 sync.runtime_Semacquire (0xcc0805) [semacquire]

   0  0x0000000000c91e36 in runtime.gopark
    at /home/gg/.goenv/versions/1.19.7/src/runtime/proc.go:364
 1  0x0000000000ca339e in runtime.goparkunlock
    at /home/gg/.goenv/versions/1.19.7/src/runtime/proc.go:369
 2  0x0000000000ca339e in runtime.semacquire1
    at /home/gg/.goenv/versions/1.19.7/src/runtime/sema.go:150
 3  0x0000000000cc0805 in sync.runtime_Semacquire
    at /home/gg/.goenv/versions/1.19.7/src/runtime/sema.go:62
 4  0x0000000000cd36d2 in sync.(*WaitGroup).Wait
    at /home/gg/.goenv/versions/1.19.7/src/sync/waitgroup.go:139
 5  0x000000000136bee7 in github.com/aquasecurity/libbpfgo.(*PerfBuffer).Stop
    at /home/gg/go/1.19.7/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.8-libbpf-1.2.0/libbpfgo.go:1894
 6  0x00000000019a9685 in github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).Run
    at ./pkg/ebpf/tracee.go:1538
 7  0x0000000001a249e7 in github.com/aquasecurity/tracee/pkg/cmd.Runner.Run
    at ./pkg/cmd/tracee.go:75


  // executing user code and are not in a blocked state
  Goroutine 20 - User: /home/gg/go/1.19.7/pkg/mod/google.golang.org/grpc@v1.53.0/balancer_conn_wrappers.go:115 google.golang.org/grpc.(*ccBalancerWrapper).watcher (0x1500f33) [select 139149764238268]
  Goroutine 22 - User: ./pkg/cmd/printer/broadcast.go:51 github.com/aquasecurity/tracee/pkg/cmd/printer.startPrinter (0x18d6f19) [select]


  Goroutine 25 - User: _cgo_gotypes.go:1751 github.com/aquasecurity/libbpfgo._Cfunc_perf_buffer__poll (0x135ff8c) [chan send]
  Goroutine 28 - User: _cgo_gotypes.go:1751 github.com/aquasecurity/libbpfgo._Cfunc_perf_buffer__poll (0x135ff8c) (thread 741656)
  Goroutine 30 - User: _cgo_gotypes.go:1751 github.com/aquasecurity/libbpfgo._Cfunc_perf_buffer__poll (0x135ff8c) (thread 741662)
  Goroutine 32 - User: /home/gg/go/1.19.7/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.8-libbpf-1.2.0/libbpfgo.go:1883 github.com/aquasecurity/libbpfgo.(*PerfBuffer).Stop.func1 (0x136bfb9) [chan receive]
```

As it affirms `Goroutine 1 is waiting to acquire a semaphore, which is causing the application to block.`, we can notice that this goroutine is a wait group wait in libbpfgo.PerfBuffer.Stop:

https://github.com/aquasecurity/libbpfgo/blob/0238ec325a967ca48d8958f449e236b5bc432263/libbpfgo.go#L1894

![image](https://user-images.githubusercontent.com/3372117/236333667-1eccd06a-0594-4d82-8d73-3853ae295c33.png)

And finally when it tells us `Additionally, Goroutines 25, 28, 30, and 32 seem to be executing system code related to perfbuf, which could also be potential areas of focus for further investigation.`, we notice that all of them are also corelated to libbpfgo, mainly the gr 32 that's in a chan receive in (libbpfgo.PerfBuffer.Stop):

https://github.com/aquasecurity/libbpfgo/blob/0238ec325a967ca48d8958f449e236b5bc432263/libbpfgo.go#L1883-L1884

![image](https://user-images.githubusercontent.com/3372117/236333850-8989c237-0e02-4b48-a360-607e69dca694.png)

**Comment by josedonizetti** [comment]
Okay, there are two deadlocks introduced.

The first deadlock was because of the [drain context](https://github.com/aquasecurity/tracee/pull/2969), it didn't considered that the Broadcast was closed with the context, and tried to print after the context was done. On the PR https://github.com/aquasecurity/tracee/pull/3059 @geyslan already created a commit to fix this.

The second deadlock is indeed because of the [go routine leak fix](https://github.com/aquasecurity/tracee/commit/1b5abef41bcc67b7952091a899f4ba17477bddf3), specifically the line [go t.processLostEvents(ctx)](https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/tracee.go#L1497).

When we call `Stop` on the perfbuffer, https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/tracee.go#L1523, it close the `stop` channel, and start to wait on the `WaitGroup` for the `pool` to finish, but the pool is never finishing, because when we create the perfbuffer we pass a function to [consume lost events that writes on the `lostChan`](https://github.com/aquasecurity/libbpfgo/blob/main/libbpf_cb.go#L23), but since we introduced the context into the function to consume events, there is no one on the other side to consume the events, which blocks the writing, and the `poll` function never returns.

To test this, remove this line and try tracee again: https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_processor.go#L53
