### ISSUE TITLE
policies are not applied to userspace events

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#3108]
## Description

in userspace events, there's no `matchedPolicies` field.

for example:
`{"timestamp":1684165773241016251,"threadStartTime":0,"processorId":0,"processId":0,"cgroupId":0,"threadId":0,"parentProcessId":0,"hostProcessId":0,"hostThreadId":0,"hostParentProcessId":0,"userId":0,"mountNamespace":0,"pidNamespace":0,"processName":"tracee-ebpf","hostName":"","container":{},"kubernetes":{},"eventId":"2013","eventName":"init_namespaces","argsNum":10,"returnValue":0,"syscall":"","stackAddresses":null,"contextFlags":{"containerStarted":false,"isCompat":false},"args":[{"name":"cgroup","type":"u32","value":4026531835},{"name":"ipc","type":"u32","value":4026531839},{"name":"mnt","type":"u32","value":4026531841},{"name":"net","type":"u32","value":4026531840},{"name":"pid","type":"u32","value":4026531836},{"name":"pid_for_children","type":"u32","value":4026531836},{"name":"time","type":"u32","value":4026531834},{"name":"time_for_children","type":"u32","value":4026531834},{"name":"user","type":"u32","value":4026531837},{"name":"uts","type":"u32","value":4026531838}]}`
`{"timestamp":0,"threadStartTime":0,"processorId":0,"processId":0,"cgroupId":0,"threadId":0,"parentProcessId":0,"hostProcessId":0,"hostThreadId":0,"hostParentProcessId":0,"userId":0,"mountNamespace":0,"pidNamespace":0,"processName":"","hostName":"","container":{},"kubernetes":{},"eventId":"2017","eventName":"hooked_syscalls","argsNum":1,"returnValue":0,"syscall":"","stackAddresses":[0],"contextFlags":{"containerStarted":false,"isCompat":false},"args":[{"name":"hooked_syscalls","type":"[]trace.HookedSymbolData","value":[]}]}`
`{"timestamp":0,"threadStartTime":0,"processorId":0,"processId":0,"cgroupId":0,"threadId":0,"parentProcessId":0,"hostProcessId":0,"hostThreadId":0,"hostParentProcessId":0,"userId":0,"mountNamespace":0,"pidNamespace":0,"processName":"","hostName":"","container":{},"kubernetes":{},"eventId":"2018","eventName":"hooked_seq_ops","argsNum":1,"returnValue":0,"syscall":"","stackAddresses":[0],"contextFlags":{"containerStarted":false,"isCompat":false},"args":[{"name":"hooked_seq_ops","type":"map[string]trace.HookedSymbolData","value":{}}]}`

## Output of `tracee version`:

```
(paste your output here)
```

0.14.1

## Output of `uname -a`:

```
(paste your output here)
```

**Comment by yanivagman** [comment]
Specifically `init_namespaces` "event" can become a data source after merging https://github.com/aquasecurity/tracee/pull/3026
For other events triggered in userspace- agree

**Comment by roikol** [comment]
> Can you please provide the policy/policies you worked with to get this output? Can it be that you had some filters that caused policies not to be matched? From what I understand, the `event.MatchedPolicies` (the bitmap) was not zero since we intialize it in BPF code to `ULONG_MAX` to match all policies, as we do for all user triggered events (maybe we should change that?), however, `event.MatchedPoliciesNames` was empty, which will cause the field to be omitted in the output, yet being printed (since `shouldProcessEvent` only checks for `event.MatchedPolicies` not being equal to zero). So it can be that some filter in your policy caused the event not to be matched to the scope (the context of userspace events, as you can see from the output you provided, is not initialized to anything, which will cause policies that have filters not to be matched)

the policy i used didn't have a filter on the `init_namespaces` event.
this event is not generated from BPF code, it is generated in userspace, maybe that's why its `event.MatchedPolicies` bitmap is zero (https://github.com/aquasecurity/tracee/blob/main/pkg/events/usermode.go#L36).
(i tried setting it to `1` in this func, but it didn't help)

**Comment by yanivagman** [comment]
The filter that is relevant here is not an event filter but scope filter. Did you have any?

**Comment by roikol** [comment]
> The filter that is relevant here is not an event filter but scope filter. Did you have any?

i didn't use any scope filter. 
this is the start of the policy (i have more events in my policy):

```
name: general policy
description: general policy
scope:
  - global
defaultAction: log
rules:
  - event: init_namespaces
......
```
