### ISSUE TITLE
Expose Tracee information to signatures

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#3153]
Information about Tracee is useful to signatures trying to protect Tracee.
We should expose at least Tracee's PID to signatures.
This could be done using the new [data source feature](#3142)

**Comment by AlonZivony** [comment]
I think that information about Tracee's BPF maps and programs would be good as well (for example, maps IDs in the kernel)

**Comment by yanivagman** [comment]
This is not relevant anymore since we move to one tracee binary that includes the signatures in it
