### ISSUE TITLE
The output option supports output file dump

### ISSUE THREAD

**Issue by caoliwu** [aquasecurity/tracee#3160]
When I use the "--output" option of tracee (for example, --table:/opt/tracee/tracee.log), tracee records the event information to a local file.
When the trace task lasts for a long time, for example, one or two days, the size of the local file may reach 100 GB. As a result, the disk space of the local computer is insufficient. Currently, the trace task does not support dump.
I hope that the "--output" option of tracee can support dumping when recording information to a local file. For example, if a 1 GB file is recorded, use gzip to compress the file and create a new file to record event tracing information.

**Comment by josedonizetti** [comment]
@caoliwu I'm not sure tracee should support it, perhaps using fluentbit/fluentd for file dump, as tracee can send data for them using the forward protocol?

**Comment by caoliwu** [comment]
@josedonizetti I solve my problem by using pipe. I export tracee output to a script through a pipe, and then in the script, I calculate the size of the output in the script, and compress the output when the size reaches the upper limit.

**Comment by rafaeldtinoco** [comment]
@caoliwu make sure to create a post or something like it and share with us (and/or even paste the URL in this issue, for reference). I'm closing this then (based on the discussion).

**Comment by caoliwu** [comment]
@rafaeldtinoco the script source code as follow：

#!/bin/bash
MaxLine=100
CurLine=0
logNum=0
WaitSeconds=120
OutPutFileName="output"
SubDir=$(date +%Y%m%d%H%M%S)
OutPutDir="/var/log/tracee_output/${SubDir}"
function DumpFile()
{
    echo "$(date '+%Y-%m-%d %H:%M:%S:%N') log ${logNum} start parse 1"  >>  "${OutPutDir}/log.txt" 
    /tracee/parse_merge "${OutPutDir}/" "${OutPutFileName}_${logNum}.txt" "${commIndex}" "${pidIndex}" "${eventIndex}" "${argsIndex}" >>  "${OutPutDir}/log.txt" 2>&1
    echo "$(date '+%Y-%m-%d %H:%M:%S:%N') log ${logNum} end parse 2" >>  "${OutPutDir}/log.txt"
        
    CompressFileName="${OutPutDir}/output_$(date +%Y%m%d%H%M%S)_${logNum}.tar.gz"
    pushd "${OutPutDir}" > /dev/null 2>&1
    tar zcpf "${CompressFileName}" "${OutPutFileName}_${logNum}.txt" >>  "${OutPutDir}/log.txt"
    popd > /dev/null 2>&1

    rm "${OutPutDir}/${OutPutFileName}_${logNum}.txt"
    echo "$(date '+%Y-%m-%d %H:%M:%S:%N') log ${logNum} end tar 3" >>  "${OutPutDir}/log.txt"
}

function main()
{
    if [ -n "${TRACEE_OUTPUT_DIR}" ]; then
        OutPutDir="${TRACEE_OUTPUT_DIR}/${SubDir}"
    fi
        
    if [ -n "${TRACEE_OUTPUT_MAXLINE}" ]; then
        MaxLine="${TRACEE_OUTPUT_MAXLINE}"
    fi

    if [ -n "${TRACEE_WAIT_SECONDS}" ]; then
        WaitSeconds="${TRACEE_WAIT_SECONDS}"
    fi

    mkdir -p "${OutPutDir}"

    TraceeStruct="{\n\"syscallWithFlags\": {},\n\"syscallNoFlags\": {},\n\"procPaths\": {},\n\"sysPaths\": {},\n\"devPaths\": {}\n}"
    echo -e "$TraceeStruct" > "${OutPutDir}/base.json"

    if read FirstLine; then
        if [ -n "${FirstLine}" ] && [ "${logNum}" -eq 0 ] && [ "${CurLine}" -eq 0 ];then
            commIndex=$(echo "${FirstLine}" | awk '{print index($0, "COMM")}')
            commIndex=$((commIndex-1))
            pidIndex=$(echo "${FirstLine}" | awk '{print index($0, "PID/host")}')
            pidIndex=$((pidIndex-1))
            eventIndex=$(echo "${FirstLine}" | awk '{print index($0, "EVENT")}')
            eventIndex=$((eventIndex-1))
            argsIndex=$(echo "${FirstLine}" | awk '{print index($0, "ARGS")}')
            argsIndex=$((argsIndex-1))
            echo "commIndex: ${commIndex} ; pidIndex: ${pidIndex} ; eventIndex: ${eventIndex} ; argsIndex: ${argsIndex}" >>  "${OutPutDir}/log.txt"
            
            ((CurLine++))
            echo "${FirstLine}" >> "${OutPutDir}/${OutPutFileName}_${logNum}.txt"
        fi
        while :
        do
            if read -t ${WaitSeconds} LINE;then
        
                echo "${LINE}" >> "${OutPutDir}/${OutPutFileName}_${logNum}.txt"
                ((CurLine++))
                if [ "${CurLine}" -ge "${MaxLine}" ];then
                    DumpFile &
                    CurLine=0
                    ((logNum++))
                fi      
  
            elif [ "$CurLine" -gt 0 ];then
                DumpFile &
                CurLine=0
                ((logNum++))
            fi
        done
    fi    
}

main

exit $?
