### ISSUE TITLE
stackAddresses empty due to capabilities

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#3161]
## Description

`stackAddresses` is empty when tracee is run with the `-o option:stack-addresses -o json`. after some inspection the error received from the map read (https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_pipeline.go#L539) is `operation not permitted`. the error check is ignored there (indicating a missed key due to map being overwritten).

When tracee is run with the flag `--caps bypass=true` `stackAddresses` gets filled.

**Comment by AsafEitani** [comment]
The that needs to be ignore should be `no such file or directory`.

**Comment by josedonizetti** [comment]
Testing it again, and it seems like working for me, or maybe I'm running tracee the same way @AsafEitani did, for the command:

```
sudo ./dist/tracee -o option:stack-addresses -o json | jq '.eventName,.stackAddresses'
```

I got: 

```
"dynamic_code_loading"
[
  140596774825051,
  15662988,
  15256029,
  15163180,
  29424606,
  29982673,
  29986771,
  14109552,
  14128939,
  14268979,
  14895719,
  18747732,
  22893817,
  140596527801267,
  22438328,
  22437699,
  14714456,
  14718127,
  13604226,
  10744069
],
"security_socket_connect"
[
  4794459,
  4773029,
  5546843,
  5652907,
  5651653,
  5603045,
  5669925,
  5669655,
  5502792,
  5499646,
  5496453,
  7749253,
  7664991,
  7681797,
  7671398,
  4677729
],
"sched_process_exec"
[
  140137529139888
]
"sched_process_exec"
[
  140138881647280
]
```

which is the same as I get when running with `bypass=true`.


@AsafEitani WDYT?

**Comment by AsafEitani** [comment]
If it works that it works :)
Probably something with the capabilities

**Comment by josedonizetti** [comment]
Marking as close, feel free to reopen it if needed.
