### ISSUE TITLE
Unexported events documentation

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#3167]
The following existing event documentations are not exported in the side navbar:
1. docs/events/builtin/extra/hidden_kernel_module.md
1. docs/events/builtin/extra/process_execute_failed.md
1. docs/events/builtin/extra/security_bpf_prog.md

Simply need to fix by exporting in `mkdocs.yml`.

**Comment by rafaeldtinoco** [comment]
mind adding this change to your docs PR ?

**Comment by josedonizetti** [comment]
@rafaeldtinoco done
