### ISSUE TITLE
policy: --output should define which printers to be used in a policy

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3173]
the policies only support actions for `log` (json to stdout), `webhook`, and `fluentd`.  We need to implement other printers like `table`, `gotemplate`, `gob`. And also file redirection, the policy printer only prints to stdout, we cannot direct the output to a file like `--output json:/output/file`

**Comment by yanivagman** [comment]
Like discussed offline, the output flag can be used to globally set the format and file path (can potentially be multiple formats and paths), then the `log` action can use those formats and files without the need to specify them as actions on their own
