### ISSUE TITLE
network events are not working correctly with policies

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3184]
## Description

Use the following test as a base line (ping -4 and ping -6):
```
$ ping -4 -c 1 -I 172.16.254.1 172.16.254.2 ; ping -6 -c 1 -I fd6e:a63d:71f:2f4::ff:1 fd6e:a63d:71f:2f4::ff:2
```

Execute tracee with a single scope in the command line:

```
$ sudo ./dist/tracee --filter event=net_packet_ipv4 --filter event=net_packet_icmp
 --filter event=net_packet_icmpv6 --filter comm=ping
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
02:42:40:518141  1000   ping             31358   31358   0                net_packet_ipv4           src: 172.16.254.1, dst: 172.16.254.2, proto_ipv4: {4 5 0 84 19254 2 0 64 ICMPv4 39757 172.16.254.1 172.16.254.2}
02:42:40:518141  1000   ping             31358   31358   0                net_packet_icmp           src: 172.16.254.1, dst: 172.16.254.2, proto_icmp: {EchoRequest 14503 51 1}
02:42:40:518190  1000   ping             31358   31358   0                net_packet_ipv4           src: 172.16.254.2, dst: 172.16.254.1, proto_ipv4: {4 5 0 84 17765 0 0 64 ICMPv4 57630 172.16.254.2 172.16.254.1}
02:42:40:518190  1000   ping             31358   31358   0                net_packet_icmp           src: 172.16.254.2, dst: 172.16.254.1, proto_icmp: {EchoReply 16551 51 1}
02:42:40:520708  1000   ping             31361   31361   0                net_packet_icmpv6         src: fd6e:a63d:71f:2f4::ff:1, dst: fd6e:a63d:71f:2f4::ff:2, proto_icmpv6: {EchoRequest 21409}
02:42:40:520754  1000   ping             31361   31361   0                net_packet_icmpv6         src: fd6e:a63d:71f:2f4::ff:2, dst: fd6e:a63d:71f:2f4::ff:1, proto_icmpv6: {EchoReply 21153}

End of events stream
Stats: {EventCount:6 EventsFiltered:0 NetCapCount:0 BPFLogsCount:0 ErrorCount:0 LostEvCount:0 LostWrCount:0 LostNtCapCount:0 LostBPFLogsCount:0}
```

WORKS AS EXPECTED.

----

Now do the same but using 2 policy files instead:

`net_packet_icmp.yaml`
```
name: net_packet_icmp
description: net_packet_icmp test
scope:
  - comm=ping
defaultAction: log
rules:
  - event: net_packet_icmp
```
`net_packet_icmpv6.yaml`
```
name: net_packet_icmpv6
description: net_packet_icmpv6 test
scope:
  - comm=ping
defaultAction: log
rules:
  - event: net_packet_icmpv6
```

And run tracee using those 2 policies:

```
$ sudo ./dist/tracee --config ~/policies/config.yaml --policy ~/policies/network/ 
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
02:40:11:421982  1000   ping             30984   30984   0                net_packet_icmp           src: 172.16.254.1, dst: 172.16.254.2, proto_icmp: {EchoRequest 29987 47 1}
02:40:11:422041  1000   ping             30984   30984   0                net_packet_icmp           src: 172.16.254.2, dst: 172.16.254.1, proto_icmp: {EchoReply 32035 47 1}
02:40:11:424594  1000   ping             30985   30985   0                net_packet_icmpv6         src: fd6e:a63d:71f:2f4::ff:1, dst: fd6e:a63d:71f:2f4::ff:2, proto_icmpv6: {EchoRequest 23837}
02:40:11:424634  1000   ping             30985   30985   0                net_packet_icmpv6         src: fd6e:a63d:71f:2f4::ff:2, dst: fd6e:a63d:71f:2f4::ff:1, proto_icmpv6: {EchoReply 23581}

End of events stream
Stats: {EventCount:4 EventsFiltered:0 NetCapCount:0 BPFLogsCount:0 ErrorCount:0 LostEvCount:0 LostWrCount:0 LostNtCapCount:0 LostBPFLogsCount:0}
```

It works..

BUUUUUUUUUT, add another policy called `net_packet_ipv4.yaml`:

```
name: net_packet_ipv4
description: net_packet_ipv4 test
scope:
  - comm=ping
defaultAction: log
rules:
  - event: net_packet_ipv4
```

And run tracee again with the same command (using all policies):

```
$ sudo ./dist/tracee --config ~/policies/config.yaml --policy ~/policies/network/ 
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
02:41:45:467755  1000   ping             31221   31221   0                net_packet_ipv4           src: 172.16.254.1, dst: 172.16.254.2, proto_ipv4: {4 5 0 84 13929 2 0 64 ICMPv4 45082 172.16.254.1 172.16.254.2}
02:41:45:467802  1000   ping             31221   31221   0                net_packet_ipv4           src: 172.16.254.2, dst: 172.16.254.1, proto_ipv4: {4 5 0 84 14237 0 0 64 ICMPv4 61158 172.16.254.2 172.16.254.1}

End of events stream
Stats: {EventCount:2 EventsFiltered:0 NetCapCount:0 BPFLogsCount:0 ErrorCount:0 LostEvCount:0 LostWrCount:0 LostNtCapCount:0 LostBPFLogsCount:0}
```

It only picks `net_packet_ipv4` now.

**Comment by rafaeldtinoco** [comment]
I'm investigating this. For now, when using the 3 policy files, I have:

```
$ sudo ./dist/tracee --config ~/policies/config.yaml --policy ~/policies/network/ 
AQUI: net_packet_icmp =net_packet_icmp
AQUI: net_packet_icmpv6 =net_packet_icmpv6
AQUI: net_packet_ipv4 =net_packet_ipv4
event: 704, submit: 3
event: 705, submit: 2
event: 701, submit: 4
event: 713, submit: 0
event: 727, submit: 18446744073709551615
event: 728, submit: 18446744073709551615
event: 2004, submit: 1
event: 2005, submit: 2
event: 714, submit: 0
event: 712, submit: 0
event: 2000, submit: 4
event: 700, submit: 5
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
```

And the `t.events` `ecfg.submit` value seems wrong for some events.

Ignoring the events used for internal stuff (fork/exec/cgroup) we have the following "submit" value (u64 describing which policies require the event submission) for the base events:

net_packet_base         w/ 0000 0101 (policy 1 and 3)
net_packet_ip_base      w/ 0000 0100 (policy 3)
net_packet_icmp_base    w/ 0000 0011 (policy 1 and 2)
net_packet_icmpv6_base  w/ 0000 0010 (policy 2)

And, for the derived events, submit seems correct:

net_packet_ipv4   0000 0100 (policy 3)
net_packet_icmp   0000 0001 (policy 1)
net_packet_icmpv6 0000 0010 (policy 2)

Judging by the final events, the base events should have submit:

net_packet_base         w/ 0000 0111 (policy 1,2,3) => was wrong
net_packet_ip_base      w/ 0000 0100 (policy 3) => was correct
net_packet_icmp_base    w/ 0000 0011 (policy 1) => was wrong
net_packet_icmpv6_base  w/ 0000 0010 (policy 2) => was correct

I'm still investigating.

**Comment by rafaeldtinoco** [comment]
Yep its clearly an issue with what policies pick what base events. If I do:

![image](https://github.com/aquasecurity/tracee/assets/7395852/6205516f-2f32-4774-a14e-9d456a85a5b4)

I'm able to pick all the 3 policies (and 3 diff events) but the net_packet_ipv4 comes from all the policies and not only from the "net_packet_ipv4" policy:

![image](https://github.com/aquasecurity/tracee/assets/7395852/358e4f35-6d02-46fd-9c73-7e2b19502571)

And you can see that the matchedPolicies are correct for the ICMP events but not for the IPv4 one. The only difference I can think of right now is that there are more than 1 derived events from the IP base (while there aren't more than 1 in the other base events for ICMP and ICMPv6).

**Comment by rafaeldtinoco** [comment]
Ill continue tomorrow.

**Comment by geyslan** [comment]
> The only difference I can think of right now is that there are more than 1 derived events from the IP base (while there aren't more than 1 in the other base events for ICMP and ICMPv6).

That makes sense. #3184 seems to solve the problem with one derivation depth only. I'm really considering that we have to propagate the MatchedScopes bitmap without bit clearing at all. Leaving the actual match in any stage to be the MatchedScopesNames.
