### ISSUE TITLE
Segmentation fault on Tracee binary

### ISSUE THREAD

**Issue by rohitburke** [aquasecurity/tracee#3199]
## Description

Not able to run **./dist/tracee** getting a segmentation fault error on every command that I run on tracee but tracee-ebpf is working fine.

![image](https://github.com/aquasecurity/tracee/assets/30924877/17c525b4-2682-4e47-b842-c16794b172c6)

## Output of `tracee version`:

```
v0.14.2
```

## Output of `uname -a`:

```
Linux kali 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2kali1 (2023-04-18) x86_64 GNU/Linux
```

**Comment by rohitburke** [comment]
@josedonizetti 
Can you check this?

**Comment by geyslan** [comment]
Non reproducible on my rig.

![image](https://github.com/aquasecurity/tracee/assets/3372117/d2d16a82-b9d8-41c3-980c-e38d4ecbbca6)


```
❯ uname -a
Linux hb 6.2.16-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:09:09 UTC 2023 x86_64 GNU/Linux

❯ sudo ./dist/tracee version
Tracee version: "v0.14.2"
```

@rohitburke anyway, can you try on the main branch?

**Comment by rohitburke** [comment]
Yes @geyslan you are correct.
I tried running it on my other device. It's running fine on it. Don't know why it's not running on my main device.
Need to check or update my main device. 

Thanks :)
