### ISSUE TITLE
improve CI times

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#323]
currently, on every pull request we build a new docker container with all the dependencies from scratch, and rebuild all the code.
If we could cache the go dependencies, and the docker layers, we would save most of the time and resources spent in the CI, the code build itself is not that intensive.
need to look into how to do that with Github Actions

**Comment by krol3** [comment]
I´d would like to help

**Comment by itaysk** [comment]
please do! take a look at the https://github.com/aquasecurity/tracee/blob/main/.github/workflows/build-test.yaml file and let me know if you have any questions

**Comment by krol3** [comment]
@itaysk, to publish the image will be the 'make docker' that use this command `docker build --build-arg VERSION=v0.3.1-42-g3aa104c -t tracee:latest .`

**Comment by itaysk** [comment]
@krol3 not sure I understand the question..
to clarify, this issue discusses the build/test phase, not the release (publish) phase

**Comment by krol3** [comment]
Yes clarify the issue, maybe for the release this [PR](https://github.com/aquasecurity/tracee/pull/432) could help

**Comment by itaysk** [comment]
ok, that's interesting. I can't accept that PR because publishing images is handled in our [current release script](https://github.com/aquasecurity/tracee/blob/7d2ce345dfca4f1f24f2aa1a0a99a97e5ad0952f/Makefile#L181), BUT:
I think your PR addresses also the caching issue, by using the `Cache Docker layers` action. If you can take just the caching parts, and integrate to the existing workflow, that would be helpful and resolve this issue.

**Comment by rafaeldtinoco** [comment]
With the new building schema I believe this can be closed.
