### ISSUE TITLE
tracee-rules panic

### ISSUE THREAD

**Issue by OriGlassman** [aquasecurity/tracee#3230]
Command: ./tracee-rules --allcaps

Error (hard to reproduce):
anic: sync: WaitGroup is reused before previous Wait has returned

 

goroutine 1 [running]:
sync.(*WaitGroup).Wait(0xc0001fc780?)
    /usr/local/go/src/sync/waitgroup.go:118 +0x7f
github.com/aquasecurity/tracee/pkg/signatures/engine.(*Engine).checkCompletion(0xc0001fc780)
    /pkg/signatures/engine/engine.go:137 +0x3f
github.com/aquasecurity/tracee/pkg/signatures/engine.(*Engine).consumeSources(0xc0001fc780, {0x1793000, 0xc0002fecc0})
    /pkg/signatures/engine/engine.go:215 +0x34a
github.com/aquasecurity/tracee/pkg/signatures/engine.(*Engine).Start(0xc0001fc780, {0x1793000, 0xc0002fecc0})
    /pkg/signatures/engine/engine.go:112 +0x1e7
main.main.func1(0xc0002fe640)
   /cmd/tracee-rules/main.go:166 +0xb17
github.com/urfave/cli/v2.(*App).RunContext(0xc0002971e0, {0x1792270?, 0xc0001280e8}, {0xc000124000, 0x7, 0x7})
    /home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x97c
github.com/urfave/cli/v2.(*App).Run(...)
    /home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
    /cmd/tracee-rules/main.go:257 +0x97a

(tracee version 0.14.2)

**Comment by josedonizetti** [comment]
This is the same bug we have at -> https://github.com/aquasecurity/tracee/issues/3151

I'll be fixing it today.
