### ISSUE TITLE
Intermittent failures of getTailCall test

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#3248]
@rafaeldtinoco Likely some form of race since the function depends on the events definitions and modifies the tail calls.

Test is in pkg/ebpf/tracee_test.go

**Comment by rafaeldtinoco** [comment]
@NDStrahilevitz thanks, will check. Having instances of the dependencies without having instances of the evet definitions themselves (could be the nature). I'm currently going through this part now. Will check the test.

**Comment by rafaeldtinoco** [comment]
I believe this was solved by:

commit 533fd9020
Author: Rafael David Tinoco <rafaeldtinoco@gmail.com>
Date:   Mon Jun 26 20:47:59 2023

    fix(pkg/events): fix tailcall dependencies race issues (#3274)
