### ISSUE TITLE
Vagrantfile typo

### ISSUE THREAD

**Issue by 64J0** [aquasecurity/tracee#3258]
## Description:

I just noticed a typo in the Vagrantfile comments: https://github.com/aquasecurity/tracee/blob/main/Vagrantfile#LL20C3-L20C44.

The text says:

> To sing in use the token retrieved with

And the right text is:

> To sign in use the token retrieved with

**Comment by 64J0** [comment]
The typo is in the "sing" word to be more direct.

**Comment by josedonizetti** [comment]
@64J0 would you be up to creating a pr to fix it?

**Comment by 64J0** [comment]
For sure, I was feeling a bit lazy to clone the repo and submit the PR just for this change, but I can do it for sure.

I'll just finish a task here first.

**Comment by 64J0** [comment]
Done @josedonizetti.

PR: https://github.com/aquasecurity/tracee/pull/3260

**Comment by josedonizetti** [comment]
Thank you
