### ISSUE TITLE
docs: Provide clarity on the different Tracee use case

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#3266]
As we change Tracee to be more focused on the cloud native ecosystem, it might be difficult for people who don't want to monitor in-cluster behaviour to see that Tracee can also be used in other environments e.g. directly on the host machine.

> Tracee enriches events using container runtime engines and knows how to distinguish between events coming from containers or from the host but everything it does it can either be done for host processes or container processes. 
[Link to the Slack where Rafael posted this](https://aquasecurity.slack.com/archives/C02LK3U786L/p1687748035268099?thread_ts=1687729455.804089&cid=C02LK3U786L)

My question is -- to what extent do we want to provide documentation on both use cases? it might be easier to change the language in the docs to make both use cases more visible
* cloud native setup
* host machine setup

I guess that relates to there not being much documentation on using the Tracee CLI itself -- we have this https://aquasecurity.github.io/tracee/v0.15/docs/events/overview/#read-in-cli but there is no documentation on when to use the CLI and how to "install" it

**Comment by rafaeldtinoco** [comment]
> My question is -- to what extent do we want to provide documentation on both use cases? it might be easier to change the language in the docs to make both use cases more visible.

IMO, when I started providing OS package building makefiles, and Ubuntu and Fedora packages, it was to enable this use case. We thought it would be better to have the "single binary" experience first before "releasing OS packages", for example.

Now that we do have the single binary, my thoughts are:

1. To provide OS packages as artifacts (Ubuntu, Fedora, Alma/CentOS) on each release.

2. Simple package that runs tracee as a daemon with a basic default policy (detection signatures only ?). Profile would be in /etc/tracee/ directory (like any other OS related tool).

`$ vi /etc/tracee/policies/default.yaml`
`$ vi /etc/tracee/config.yaml`

3. Logs are provided through systemd (journalctl) like any other system daemon (or user can configure /etc/tracee/config and provide options for tracee daemon).

`$ systemctl edit --full tracee.service`
<edit service>

If we provide those 3 things, very simple to be accomplished with the packaging infrastrcuture we already have, the instructions to run tracee in OS would be only related to installing the packages, changing the config files (if needed, or stick with the default settings) and restaring systemd daemon:

`$ systemctl restart tracee.service`

**Comment by itaysk** [comment]
Tracee is in an early stage and in order to break through I think we need to focus on a primary use case. We've discussed it before and decided that primary use case will be a cloud native environment. So I think it's fine that the quickstart is opinionated.
In addition to primary use case, we can support and document secondary use cases, if there's demand for it. For example, we could create a tutorial for how to use Tracee in a special setup, or to achieve a specific task. Having said that, I don't think we should come out with officially supported packages now.
