### ISSUE TITLE
Add filter comparison operation options (>, <, !=) 

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#328]
Now that the filter flag was merged in #315 it would be great to have more options besides '=' for matching on filters. For example:

--filter uid > 0

--filter uid != 1000

--filter return < 0

**Comment by grantseltzer** [comment]
The way i'm thinking of going about this is as follows:

- Use the BPF_HASH `uid_filter` to store both the 'operator' and the values to compare the process uid to.
- `uid_filter[0]` contains the operator in first 3 bits (1 is '=', 2 is '!=', 3 is '>', 4 is '<') 
- If the operator is `=` or `!=` the `uid_filter` hash works the way it does now
  - To avoid collisions (i.e. `uid=0` is specified):
    - i'll `>> 3` the value in the hash before checking if the uid matches.
    - When checking operator i'll `&&` with FFFFFFF8 
- If the operator is `>` or `<` then `uid_filter[1]` contains the value to compare to.

I can also tune this to instead have operator values for multiple operators specified (i.e. uid<1000 and uid >5000) where uid_filter[2] contains the second value. I don't see too much usecase for supporting this but it couldn't hurt. 

Let me know if you have any thoughts.

**Comment by yanivagman** [comment]
I don't know about using index 0 and 1 to store this metadata, as it requires special handling for these uids.
I understand that the previous apprach I suggested is problematic? (using the value of the uid to store ">", "<").
I guess this is because it may be hard to know where to find the ">" and "<" uids in the map, right? (and we want to avoid loops where possible).

Let me suggest a different approach.
We can use the uid_filter as we have today, and have 2 values (the key is the uid):
"1" will represent "="
"2" will represent "!="

Then we can have a different map for "<" and ">" , which will have a limited size (say 3).
Then, we can just "loop" over these 3 elements, and check if our given uid is bigger or smaller than, according to:
"1" that will represent "<"
"2" that will represent ">"

WDYT?

**Comment by grantseltzer** [comment]
Sure, that is simpler. I can set the bpfConfigMap's 'configFilterByUid' field to the corresponding operator. 

Have to make sure all the combination of filters are supported:

`--filter uid=1000 --filter uid>5000` 
`--filter uid>0 --filter uid<1000`
`--filter uid<1000 --filter uid!=0` 
`--filter uid>0` --filter uid>1000` (>0 overwrites >1000)
`--filter uid<1000 --filter uid<500` (<1000 overwrites <500)
`--filter uid=1000 --filter uid!=1000` (error out? or second filter flag overwrites the first?)

**Comment by yanivagman** [comment]
Actually, I think configFilterByUid is not needed anymore. We can make a default filter of uid>=0 if non is chosen (which will capture all uids).

I also think that the conditions should be logical "and" and not "or" so uid>0 and uid>1000 should provide only uid>1000.

I don't think we should handle logical filters errors (like uid==1000 and uid!=1000 - in that case, no output will be shown by tracee (as logical anding these value gives an empty uid set)

**Comment by yanivagman** [comment]
One more thing about uid==1000 and uid!=1000.
In that case, we have to use a different value that will represent that both operator ls were chosen. This can be done by bitwise operations.
If "=" have a value of 1 in the map, and "!=" Have a value of 2, we can "or" these values together: 1||2, which equals 3.
Then, in the bpf code, we can check for equality by anding with "1", and for inequality by anding with 2

**Comment by grantseltzer** [comment]
The problem is that if don't use configFilterByUid we'd have to populate the content of every possible key/value in the map, right? Were you thinking that if `--filter uid=1000` is specified uid_hash[1000] would be 1 and every other key's value would be 2? This is the reason I was thinking of having the operator in bpfConfigMap.

Otherwise, everything makes sense to me. Logical "and"ing `<` arguments with `>` arguments is a good idea.

**Comment by yanivagman** [comment]
We don't need to populate the map if removing configFilterByUid as we will support ">" operator, and default to uid>0.
If no filter was chosen, bpf code checks uid filters and see that uid>0 was chosen and continues.
If uid=xxx or uid!=xxx was given, then bpf code will just try to match.

**Comment by grantseltzer** [comment]
Ah, makes sense! Thanks for suggestions, working on it!

**Comment by grantseltzer** [comment]
Have a working branch for this, I added a test but need to add a makefile entry for building a test binary (`go test` fails because of linker issues related to cgo). Branch: https://github.com/grantseltzer/tracee/tree/gs/filter-operations
