### ISSUE TITLE
reduce the size of docker images

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#329]
currently, the latest image weights 654MB we need to to reduce it. This is is mostly due to the `apt-get install` layer, which is 574.5MB alone, and confirmed by looking at the slim image which is 107MB.

**Comment by yanivagman** [comment]
Moving to alpine will reduce ~50MB (non compressed) by installing the following packages for fat:

FROM golang:alpine
RUN apk update
RUN apk add clang llvm make gcc libc6-compat coreutils linux-headers musl-dev elfutils-dev libelf-static zlib-static
WORKDIR /

And for slim, will reduce the image size to less than 10MB (non compressed):
FROM alpine
RUN apk update
RUN apk add libc6-compat elfutils-dev
WORKDIR /
