### ISSUE TITLE
Help subcommand doesn't work as expected

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#3299]
## Description

Help subcommand says the follwing:
```
./dist/tracee help
Tracee uses eBPF technology to tap into your system and give you
access to hundreds of events that help you understand how your system behaves.

Usage:
  tracee [flags]
  tracee [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
->  help        Help about any command
  ...
```

However, when I want to get help about the output flag, I get the following:
```
./dist/tracee help output
Unknown help topic [output]
```

While I would expect to get help about the output flag.

Adding to the confusion, not only `help` subcommand exists, but also `--help` flag:
```
./dist/tracee --help output
Control how and where output is printed.
...
```

I think we should do the following:
1. Remove support for --help flag
2. Add help about flags in the help subcommand

Alternatively (and easier to implement), we should disable the `help` subcommand and only keep the `--help` flag

## Output of `tracee version`:

```
v0.16.0
```

## Output of `uname -a`:

```
(paste your output here)
```

**Comment by geyslan** [comment]
Taking these steps: https://github.com/aquasecurity/tracee/pull/3302#issuecomment-1632859656
