### ISSUE TITLE
Docs: link not working

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#3309]
Link to docs not working :D https://github.com/aquasecurity/tracee/tree/main/cmd/tracee-rules

**Comment by josedonizetti** [comment]
@AnaisUrlichs it is because tracee-ebpf and tracee-rules are getting deprecated, their docs are not up anymore.

**Comment by AnaisUrlichs** [comment]
Sorry just replaying -- I think we should mention it there in that file that it is deprecated and link to the new docs BECAUSE when I google Tracee THIS link comes up on the tracee-rules. What do you think?

https://github.com/aquasecurity/tracee/pull/3317
