### ISSUE TITLE
Missing symbols on newer kernels (> ~6.3)

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#3356]
## Description

I noticed that my 6.3.6 machine is missing the following symbols:
* `exec_binprm` - part of the `process_execute_failed` event
* `layout_and_allocate` - part of the `module_load` event

## Output of `tracee version`:

```
v0.16.1
```

## Output of `uname -a`:

```
Linux Alon-Zivony 6.3.6-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Mon Jun 12 11:59:43 IDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by OriGlassman** [comment]
There's a problem hooking functions that are not explicitly defined to be not inlined.
The compiler can decide to make a certain function inlined in arbitrary kernel versions, causing the errors described above.

First, if a symbol is missing, tracee should report an error and NOT terminate (tracee terminating in customer's environment is very much not desired).
Second, to at least partially address this issue, I suggest to make a mechanism in tracee that will allow to supply several symbols, and tracee will load only one symbol from this list (potentially by a provided order from the user (priority)), and if it didn't successfully any all of the symbols provided, report an error.

@yanivagman @rafaeldtinoco

**Comment by geyslan** [comment]
> First, if a symbol is missing, tracee should report an error and NOT terminate (tracee terminating in customer's environment is very much not desired).

Orthogonal context in relation to the above requirement: https://github.com/aquasecurity/tracee/issues/3455#issuecomment-1714402081

**Comment by rafaeldtinoco** [comment]
This is related to https://github.com/aquasecurity/tracee/issues/3653 as well.
