### ISSUE TITLE
Yesterday's release was tagged incorrectly (`v0.3` instead of `v0.3.X`)

### ISSUE THREAD

**Issue by 06kellyjac** [aquasecurity/tracee#336]
It was tagged `v0.3` instead of `v0.3.X` like the rest of the releases

**Comment by itaysk** [comment]
@06kellyjac thanks for bringing this into attention. we are considering what's the best way to address this issue

**Comment by itaysk** [comment]
we have released a v0.3.0 just now. I've deleted the old v0.3 to avoid confusion
