### ISSUE TITLE
docs: Why does it say "tracee will start with a sane default"

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#3398]
What is sane default? I don't understand https://aquasecurity.github.io/tracee/v0.17/docs/events/overview/

**Comment by josedonizetti** [comment]
Hmm, the idea is that tracee starts with a set of [default events](https://aquasecurity.github.io/tracee/v0.17/docs/events/overview/#default-events) to help the user. But unfortunately the default set of events currently is different if you using the binary/docker or kubernetes, we want to fix it after adding a few higher level events, which will take over as the default events.

**Comment by AnaisUrlichs** [comment]
Thank you for the explanation -- to me the "sane" part in the sentence did not make sense

**Comment by josedonizetti** [comment]
@AnaisUrlichs  gotcha, can you do a PR to fix/improve it? :)
