### ISSUE TITLE
Docs: Change wording around behavioural signatures

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#3426]
Currently, behavioural signatures are described in the following way:

> Tracee has a library of behavioral patterns that might indicate suspicious malicious activity. These Tracee events, sometimes referred to as "signatures" help you detect more sophisticated security insights than basic observability events like syscalls.

Docs: https://aquasecurity.github.io/tracee/v0.17/docs/events/builtin/signatures/ -- top of the page

This is confusing as we refer to these advanced events as behavioural signatures -- so they are a type of event rather than called signatures or events interchangeably. I propose we change it to the following:

> Tracee has a library of behavioral patterns that can indicate suspicious or malicious activity. Thse patterns are referred to as behavioral signatures, which is a type of event in Tracee. Behavioral Signatures help you detect more sophisticated security insights than basic observability events like syscalls.

Thoughts on the change?

**Comment by josedonizetti** [comment]
@

**Comment by AnaisUrlichs** [comment]
We are updating this to `security` events and renaming `extra` events into multiple new event types, as discussed in https://github.com/aquasecurity/tracee/issues/3607
