### ISSUE TITLE
Readme broken link for Tracee Docker quickstart page

### ISSUE THREAD

**Issue by wr46** [aquasecurity/tracee#3453]
The Docker Quick Start page referenced in Readme.md file link **[Experiment using the Tracee container image.](https://aquasecurity.github.io/tracee/latest/getting-started/docker-quickstart)** was removed in version v0.12 documentation page.

**Comment by AnaisUrlichs** [comment]
Hi there, thank you for pointing it out. As part of changing the RADME I had to change the first page of the docs to reflect the content/show the same content as the README. However, while the changes to the README are instantly visible after merging, the changes to the docs pages only become visible once a new Tracee release is cut. 

So the link will work once we cut a new release and the changes to the docs become visible

Here is the PR for the docs https://github.com/aquasecurity/tracee/pull/3378/files

**Comment by AnaisUrlichs** [comment]
@rafaeldtinoco -- this should be resolved as part of the new release of the docs -- so it should be part of milestone v0.18.0 -- basically the README assumes that the changes are already visible in the docs but they will only be visible once a new release of the docs is made

**Comment by AnaisUrlichs** [comment]
To clarify, this should be resolved automatically with the new release -- will check then

**Comment by itaysk** [comment]
Looks like the link works now, @AnaisUrlichs can we close this?
