### ISSUE TITLE
Document ARM64 quickstart

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#3454]
The current documentation mentions a docker image with the latest tag, however, this image is for x86 architecture only. We should document arm64 image usage as well

**Comment by geyslan** [comment]
Additional info:

- https://github.com/aquasecurity/tracee/pull/3464
- https://github.com/aquasecurity/libbpfgo/blob/bd31ff0bdba11491d7d31df7675274e6829b769f/docs/Vagrantfile.md#darwin
