### ISSUE TITLE
Kernel symbols error

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#3455]
## Description

While trying to run tracee using the docker image with the aarch64 tag, we get the following error:

`{"level":"fatal","ts":1694377647.5739548,"msg":"Tracee runner failed","error":"cmd.Runner.Run: error initializing Tracee: ebpf.(*Tracee).Init: ebpf.(*Tracee).NewKernelSymbols: invalid ksymbol table (capabilities issue ?)"}`

## Output of `tracee version`:

```
V0.17.1
```

## Output of `uname -a`:

```
(paste your output here)
```

**Comment by geyslan** [comment]
This error occurs when trying to run tracee directly on the linuxkit used by Docker on macOS. This kernel is limited, lacking `/proc/kallsyms` addresses and BTF support.

In fact, Tracee is compatible with Linux x86_64 and arm64 architectures. To provide these environments for testing, we must make changes to the Vagrantfile as in https://github.com/aquasecurity/libbpfgo/blob/main/builder/Vagrantfile-ubuntu#L18-L36.

**Comment by geyslan** [comment]
As explained above, running Tracee directly on macOS isn't supported. However this https://github.com/aquasecurity/tracee/pull/3464 will bring a way to run an arm64 Linux on macOS using vagrant + parallels.

Closing as not planned.
