### ISSUE TITLE
Distro and Kernel Support Dedications?

### ISSUE THREAD

**Issue by jrmwooldridge** [aquasecurity/tracee#3472]
I would like to know if there are distro and kernel support windows. primarily for legacy non-BTF kernels and early supported BTF kernels, etc.

**Comment by yanivagman** [comment]
Basically tracee supports any kernel that has BTF enabled in kernel config, and is tested regularly on the major distros (we do need to add a support matrix - https://github.com/aquasecurity/tracee/issues/2929)
Regarding legacy non-BTF kernels - we use BTFHub to support kernels starting from 5.2 and above, and also rhel based kernels from 4.19.

**Comment by jrmwooldridge** [comment]
Thanks. I was curious because kernel version support might be important for me EL8+.  I tried a basic running with just `sudo ./dist/trace -e execve ...` and hit a kprobe attach error on execve_bprm. Luckily I can attach other relavent hooks.

**Comment by yanivagman** [comment]
If you have an issue with a specific event on some specific environment please open a bug describing the command you used and details about the environment and we will try to help.
Closing this issue now as it will be handled in #2929 (other prerequisites are described here: https://aquasecurity.github.io/tracee/v0.17/getting-started/installing/prerequisites/)
