### ISSUE TITLE
Missing process values in process tree

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#3489]
There are some useful values that are missing from the current process tree `Process` struct:
 - [ ] Execution time - the executable file information is changed in the change log during execution feed, but the time of the change is impossible to get in the current API
 - [ ] Container ID
 - [ ] Execution CMD
    * Maybe we even want the environment variables?
 - [ ] Files hashes in the `FileInfo` struct

**Comment by yanivagman** [comment]
Will be handled as a part of #2586
