### ISSUE TITLE
Export datasource information to analyze mode

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#3535]
We need a method to stream or export the datasources information so it will be available in analyze mode.
We can maybe create a specific type of events that pass datasources information, or create a file format for exporting it or any other idea.
It should be available to use in runtime if tracee is streaming events to analyze mode instance in different host.

**Comment by rafaeldtinoco** [comment]
Closed as a duplicate of https://github.com/aquasecurity/tracee/issues/3535 (after it was re-written to contemplate everything in a single issue).
