### ISSUE TITLE
Event "cap_capable" doesn't display capability names 

### ISSUE THREAD

**Issue by tweetLilly** [aquasecurity/tracee#3552]
Hi All, I am trying out tracee for container monitoring. I use the docker image and tried some basic rules like to extract all capabilities of apps on new containers as follows: 
```
docker run \
  --name tracee --rm -it \
  --pid=host --cgroupns=host --privileged \
  -v /etc/os-release:/etc/os-release-host:ro \
  aquasec/tracee:latest --scope container --events cap_capable --output option:parse-arguments

```
But the output doesn't display the capability values but just the numbers. This feature is supported in the previous tracee releases though through parse-argument option

Thanks

**Comment by yanivagman** [comment]
Thanks for reporting this.
Should be fixed by https://github.com/aquasecurity/tracee/pull/3554
