### ISSUE TITLE
Support sets usage in policies

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#3556]
Just noticed that we are not supporting sets of events through the policy file.
Probably should support it.

**Comment by geyslan** [comment]
Even when defining it as an event?

**Comment by AlonZivony** [comment]
Yea, you get the "policy %s, event %s is not valid" error from the `policy_file.go`.

**Comment by geyslan** [comment]
Alright. I'll assign this to @josedonizetti who is acquainted with policy file parser.

**Comment by josedonizetti** [comment]
@yanivagman Is this something we want to implement? I remember we once discussed, and decided not to, not sure if anything changed.

**Comment by josedonizetti** [comment]
This feature won't be supported.
