### ISSUE TITLE
Tracee reports socket_accept event with nil remote_addr argument and no accept()

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3563]
## Description

```
$ sudo ./dist/tracee --output option:sort-events --output json --ou
tput option:parse-arguments --events socket_accept
```

And

```
$ nc -l -p 8123
<ctrl+c> without accepting a connection
```

Observe tracee:

```json
{"timestamp":1697027857239882931,"threadStartTime":1697027855975220468,"processorId":0,"processId":798695,"cgroupId":4728,"threadId":798695,"parentProcessId":794638,"hostProcessId":798695,"hostThreadId":798695,"hostParentProcessId":794638,"userId":1000,"mountNamespace":4026531841,"pidNamespace":4026531836,"processName":"nc","executable":{"path":""},"hostName":"rugged","containerId":"","container":{},"kubernetes":{},"eventId":"761","eventName":"socket_accept","matchedPolicies":[""],"argsNum":2,"returnValue":0,"syscall":"accept4","stackAddresses":null,"contextFlags":{"containerStarted":false,"isCompat":false},"threadEntityId":2393563162,"processEntityId":2393563162,"parentEntityId":3154888818,"args":[{"name":"sockfd","type":"int","value":3},{"name":"local_addr","type":"struct sockaddr*","value":{"sa_family":"AF_INET","sin_addr":"0.0.0.0","sin_port":"8123"}},{"name":"remote_addr","type":"struct sockaddr*","value":null}]}
```
2 issues perhaps:

1. `remote_address` is nil
2. was there an accept() event ?

## Output of `tracee version`:

```
Tracee version: "v0.18.0-rc-32-g7b095a8d9"
```

## Output of `uname -a`:

```
Linux rugged 6.1.55-1-lts #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 16:57:15 +0000 x86_64 GNU/Linux
```

**Comment by NDStrahilevitz** [comment]
So from a quick investigation, an accept syscall (accept4 in my machine's case) is generated and as can be seen the sockaddr of it will have family `AF_UNSPEC`:

`"args":[{"name":"sockfd","type":"int","value":3},{"name":"addr","type":"struct sockaddr*","value":{"sa_family":"AF_UNSPEC"}},{"name":"addrlen","type":"int*","value":"0x7fff88661ca0"},{"name":"flags","type":"int","value":2048}]`

This is the remote address which should have connected, in comparison this is from a test where after starting `nc` I ran `curl 0.0.0.0:8123`:

`"args":[{"name":"sockfd","type":"int","value":3},{"name":"addr","type":"struct sockaddr*","value":{"sa_family":"AF_INET","sin_addr":"127.0.0.1","sin_port":"42396"}},{"name":"addrlen","type":"int*","value":"0x7ffd8853d920"},{"name":"flags","type":"int","value":2048}]`

The port confirms that this address is the remote one. 

The catch is, we have this short circuit in the ebpf program:
```
   if (new_sock == NULL) {
        return -1;
    }
    if (old_sock == NULL) {
        return -1;
    }
```
So we know, both from the accept4 syscall and from the code that the remote address is not actually null, just unspecified. In the buffer decoding part however, we have no code section which defines how an AF_UNSPEC is parsed, so the resulting map is left empty (but it should not be nil).

However, considering there really is no address which was accepted (only  an accepting address shown in `socket_accept`), I am not sure if this isn't the best defined representation of the event there is, unless we want to replace it with the dummy `AF_UNSPEC` address we have in `accept4`.

**Comment by itaysk** [comment]
this is the desired behavior of the event
