### ISSUE TITLE
--scope help doesn't work

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#3564]
## Description

```
tracee --scope help
Error: invalid scope option specified (help), use '--help' for more info
```

https://aquasecurity.github.io/tracee/v0.18/docs/filters/filtering/

## Output of `tracee version`:

latest (7b095a8d9a11cbd11ac61d3eec4b0a0f77f66dd9)

## Output of `uname -a`:

```
(paste your output here)
```

**Comment by geyslan** [comment]
That doc is clearly a leftover since the behaviour of the new binary changed after this: https://github.com/aquasecurity/tracee/pull/3321

**Comment by geyslan** [comment]
We discussed creating a new option called 'man' that would run the man binary against our man file (converted from the respective .md).

Like: `tracee man scope`

**Comment by itaysk** [comment]
thanks. 
1. so please update the docs accordingly. 
2. is there an issue to track the reintroduction of help/man?

**Comment by geyslan** [comment]
> thanks.
> 
>     1. so please update the docs accordingly.

Going to. 👍🏼 
> 
>     2. is there an issue to track the reintroduction of help/man?

I don't think so. Will check, if not, raising one.

**Comment by geyslan** [comment]
Closing in favour of https://github.com/aquasecurity/tracee/issues/3570.
