### ISSUE TITLE
events.ParseArgsFDs: failed to lookup value 0xc000xxx in map fd_arg_path_map

### ISSUE THREAD

**Issue by lclin56** [aquasecurity/tracee#3578]
## Output of `tracee version`:
```
Tracee version: "v0.18.0-rc-38-g52b27bbc7"
```

## Output of `uname -a`:
```
Linux VirtualBox 5.4.0-152-generic #169~18.04.1-Ubuntu SMP Wed Jun 7 22:22:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

## Additional details 
When I attempted to obtain the parsing of file descriptors (fds) using the parse-arguments-fds option, the program threw an error: 
{"level":"error","ts":1697522720.9941738,"msg":"Tracee encountered an error","error":"events.ParseArgsFDs: failed to lookup value 0xc00068e060 in map fd_arg_path_map: operation not permitted"}
{"level":"error","ts":1697522721.0668566,"msg":"Tracee encountered an error","error":"events.ParseArgsFDs: failed to lookup value 0xc0001b4080 in map fd_arg_path_map: operation not permitted"}
{"level":"error","ts":1697522721.227153,"msg":"Tracee encountered an error","error":"events.ParseArgsFDs: failed to lookup value 0xc001cd0060 in map fd_arg_path_map: operation not permitted"}
{"level":"error","ts":1697522721.2292562,"msg":"Tracee encountered an error","error":"events.ParseArgsFDs: failed to lookup value 0xc001cd0110 in map fd_arg_path_map: operation not permitted"}
My command for execution was: "sudo ./dist/tracee --output json --scope comm=bash --scope follow --events read --output option:parse-arguments-fds." What might be the cause of this issue, and how can I resolve it?

**Comment by geyslan** [comment]
Hey @lclin56. Thanks for using Tracee.

It's an error related to lack of permission to interact with bpf. Please check if you have `CAP_SYS_ADMIN` set via `capsh --print`.

**Comment by lclin56** [comment]
> Hey @lclin56. Thanks for using Tracee.
> 
> It's an error related to lack of permission to interact with bpf. Please check if you have `CAP_SYS_ADMIN` set via `capsh --print`.

I overlooked the BPF-related configuration. Thank you very much!
