### ISSUE TITLE
Cloud Foundry container runtime support

### ISSUE THREAD

**Issue by hagitaquasec** [aquasecurity/tracee#3584]
## Description

1. deploy tracee in TAS environment and use tracee to detect "container_create" events
2. deploy cloud-foundry application using the "cf" cli. 
3. expected to receive "container_create" event for the new created container. But the event is missing.

## Output of `tracee version`:
```
v0.11.1
```

## Output of `uname -a`:

```
Linux 2c3cb5b4-c159-485f-9b85-138cd8011e42 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

## Additional details 
The reason why the event is missing, is because tracee does not detect the events as container events. The "container_id" field is empty.
"container_id" is empty because the regex of TAS containers has a different format than crio/containerd formats. e.g:
8a37cb6f-385b-4dd3-732c-34d6
afbd0a34-4372-4c89-64ff-08c5

**Comment by rafaeldtinoco** [comment]
Context about supporting this:

https://github.com/aquasecurity/tracee/pull/3586#discussion_r1364804067
