### ISSUE TITLE
The file paths parsed by the `parse-arguments-fds` option are incorrect.

### ISSUE THREAD

**Issue by lclin56** [aquasecurity/tracee#3609]
## Description

Run the following command: `sudo ./tracee/tracee-ebpf -s pid=91824 -s follow -e open*,close -o option:parse-arguments-fds --capabilities bypass=true` to test the file handle parsing of the `open` and `close` syscalls for the `ls` tool. You may notice that within the same process, the handles opened in the previous context do not correspond to the handles closed in the subsequent context.

For example, in the line

`17:17:57:041828  1000   ls               116411  116411  3                openat                    dirfd: -100, pathname: /lib/x86_64-linux-gnu/libpthread.so.0, flags: O_RDONLY|O_CLOEXEC, mode: 0`

a file "/lib/x86_64-linux-gnu/libpthread.so.0" is opened, and the corresponding handle is "3." 

However, in the following line

`17:17:57:042082  1000   ls               116411  116411  0                close                     fd: 3=/usr/lib/x86_64-linux-gnu/libpthread-2.31.so", handle "3=/usr/lib/x86_64-linux-gnu/libpthread-2.31.so`

is closed.

It is clear that the parsing of the "close" line is incorrect.

## Output of `tracee version`:

```
Tracee version "v0.18.0-rc-38-g52b27bbc7"
```

## Output of `uname -a`:

```
Linux yxu-pc 5.15.0-87-generic #97~20.04.1-Ubuntu SMP Thu Oct 5 08:25:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

## Additional details 

```
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
17:17:57:033024  1000   bash             116411  116411  0                close                     fd: 4=
17:17:57:033084  1000   bash             91824   91824   0                close                     fd: 3=
17:17:57:033229  1000   bash             91824   91824   0                close                     fd: 4=
17:17:57:033785  1000   bash             116411  116411  0                close                     fd: 3=
17:17:57:036524  1000   ls               116411  116411  3                openat                    dirfd: -100, pathname: /etc/ld.so.cache, flags: O_RDONLY|O_CLOEXEC, mode: 0
17:17:57:036873  1000   ls               116411  116411  0                close                     fd: 3=/etc/ld.so.cache
17:17:57:036952  1000   ls               116411  116411  3                openat                    dirfd: -100, pathname: /lib/x86_64-linux-gnu/libselinux.so.1, flags: O_RDONLY|O_CLOEXEC, mode: 0
17:17:57:037779  1000   ls               116411  116411  0                close                     fd: 3=/usr/lib/x86_64-linux-gnu/libc-2.31.so
17:17:57:038731  1000   ls               116411  116411  3                openat                    dirfd: -100, pathname: /lib/x86_64-linux-gnu/libc.so.6, flags: O_RDONLY|O_CLOEXEC, mode: 0
17:17:57:039520  1000   ls               116411  116411  0                close                     fd: 3=/usr/lib/x86_64-linux-gnu/libc-2.31.so
17:17:57:040127  1000   ls               116411  116411  3                openat                    dirfd: -100, pathname: /lib/x86_64-linux-gnu/libpcre2-8.so.0, flags: O_RDONLY|O_CLOEXEC, mode: 0
17:17:57:040734  1000   ls               116411  116411  0                close                     fd: 3=/usr/lib/x86_64-linux-gnu/libpcre2-8.so.0.9.0
17:17:57:041151  1000   ls               116411  116411  3                openat                    dirfd: -100, pathname: /lib/x86_64-linux-gnu/libdl.so.2, flags: O_RDONLY|O_CLOEXEC, mode: 0
17:17:57:041643  1000   ls               116411  116411  0                close                     fd: 3=/usr/lib/x86_64-linux-gnu/libpthread-2.31.so
17:17:57:041828  1000   ls               116411  116411  3                openat                    dirfd: -100, pathname: /lib/x86_64-linux-gnu/libpthread.so.0, flags: O_RDONLY|O_CLOEXEC, mode: 0
17:17:57:042082  1000   ls               116411  116411  0                close                     fd: 3=/usr/lib/x86_64-linux-gnu/libpthread-2.31.so
17:17:57:044496  1000   ls               116411  116411  3                openat                    dirfd: -100, pathname: /proc/filesystems, flags: O_RDONLY|O_CLOEXEC, mode: 0
17:17:57:044979  1000   ls               116411  116411  0                close                     fd: 3=/proc/filesystems
17:17:57:045124  1000   ls               116411  116411  3                openat                    dirfd: -100, pathname: /usr/lib/locale/locale-archive, flags: O_RDONLY|O_CLOEXEC, mode: 0
17:17:57:045477  1000   ls               116411  116411  0                close                     fd: 3=/usr/lib/locale/locale-archive
17:17:57:046272  1000   ls               116411  116411  3                openat                    dirfd: -100, pathname: ., flags: O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC, mode: 0
17:17:57:047016  1000   ls               116411  116411  0                close                     fd: 3=/home/yxu/analysis
17:17:57:049216  1000   ls               116411  116411  0                close                     fd: 1=/dev/pts/1
17:17:57:049775  1000   ls               116411  116411  0                close                     fd: 2=/dev/pts/1
```

**Comment by lclin56** [comment]
I conducted further tests today, and it appears that this issue still persists. I wrote a C program to randomly create 10 files and used Tracee-EBPF to trace the behavior of `open` and `close` operations. From the output, it seems that the files opened and the files closed do not appear to match.

This is my program:
```
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define FILE_COUNT 10
#define FILE_NAME_SIZE 20
#define STRING_SIZE 100

void generate_random_string(char *str, int length) {
    char charset[] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    
    while (length-- > 0) {
        size_t index = (double) rand() / RAND_MAX * (sizeof charset - 1);
        *str++ = charset[index];
    }
    *str = '\0';
}

int main() {
    srand(time(NULL)); 

    for (int i = 0; i < FILE_COUNT; i++) {
        char file_name[FILE_NAME_SIZE];
        char random_string[STRING_SIZE];

        
        sprintf(file_name, "file_%d.txt", rand());
        generate_random_string(random_string, sizeof(random_string) - 1);

        
        FILE *file = fopen(file_name, "w");
        if (file == NULL) {
            perror("Error opening file");
            return 1;
        }
        fprintf(file, "%s\n", random_string);
        fclose(file);
    }

    return 0;
}
```
This is the command I executed for tracing：
`sudo ./tracee/tracee-ebpf -s pid=118818 -s follow -e open*,close -o option:parse-arguments-fds -o out-file:/tmp/events.txt --capabilities bypass=true`

This is the output from Tracee：
`TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
16:29:31:028214  1000   bash             118818  118818  0                close                     fd: 5=
16:29:31:028447  1000   bash             118818  118818  0                close                     fd: 6=
16:29:31:028571  1000   bash             118818  118818  0                close                     fd: 4=
16:29:31:029822  1000   bash             147697  147697  0                close                     fd: 5=
16:29:31:030303  1000   bash             147697  147697  0                close                     fd: 6=
16:29:31:030945  1000   bash             147697  147697  0                close                     fd: 4=
16:29:31:031043  1000   bash             147697  147697  0                close                     fd: 3=
16:29:31:034473  1000   bash             118818  118818  0                close                     fd: 3=
16:29:31:035773  1000   bash             118818  118818  0                close                     fd: 3=
16:29:31:035842  1000   bash             118818  118818  0                close                     fd: 4=
16:29:31:035973  1000   bash             147699  147699  0                close                     fd: 4=
16:29:31:036080  1000   bash             147699  147699  0                close                     fd: 3=
16:29:31:036631  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: /etc/ld.so.cache, flags: O_RDONLY|O_CLOEXEC, mode: 0
16:29:31:036710  1000   test_file        147699  147699  0                close                     fd: 3=/usr/lib/x86_64-linux-gnu/libc-2.31.so
16:29:31:036762  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: /lib/x86_64-linux-gnu/libc.so.6, flags: O_RDONLY|O_CLOEXEC, mode: 0
16:29:31:036859  1000   test_file        147699  147699  0                close                     fd: 3=/usr/lib/x86_64-linux-gnu/libc-2.31.so
16:29:31:037286  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: file_1394120526.txt, flags: O_WRONLY|O_CREAT|O_TRUNC, mode: 438
16:29:31:037465  1000   test_file        147699  147699  0                close                     fd: 3=/home/yxu/analysis/test/file_733014300.txt
16:29:31:037517  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: file_1544018474.txt, flags: O_WRONLY|O_CREAT|O_TRUNC, mode: 438
16:29:31:037593  1000   test_file        147699  147699  0                close                     fd: 3=/home/yxu/analysis/test/file_733014300.txt
16:29:31:037640  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: file_786024187.txt, flags: O_WRONLY|O_CREAT|O_TRUNC, mode: 438
16:29:31:037747  1000   test_file        147699  147699  0                close                     fd: 3=/home/yxu/analysis/test/file_733014300.txt
16:29:31:037792  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: file_733014300.txt, flags: O_WRONLY|O_CREAT|O_TRUNC, mode: 438
16:29:31:037879  1000   test_file        147699  147699  0                close                     fd: 3=/home/yxu/analysis/test/file_1186576285.txt
16:29:31:037924  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: file_1186576285.txt, flags: O_WRONLY|O_CREAT|O_TRUNC, mode: 438
16:29:31:037989  1000   test_file        147699  147699  0                close                     fd: 3=/home/yxu/analysis/test/file_1186576285.txt
16:29:31:038035  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: file_1948931735.txt, flags: O_WRONLY|O_CREAT|O_TRUNC, mode: 438
16:29:31:038145  1000   test_file        147699  147699  0                close                     fd: 3=/home/yxu/analysis/test/file_1618188760.txt
16:29:31:038191  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: file_191064289.txt, flags: O_WRONLY|O_CREAT|O_TRUNC, mode: 438
16:29:31:038255  1000   test_file        147699  147699  0                close                     fd: 3=/home/yxu/analysis/test/file_1618188760.txt
16:29:31:038379  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: file_1851748232.txt, flags: O_WRONLY|O_CREAT|O_TRUNC, mode: 438
16:29:31:038447  1000   test_file        147699  147699  0                close                     fd: 3=/home/yxu/analysis/test/file_1618188760.txt
16:29:31:038493  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: file_1240824956.txt, flags: O_WRONLY|O_CREAT|O_TRUNC, mode: 438
16:29:31:038641  1000   test_file        147699  147699  0                close                     fd: 3=/home/yxu/analysis/test/file_1618188760.txt
16:29:31:038688  1000   test_file        147699  147699  3                openat                    dirfd: -100, pathname: file_1618188760.txt, flags: O_WRONLY|O_CREAT|O_TRUNC, mode: 438
16:29:31:038782  1000   test_file        147699  147699  0                close                     fd: 3=/home/yxu/analysis/test/file_1618188760.txt
16:29:31:039287  1000   bash             118818  118818  0                close                     fd: 5=
16:29:31:039358  1000   bash             118818  118818  0                close                     fd: 6=
16:29:31:039401  1000   bash             118818  118818  0                close                     fd: 4=
16:29:31:039466  1000   bash             147700  147700  0                close                     fd: 5=
16:29:31:039546  1000   bash             147700  147700  0                close                     fd: 6=
16:29:31:039646  1000   bash             147700  147700  0                close                     fd: 4=
16:29:31:039693  1000   bash             147700  147700  0                close                     fd: 3=
16:29:31:042026  1000   bash             118818  118818  0                close                     fd: 3=
End of events stream
Stats: {EventCount:{value:44} EventsFiltered:{value:0} NetCapCount:{value:0} BPFLogsCount:{value:0} ErrorCount:{value:0} LostEvCount:{value:0} LostWrCount:{value:0} LostNtCapCount:{value:0} LostBPFLogsCount:{value:0}}
`

**Comment by geyslan** [comment]
It seems clearly a race condition since the bpf map uses only pid, tid and fd for the key. So opening and closing FDs so fast would keep the same FD in use and taint the map. We need to think in a way of key it with more metadata that could be in the event and reused from the userland.

**Comment by lclin56** [comment]
Thank you for your response. I also thought about this issue. So, does this version of Tracee currently not have a solution for this problem?

**Comment by geyslan** [comment]
@lclin56 sorry for the delay. I'm not saying yet there won't be a fix in this release, but let me look more carefully.

**Comment by lclin56** [comment]
@geyslan "Thank you for your reply. I am also reviewing the relevant code to find a solution, and I look forward to hearing back from you soon."
