### ISSUE TITLE
Measure performance impact

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#364]
As we want tracee to be a runtime security solution, and as we add more logic that executes on every syscall in the system - we need to test the performance impact of Tracee on the system.
While performing the test, one should take into account that the following configurable parameters might affect the results:
1. Number of "active" events. Especially interesting is running tracee with the "default" set of events, but other configurations should be checked as well.
2. Trace mode - different tracing modes trace different number of processes
3. Kernel version - the BPF subsytem in the Linux kernel is being actively developed, which may cause different results on different kernel versions

**Comment by yanivagman** [comment]
Starting from kernel version 5.1, it is possible to measure the overhead of eBPF programs using program stats:
https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=492ecee892c2a4ba6a14903d5d586ff750b7e805

This will enable us to measure overhead correctly for different scenarios

**Comment by xjas** [comment]
Sorry to disturb, I noticed that we can hook sys_enter/sys_exit, which are the entrance to all the syscalls, I just want to know if there are some performance test of the feature?

Or is there some advice of the relevant tests before using the hooks:sys_enter/sys_exit

**Comment by rafaeldtinoco** [comment]
I'm closing this as I believe https://github.com/aquasecurity/tracee/issues/1986 is currently addressing this issue (we usually should keep this old one and mark the other as duplicate, but the new one is being worked as has more context).

**Comment by xjas** [comment]
> Check https://github.com/aquasecurity/tracee/pull/1985, it might help you in testing overhead for sys_enter/sys_exit. Or you can just follow https://github.com/aquasecurity/tracee/issues/1986 as well.

Sorry to bother again. 

Maybe I'm not fully understand, I think tracee-bench is to test tracee's performance.

Take sys_enter/sys_exit as an example, tracee-bench can collect info such as the tracee's CPU/Memory usage when in different rate of events emitted per second.

I don't know if it's considerable to test the system stress(eg: cpu consumed in kernel space because of the ebpf-hook)?
