### ISSUE TITLE
Cannot create probe on symbols with duplicate entries in kallsyms (multiple addresses) in recent kernels

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3653]
## Description

```
sudo ./dist/tracee --install-path /tmp/tracee \
--cache cache-type=mem --cache mem-cache-size=512 --output option:sort-events \
--output none --output option:parse-arguments --events openat
{"level":"warn","ts":1698863276.173086,"msg":"libbpf: prog 'trace_load_elf_phdrs': failed to create kprobe 'load_elf_phdrs+0x0' perf event: Cannot assign requested address"}
```

kprobe attachment fails in some "recent" (and LTS) kernels. 

## Output of `tracee version`:

```
Tracee version: "v0.18.0-rc-106-g7ba03ff68"
```

## Output of `uname -a`:

```
Linux rugged 6.1.60-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 25 Oct 2023 11:10:15 +0000 x86_64 GNU/Linux
```

**Comment by rafaeldtinoco** [comment]
I believe that "load_elf_phdrs" can't have more than 1 kprobe handler. So the "SchedProcessExec" is competing with "SignalSchedProcessExec" because they both declare the same probe (instead of depending on the LoadElfPhdrs event). This might explain why picking the LoadElfPhdrs event generates 2 errors:

```
$ sudo ./dist/tracee --install-path /tmp/tracee --cache ca
che-type=mem --cache mem-cache-size=512 --output option:sort-events --output none --o
utput option:parse-arguments --events load_elf_phdrs
{"level":"warn","ts":1698863397.3871963,"msg":"libbpf: prog 'trace_load_elf_phdrs': failed to create kprobe 'load_elf_phdrs+0x0' perf event: Cannot assign requested address"}
{"level":"error","ts":1698863397.3872733,"msg":"Event canceled because of missing probe dependency","missing probe":54,"event":"load_elf_phdrs"}
{"level":"warn","ts":1698863397.3873827,"msg":"libbpf: prog 'trace_load_elf_phdrs': failed to create kprobe 'load_elf_phdrs+0x0' perf event: Cannot assign requested address"}
```

**Comment by rafaeldtinoco** [comment]
Might be something in my environment only, testing.

**Comment by rafaeldtinoco** [comment]
I also got this with:

Linux rugged 6.5.9-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000 x86_64 GNU/Linux

which makes me think it could be a kconfig related option (rather than a broken kernel or build).

**Comment by geyslan** [comment]
> I also got this with:
> 
> Linux rugged 6.5.9-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000 x86_64 GNU/Linux
> 
> which makes me think it could be a kconfig related option (rather than a broken kernel or build).

But it should log a warning if is a kconfig miss.

**Comment by rafaeldtinoco** [comment]
Okay, since I had a problem with a recent upstream kernel (6.5) and a older one (6.1-lts, which might have backported a patch) I found something:


```
commit b022f0c7e404
Author: Francis Laniel <flaniel@linux.microsoft.com>
Date:   Fri Oct 20 07:42:49 2023

    tracing/kprobes: Return EADDRNOTAVAIL when func matches several symbols
    
    When a kprobe is attached to a function that's name is not unique (is
    static and shares the name with other functions in the kernel), the
    kprobe is attached to the first function it finds. This is a bug as the
    function that it is attaching to is not necessarily the one that the
    user wants to attach to.
    
    Instead of blindly picking a function to attach to what is ambiguous,
    error with EADDRNOTAVAIL to let the user know that this function is not
    unique, and that the user must use another unique function with an
    address offset to get to the function they want to attach to.
    
    Link: https://lore.kernel.org/all/20231020104250.9537-2-flaniel@linux.microsoft.com/
    
    Cc: stable@vger.kernel.org
    Fixes: 413d37d1eb69 ("tracing: Add kprobe-based event tracer")
    Suggested-by: Masami Hiramatsu <mhiramat@kernel.org>
    Signed-off-by: Francis Laniel <flaniel@linux.microsoft.com>
    Link: https://lore.kernel.org/lkml/20230819101105.b0c104ae4494a7d1f2eea742@kernel.org/
    Acked-by: Masami Hiramatsu (Google) <mhiramat@kernel.org>
    Signed-off-by: Masami Hiramatsu (Google) <mhiramat@kernel.org>
```

if there are multiple matches for a symbol it might return EADDRNOTAVAIL when trying to attach a kprobe to that function name.

**Comment by rafaeldtinoco** [comment]
If that is right, then we might be attaching kprobes just to first addresses (and not all of them) when having kprobes set to functions that have multiple addresses. => This could be a **current** bug.

Reasons for functions to have multiple addresses are, among others: we are kprobing a "static function" and, because they're static, they should not be available in kallsyms (not directly exported) nor to kprobe mechanism.

Fortunately, or not, there is also a kconfig option: `CONFIG_KALLSYMS_ALL` that tries to pick static function addresses and make them available to both (causing duplicates, for example).

With that said, if we are doing kprobes on duplicate symbols, it might be happening what patch `b022f0c7e404` describes (attaching to the first address only and missing events from the second when the second is executed).

**Comment by rafaeldtinoco** [comment]
There is already a fix on top of that patch:

```
commit 926fe783c8a6
Author: Andrii Nakryiko <andrii@kernel.org>
Date:   Fri Oct 27 20:31:26 2023

    tracing/kprobes: Fix symbol counting logic by looking at modules as well
    
    Recent changes to count number of matching symbols when creating
    a kprobe event failed to take into account kernel modules. As such, it
    breaks kprobes on kernel module symbols, by assuming there is no match.
    
    Fix this my calling module_kallsyms_on_each_symbol() in addition to
    kallsyms_on_each_match_symbol() to perform a proper counting.
    
    Link: https://lore.kernel.org/all/20231027233126.2073148-1-andrii@kernel.org/
    
    Cc: Francis Laniel <flaniel@linux.microsoft.com>
    Cc: stable@vger.kernel.org
    Cc: Masami Hiramatsu <mhiramat@kernel.org>
    Cc: Steven Rostedt <rostedt@goodmis.org>
    Fixes: b022f0c7e404 ("tracing/kprobes: Return EADDRNOTAVAIL when func matches several symbols")
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Song Liu <song@kernel.org>
    Signed-off-by: Masami Hiramatsu (Google) <mhiramat@kernel.org>
```

so there might be more in next days. Need to watch (and check how the duplicates will be handled, so we decide what to do in tracee).

**Comment by AlonZivony** [comment]
Interesting.
I think that most of the hooks that I know that we use are not likely to be affected by it.
I agree that we should probably put hooks on all occurrences if this happens.

**Comment by rafaeldtinoco** [comment]
Okay so the summary for this issue is the following, recent kernels have the following kernel commit:

```
commit b022f0c7e404
Author: Francis Laniel <flaniel@linux.microsoft.com>
Date:   Fri Oct 20 07:42:49 2023

    tracing/kprobes: Return EADDRNOTAVAIL when func matches several symbols
    
    When a kprobe is attached to a function that's name is not unique (is
    static and shares the name with other functions in the kernel), the
    kprobe is attached to the first function it finds. This is a bug as the
    function that it is attaching to is not necessarily the one that the
    user wants to attach to.
    
    Instead of blindly picking a function to attach to what is ambiguous,
    error with EADDRNOTAVAIL to let the user know that this function is not
    unique, and that the user must use another unique function with an
    address offset to get to the function they want to attach to.
    
    Link: https://lore.kernel.org/all/20231020104250.9537-2-flaniel@linux.microsoft.com/
    
    Cc: stable@vger.kernel.org
    Fixes: 413d37d1eb69 ("tracing: Add kprobe-based event tracer")
    Suggested-by: Masami Hiramatsu <mhiramat@kernel.org>
    Signed-off-by: Francis Laniel <flaniel@linux.microsoft.com>
    Link: https://lore.kernel.org/lkml/20230819101105.b0c104ae4494a7d1f2eea742@kernel.org/
    Acked-by: Masami Hiramatsu (Google) <mhiramat@kernel.org>
    Signed-off-by: Masami Hiramatsu (Google) <mhiramat@kernel.org>
```
The commit was only introduced in v6.6 kernel, but since it was also sent to the stable list, it was applied in some older kernels (and distributions will start using it, and tracee would start having errors by the time those kernels are used).

This commit changes the behavior for kprobe attachments. Whenever a kprobe is being created, if the symbols the kprobe attaches to isn't unique (meaning that /proc/kallsyms has multiple address for the same symbol, for example) then, instead of attaching to "one of them", up to this commit, the attachment won't occur, resulting in an error similar to:

```
{"L":"WARN","T":"2023-11-29T16:36:36.013-0300","M":"libbpf: prog 'trace_load_elf_phdrs': failed to create kprobe 'load_elf_phdrs+0x0' perf event: Cannot assign requested address"}
```

My proposed course of action here is the following:

- replace libbpfgo package to a local ./3rdparty/libbpfgo so you can change libbpfgo and test it right away.
- within tracee attachProbes() function, tracee attaches all loaded eBPF programs to their hooks. It is likely that the error comes from the attachment phase (but it could be coming from the load phase as well, when the object is loaded, or, maybe not, because if I remove load_elf_phdrs from the probes dependency I don't get the error). 
- The TraceProbe type calls libbpfgo for attaching the hooks:
```go
	switch p.probeType {
	case KProbe:
		link, err = prog.AttachKprobe(p.eventName)
	case KretProbe:
		link, err = prog.AttachKretprobe(p.eventName)
	case Tracepoint:
		tp := strings.Split(p.eventName, ":")
		tpClass := tp[0]
		tpEvent := tp[1]
		link, err = prog.AttachTracepoint(tpClass, tpEvent)
	case RawTracepoint:
		tpEvent := strings.Split(p.eventName, ":")[1]
		link, err = prog.AttachRawTracepoint(tpEvent)
	}
``` 
So, both the kprobe and kretprobe are affected. Both translate into a libbpfgo function that calls `bpf_program__attach_kprobe_opts()` (or similar). I believe that the struct `bpf_kprobe_opts` passed to the bpf_program__attachXXX() functions contain:

```C
struct bpf_kprobe_opts {
	/* size of this struct, for forward/backward compatibility */
	size_t sz;
	/* custom user-provided value fetchable through bpf_get_attach_cookie() */
	__u64 bpf_cookie;
	/* function's offset to install kprobe to */
	size_t offset;
	/* kprobe is return probe */
	bool retprobe;
	/* kprobe attach mode */
	enum probe_attach_mode attach_mode;
	size_t :0;
};
#define bpf_kprobe_opts__last_field attach_mode
```

and that the "offset" here is the kernel symbol address. Example:

```
$ sudo cat /proc/kallsyms | grep " load_elf_phdrs"
ffffffff8f088eb0 t load_elf_phdrs
ffffffff8f08ba40 t load_elf_phdrs
```

Attach would fail for the eBPF Program that uses this hook because there are 2 addresses for it. Then, we can make libbpfgo call the `bpf_program__attachXXX()` two times, but instead of using the symbol name only (like we do), we can specify in one call `ffffffff8f088eb0` as the offset and in the other call `ffffffff8f08ba40` as the offset.

This would make our eBPF program to run on both cases (whenever those 2 addresses are called as functions from the kernel). Nowadays, with the buggy kernels (all until this fix was done) our eBPF programs are running only in one of them (and we dont know which).

**Comment by rafaeldtinoco** [comment]
I'll be mentoring @josedonizetti on this one until further notice.

**Comment by rafaeldtinoco** [comment]
I believe https://github.com/aquasecurity/tracee/issues/3798 needs to be sorted out, and then I need a libbpfgo change adding the functions to attach the kpropes to specific offsets, and then the real fix for this issue.

**Comment by rafaeldtinoco** [comment]
With https://github.com/aquasecurity/libbpfgo/pull/399 merged I believe I can fix this issue in Tracee by giving the symbol offsets in the kprobe attachment.

**Comment by rafaeldtinoco** [comment]
Addressed by https://github.com/aquasecurity/tracee/pull/3802
