### ISSUE TITLE
Signatures receive events from pipeline even when are not used

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#3656]
## Description

It seems that signatures `OnEevent` function is called even when they are not used.
Just noticed when for debugging I have put a print inside the `ld_preload` signature, and it printed even when I ran tracee in the following way:
```bash
sudo ./dist/tracee -e sched_process_exec -o json:./out.json -o option:exec-env
```
I don't see any reason for this to happen, as the unused events eBPF programs are not used when the event is not used.

## Output of `tracee version`:

```
Tracee version: "v0.18.0-rc-70-gcc534be9b"
```

## Output of `uname -a`:

```
Linux Alon-Zivony 6.3.6-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Mon Jun 12 11:59:43 IDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rafaeldtinoco** [comment]
Have you tried for other events ? Exec is always enabled so that might explain (not saying it's good). Let's see if events not enabled by default also make that happen please.

**Comment by AlonZivony** [comment]
> Have you tried for other events ? Exec is always enabled (but now always emitted) so that might explain (not saying it's good). Let's see if events not enabled by default also make that happen please.

I will check and update this issue accordingly

**Comment by NDStrahilevitz** [comment]
Possibly a duplicate of #3195 and related issue #3190. @AlonZivony could you confirm these describe the same issue?

**Comment by AlonZivony** [comment]
> Possibly a duplicate of #3195 and related issue #3190. @AlonZivony could you confirm these describe the same issue?

It is very similar. The difference here is that I am not sure of the source of the problem.
I see that it was closed as completed already, so if you prefer we can just reopen #3190.

**Comment by NDStrahilevitz** [comment]
Yes it seems to be the same. Both of our reproduction steps include compiling tracee with "extra" stuff, but yours isn't breaking tracee. Let's keep this in your issue, i'll close the previous one.
