### ISSUE TITLE
kconfig management refactor

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#3667]
## Description

Context: https://github.com/aquasecurity/tracee/pull/3642#pullrequestreview-1707260838

> LGTM (as a mitigation). I would open a new issue for the kconfig refactoring (removing from libbpfgo, making sure it is still needed in tracee, make it simpler if it is). I know there are signatures that assume things that are only possible to know from kconfig (at least in an easy way), such as size of pages for some architectures, paging level hierarchy size, etc.

**Comment by yanivagman** [comment]
kconfig management was moved from libbpfgo to pkg/utils/environment.
there is no specific task here other than that, so I'm closing this one
