### ISSUE TITLE
don't try to load events that depend on missing feature (e.g kallsyms)

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#3668]
- [ ] automatize dependency (event/symbol) check in the event type itself

**Comment by rafaeldtinoco** [comment]
What does this mean ?

**Comment by geyslan** [comment]
The main issue is to list all events that depend on kallsyms and disable them by default on macOS, as discussed in last month's meetings. `automating dependency (event/symbol) checking on the event type itself` would be a task to create methods in the event definition that retrieve dependencies/requirements.

**Comment by geyslan** [comment]
It was already done.
