### ISSUE TITLE
Data source for dns<->ip mapping

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#3678]
It would be useful for networking related signatures to be able to check the relation of ip/dns addresses to the other and vice versa.
Tracee can track these relations through it's DNS events and resolving queries itself where needed, and provide them to signatures through a data source. 

The data source query should give the following (a more accurate schema will be given once the PR is finalized)
[string: ip] -> matched dns records
[string: dns] -> matched A and AAAA records + dns aliases and cname

**Comment by itaysk** [comment]
@NDStrahilevitz can you please add the data structure of this data source? what is key and what is value.

**Comment by NDStrahilevitz** [comment]
@itaysk I've given an outline of what the data source should more or less give, and will post the accurate schema once it's finalized in the PR.
