### ISSUE TITLE
Signatures feed into the early pipeline stages

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#3680]
Currently, signatures are both events and not events.
They are converted to events, but are only inserted into the "sink" stage of the events pipeline.
This makes little sense, as this disables the option to use signatures in signatures (though they are an event), and even maybe processing them inside Tracee for other uses in the future.
I think the signatures should at least be fed to the input of the signatures engine, instead of the "sink" stage.

**Comment by yanivagman** [comment]
I agree that in the future "signature events" can become a dependency of other "signature events". I think that in this effort we should totally remove the signature engine, which was part of the legacy tracee-rules. Instead, such user-defined events, of which "signature events" are a private case, should define their dependencies in other events, just like what we do today with "derived events". Eventually these two mechanisms of "derived events" and "signature events" should be combined into one mechanism of user defined events.

**Comment by AlonZivony** [comment]
I don't see a reason to not implement signature on signature dependency right now like I have done in #3681.
Unless you want to change the event selector, there is no reason to not support it currently. And even if not, either way all signatures will change their event selecting method so it doesn't matter to enable this also right now and for it to be prone to change.
In the end of the day its very easy to implement this mechanism, so it shouldn't be delayed.
