### ISSUE TITLE
README links to Docker and Kubernetes Docs are 404

### ISSUE THREAD

**Issue by raesene** [aquasecurity/tracee#3684]
Just looking through the Tracee readme and at the moment when I click on the "Docker Getting Started Guide" or "Kubernetes Getting Started Guide" I'm getting 404. 

Docker link goes to https://aquasecurity.github.io/tracee/latest/docker.md should be https://aquasecurity.github.io/tracee/latest/docs/install/docker/ ?

Kubernetes link goes to https://aquasecurity.github.io/tracee/latest/kubernetes.md , should be https://aquasecurity.github.io/tracee/latest/docs/install/kubernetes/ ?

**Comment by rafaeldtinoco** [comment]
Thanks a lot for reserving the time to let us know!
