### ISSUE TITLE
Kubernetes Information on tracee events doesn't appear on EKS

### ISSUE THREAD

**Issue by michaelkatch** [aquasecurity/tracee#3689]
## Description
 
Hey,
I used installed tracee helm chart on eks version 1.27 and 1.25 
The helm charts deployed tracee version 0.18.1.
To do so I followed the instructions found here - https://aquasecurity.github.io/tracee/v0.19/tutorials/k8s-policies/
I added to tracee policy "sched_process_exec" event and restarted the daemonset. 
As you can see from the logs the Kubernetes information is empty for every event/signature.

I tried using global scope (the default) and tried changing it to container scope and nothing helped.

## Output of `tracee logs`:

```
{"level":"error","ts":1699967074.7665052,"msg":"error triggering container enrich in control plane","error":"containers.(*Containers).EnrichCgroupInfo: container already deleted"}

{"timestamp":1699967074786654029,"threadStartTime":1699967074754526405,"processorId":1,"processId":1,"cgroupId":1498,"threadId":1,"parentProcessId":741122,"hostProcessId":806569,"hostThreadId":806569,"hostParentProcessId":741122,"userId":0,"mountNamespace":4026532537,"pidNamespace":4026532538,"processName":"sh","executable":{"path":""},"hostName":"test-pod-1","containerId":"72ce9c01309449fcbe7374f7a3b76b9d561a5969b7ac8f5374405186858619a6","container":{"id":"72ce9c01309449fcbe7374f7a3b76b9d561a5969b7ac8f5374405186858619a6"},"kubernetes":{},"eventId":"713","eventName":"sched_process_exec","matchedPolicies":["signature-events"],"argsNum":11,"returnValue":0,"syscall":"execve","stackAddresses":null,"contextFlags":{"containerStarted":true,"isCompat":false},"threadEntityId":1076268326,"processEntityId":1076268326,"parentEntityId":2561041611,"args":[{"name":"cmdpath","type":"const char*","value":"/usr/bin/sh"},{"name":"pathname","type":"const char*","value":"/usr/bin/bash"},{"name":"dev","type":"dev_t","value":149},{"name":"inode","type":"unsigned long","value":6884317},{"name":"ctime","type":"unsigned long","value":1699952785706805776},{"name":"inode_mode","type":"umode_t","value":33261},{"name":"interpreter_pathname","type":"const char*","value":null},{"name":"interpreter_dev","type":"dev_t","value":null},{"name":"interpreter_inode","type":"unsigned long","value":null},{"name":"interpreter_ctime","type":"unsigned long","value":null},{"name":"argv","type":"const char**","value":["sh","-c","sleep 999"]},{"name":"interp","type":"const char*","value":"/usr/bin/sh"},{"name":"stdin_type","type":"string","value":"S_IFCHR"},{"name":"stdin_path","type":"char*","value":"/dev/null"},{"name":"invoked_from_kernel","type":"int","value":0},{"name":"env","type":"const char**","value":null}]}

{"timestamp":1699967074790669995,"threadStartTime":1699967074754526405,"processorId":1,"processId":1,"cgroupId":1498,"threadId":1,"parentProcessId":1,"hostProcessId":806569,"hostThreadId":806569,"hostParentProcessId":741122,"userId":0,"mountNamespace":4026532537,"pidNamespace":4026532538,"processName":"sleep","executable":{"path":""},"hostName":"test-pod-1","containerId":"72ce9c01309449fcbe7374f7a3b76b9d561a5969b7ac8f5374405186858619a6","container":{"id":"72ce9c01309449fcbe7374f7a3b76b9d561a5969b7ac8f5374405186858619a6"},"kubernetes":{},"eventId":"713","eventName":"sched_process_exec","matchedPolicies":["signature-events"],"argsNum":15,"returnValue":0,"syscall":"execve","stackAddresses":null,"contextFlags":{"containerStarted":true,"isCompat":false},"threadEntityId":1076268326,"processEntityId":1076268326,"parentEntityId":2561041611,"args":[{"name":"cmdpath","type":"const char*","value":"/usr/bin/sleep"},{"name":"pathname","type":"const char*","value":"/usr/bin/coreutils"},{"name":"dev","type":"dev_t","value":149},{"name":"inode","type":"unsigned long","value":6291895},{"name":"ctime","type":"unsigned long","value":1699952785730805852},{"name":"inode_mode","type":"umode_t","value":33261},{"name":"interpreter_pathname","type":"const char*","value":"/usr/lib64/ld-2.28.so"},{"name":"interpreter_dev","type":"dev_t","value":149},{"name":"interpreter_inode","type":"unsigned long","value":18975284},{"name":"interpreter_ctime","type":"unsigned long","value":1699952786674808884},{"name":"argv","type":"const char**","value":["/usr/bin/coreutils","--coreutils-prog-shebang=sleep","/usr/bin/sleep","999"]},{"name":"interp","type":"const char*","value":"/usr/bin/coreutils"},{"name":"stdin_type","type":"string","value":"S_IFCHR"},{"name":"stdin_path","type":"char*","value":"/dev/null"},{"name":"invoked_from_kernel","type":"int","value":0},{"name":"env","type":"const char**","value":null}]}


```

## Output of `tracee when executed`:

```
"level":"warn","ts":1699952901.596234,"msg":"KConfig: could not check enabled kconfig features","error":"could not read /boot/config-5.10.198-187.748.amzn2.x86_64: stat /boot/config-5.10.198-187.748.amzn2.x86_64: no such file or directory"}


```

**Comment by NDStrahilevitz** [comment]
Likely related to #3003 - will investigate.

**Comment by michaelkatch** [comment]
@NDStrahilevitz  Please reach me via teams if you need help reproducing/more information

**Comment by itaysk** [comment]
@michaelkatch any update?

**Comment by NDStrahilevitz** [comment]
So from the immediate investigation I had time to do, it seems that the cause here is not related to #3003. I suspect instead that it's a pipeline issue and container enrichment is actually stuck in these environments.

**Comment by AlonZivony** [comment]
It seems that in EKS the `kubepods.slice` directory is missing from the mounted cgroup cpuset directory (`/sys/fs/cgroup/cpuset`).
After checking from the host of the node, we saw that it is available from there. It is not available from the pod's cgroup fs.
The possible solution for it, as already should be implemented by tracee but for some reason doesn't work, is to remount the cgroup directory using the host cgroup namespace.

**Comment by AlonZivony** [comment]
After more digging, @NDStrahilevitz and I figured that we can find the right cgroup directory if we are in the same mount namespace as the host.
So for now, the easy solution for this problem is to run Tracee from the host mount namespace.

**Comment by AlonZivony** [comment]
I add here that adding in the pod yaml a mounting of the host's `/sys/fs/cgroup` on the pod in the same path solved the problem.
So maybe adding it as a requirement for running Tracee in Kubernetes will be the solution.

**Comment by NDStrahilevitz** [comment]
> I add here that adding in the pod yaml a mounting of the host's `/sys/fs/cgroup` on the pod in the same path solved the problem. So maybe adding it as a requirement for running Tracee in Kubernetes will be the solution.

This is what the current solution attempts to avoid.

**Comment by AlonZivony** [comment]
> This is what the current solution attempts to avoid.

Wrote it to make all solutions available on the thread.
For now, if someone has a similar issue, he can use this to solve it.
The long term solution can be something else.

**Comment by NDStrahilevitz** [comment]
I'm starting to think that mounting `/sys/fs/cgroup` is the only reasonable option we have.
I've tried a solution where we changed namespace to the root mount namespace, and it works, but it breaks every path we use throughout tracee in container environments. 
This is because in go you can only move mount namespaces once, and that is before the runtime starts, because the `setns` call requires a single threaded process, and golang is almost immediately multi threaded. The trick is to do the switch in a cgo constructor, the catch being, you can't switch back.
So if we switch, paths are broken. If we don't, there doesn't seem to be any other solution, as AWS will prevent us from mounting the correct file system.

**Comment by NDStrahilevitz** [comment]
@yanivagman FYI to help choose between the options.

**Comment by AlonZivony** [comment]
An option is to create a sub-process which will move to the mount ns of the host, and use it as a worker for probes on the cgroup fs.
I agree that this is also not optimal, and I think that requiring the mounting of tracee is not too much of a big deal.
