### ISSUE TITLE
Cgroups control plane overrides ebpf map with unrelated hierarchy id

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#3695]
The following code section in the cgroups control plane is faulty:
```
info, err := ctrl.cgroupManager.CgroupMkdir(cgroupId, path, hId)
if err != nil {
     return errfmt.WrapError(err)
}
if info.Container.ContainerId == "" && !info.Dead {
     // delete cgroup from ebpf map
}
```

The CgroupMkdir call returns an empty value and **no** error when applying a cgroup id from a non default hierarchy (in cgroup v1). The result will have the ContainerID field set to empty and info.Dead set to `false`. Since the next section will attempt deletion for every hierarchy, it could potentially delete the correctly set cgroup id from the default hierarchy.

**Comment by itaysk** [comment]
@NDStrahilevitz ?

**Comment by NDStrahilevitz** [comment]
> @NDStrahilevitz ?

This was opened in a rush and probably isn't accurate. I opened it while investigating #3689 and seeing logs which looked out of place due to the current implementation, this was one of the things I _thought_ was happening.
