### ISSUE TITLE
network connection event

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#3697]
new network event to indicate connection-oriented communication. we already have tcp level connections which are packet level, this event will join as a less verbose option. also, we want to add more user friendly information there such as dns (depends on https://github.com/aquasecurity/tracee/issues/3678).

```
net_tcp_connect {
  src : "1.2.3.4"
  dst: "4.3.2.1"
  src_port: 5677
  dst_port: 80
  src_dns: ["itay_mbp"]
  dst_dns: ["itaysk.com","blog.itaysk.com","internal-server"]
}
```

field names were chosen to align with other network events naming convention.
src_dns is likely less attractive but we might add it for completeness if not too hard.
DNS information is an array of names that participated in the resolution of the IP, including CNAME and A, and possibly multiple of each. the array is ordered by the order of resolution, so that the beginning of the array is closer to the user's query and the ending is closer to the servers. we're not sure this is the best solution but it's a practical first step.
DNS information is based only on the internal DNS cache (#3678) and we won't do any lookups at runtime

TBD:
connection might be traced on both parties. do we need to indicate directionality or src/dst is sufficient.
which hook? likely derive from existing network events

**Comment by rafaeldtinoco** [comment]
I'll implement this one once we have https://github.com/aquasecurity/tracee/pull/3706 from @NDStrahilevitz merged.

**Comment by rafaeldtinoco** [comment]
Initial event, does not look like the one described here, but its based on "security_socket_connect" event (as requested by users).
https://github.com/aquasecurity/tracee/pull/3738

**Comment by rafaeldtinoco** [comment]
An initial net_tcp_connect event was created at https://github.com/aquasecurity/tracee/pull/3738 based on security_socket_connect LSM hook.
