### ISSUE TITLE
Add WriteableDataSource interface

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#3704]
## Summary

Add a new capability to Tracee — the ability for data sources to have an optional "Write" method.

## Background

In Tracee, data sources are currently used as a means to access data external to the signature context. They serve as a kind of bridge or interface to this data. The key aspect here is that these data sources are 'opaque', which means their internal workings or the nature of the external data they access are not transparent or directly manipulated by signatures. Initially, the design of these data sources did not include the functionality to write (or modify) the data they can access; they were only meant for reading it in signatures.
Historical Context: In Tracee, any writing of data was an internal process to the context of the data source. Tracee had certain "state managers" that were modified by events occurring within Tracee. These state managers then provided data to what are known as 'signatures' through the data sources. Thus, any writing in these data sources was internal to Tracee. In simple terms, data sources were used as a means to read the data stored or managed by Tracee internally, but they weren't used to modify data, only to expose it in signatures.

## Why

The proposal indicates that these data sources, while currently limited to reading internal state data, could theoretically be expanded to access and possibly modify data in external systems like databases or web endpoints.
The new feature is intended for users who don't want to or can't set up their own service to write data that is accessible through a Tracee data source. In such cases, Tracee could offer a direct method to transfer or write this data to the external sources. 

## Design

The following interfaces would be added:
1. in detect.go:
```
type WriteableDataSource interface {
    Datasource
    Write(key, value any) error
}

var ErrDataWriteFailed = errors.New("data source failed to unpack or write data")
```

2. The following change will be done in the existing data source interface
```
type Datasource interface {
    ...
    Get(key interface{}) (map[string]interface{}, error) -> Get(key any) (any, error)
    ...
}
```

3. The following gRPC methods and messages will be added to the existing TraceeService:
```
message WriteDataSourceRequest {
    string id;
    string namespace;
   google.anypb key;
   google.anypb value;
}

message WriteDataSourceResponse{}

service TraceeService {
    ...
    rpc WriteDataSource(WriteDataSourceRequest) returns (WriteDataSourceResponse)
    rpc StreamDataSource(stream WriteDataSourceRequest) returns (WriteDataSourceResponse)
}
```

The RPC will return OK for a successful write, UNIMPLEMENTED if the data source isn not writable, INVALID_ARGUMENT if the `ErrDataWriteFailed` is returned from the `datasource.Write` method, and INTERNAL for any other error.

**Comment by NDStrahilevitz** [comment]
@mcherny @itaysk

**Comment by rafaeldtinoco** [comment]
> Data sources were initially meant to be an opaque way to access external data, that is, writing data would not be a concern of tracee. 

Write which type of data ? Where ? The datasource ? You mean feeding a datasource from external data instead of only created by events ?

I believe this clarification could be good in the issue description in order to helper others to understand.

**Comment by NDStrahilevitz** [comment]
> > Data sources were initially meant to be an opaque way to access external data, that is, writing data would not be a concern of tracee.
> 
> Write which type of data ? Where ? The datasource ? You mean feeding a datasource from external data instead of only created by events ?
> 
> I believe this clarification could be good in the issue description in order to helper others to understand.

Any kind. Data Sources were not concerned with writing regardless of where the writing would occur. I can clarify that current data sources were fed internally by tracee events, but this wasn't ever the exclusive way to write data sources.

**Comment by itaysk** [comment]
while discussing this issue, we came up with this diagram:

<img width="981" alt="image" src="https://github.com/aquasecurity/tracee/assets/1161307/22709f49-5b38-4815-8d40-3a6251d82b89">
