### ISSUE TITLE
Timestamp field: GetEpoch and a GetMonotonic methods for event context.

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3726]
## Description

Today, in the event processor, we are normalizing the event timestamp to relative time (timestamp + starttime) or wall time (timestamp + boottime). This normalization happens at the end of this stage but there is a problem:

- derived events will get timestamp already normalized
- some processing might happen from derived stages only (normalized ts)
- all other processing will happen with original ts

After quick discussion, @AlonZivony gave a nice idea:

https://github.com/aquasecurity/tracee/pull/3718#issuecomment-1838543440

> Another option might be to expose more complicated types from the event, and exporting for the Timestamp field a GetEpoch and a GetMonotonic methods.

Which should be implemented for this issue to be solved.

**Comment by yanivagman** [comment]
@AlonZivony I remember you recently made some change related to that.
Can you tell what is still required to close this issue?

**Comment by AlonZivony** [comment]
Actually I didn't change anything.
I tried to pass the boot time to the analyze mode.
What is proposed here is to save both the monotonic time and boot time in the event under the `Timestamp` member as a new time, let's call it `Time`, which exposes methods of `GetMonotonic` and `GetAbsolute`.
This way you don't have to choose if you want relative or not times, you can have both.

**Comment by NDStrahilevitz** [comment]
Closing in favor of #4287
