### ISSUE TITLE
Creation of tracee.pid file is not under installation path and not configurable

### ISSUE THREAD

**Issue by denisgersh** [aquasecurity/tracee#3756]
## Description

There is a file that being created on start of Tracee - `tracee.pid`.
It is always being created at the same path `/tmp/tracee/out/tracee.pid`.
In the configuration file there is an option to specify the installation path for Tracee.
I expected to see all the Tracee related files (that being created by it) always be under the provided installation path.
Reconfiguring of the capture path in the configuration file does not affect the creation of this file.

Looks like creation of this file is hardcoded to the specific path mentioned above: 
https://github.com/aquasecurity/tracee/blob/c780a063e81fd007cd83d3302f05e31625b9ce1c/pkg/cmd/flags/capture.go#L94
https://github.com/aquasecurity/tracee/blob/c780a063e81fd007cd83d3302f05e31625b9ce1c/pkg/cmd/flags/capture.go#L200
https://github.com/aquasecurity/tracee/blob/c780a063e81fd007cd83d3302f05e31625b9ce1c/pkg/ebpf/tracee.go#L465
https://github.com/aquasecurity/tracee/blob/c780a063e81fd007cd83d3302f05e31625b9ce1c/pkg/cmd/tracee.go#L64
https://github.com/aquasecurity/tracee/blob/c780a063e81fd007cd83d3302f05e31625b9ce1c/pkg/cmd/tracee.go#L132

Expected: Creation of all the files under the provided installation path.
Actual: Noticed create of `tracee.pid` file at constant path `/tmp/tracee/out/tracee.pid`.

## Output of `tracee version`:

```bash
$ ./tracee version
Tracee version: "v0.19.0-1-g47951f66"
```

## Output of `uname -a`:

```bash
$ uname -a
Linux ip-10-0-1-8 6.2.0-1017-aws #17~22.04.1-Ubuntu SMP Fri Nov 17 21:07:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

## Additional details 

N/A

**Comment by itaysk** [comment]
it's still a bug because the readiness file should be created in the working dir flag location and not via the capture dir flag location

**Comment by itaysk** [comment]
@NDStrahilevitz i believe it should use the work dir flag as i wrote, not the install dir.
