### ISSUE TITLE
New event conversion and Finding (process lineage) issues

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3767]
Tracee currently converts `trace.Event` to protobuf `Event`:

![image](https://github.com/aquasecurity/tracee/assets/7395852/a1114a6b-7c58-485c-a7aa-390702b31aa4)

![image](https://github.com/aquasecurity/tracee/assets/7395852/091ca424-1c0d-43a2-9759-8c83ac9166a6)

And the conversion doesn't seem to be handling some `Finding` data properly (like the process lineage). For the process lineage particular case, some signatures **might** provide those types within the `Finding` data, causing issues when the conversion is done. OTOH, this data might not be needed to exist in there because it is already being provided as the "new event structure" information.

Suggestion from @yanivagman 

- remove the code (signature) that builds the lineage in their end
- remove the code in all signatures that populate the lineage field
- build a helper in tracee to add the full lineage to the event's parent field from the new infrastructure you guys recently introduced
- Call this helper on demand from the signature

**Comment by NDStrahilevitz** [comment]
@josedonizetti I think this can be closed as we've also resolved it on the process lineage side.
