### ISSUE TITLE
Hooked syscalls not triggered by kernel module loading

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#3783]
## Description

1. `tracee --events hooked_syscall`
2. Install diamorphine (https://github.com/m0nad/Diamorphine)
3. note that no `hooked_syscall` event is immediately sent

The cause is that the `do_init_module` dependency was removed in the event definition.

## Output of `tracee version`:

```
Tracee version: v0.19.0-112-g1c5ca9564
```

## Output of `uname -a`:

```
Linux ip-172-31-75-171 6.2.0-1017-aws #17~22.04.1-Ubuntu SMP Fri Nov 17 21:07:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rafaeldtinoco** [comment]
@OriGlassman wasn't this "by design" ? Just checking.
