### ISSUE TITLE
No default `exec-hash` option

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#3817]
## Description

Recently we have changed the `exec-hash` feature to increase its performance (#3752 ).
To do so, options for the hash caching were introduced.
However, the implementation for choosing the caching key requires the user to specify it by configuration.
This broke the previous API for this feature, requiring users to update their config file or CMD usage.
The use of `-o option:exec-hash` is not supported anymore, and the form of `-o option:exec-hash=<option>` became mandatory.
There is no real reason for breaking the previous API, which could have been preserved by simply providing default algorithm if non was chosen.
Even without the previous API to consider, providing a default option seem wise as it is not trivial to understand which option suits the user more.

**Comment by NDStrahilevitz** [comment]
I see two possible options:

1. Conditional default - if enrichment is enabled (which is the default) use the digest based option, otherwise use dev+inode.
2. always use dev+inode

@yanivagman @AlonZivony  WDYT?

**Comment by AlonZivony** [comment]
If it is easy to implement, I think that the first option is better as the user won't probably know that once he activates the enrichment he should switch manually.
