### ISSUE TITLE
Incorrect Container Tracking in TAS Cloud-Foundry Environment Due to Cgroup Mount Path Selection

### ISSUE THREAD

**Issue by hagitaqua** [aquasecurity/tracee#3824]
## Description
There is an issue in the container tracking mechanism for existing containers within TAS environments. The current implementation selects the last matching record in `/proc/mounts` for cgroup mounts. However, this approach has encountered challenges, particularly in scenarios where the mount paths are listed in a reverse order compared to our initial assumptions.
As a result, existing containers are not being tracked at all in cloud-foundry environment.

**Observed Behavior:**

In specific setups, the order of mount paths in `/proc/mounts` differs from the usual pattern. The last record found, which our system currently relies on to identify the container's mount path, often does not correctly reflect the actual host mount. This leads to a failure in accurately detecting and tracking existing containers.

**Expected Behavior:**

The container tracking mechanism should reliably identify and track containers regardless of the order of mount paths in `/proc/mounts`. The correct host mount path should be determined in a way that is not dependent on the order of the records.

### Steps to Reproduce:

1. **Deploy an Application**: Start by running any application within a TAS (Tanzu Application Service) environment.

2. **Install Tracee**: Proceed to install Tracee in the same TAS environment.

3. **Observe Application Tracking**: After the installation of Tracee, observe the behavior related to application tracking. You may notice that the existing application, which was running prior to the Tracee installation, is not being tracked as expected.

**Suggested Fix:**

A potential solution is to modify the logic for selecting the mount path by considering the length of the path, rather than its position in the list. By selecting the longest mount path, we can achieve a more accurate representation of the host mounts.

## Output of `tracee version`:

```
v0.19.0
```

## Output of `uname -a`:

```
Linux 5c79c746-5998-4cb1-9a97-7bd3d46d76fe 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by hagitaquasec** [comment]
Tracee version: `v0.19.0`
