### ISSUE TITLE
Tracee outputs bogus timestamps

### ISSUE THREAD

**Issue by oshaked1** [aquasecurity/tracee#3828]
## Description

When running tracee with JSON output, some events contain bogus timestamps (very large or even negative numbers). In these cases, both the timestamp and threadStartTime fields contain (slightly different) invalid timestamps.

## Output of `tracee version`:

```
Tracee version: "v0.19.0"
```

## Output of `uname -a`:

```
Linux *********** 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

## Additional details 

Example of invalid timestamps (rest of event truncated):
```
{'timestamp': 33259358447748, 'threadStartTime': 33259355176567,
{'timestamp': -8207706047079014194, 'threadStartTime': -8207706047079194457,
{'timestamp': 8532537232442238823, 'threadStartTime': 8532537232441643203,
{'timestamp': -1381702870323630858, 'threadStartTime': -1381702870324338633,
{'timestamp': 6826036438253662974, 'threadStartTime': 6826036438252929247,
```

Example of a valid timestamp:
```
{'timestamp': 1706534053545998934, 'threadStartTime': 1706534053543890523,
```

Unique events with invalid timestamps:
```
{'security_file_mprotect', 'security_bprm_check', 'do_mmap', 'shared_object_loaded', 'security_file_open', 'sched_process_exec', 'execve'}
```

**Comment by geyslan** [comment]
@oshaked1 thank you for the report. Could you please tell which was the cli flags used or the policy file loaded?

**Comment by oshaked1** [comment]
I managed to narrow the problem down to the `existing_container` event. Combined with any other event, it causes seemingly random events to have invalid timestamps. Example command line:

```
docker run -dit --rm --pid=host --cgroupns=host --privileged -v /etc/os-release:/etc/os-release-host:ro  -v /var/run:/var/run:ro  -v /sys/fs/cgroup:/sys/fs/cgroup  aquasec/tracee:latest --events existing_container,sched_process_exec -o json
```

**Comment by OriGlassman** [comment]
To add on top of that, it seems like hidden_kernel_module comes out with different time than other "normal" events:
![image](https://github.com/aquasecurity/tracee/assets/39296766/f9ffb85f-39d1-415d-a817-0bee850caca8)
Might be related to it being derived event.
