### ISSUE TITLE
container name, and container id not seen.

### ISSUE THREAD

**Issue by venumadhavjosyula** [aquasecurity/tracee#3854]
## Description

container name, and container id not seen.

## Output of `tracee version`:
{
  "timestamp": 29987099453068,
  "threadStartTime": 29987099069516,
  "processorId": 5,
  "processId": 56216,
  "cgroupId": 4294967297,
  "threadId": 56216,
  "parentProcessId": 7653,
  "hostProcessId": 56216,
  "hostThreadId": 56216,
  "hostParentProcessId": 7653,
  "userId": 0,
  "mountNamespace": 4026531840,
  "pidNamespace": 4026531836,
  "processName": "runc",
  "executable": {
    "path": ""
  },
  "hostName": "rdev1-rocky8-co",
  "containerId": "",
  "container": {},
  "kubernetes": {},
  "eventId": "6006",
  "eventName": "ld_preload",
  "matchedPolicies": [
    "default-policy"
  ],
  "argsNum": 2,
  "returnValue": 0,
  "syscall": "",
  "stackAddresses": null,
  "contextFlags": {
    "containerStarted": false,
    "isCompat": false
  },
  "threadEntityId": 0,
  "processEntityId": 0,
  "parentEntityId": 0,
  "args": [
    {
      "name": "LD_LIBRARY_PATH",
      "type": "const char *",
      "value": "LD_LIBRARY_PATH=/opt/containerd/lib:"
    },
    {
      "name": "triggeredBy",
      "type": "unknown",
      "value": {
        "args": [
          {
            "name": "cmdpath",
            "type": "const char*",
            "value": "/usr/bin/runc"
          },
          {
            "name": "pathname",
            "type": "const char*",
            "value": "/usr/bin/runc"
          },
          {
            "name": "dev",
            "type": "dev_t",
            "value": 264241157
          },
          {
            "name": "inode",
            "type": "unsigned long",
            "value": 184553
          },
          {
            "name": "ctime",
            "type": "unsigned long",
            "value": 1705092441392452072
          },
          {
            "name": "inode_mode",
            "type": "umode_t",
            "value": 33261
          },
          {
            "name": "interpreter_pathname",
            "type": "const char*",
            "value": "/usr/lib64/ld-2.28.so"
          },
          {
            "name": "interpreter_dev",
            "type": "dev_t",
            "value": 264241157
          },
          {
            "name": "interpreter_inode",
            "type": "unsigned long",
            "value": 8399615
          },
          {
            "name": "interpreter_ctime",
            "type": "unsigned long",
            "value": 1705091681118567735
          },
          {
            "name": "argv",
            "type": "const char**",
            "value": [
              "runc",
              "--root",
              "/run/containerd/runc/k8s.io",
              "--log",
              "/run/containerd/io.containerd.runtime.v2.task/k8s.io/625e486ac868a8d5aae177f69787ffbd4f4b2b49ca66411bd3eadc58d6429a73/log.json",
              "--log-format",
              "json",
              "--systemd-cgroup",
              "exec",
              "--process",
              "/tmp/runc-process1436277596",
              "--detach",
              "--pid-file",
              "/run/containerd/io.containerd.runtime.v2.task/k8s.io/625e486ac868a8d5aae177f69787ffbd4f4b2b49ca66411bd3eadc58d6429a73/1eda27319d8f5a1291bacdc3dd3f30830b51e0579f2b32d6b4fcfd9b55b7519e.pid",
              "625e486ac868a8d5aae177f69787ffbd4f4b2b49ca66411bd3eadc58d6429a73"
            ]
          },
          {
            "name": "interp",
            "type": "const char*",
            "value": "/usr/bin/runc"
          },
          {
            "name": "stdin_type",
            "type": "string",
            "value": "S_IFCHR"
          },
          {
            "name": "stdin_path",
            "type": "char*",
            "value": "/dev/null"
          },
          {
            "name": "invoked_from_kernel",
            "type": "int",
            "value": 0
          },
          {
            "name": "env",
            "type": "const char**",
            "value": [
              "HTTPS_PROXY=http://10.158.100.3:8080",
              "HTTP_PROXY=http://10.158.100.3:8080",
              "LANG=en_US.UTF-8",
              "NO_PROXY=127.0.0.1,::1,localhost,127.0.0.53,10.1.0.0/16,10.152.183.0/24,10.0.0.0/8,192.168.0.0/16,127.0.0.0/8,172.16.0.0/16,",
              "PATH=/opt/containerd/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/nri/bin",
              "http_proxy=http://10.158.100.3:8080",
              "https_proxy=http://10.158.100.3:8080",
              "no_proxy=127.0.0.1,::1,localhost,127.0.0.53,10.1.0.0/16,10.152.183.0/24,10.0.0.0/8,192.168.0.0/16,127.0.0.0/8,172.16.0.0/16,",
              "INVOCATION_ID=b33b4580fa514ff0b0c4ca02fc4f560c",
              "JOURNAL_STREAM=9:32717",
              "LD_LIBRARY_PATH=/opt/containerd/lib:",
              "TTRPC_ADDRESS=/run/containerd/containerd.sock.ttrpc",
              "GOMAXPROCS=4"
            ]
          },
          {
            "name": "sha256",
            "type": "const char*",
            "value": "5b37e362d72cceec7d392b8646d80a7a3a909a7362bdab23e3e7c8f9c48aae02"
          }
        ],
        "id": 713,
        "name": "sched_process_exec",
        "returnValue": 0
      }
    }
  ],
  "metadata": {
    "Version": "1",
    "Description": "LD_PRELOAD usage was detected. LD_PRELOAD lets you load your library before any other library, allowing you to hook functions in a process. Adversaries may use this technique to change your applications' behavior or load their own programs.",
    "Tags": null,
    "Properties": {
      "Category": "persistence",
      "Kubernetes_Technique": "",
      "Severity": 2,
      "Technique": "Hijack Execution Flow",
      "external_id": "T1574",
      "id": "attack-pattern--aedfca76-3b30-4866-b2aa-0f1d7fd1e4b6",
      "signatureID": "TRC-107",
      "signatureName": "LD_PRELOAD code injection detected"
    }
  }
}

## Output of `uname -a`:

[rocky@rdev1-rocky8-control-1 ~]$ uname -a
Linux rdev1-rocky8-control-1 5.4.266-1.el8.elrepo.x86_64 #1 SMP Mon Jan 8 23:20:07 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
[rocky@rdev1-rocky8-control-1 ~]$ 

## Additional details 

Had showed it to @yanivagman based on his suggestion

addtional output
-------------------
[rocky@rdev1-rocky8-control-1 ~]$ kubectl describe configmap/tracee-config -n tracee
Name:         tracee-config
Namespace:    tracee
Labels:       app.kubernetes.io/instance=tracee
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=tracee
              app.kubernetes.io/version=0.19.0
              helm.sh/chart=tracee-0.19.0
Annotations:  meta.helm.sh/release-name: tracee
              meta.helm.sh/release-namespace: tracee

Data
====
config.yaml:
----
cache:
    type: mem
    size: 512
cri:
   - runtime:
       name: containerd
       socket: /var/run/containerd/containerd.sock
perf-buffer-size: 1024
healthz: true
metrics: true
pprof: false
pyroscope: false
listen-addr: :3366
log:
    level: debug
output:
    json:
      files:
        - stdout
    options:
        parse-arguments: true
        stack-addresses: false
        exec-env: true
        relative-time: true
        exec-hash: true
        sort-events: true
    trace:
        container

BinaryData
====

Events:  <none>
[rocky@rdev1-rocky8-control-1 ~]$ 

[rocky@rdev1-rocky8-control-1 ~]$ kubectl get pods -n tracee -o wide
NAME                              READY   STATUS    RESTARTS   AGE     IP                NODE                     NOMINATED NODE   READINESS GATES
tracee-g94kz                      1/1     Running   0          9h      192.168.154.57    rdev1-rocky8-worker-2    <none>           <none>
tracee-operator-7494646f7-rnst7   1/1     Running   0          7d15h   192.168.154.25    rdev1-rocky8-worker-2    <none>           <none>
tracee-rvx47                      1/1     Running   0          9h      192.168.163.164   rdev1-rocky8-control-1   <none>           <none>
tracee-wf9tq                      1/1     Running   0          9h      192.168.155.31    rdev1-rocky8-worker-1    <none>           <none>
[rocky@rdev1-rocky8-control-1 ~]$

**Comment by geyslan** [comment]
@venumadhavjosyula thanks for your report.

@NDStrahilevitz could this be already fixed by https://github.com/aquasecurity/tracee/pull/3829?

**Comment by venumadhavjosyula** [comment]
@geyslan Please note we are using v0.19 version, which seem to be latest ?

**Comment by josedonizetti** [comment]
@venumadhavjosyula are you seen this on minikube? gke? other? which k8s version?

**Comment by venumadhavjosyula** [comment]
Hi,

We are not using on gke,minikube. It is an open stack compute node based kvm

The details are as follows,
***@***.*** ~]$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5

***@***.*** ~]$ uname -a
Linux rdev1-rocky8-control-1 5.4.266-1.el8.elrepo.x86_64 #1 SMP Mon Jan 8 23:20:07 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
***@***.*** ~]$



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yanivagman** [comment]
@venumadhavjosyula in your tracee output, the command which was running is runc, meaning the container runtime. From my understanding, runc is running on your host, and not from a container - so why do you expect to see a container id and container name? Are you running a container from inside another container?

**Comment by venumadhavjosyula** [comment]
No we are not running from inside another container. We are running it on host.

If yes runc doesn't capture container I'd ? What is trigger to get container I'd ?

We have other pods running on the host. So we wanted the to get container information for those  nodes ?

Thanks
Regards
Venu

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by venumadhavjosyula** [comment]
I meant those pods

Please not we have deployed Tracee as daemonset

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by yanivagman** [comment]
Sorry for the late response,
We only capture container id for events originating from within a container.
Since runc is a process which runs on the host, you will not see a container id for events coming from runc.
For pods (and the containers of the pods) you should be able to see the container id - Do you have an example where that is not the case?

**Comment by yanivagman** [comment]
Since the example given here is of the runc process running on the host, for which Tracee won't produce container id, I'm marking this issue as invalid.
If you have any other example with a missing container id where there should be one, please reopen.
