### ISSUE TITLE
Typo in the documentation!! 

### ISSUE THREAD

**Issue by Tej-Singh-Rana** [aquasecurity/tracee#3857]
Hi Team,

I have seen one typo under the policies section.

Link of the docs: - https://aquasecurity.github.io/tracee/v0.19/docs/policies/

At the very beginning para, there is a typo in the name of the "Installation". 

> Policies are used both for the [Tracee CLI](https://aquasecurity.github.io/tracee/v0.19/docs/policies/usage/cli/) and for the [Tracee Kubernetes](https://aquasecurity.github.io/tracee/v0.19/docs/policies/usage/kubernetes/) installaction.

Regards,

**Comment by josedonizetti** [comment]
@Tej-Singh-Rana thanks! Do you mind creating a pull request to fix it?

**Comment by Tej-Singh-Rana** [comment]
I created a PR for this.
