### ISSUE TITLE
helm: rename `traceeConfig` to `traceeConfigFile`

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3885]
There has been some confusion around [`traceeConfig`](https://github.com/aquasecurity/tracee/blob/main/deploy/helm/tracee/values.yaml#L59) option on the helm values, the idea behind it is to allow the user to inject a full config file, using `helm --set-file`, when configuring individual values, we can use https://github.com/aquasecurity/tracee/blob/main/deploy/helm/tracee/values.yaml#L61.

So, let's rename it to `traceeConfigFile` and add a comment explaining it on the values.yaml

**Comment by rscampos** [comment]
@josedonizetti what do you think: instead of using `traceeConfigFile` we simply use `configFile`? I thought this way because the `config` (that already exists) don't have `tracee` in the field.
