### ISSUE TITLE
[K8S] Namespace Tracee

### ISSUE THREAD

**Issue by hangrymuppet** [aquasecurity/tracee#3897]
**New functionality:** Install multiple instances of Tracee to a k8s cluster in separate namespaces.

Currently there are two blockers to this.

1. ClusterRole and ClusterRoleBinding cannot be namespaced by design. The `name` field is currently hardcoded and it clashes when trying to install a second instance of Tracee. A simple fix could be to append `{{ .Release.Namespace }}` to it.

2. The policy has cluster scope. The operator would need to be changed to only read a policy that is in the current namespace. Right now with my testing (by modifying the crd myself and installing multiple instances), all instances perform a rolling restart when any policy in any namespace changes.

At the moment I am only using this for development but I can envision a situation where different events need to go to different downstream consumers in different formats and it would be easily facilitated by such a design.

**Comment by itaysk** [comment]
Hi, thanks for the suggestion. Tracee is designed to be a node-level component, as it interacts with, and manipulates, the node operating system. Running multiple instances of Tracee on the same node might work, but isn't tested or optimized too much.

**Comment by yanivagman** [comment]
We don't plan to support multiple instances of Tracee on the same node.
Instead, we plan to add support for k8s filters, including pod name and namespaces, which is already tracked by this issue: https://github.com/aquasecurity/tracee/issues/3711
