### ISSUE TITLE
Regression in process info

### ISSUE THREAD

**Issue by oshaked1** [aquasecurity/tracee#3949]
## Description

A recent optimization effort (https://github.com/aquasecurity/tracee/commit/f806cb4b71b8f4082e182adf6c201c1e81f05753) moved some parts of the program data initialization to the event submission stage. This results in the information that is used to construct pcap file names to be missing (the process name portion of the pcap file is empty).

I also noticed that (somewhat expectedly), using process info inside a bpf program results in incorrect data. Some bpf programs may rely on this data which will result in unexpected behavior.

There may be more side effects for this change, anywhere that process info is used and isn't in a regular event submitted to user space.

## Output of `tracee version`:

Commit f806cb4b71b8f4082e182adf6c201c1e81f05753

**Comment by yanivagman** [comment]
> A recent optimization effort ([f806cb4](https://github.com/aquasecurity/tracee/commit/f806cb4b71b8f4082e182adf6c201c1e81f05753)) moved some parts of the program data initialization to the event submission stage. This results in the information that is used to construct pcap file names to be missing (the process name portion of the pcap file is empty).

The commit was intended to update all instances where a particular field was necessary for a program but left uninitialized. However, network events were inadvertently omitted, as they involve duplicating the entire event context within a different kprobe (__cgroup_bpf_run_filter_skb).

> I also noticed that (somewhat expectedly), using process info inside a bpf program results in incorrect data. Some bpf programs may rely on this data which will result in unexpected behavior.
> 
> There may be more side effects for this change, anywhere that process info is used and isn't in a regular event submitted to user space.

This is the intended behavior. We don't want to intialize any field if in general it is not required by all (or most) bpf programs. If a specific program needs a certain field - it is the program responsibility to initialize it.
Adding the following line to where we save the network event task context should fix the problem:
`init_task_context(&p->event->context.task, p->event->task, p->config->options);`
