### ISSUE TITLE
Analyze mode doesn't support sigs-on-sigs

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#4009]
## Description

The current tracee analyze mode is not well maintained or tested, so the sigs-on-sigs option is not yet supported yet.
For compatibility we should support it for now until the full analyze mode will be implemented.

## Output of `tracee version`:

```
 v0.20.0-93-ge8d7a3516
```

**Comment by yanivagman** [comment]
This should be fixed by the full analyze mode PR as mentioned here:
https://github.com/aquasecurity/tracee/pull/4010#issuecomment-2156361259
