### ISSUE TITLE
Write to outer map fails due to no wrap around of version in snapshot

### ISSUE THREAD

**Issue by subkin13** [aquasecurity/tracee#4019]
The code in `func (s *snapshots) Store(ps *Policies)` does not wrap s.lastVersion when it reaches maxSnapshots which eventually causes failure when writing to an outer map - see `func (ps *Policies) createNewFilterMapsVersion(bpfModule *bpf.Module) error` 

Also the following code sets the minimal version to 1, it is never zero, so there is never write to cell #0 in the outer map. Is that on purpose?

```
s.lastVersion++ // new version
if s.lastVersion >= uint16(MaxPolicies) {
     logger.Warnw("Policies version has wrapped around, resetting to 1")
     s.lastVersion++
}
```

Also - `prune       func(*Policies) []error`  is not initialized so the inner maps are never closed which will eventually cause fd leak

**Comment by yanivagman** [comment]
@subkin13 thanks for reporting,
@geyslan can you have a look?

**Comment by subkin13** [comment]
also:
1. in createNewInnerMap - GetBTFFDByID creates another fd for the process, you should close it before exiting the function
2. in createNewFilterMapsVersion - if the call to updateOuterMap fails you should close the newInnerMap fd

**Comment by geyslan** [comment]
Hi @subkin13, thanks for bringing us your founds.

> The code in func (s *snapshots) Store(ps *Policies) does not wrap s.lastVersion when it reaches maxSnapshots...

The `Snapshots` is a circular buffer of size `maxSnapshots`. This check

https://github.com/aquasecurity/tracee/blob/a458fa9f6e77df4144164ed08fda1f6f450b0c53/pkg/policy/snapshots.go#L75-L79

is only to deal with uint wrap around.

The version can and should be increased to the holder's limit, as it communicates the version number of these policies, even if we only have `maxSnaphosts` at a time. So for this I don't see any problem.

---

> Also - prune       func(*Policies) []error is not initialized so the inner maps are never closed which will eventually cause fd leak

This is true. I was tackling it in currently closed PRs. That will be solved soon.

i.e.: https://github.com/aquasecurity/tracee/pull/3912/files#diff-aab7c4298207977c2b1b634dfc0fc67eb9004e74324ab1c0df0306869d1714b5R607-R609

![image](https://github.com/aquasecurity/tracee/assets/3372117/33af9de9-e70e-4fd8-b9c2-98cd386f811c)


> in createNewInnerMap - GetBTFFDByID creates another fd for the process, you should close it before exiting the function

I suppose you're right. I need to check if after the map creation the BTFFD is not required anymore. Let's deal with it in upcoming efforts. Thanks!

> in createNewFilterMapsVersion - if the call to updateOuterMap fails you should close the newInnerMap fd

This is also true and was being tackled on the referred PR.

Thanks a million.

**Comment by geyslan** [comment]
https://github.com/aquasecurity/tracee/issues/3239 updated with findings.
