### ISSUE TITLE
hidden kernel module potential FP

### ISSUE THREAD

**Issue by OriGlassman** [aquasecurity/tracee#4021]
## Description

 The MAX_NUM_MODULES was recently decreased from 600 to 450 and is anyway relatively small.
  In case there are more modules to iterate on than the number of the
  iterations done, it will report the rest as false positives.
    

## Output of `tracee version`:

```
(paste your output here)
```

## Output of `uname -a`:

```
(paste your output here)
```

**Comment by yanivagman** [comment]
Should have been closed by #4020
