### ISSUE TITLE
Tracee have a problem in CentOS 7

### ISSUE THREAD

**Issue by chansgt** [aquasecurity/tracee#404]
Tracee (docker container) cannot running in CentOS 7

Here is the following environment:

Cluster: OKD 3.11
Container Engine: cri-o 1.11.13-1.rhaos3.11.gitfb88a9c.el7, docker v1.13.1
OS: CentOS Linux release 7.9.2009 (Core)
Kernel Version: 5.4.86-1.el7.elrepo.x86_64

Error log:

libbpf: Error in bpf_object__probe_loading():Permission denied(13). Couldn't load trivial BPF program. Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value. libbpf: failed to load object '/tmp/tracee/tracee.bpf.5_4_86-1_el7_elrepo_x86_64.v0_3_1.o' 2021/01/03 11:06:31 error creating Tracee: failed to load BPF object

**Comment by simar7** [comment]
hi @chansgt - I had a quick look and was able to reproduce it. I think this is happening because of selinux being enabled. See the following for more details:

Before changing:
```
[vagrant@centos7 tracee]$ sudo sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31

[vagrant@centos7 tracee]$ docker run  --name tracee --rm --privileged --pid=host -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro -v /tmp/tracee:/tmp/tracee  aquasec/tracee:latest
libbpf: Error in bpf_object__probe_loading():Permission denied(13). Couldn't load trivial BPF program. Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value.
libbpf: failed to load object '/tmp/tracee/tracee.bpf.5_4_91-1_el7_elrepo_x86_64..o'
2021/01/21 01:25:57 error creating Tracee: failed to load BPF object
```

After changing:
```
[vagrant@centos7 tracee]$ sudo setenforce 0

[vagrant@centos7 tracee]$ sudo sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31

[vagrant@centos7 tracee]$ docker run  --name tracee --rm --privileged --pid=host -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro -v /tmp/tracee:/tmp/tracee  aquasec/tracee:latest
TIME(s)        UID    COMM             PID     TID     RET              EVENT                ARGS
<...>
```

Notice the current mode changed to `permissive`.

Hope this helps!

**Comment by simar7** [comment]
We should probably add this to the Readme, since on CentOS this is enabled by default out of the box. So thanks for trying it out!

**Comment by yanivagman** [comment]
@simar7 thanks for checking this and finding the cause.
Interesting is the fact that I already run tracee on Linux systems that are enforcing selinux policies, but using the binary itself, and not the docker container - maybe the fact that we run it from a container is causing this selinux enforcement problem?

**Comment by itaysk** [comment]
Thanks @simar7 ! 
@chansgt can you please confirm?
@yanivagman so we remove this from v0.4.0 milestone, right?

**Comment by simar7** [comment]
> @simar7 thanks for checking this and finding the cause.
> Interesting is the fact that I already run tracee on Linux systems that are enforcing selinux policies, but using the binary itself, and not the docker container - maybe the fact that we run it from a container is causing this selinux enforcement problem?

@yanivagman - Interesting,  what kernels did you try that scenario with?

**Comment by yanivagman** [comment]
> Interesting, what kernels did you try that scenario with?

Android :-)

**Comment by simar7** [comment]
Some more insight: This was introduced with this patch in the kernel I believe: https://github.com/torvalds/linux/commit/ec27c3568a34c7fe5fcf4ac0a354eda77687f7eb

The earlier tag it seems to have is the v4.15-rc1 on it. I'm going to guess it's been part ever since which would explain why 4.9 worked in your case.

**Comment by chansgt** [comment]
Hi @simar7,

I already check it, and the result is working now. So the problem is because selinux is enabled. Thank you so much @simar7. 

![image](https://user-images.githubusercontent.com/52393770/105495257-89df0b80-5cee-11eb-842d-ce622e48e691.png)

@itaysk, i will close this issue because tracee is working perfectly now.

Thank you guys for helping me out with this problem!
