### ISSUE TITLE
Update readme to include all the recent changes

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#424]
Many changes that influence the UX have been done recently, and those are not reflected in the readme.
These include: #421, #420, #411, #395, #378, #376, #375, #371 #357 #355
And more to come: #419, #408, #401, #397

Before releasing 0.4.0 we should update the readme to reflect those changes

**Comment by itaysk** [comment]
yes I refrained from writing this as a pr comment because we need to rewrite anyway because of the move to tracee-ebpf. I will do it in the same pr as the split

**Comment by yanivagman** [comment]
In addition to what you wrote, no reason to do it now, because it may confuse people who are using the docker image and not building from source.
I wrote it here so that we will remember to do that before the release.

**Comment by yanivagman** [comment]
0.4.0 released with all the changes
