### ISSUE TITLE
Enrich container events with image name and container id

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#430]
Container events metadata can be enriched by interfacing with the container runtime.
The two most useful fields are container id and image name, which can then be used, for example, by tracee-rules, and also help with the implementation of #255.
To get this metadata, Tracee can interface with the container runtime using CRI.
The implementation should be able to get the metadata before the container starts its execution.
For cri-o, this can be done by using a prestart hook, which is a binary that runs before the container starts. 
As containerd doesn't support the configuration of prestart hooks, we can use its container events mechanism, that produces an event when a new container is created.
We can then map the mount namespace that we get from the kernel with the collected metadata we have from the container runtime, and add the extra metadata to the event as required.

**Comment by simar7** [comment]
> To get this metadata, Tracee can interface with the container runtime using CRI.

Are you sure CRI can support this? My understanding after asking a few people about it that containers created via higher level tools like docker or ctr aren't visible via CRI. I opened an issue to confirm this: https://github.com/kubernetes-sigs/cri-tools/issues/758

One idea that was suggested on slack was to use something like runc to get hold of all the containers that were created using it. Upon trying it there seems to be some success in that:
```
sudo runc --root=/run/docker/runtime-runc/moby list
ID                                                                 PID         STATUS      BUNDLE                                                                                                                CREATED                          OWNER
bd538a379da8fb4553272722d2c510092d5b5a104a1faa8c4494d3feb21c0039   117889      running     /run/containerd/io.containerd.runtime.v2.task/moby/bd538a379da8fb4553272722d2c510092d5b5a104a1faa8c4494d3feb21c0039   2021-04-23T19:26:33.232357786Z   root
```

Thoughts?

**Comment by yanivagman** [comment]
CRI is an interface used by k8s to interact with container runtimes (docker, containerd, cri-o all implement this interface).
If a container is created by k8s (configured to use containerd by default if I'm not wrong), the container state metadata will be saved by this containerd instance. In case that the containers you tried to list were started with docker, it may be that a different containerd instance was used to create these containers, thus are not presented by crictl. (crictl can be given a unix socket of the container runtime to interact with).

If the same container runtime is used for both docker and k8s, it may be that the problem you encountered is containerd namespaces as described here:
https://github.com/containerd/containerd/issues/1815

The problem with using runc to solve our problem is that it does not have any information about the container image, because it is not its responsibility. runc is only responsible for the runtime related stuff, and not for images.

**Comment by simar7** [comment]
> CRI is an interface used by k8s to interact with container runtimes (docker, containerd, cri-o all implement this interface).
> If a container is created by k8s (configured to use containerd by default if I'm not wrong), the container state metadata will be saved by this containerd instance. In case that the containers you tried to list were started with docker, it may be that a different containerd instance was used to create these containers, thus are not presented by crictl. (crictl can be given a unix socket of the container runtime to interact with).
> 

That's right. In such a case where containers can be created via different containerd instances, checking CRI won't be sufficient (a container could have been created by docker cli, which would be outside of CRI's knowledge, assuming they both use different containerd instances). Maybe we can start with CRI first and add support for others later.

> If the same container runtime is used for both docker and k8s, it may be that the problem you encountered is related to containerd namespaces as described here:
> [containerd/containerd#1815](https://github.com/containerd/containerd/issues/1815)
> 

Thanks. I actually had a different problem where I was using minikube (uses a VM) so the pods were not visible outside of VM. Running `crictl` within the minikube VM works fine.

> The problem with using runc to solve our problem is that it does not have any information about the container image, because it is not its responsibility. runc is only responsible for the runtime related stuff, and not for images.
> 
> If we only want to exract the container id, we can do it by using the cgroup name. But if we also want other metadata of the container, we will have to interact with the container runtime, and CRI is our best option to do that

Maybe this is a good time to discuss what information we are looking for. To start off, maybe we can expose everything that CRI api provides us with: https://github.com/kubernetes/cri-api/blob/v0.21.0/pkg/apis/runtime/v1alpha2/api.pb.go#L3986-L4012

**Comment by simar7** [comment]
Some relevant output for using containerd events:
```
$ sudo ctr --address="/run/docker/containerd/containerd.sock" events
2021-04-27 06:38:40.437533669 +0000 UTC moby /containers/create {"id":"43e8cc02a468d2a7526c3d3b62f00f7f07e3137be5e7aa75990b521b235247d0","runtime":{"name":"io.containerd.runc.v2","options":{"type_url":"containerd.runc.v1.Options","value":"MgRydW5jOhwvdmFyL3J1bi9kb2NrZXIvcnVudGltZS1ydW5jSAE="}}}
2021-04-27 06:38:40.627217642 +0000 UTC moby /tasks/create {"container_id":"43e8cc02a468d2a7526c3d3b62f00f7f07e3137be5e7aa75990b521b235247d0","bundle":"/var/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/43e8cc02a468d2a7526c3d3b62f00f7f07e3137be5e7aa75990b521b235247d0","io":{"stdout":"/var/run/docker/containerd/43e8cc02a468d2a7526c3d3b62f00f7f07e3137be5e7aa75990b521b235247d0/init-stdout","stderr":"/var/run/docker/containerd/43e8cc02a468d2a7526c3d3b62f00f7f07e3137be5e7aa75990b521b235247d0/init-stderr"},"pid":6361}
2021-04-27 06:38:40.780713015 +0000 UTC moby /tasks/start {"container_id":"43e8cc02a468d2a7526c3d3b62f00f7f07e3137be5e7aa75990b521b235247d0","pid":6361}
```

**Comment by simar7** [comment]
> The implementation should be able to get the metadata before the container starts its execution.

@yanivagman CRI also has information about container creation, before it starts to run. https://github.com/kubernetes/cri-api/blob/708d0d76e582f969d2a1056b07eaf19109b76b9e/pkg/apis/runtime/v1alpha2/api.proto#L861-L866 

Is this not sufficient or you do think we will need to query containerd events / cri-o prehooks for some other reason?

**Comment by yanivagman** [comment]
CRI is an API that you need to query, it is not event driven ( as far as I know). When a new container is created, we need an event that will trigger an API call to the CRI enabled interface. This is why I mentioned containerd events and the prestart hooks - these are events which can trigger the API call.

**Comment by itaysk** [comment]
is the direction to build a local representation of the cri state, and use that local cache to enrich containers? is that why we need the hooks/lifecycle events?

**Comment by simar7** [comment]
> is the direction to build a local representation of the cri state, and use that local cache to enrich containers? is that why we need the hooks/lifecycle events?

My understanding is that we subscribe to containerd events and on each new container creation, we will get an event which we will hold and use when we have to print the event within tracee-ebpf. At this time we will augment the output event with the obtained metadata (image name, container id, etc.) This is in contrast with querying the CRI api directly on each print (expensive). 

Another reason we need the events/hooks mechanism is when talking to the CRI api, you have two options: 
1. Get a list of all containers and their info `crictl ps -a`
or
2. Get info of one container by an identifier such as container ID, image, last etc.

Doing 1. is possible but then how do we identify from all the running containers the one we're interested in? Container ID seems to be that key we need.

Since we are looking for container id, it becomes a chicken and egg problem to query CRI api directly. So getting container id through the containerd events is a way to solve it.

I'm open to suggestions or corrections if there are any on my understanding.

**Comment by simar7** [comment]
Some debug output to understand the above mentioned points:
```
vagrant@ubuntu-groovy:/usr/vagrant/repos/tracee/tracee-rules$ sudo ctr events 
2021-04-30 23:13:07.902554137 +0000 UTC moby /containers/create {"id":"9b1e8b1eb42a36087e6264511bb785510b72af3a57774a1820c40f0c08afa932","runtime":{"name":"io.containerd.runc.v2","options":{"type_url":"containerd.runc.v1.Options","value":"MgRydW5jOhwvdmFyL3J1bi9kb2NrZXIvcnVudGltZS1ydW5j"}}}
2021-04-30 23:13:08.066444156 +0000 UTC moby /tasks/create {"container_id":"9b1e8b1eb42a36087e6264511bb785510b72af3a57774a1820c40f0c08afa932","bundle":"/run/containerd/io.containerd.runtime.v2.task/moby/9b1e8b1eb42a36087e6264511bb785510b72af3a57774a1820c40f0c08afa932","io":{"stdout":"/var/run/docker/containerd/9b1e8b1eb42a36087e6264511bb785510b72af3a57774a1820c40f0c08afa932/init-stdout","stderr":"/var/run/docker/containerd/9b1e8b1eb42a36087e6264511bb785510b72af3a57774a1820c40f0c08afa932/init-stderr"},"pid":273682}
2021-04-30 23:13:08.105193132 +0000 UTC moby /tasks/start {"container_id":"9b1e8b1eb42a36087e6264511bb785510b72af3a57774a1820c40f0c08afa932","pid":273682}
^C
```

```
vagrant@ubuntu-groovy:/usr/vagrant/repos/tracee/tracee-rules$ k get pods
NAME                         READY   STATUS        RESTARTS   AGE
nginx-app-d6ff45774-fgbxr    1/1     Running       0          28s
```

```
vagrant@ubuntu-groovy:/usr/vagrant/repos/tracee/tracee-rules$ sudo crictl ps --id 9b1e8b1eb42a36087e6264511bb785510b72af3a57774a1820c40f0c08afa932
CONTAINER           IMAGE                                                                           CREATED             STATE               NAME                ATTEMPT             POD ID
9b1e8b1eb42a3       nginx@sha256:75a55d33ecc73c2a242450a9f1cc858499d468f077ea942867e662c247b5e412   42 seconds ago      Running             nginx               0                   48523e59e422c
```

**Comment by itaysk** [comment]
possibly useful code here: https://github.com/spiffe/spire/tree/main/pkg/agent/plugin/workloadattestor
specifically https://github.com/spiffe/spire/blob/main/pkg/agent/plugin/workloadattestor/docker/cgroup/dockerfinder.go

**Comment by yanivagman** [comment]
@itaysk we already have container id implemented in a different way - using cgroup attach tracepoint.

**Comment by itaysk** [comment]
I know.. I linked here so we can look at the cgroup path parsing

**Comment by yanivagman** [comment]
Done
