### ISSUE TITLE
Container enrichment doesn't works when running Tracee in docker container on macos

### ISSUE THREAD

**Issue by shahafa** [aquasecurity/tracee#4351]
## Description

I'm running Tracee in a Docker container on macOS using this command:
```
docker run --name tracee -it --rm \
        --pid=host --cgroupns=host --privileged \
        -v /etc/os-release:/etc/os-release-host:ro \
        -v /var/run:/var/run:ro \
        aquasec/tracee:latest
```

When the Tracee container starts, it displays the following warning and error messages:
```
{"level":"warn","ts":1728745128.1671033,"msg":"Cgroup mountpoint is not in the host cgroup namespace","mountpoint":"/tmp/tracee172862653","inode":113}
{"level":"warn","ts":1728745128.2265053,"msg":"Event canceled because of missing kernel symbol dependency","missing symbols":["sys_call_table"],"event":"syscall_table_check"}
{"level":"error","ts":1728745130.256334,"msg":"Handling event by signature Docker socket abuse detected: argument remote_addr is not initialized"}
```

when I start another container, the Tracee logs include only the container ID in the container object. Is there a way to enable container enrichment including container name while running Tracee in Docker on macOS?

Steps to reproduce:
1. Run tracee container in macos using the following command:
```
docker run --name tracee -it --rm \
        --pid=host --cgroupns=host --privileged \
        -v /etc/os-release:/etc/os-release-host:ro \
        -v /var/run:/var/run:ro \
        aquasec/tracee:latest
```
2. Run another docker container:
```
docker run hello-world
```
3. Inspect Tracee logs you'll notice no container name available

## Output of `tracee version`:

```
Tracee version: v0.22.2
```

## Output of `uname -a`:

```
Darwin *******-MacBook-Pro.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000 arm64```

**Comment by geyslan** [comment]
Hi @shahafa, please take a look at https://aquasecurity.github.io/tracee/dev/docs/advanced/mac/.
