### ISSUE TITLE
Possible not initialized memory in HiddenKernelModules

### ISSUE THREAD

**Issue by trvll** [aquasecurity/tracee#4356]
## Description

During stress tests using custom image to trigger signatures tracee crashes:

![image](https://github.com/user-attachments/assets/cc00c5ec-c8f2-4cf7-a104-dd3d03c8b581)

## Output of `tracee version`:

```
Tracee version: v0.22.1
```

## Output of `uname -a`:

```
Linux e6d3f5f9a519 6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024 x86_64 Linux
```

**Comment by OriGlassman** [comment]
Fixed in a23b9f634b117b8ec82def7257c641c0a3665ac5
