### ISSUE TITLE
share text between cli help and online docs

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#436]
in order to avoid duplication, we should reuse the same text between the cli `--help`/`--trace help`/`--capture help`/`--output help` and the online documentation (#435). What comes to mind is:
1. store each docs section (for example "capture" docs) in a separate file in the docs directory
2. this file will be used by docs generator to create the webpage
3. embed this file into the binary (using #434), so the text is available at runtime
4. when needed a help command is invoked, use the appropriate embedded help text to print help message to cli

**Comment by itaysk** [comment]
@AlonZivony after talking with @rafaeldtinoco I understand you were working on something similar but for events documentation. FYI

**Comment by itaysk** [comment]
This is the most reasonable solution I found: https://umarcor.github.io/cobra/#markdown-docs

**Comment by josedonizetti** [comment]
This can be closed, we are now sharing the text since the `man` subcommand was introduced here -> https://github.com/aquasecurity/tracee/pull/3572
