### ISSUE TITLE
Groundwork for In-Kernel Data Filtering

### ISSUE THREAD

**Issue by rscampos** [aquasecurity/tracee#4431]
The goal of this task is to efficiently filter relevant data in the kernel, reducing overhead in user-space processing. This first phase lays the groundwork for in-kernel data filtering by creating the initial function to match string-based filters (**exact**, **prefix**, **suffix**) for `security_file_open`, `magic_write`, and `security_mmap_file` events.

**Comment by itaysk** [comment]
I'm renaming this to better reflect that this is a new feature and not *just* groundwork
