### ISSUE TITLE
Implement Config File Parsing

### ISSUE THREAD

**Issue by ShohamBit** [aquasecurity/tracee#4445]
**Background**  
We need to introduce a YAML-based configuration file to simplify how users manage their settings. With the new config file, users can define all their desired configurations in one place, and the system will parse and apply these settings at runtime. This approach will make it easier to store, share, and version control configurations.

**What Needs to Be Done**

- [ ] Parse the YAML configuration file, covering all sections:
  - events
  - source
  - enrichment
  - data stores
  - output
  - server
  - logging
  - buffers
  - general
  - capabilities
  - capture (deprecated)
  - signatures (deprecated)
  
- [ ] Implement handling of default values and optional fields.  
- [ ] Validate the structure and values within the config file:
  - Show clear error messages if something is malformed or invalid.
  - Ensure all required fields are present and correct.
  
- [ ] Add the ability to specify a config file path (will be integrated with the `--config` flag in another issue).

**Acceptance Criteria**
- The system can read and parse the YAML config file without errors.
- Default values are correctly applied when fields are missing.
- Validation catches invalid or unsupported configurations and reports them clearly.
- The parsed configuration is ready to be merged with command-line flags (handled in separate issues).

**Why This Matters**
A well-structured config file reduces complexity for users. It provides a single source of truth for their settings, making it easier to set up, share, and maintain configurations over time.

**Comment by yanivagman** [comment]
Part of #4453
