### ISSUE TITLE
Throw an error if pid/uid<0 are provided as input filters

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#450]
**What did I see:**
`tracee --trace 'uid<0'` started tracing normally
`tracee --trace 'pid<0'` started tracing normally

**What did I expect to see:**
`tracee --trace 'uid<0'` should throw an error as it's an invalid filter.
`tracee --trace 'pid<0'` should throw an error as it's an invalid filter.

**Acceptance criteria:**
`tracee --trace 'uid<0'` throws an invalid filter error.
`tracee --trace 'pid<0'` throws an invalid filter error.

**Comment by itaysk** [comment]
This is requires a little bit further discussion about whether the "preparer" functions should do input validation (I think no), or just parse the input and let the config validate the parsed struct. 
A good example is from `prepareOutput` which I explicitly mention here:  https://github.com/aquasecurity/tracee/blob/main/main_test.go#L1023
`prepareOutput` will blindly parse `--output foo` into an `OutputConfig.Format: foo`, and then rely on `OutputConfig.Validate()` to do the validation for better code reuse. I think this approach is better but open for other opinions.
