### ISSUE TITLE
readArgFromBuff doesn't always empty the passed in buffer

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#451]
This is more of a question than a bug report but I'll make it into one as per: https://github.com/aquasecurity/tracee/pull/427/files#r563167577

Currently doing an assertion on checking the size of the passed in bytes buffer (post consumption) in the following test cases:
- strArrT
- unknown
- sockAddrT - AF_UNIX

for the test `TestReadArgFromBuff` (as shown here: https://github.com/aquasecurity/tracee/pull/427/files#diff-ab71755492df31ad437f0c5bc9833074ddda362813da07b04f7a0d491caf4ba1R152-R157) shows the buffer isn't fully cleared out.

It seems to be cleared out for the following type:
https://github.com/aquasecurity/tracee/blob/main/tracee/tracee.go#L1393-L1396

My understanding is that we need to fully empty the buffer each time, for each type. Is that a correct statement?

**Comment by itaysk** [comment]
yes the buffer should be cleared. the only exception is when encountering unknown event, in which case tracee should exist. (this case can be excluded from the assertion)

re strArrT - I believe this is a bug in the existing test, it is adding a `11, // end strArrT` which I THINK is a leftover from an older method we used to encode string arrays.

re sockaddrT - I think it's a mistake in the test you added, see the mentioned PR for my comment

**Comment by simar7** [comment]
> re strArrT - I believe this is a bug in the existing test, it is adding a `11, // end strArrT` which I THINK is a leftover from an older method we used to encode string arrays.


Oh I see - @yanivagman do you know if it still is the case?

**Comment by yanivagman** [comment]
We previously used a marker to mark the start and end of the string array.
We changed this since to use array length, which simplifies the logic.
So yes, @itaysk is right and we should remove this "11" byte.

**Comment by yanivagman** [comment]
I see that the last byte in strArrT was removed.
@itaysk/ @simar7  Is this still an issue or we can close this?

**Comment by yanivagman** [comment]
I don't think this is an issue anymore. Please reopen if you think it still is.
