### ISSUE TITLE
Upgrade minimal kernel version to 4.18

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#452]
I had a comment in #447 about some of the benefit but please add additional reasons in response to this issue. 

I believe this would involve deprecating `AttachK(ret)probeLegacy` in `trace/tracee.go`and mention of them elsewhere. Perhaps the proper way of doing that is to have a compile flag which we turn on by default and document that having it off (meaning use the legacy version) is no longer supported. We would plan for a future release to remove the flag completely.

**Comment by yanivagman** [comment]
Before proceeding with this task, we need to make sure that all of the current consumers of Tracee have moved to kernel > 4.18.
DTA currently uses v4.15

**Comment by grantseltzer** [comment]
@yanivagman I was thinking instead of just killing support for  kernels <4.18 I would just put them behind kernel version checks. For example `AttachKprobeLegacy` would be called 4.17 and before, and `AttachKprobe` otherwise. We don't have to explicitly kill support in this way.

**Comment by yanivagman** [comment]
@grantseltzer  In general, I agree that we should use kernel version checks. and this is exactly what we do today for raw tracepoints. 
Yet, there are many things that were changed between 4.14 to 4.18, and keeping support for kernels <4.18 will force us to keep too many compilation flags and kernel version checks.
Some of the changes that come to mind:
1. bpf_get_current_cgroup_id() helper function that was added in 4.18 (if I remember correctly) and that will allow us to better distinguish between different containers (we currently use pid namespace for that, which is far from ideal)
2. raw tracepoints vs "regular" tracepoint - today we support both, but there is no good reason to use the "regular" tracepoints.
3. attach_Xprobe() vs attach_legacyXprobe()
4. syscall arguments passing was changed in 4.17, and now it is save in pt_regs struct indirectly. We already support both in the code, but it makes the code less readable.
5. btf support was added in kernel 4.18 (although requires CONFIG_BTF to be enabled)
