### ISSUE TITLE
print raw arguments

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#461]
Currently, tracee-ebpf pretty-prints some of the events arguments (e.g. execve and clone flags).
We should enable the user to choose if he wants to print the arguments as raw.
To do that, we can add a new output option to the output flag.

**Comment by itaysk** [comment]
we have recently discussed this and agreed to change tracee-ebpf to send only raw data (for argument values), and the consumer (tracee-rules or tracee-ebpf printer) will be able to present them differently. to support that, we will move "argPrinters" from Tracee to libbpfgo (#485).

**Comment by itaysk** [comment]
now let's discuss the UX: I think that the by default, only table printer should print decoded args. all the rest should send raw args.
we can say this is controllable using an output "option" like `-o option:printargs`. setting this flag will take the extra step of printing the args into textual form, and by default this will be enabled only for table output. 
how does this sound?
