### ISSUE TITLE
tracee entrypoint

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#464]
We need a new entrypoint for the tracee container that orchestrates tracee the "runtime security" use case.
Also, this entrypoint should allow invoking tracee-ebpf directly when a subcommand is used (I suppose `trace`)

if running the container with no arguments it should:
1. start tracee-ebpf 
  1. write to stdout
  2. use gob format
  3. use EOT output option
2. pipe the output to tracee-rules
3. start tracee-rules
  1. use tracee input source from stdin
  2. load all build-in rules
  3. configure webhook to falco-sidekick
4. start falco-sidekick
  1. configured to read a config the will be mounted in

if running the container with `trace` subcommand
1. start tracee-ebpf
  1. pass all the additional args to the tracee-ebpf command

**Comment by yanivagman** [comment]
As per my comment in #463 - maybe we should have a separate tracee-ebpf image, and then there will be no need for the `trace` command
