### ISSUE TITLE
tracee kubernetes deployment yamls

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#468]
create yaml deployment files for deploying tracee into a kubernetes cluster.
should create a daemonset for running tracee on each node.
should  be configurable via a configmap.

**Comment by krol3** [comment]
I would like to help

**Comment by itaysk** [comment]
let's take it step by step, I think that we can start without a configurable deployment, just run the tracee container and use the default options. another question is how the results are accessible to the user. the deployment should give an example of running falcosidekick (in the future maybe postee), which is independently configured by the user.

So to summarize
1. Deployment + Service that runs falcosidekick in the cluster. configurable by the user to send the event wherever they want. falcosidekick has a helm chart that we could use, so we can just add an instruction to helm install it (options that will install a minimal setup of just deployment+service)
2. Daemonset for Tracee. runs the aquasec/tracee container. the only configuration we need now is to point to the falcosidekick service endpoint.

potential improvements **for the future**:
1. control tracee-ebpf configs
2. use the slim image
3. persist /tmp/tracee as volume
4. select which rules to load
