### ISSUE TITLE
what is the difference compared with falco?

### ISSUE THREAD

**Issue by carmark** [aquasecurity/tracee#48]

**Comment by yanivagman** [comment]
Falco is a rule engine, based on sysdig open source. It takes raw events from sysdig, and matches it with rules defined by falco language in a yaml file. In contrast, Tracee traces events from eBPF, but does not enforce rules based on those events.

We wrote Tracee with the following in mind:
- Tracee was designed to be a lightweight event tracer based on eBPF from its inception
- Tracee is built on bcc, and doesn't rewrite the low level BPF interface.
- Tracee was designed to be easily extensible, for example, adding support for new system calls in tracee is as easy as adding two lines of code, where you describe the syscall name and argument types.
- Other events are also supported, such as internal kernel functions. We now already have cap_capable supported, and we are adding support for security_bprm_check lsm hook. As lsm security hooks are strategic points to security, we plan to add more of these in the near future.

**Comment by carmark** [comment]
Thanks @yanivagman .
