### ISSUE TITLE
convert basic signatures from go to rego

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#487]
we have implemented a couple of signatures in rego, with a few in other forks. now that we have rego signatures which are significantly simpler, we should convert the basic signatures - those that are have simple business logic and no state - into rego.

**Comment by simar7** [comment]
Sounds good to me but should we shortlist such signatures and list them in this issue so we can keep track of them?

**Comment by itaysk** [comment]
there are just 2 signatures at the moment:
- anti debugging
- code injection
first one is already converted, second is being worked on by @roikol .

**Comment by yanivagman** [comment]
Do we know something about how the performance overhead of the OPA signatures is compared to the GO signatures?
I think this should be tested before deciding we should always default to OPA signatures for signatures with no state

**Comment by itaysk** [comment]
I thought the same as you and had it in the plan, but it was decided to skip the benchmark in the bigger forum (including you). I think it's too late to change our minds now, we are on the final stretch. It's a good idea to open an issue for benchmarking sigs

**Comment by itaysk** [comment]
closed by #528
