### ISSUE TITLE
self registration for go signatures

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#488]
if we add/remove go signatures, we need to add/remove the signature's file, and also update the `ExportedSignatures` in a different file. it would be better if a signatures could self-register themselves

**Comment by yanivagman** [comment]
I think this is what I had in the original design of Tracee-rules when I used the init() function to register the signals, can we do the same with goplugins?

**Comment by simar7** [comment]
> if we add/remove go signatures, we need to add/remove the signature's file, and also update the `ExportedSignatures` in a different file. it would be better if a signatures could self-register themselves

Which part of the existing setup are we trying to improve upon? If an external user wants to use a Go plugin they created, they have to tell us though someway (today it's an exported variable `ExportedSignatures`) about their plugin so we can register. 

Maybe I don't understand what "self registration" implies in this context. Could you expand on that a bit? It might help to describe the desired state.

**Comment by itaysk** [comment]
@yanivagman yes IIRC you're right
@simar7 we are talking about how this `ExportedSignatures` is being maintained. instead of a hardcoded list of sigs it can be that every sig adds itself to the list. the improvement is in the contribution workflow, so each sig is self contained, and we eliminate a point of coordination (between the sigs) that was the list. 

I actually don't think it's a change in tracee-rules even, probably just a signature scoped change, so other plugin authors can do whatever they want, but at least in our sigs, it beneficial because we are expecting external contributors and because this will be used as example for others.

**Comment by simar7** [comment]
> @yanivagman yes IIRC you're right
> @simar7 we are talking about how this `ExportedSignatures` is being maintained. instead of a hardcoded list of sigs it can be that every sig adds itself to the list. the improvement is in the contribution workflow, so each sig is self contained, and we eliminate a point of coordination (between the sigs) that was the list.
> 
> I actually don't think it's a change in tracee-rules even, probably just a signature scoped change. the plugin author could already do this in their plugin, and contaty if we do this in our plugin it doesn't force other to do so as well. BUT the reason to still to it in ours is because we are expecting external contributors to our sigs, and because our sigs code will be used as example for others.

I see. So if I'm understanding it correctly, signatures will modify some run time state, by registering themselves with Tracee on their own (maybe via a global state variable through init()?) If it is the case, I personally think it's an anti-pattern. Global state is prone to failures in various ways.

The current behaviour seems simpler to use and debug. If the signature doesn't do what we define as a requirement, we don't use it. https://github.com/aquasecurity/tracee/blob/d58ae466fc2ef363919119820deac488e23c7161/tracee-rules/signature.go#L67-L71

While it is stricter, it is simpler to debug and implement.

**Comment by itaysk** [comment]
> Global state is prone to failures in various ways

we already have a global var today, that is the `ExportedSignatures`. So this proposal will not help or harm this, it's just about how updating this var is done (that the sig will update it autonomously). Also it's worth mentioning that it's global only within the plugin. the plugin is a standalone go module/package and shares nothing with Tracee. Finally I'll add that this is not uncommon in go e.g Kubernetes controller runtime

Having said that I think this is not very important.. I thought it'll be a small quality of life improvement for signature authors will help us avoid merge conflicts, but if you don't think it's an improvement we can forgo this
