### ISSUE TITLE
Improve gobpf resiliency

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#49]
With the rewrite from Python to Go, the are some issues that require investigation: 
- [x] Configurable perf map size
- [ ] Consider events channel size
- [x] How to handle lost events
- [x] Show events count and lost/err count in epilogue

**Comment by itaysk** [comment]
configurable perfmap size has an open PR: https://github.com/iovisor/gobpf/pull/218/files

**Comment by itaysk** [comment]
I created a PR in gobpf to add lost events channel: https://github.com/iovisor/gobpf/pull/235

**Comment by yanivagman** [comment]
@itaysk are there any more items that need to be investigated here or we can close this issue?

**Comment by yanivagman** [comment]
Closing this as we are not using gobpf anymore

**Comment by itaysk** [comment]
the one item that's left in this list is unrelated to gobpf

**Comment by yanivagman** [comment]
If you think this item deserves its own issue - go ahead and open a new one
