### ISSUE TITLE
Example in tracee-rules/README.md is invalid

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#494]
The quickstart command in the tracee-rules readme fails: `sudo tracee-ebpf -o format:gob -o option:eot | tracee-rules --tracee-file /dev/stdin`

 In particular the following error is emitted `error handling event by signature Code injection: argument flags not found`

I believe this is because the default rules for tracee-ebpf do not emit events with the argument 'flags' which is looked for in the 'Code injection' rule which is used by default in tracee-rules.

I believe to resolve this issue a working quickstart example should be added to the README and a test should be added to verify that it's always working.

**Comment by itaysk** [comment]
the example is working for me (I checked before I write it). which commit are you on?

**Comment by itaysk** [comment]
thanks @grantseltzer . I did check that it was working before I added this to the readme. I'll investigate this today

**Comment by itaysk** [comment]
I accidentally opened #496 today and it seems to be related to this issue. I'll push a fix today

**Comment by grantseltzer** [comment]
Closed by #498
