### ISSUE TITLE
Consider using filepath.Walk() to recursively scan for signatures

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#501]
Currently we do a custom logic to go through signatures in rules-dir: https://github.com/aquasecurity/tracee/blob/efdc613024f04f45b4be877372bd474f31da890d/tracee-rules/signature.go#L48-L98

We can probably improve this (also cut down on logic) if we use filepath.Walk() from stdlib.

please create an issue for this feature request and remove this from the code.. (same for the other similar comment)

_Originally posted by @itaysk in https://github.com/aquasecurity/tracee/pull/477#discussion_r566815240_

**Comment by simar7** [comment]
Since the creation of this issue, Go 1.16 has released filepath.WalkDir which guarantees better perf than filepath.Walk. https://golang.org/pkg/path/filepath/#WalkDir

**Comment by danielpacak** [comment]
Resolved by #901
