### ISSUE TITLE
Upgrade libbpf submodule to v0.3

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#511]
The latest release of libbpf contains a handful of new features (task local storage, ringbuf epoll fd) and a particular fix (for ringbuff_poll) that we're going to want. See release notes here:

https://github.com/libbpf/libbpf/releases/tag/v0.3

**Comment by yanivagman** [comment]
We should probably wait a few more days for 0.4 to be out.
This relaese will include https://github.com/libbpf/libbpf/commit/a26ae1b2540a8e9bb46b66f41d16d0c2e73ea4d8
which should allow us to replace our READ_KERN macros and make the move to CO-RE easier (while still supporting older kernels)
