### ISSUE TITLE
exclude example signatures

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#514]
We have example signatures in tracee-rules, which live next to the regular signatures, and are included in the final build. We need to make sure that the examples are excluded from final product (or at least not being activated). I think the best approach would be to move them to a different directory will not get picked up by the build. Maybe a "test" directory because at some point we should use those example sigs for testing

**Comment by simar7** [comment]
How about adding build flags?

**Comment by itaysk** [comment]
SGTM
