### ISSUE TITLE
ID for rules

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#515]
Currently rules are identified by their name. If a user wants to select which rules to load, they need to give their full name on the command like, which is not ideal. We should add an ID field to signatures' metadata and use that in the --rules option.

**Comment by yanivagman** [comment]
Signatures will need to add their own signature id?
This may cause conflicts (in the future) when using signatures from two different sources, and require signature writers to check for an available id.

**Comment by itaysk** [comment]
good point! on the other hand, auto generating IDs will be hard to make deterministic. another consideration is that we need to be able to support 3rd party sigs, that were not bundled with tracee

**Comment by itaysk** [comment]
Here's a suggestion: ID takes the following form: `XXX-12345`.
`XXX` is a prefix that indicates the source of the sig, for example for builtin signatures we can have `TRACEE` prefix and the number is a running number that uniquely identifies signatures.
For buildin signatures, because it's controlled by us and every new sig has to go through a PR, we can control how numerical ids are issued (just look at the latest). and for others - just use your own prefix and then you're in charge it's numerical IDs.
examples:
`TRACEE-123`
`ITAYSK-321`

**Comment by yanivagman** [comment]
I'm not sure I understand the benefit of using such IDs. What's the difference between the user entering an ID compared to signature name? Is it the size of the name of the signature? If so, there are other possible solution that don't use ID for that, like using a unique prefix of a signature name

**Comment by itaysk** [comment]
1. format of the field: name can be any size and include any character. so entering a name on the command line, into a flag that takes csv, is not ideal experience
2. uniqueness: id is unique and name doesn't have to be

**Comment by yanivagman** [comment]
> format: name can be any size and include any character. so entering a name on the command line, into a flag that takes csv, is not ideal experience

Is remembering the signature ID considered an ideal experience? I don't think so

> uniqueness: id is unique and name doesn't have to be

We can require that names will be unique, I don't see a reason that two different rules will have the same name.
If you still think that signatures IDs are required (for the MVP? why?), I think they should be auto generated.
An example of a deterministic ID generation can be taking the hash of the signature name or filename (in the case that we decide that signature names are not unique)

**Comment by itaysk** [comment]
> Is remembering the signature ID considered an ideal experience? I don't think so

not sure what you mean by remember. you do `tracee-rules --list` and see which rules are available, and if you want to pick just some of them you see their ID right there

> If you still think that signatures IDs are required (for the MVP? why?)

because names can be any length any char, inputing them into a csv flag will be bad. 
`tracee-rules --rules this is a very, vary! weird name, and this name \is ever $worse!`

IDs can be limited to `[A-Z]+-[0-9]+` which is easier to handle as user input.

> An example of a deterministic ID generation can be taking the hash of the signature name or filename

thought about it too, not a bad idea is it better than a "friendly" ID name? something that you can understand. I think of an ID like a URI (also considered using URI but that would be overkill)

**Comment by yanivagman** [comment]
> thought about it too, not a bad idea is it better than a "friendly" ID name? something that you can understand. I think of an ID like a URI (also considered using URI but that would be overkill)

It is better as you will not need to add an ID to each signature as part of its metadata, as well as to avoid collisions

**Comment by itaysk** [comment]
I'm fine with hash if you think it's better, but we'll need to add it to metadata anyway. signatures would be referenced in other places as well: just one example is AVD.

**Comment by yanivagman** [comment]
Why should it be part of the metadata if we can auto generate it?

**Comment by itaysk** [comment]
who should auto-generate it? (and when?)

**Comment by yanivagman** [comment]
That's an implementation decision.
Tracee-rules can auto-generate it on start, after enumerating the signatures. The result will always be the same. It is also possible to cache the generated IDs for later use

**Comment by itaysk** [comment]
how do you suggest it will work in the case of AVD?

**Comment by yanivagman** [comment]
What do you mean? Just like I wrote

**Comment by itaysk** [comment]
tracee-rules is not involved in this use case. are you familiar with AVD?

**Comment by yanivagman** [comment]
Never worked with it. 
Anyways, no matter what will generate the IDs - the result will always be the same

**Comment by itaysk** [comment]
we can't expect from external tools, like AVD to regenerate hashes for signatures every time they want to interact with one. not only it's cumbersome, it's also a huge potential for bugs (even the slightest difference from how trace does it vs. the external tool will break the hash). regardless if the ID is hash or sequential number, I think it needs to be included with the metadata.

@simar7 as the maintainer for AVD, and having worked with similar scenarios from indexing trivy/kube-hunter/nvd/etc - wdyt?

**Comment by simar7** [comment]
Here are my thoughts in no particular order:

1. As a user of tracee-rules, I do like the ease of use of having IDs. Passing in the name is cumbersome today and is error prone as @itaysk pointed out.
2. The problem of having unique IDs doesn't exist today (no third party signatures AFAIK) but may do so in the near future. While it is a good concern, I think it's a premature optimization for the MVP deliverable. We could enforce a naming convention like `TRC-12345` for first party (written by the core team aka us) and `XYZ-12345` if the need arrives. 
3. I don't think we can expect the users to generate anything for that matter. People and Tools are both considered Users of Tracee. Users want (and should) use signatures (created by us or someone else) as packages, not having to worry about generating hashes etc. 
4. Specifically for AVD, I believe the idea is to expose Tracee signatures via an AVD page (e.g. https://avd.aquasec.com/tracee/TRC-12345) citing all relevant information. AVD as a consumer of signatures shouldn't need to worry about their implementation. Think of it as AppShield policies today. They are simple, come with a unique ID and can be taken as-is by AVD to generate a page. We do the same for kube-hunter and NVD as well. This approach is plain and simple.

**Comment by yanivagman** [comment]
Agree that this shouldn't be part of the MVP.
I don't like the idea that whoever writes a new signature will have to look for an available ID and put it in the signature metadata - this is cumbersome, and error prone (ID collision)
What I had in mind is to auto-generate the IDs by hashing the signature names using tracee-rules or some dedicated binary that will do this hashing - why is this a problem for AVD?

**Comment by simar7** [comment]
AVD is just a consumer of these signatures. The future workflow would be like the following:

1. AVD reads a signature (Go or Rego) as input.
2. Signature is created into a Markdown and with its own unique Signature ID that it contains as metadata.
3. The said Markdown page is linked via an interface that's TBD (potentially tracee cli).

There are a few unknowns here: Does AVD only show Aqua created signatures? Or all signatures including third party as well? If it's the former we can label our signatures appropriately (Unique ID or otherwise) to solve this. If not my proposed idea of `XXX-12345` would work.

My point is that AVD shouldn't need to calculate anything. It should be able to just consume the signature files as-is, generate markdown and that's all. After all that's what it was designed to do. So I'm not saying generation of hash is a problem, it's just added complexity for the consumer to consume signatures which we can avoid.

**Comment by itaysk** [comment]
Good point Simar, thank you.

> Agree that this shouldn't be part of the MVP.

@yanivagman if I'm understanding @simar7 correctly (Simar correct me if I'm wrong!), he referred to just enforcing uniqueness which isn't needed, not to generally having IDs which is needed ("The problem of having unique IDs doesn't exist today")

I don't think it's reasonable to ship Tracee with the `--rules` flag as it is today. it's almost unusable. If we exclude ID from the release, we should exclude this flag as well (which I know we will be asked to re-add soon enough)

**Comment by yanivagman** [comment]
I think we should discuss in more details about the ID generation before we add it, as it will be part of the signature creation process from this point and forward.
I also think that for the MVP we can remove the "--rules" flag if we are not sure about the proper way to implement this feature.

**Comment by itaysk** [comment]
I have left the --rules flag in the entrypoint for now because it's implementation will probably be the same when we move to ID, but I've removed it from the readme as to not advertise this flag.

**Comment by simar7** [comment]
> Good point Simar, thank you.
> 
> > Agree that this shouldn't be part of the MVP.
> 
> @yanivagman if I'm understanding @simar7 correctly (Simar correct me if I'm wrong!), he referred to just enforcing uniqueness which isn't needed, not to generally having IDs which is needed ("The problem of having unique IDs doesn't exist today")
> 
> I don't think it's reasonable to ship Tracee with the `--rules` flag as it is today. it's almost unusable. If we exclude ID from the release, we should exclude this flag as well (which I know we will be asked to re-add soon enough)

Yeah that's a good call. We can circle back on this.

**Comment by itaysk** [comment]
after discussing this further, we agreed that the format of an ID is:
1. `[A-Z]3-[0-9]+`
2. sequential
3. included in the signature metadata

**Comment by simar7** [comment]
Closed via https://github.com/aquasecurity/tracee/pull/567
