### ISSUE TITLE
Decode syscalls arguments

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#520]
We alreaady decode some of the syscall arguments (see #493), but there are stil some syscall arguments for which we don't decode the argument values although it can be useful.
- [ ] nstype for setns syscall
- [ ] cap_user_data_t for capset syscall
- [x] struct timespec for nanosleep and some other syscalls
- [ ] mmap flags (#2336)
More...

**Comment by itaysk** [comment]
also https://github.com/aquasecurity/tracee/issues/453

**Comment by yanivagman** [comment]
Closing in favor of #2336
