### ISSUE TITLE
Place artifacts/configurations in a system directory instead of searching next to the executable

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#522]
in `tracee-rules` the default behavior is to search for rules files in the same directory as the executable. This isn't optimal for when people have the executable installed in their PATH. We should decide on a location like `/var/tracee`,  `/opt/tracee`, `/usr/share/tracee` or some like this.

**Comment by itaysk** [comment]
some thoughts:
1. tracee-rules is a component of tracee and the primary use case for it is via the tracee container image. people starting to use tracee-rules standalone - that's a problem that we'd want to have, but I don't think we're there yet.
2. the rules directory location is already configurable using the `--rules-dir` flag. you can already put the rules in a system-wide location and use it this way.
3. who is creating this system-wide rules directory? is it manually created by the user or by tracee? I think that if we did think that this use case is relevant, it can be generalized into "installing tracee" by packaging deb/rpm/etc packages.

having said all of this, I think tracee-erules can generally align with tracee-ebpf in that we use /tmp/tracee as a work dir for various things (including rules), and that work dir should definitely be use configurable.

many thoughts in one comment but wdyt?

**Comment by grantseltzer** [comment]
You bring up good points, perhaps the best course of action is to wait on doing anything related to this and decide once the project is more mature and we have data points on how users want to consume the functionality.
