### ISSUE TITLE
Link to the examples are broken

### ISSUE THREAD

**Issue by naveensrinivasan** [aquasecurity/tracee#524]
Trying to follow the examples in `tracee-rules` https://github.com/aquasecurity/tracee/blob/fc534300281f1ca60498cf49b196825432054e07/tracee-rules/Readme.md 

The example.go and rego are pointing to broken links.

**Comment by simar7** [comment]
Thanks @naveensrinivasan for the heads up - we'll handle this via https://github.com/aquasecurity/tracee/pull/523
