### ISSUE TITLE
document signature helpers

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#538]
document the fact that we have helpers, why/when/how to use them. both rego and go

**Comment by simar7** [comment]
Could you add what's the acceptance criteria here? Is this to document `helpers.rego`?

**Comment by itaysk** [comment]
document the fact that we have helpers, why/when/how to use them. both rego and go

**Comment by itaysk** [comment]
related: https://github.com/aquasecurity/tracee/issues/599
