### ISSUE TITLE
investigate alternatives to json unmarshaling in event processing

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#544]
json unmarshaling is notoriously inefficient and using it in the critical path should be considered.
alternatives might be a simple string operation, or using a different, more efficient json library. a valid outcome of this task is to leave things the way they are.

original discussion:
https://github.com/aquasecurity/tracee/pull/528#discussion_r573841114

**Comment by yanivagman** [comment]
I don't see we use json unmarshaling in event processing anymore so I'm closing this.
Please reopen if you think I missed something.
