### ISSUE TITLE
document event args for custom kprobes

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#546]
we have some kprobes where we create a custom event with args that we choose to collect (e.g cap_capable, commit_creds). unlike syscalls, where the user can expect the same args as in the man pages, here it's up to us to document what we chose to collect.
this should be included in the --list flag as well as in the online documentation

**Comment by yanivagman** [comment]
related: #1398

**Comment by yanivagman** [comment]
closing in favor of #1579
