### ISSUE TITLE
tracee-ebpf panics on invalid flag usage

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#560]
**What I wanted to do**
Print events as JSON output to a file.

**What I observed**
```
sudo ./dist/tracee-ebpf -o json -o out.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x5a17a4]

goroutine 1 [running]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.newEventPrinter(0xc0000acc50, 0x8, 0xc000111e00, 0x73c8e0, 0xc0000ae008, 0x73c8e0, 0xc0000ae010, 0xc00012ca00, 0x3c, 0x0, ...)
        /usr/vagrant/repos/tracee/tracee-ebpf/tracee/printer.go:67 +0xc4
github.com/aquasecurity/tracee/tracee-ebpf/tracee.New(0xc000119d00, 0xc000111f00, 0xc000111ec0, 0x400, 0x400, 0x0, 0x0, 0xc00012ca00, 0x3c, 0xc000080460, ...)
        /usr/vagrant/repos/tracee/tracee-ebpf/tracee/tracee.go:272 +0x3a5
main.main.func1(0xc000111e80, 0xc00013e400, 0x14)
        /usr/vagrant/repos/tracee/tracee-ebpf/main.go:75 +0x5ad
github.com/urfave/cli/v2.(*App).RunContext(0xc000086480, 0x73e9a0, 0xc0000ac010, 0xc000080050, 0x5, 0x5, 0x0, 0x0)
        /home/vagrant/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:311 +0x70d
github.com/urfave/cli/v2.(*App).Run(...)
        /home/vagrant/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
        /usr/vagrant/repos/tracee/tracee-ebpf/main.go:144 +0x832
```

**What I expected to see**
1. Tracee not panicking.
2. JSON event output in a file. It works when I specify the correct flags: `sudo ./dist/tracee-ebpf -o json -o out-file:out.json
`

**Acceptance Criteria**
Tracee should not panic but rather gracefully exit with an meaningful error message.

**Comment by simar7** [comment]
Note for the reader/contributor: This happens due to this line not checking `res` before usage https://github.com/aquasecurity/tracee/blob/ef7e96ace8592fe6eb2333008391f0bfb9b6ce8e/tracee-ebpf/tracee/printer.go#L67

**Comment by itaysk** [comment]
Agree this is a bug that should be fixed, but why wait until printing to determine.
we discussed this in comments of another pr, I think what should be done is that every XXXConfig struct have an associated ValidateXXXConfig function (like output already has), which is used to validate input before/when starting the trace

**Comment by krol3** [comment]
@simar7 could be closed this issue or is missing something?
