### ISSUE TITLE
Make use of CAP_BPF (5.8+) to remove need to run tracee-ebpf as root

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#575]
Starting in kernel 5.8 linux supports the CAP_BPF capability which we can grant to the tracee-ebpf binary (or container) to remove the need to run as root/privileged.

**Comment by itaysk** [comment]
is this a dup of https://github.com/aquasecurity/tracee/issues/286 ?

**Comment by grantseltzer** [comment]
@itaysk Why yes, yes it is!
