### ISSUE TITLE
Add tests common framework

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#594]
Issue #253 subject was changed to e2e tests as "adding tests" was too large scope.
I think we should add some common framework code that will be used by unit tests, and will enable us to add selftests to new and existing events on the go. This common framework code should probably do the following:

Initialize itself (whatever that will be)
For some_event := range Tracee's events:
a. Start tracee with -e "some_event" -p "self_pid"
b. Generate some_event (e.g. call the syscall that generates it)
c. Stop tracee
d. Check output matches expectation
e. Check no errors occured.

After having this common code, we can write simple selftests to many of Tracee's events. To trigger an event, it should be enough to give dummy arguments to the event and check that we traced the event correctly (the dummy arguments should be traced even if the event returned an error - for example in a failed syscall)

**Comment by simar7** [comment]
After discussing this on the meeting today a few more interesting points were raised:

1. Using Tracee as a library to instantiate eBPF code once and use many times across various test cases
2. Parallelize test inputs
3. First cover those test inputs that don't cause a side effect on the system/setup (e.g. mounting fs calls)
4. Potentially take a look into https://github.com/testcontainers/testcontainers-go if it can help with isolation
