### ISSUE TITLE
Create a unique pid file

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#607]
Today the code looks like was written to only run a single instance of Tracee at a time. https://github.com/aquasecurity/tracee/blob/228c6d329e86dd8f62bb5fe48761e78b67dafb39/tracee-ebpf/tracee/tracee.go#L328-L331

But this has changed now so we will need to support creating a unique pid file for each run. `WriteFile` truncates the file if it exists and rewrites it. 

_Originally posted by @simar7 in https://github.com/aquasecurity/tracee/pull/606#r593393644_

**Comment by itaysk** [comment]
https://github.com/aquasecurity/tracee/pull/261 : "instead of tracee.${pid}, will be tracee.pid with the ${pid} written in it"
This was based on good feedback from @yanivagman that this way is more conventional (e.g. docker).
Yaniv, do you have an idea how to address this?

**Comment by yanivagman** [comment]
I'm not sure I understand - why do we need more than one instance of tracee?

**Comment by simar7** [comment]
While implementing this, I also noticed that the readiness file is not cleaned up after tracee quits. If we need a unique file we will have to make sure it is cleaned up after tracee exits.

**Comment by itaysk** [comment]
I think we can close this on grounds that tracee-ebpf is not meant to run concurrently and if so, different output directories can be provided so outputs won't collide. If you still think this is needed please reopen
