### ISSUE TITLE
can't specify multiple rules to load

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#610]
the `--rules` flag works only if one rule id is specified

```
❯ ./tracee-rules --input-tracee file:stdin --input-tracee format:json --rules TRC-2              
{ "eventName": "ptrace", "args": [ {"name": "request", "value": "PTRACE_TRACEME"} ] }

*** Detection ***
Time: 2021-03-13T14:36:56Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: 
Hostname: 
^C

❯ ./tracee-rules --input-tracee file:stdin --input-tracee format:json --rules TRC-1,TRC-2
{ "eventName": "ptrace", "args": [ {"name": "request", "value": "PTRACE_TRACEME"} ] }
```

**Comment by simar7** [comment]
Good question, it confused me at first as well but it looks like urfave/cli is a little different when specifying flags. `--rules` is a type `StringSlice` and while we may think `--rules TRC-1,TRC-2` should work the library doesn't handle it but rather expects: `--rules TRC-1 --rules TRC-2`.  See this issue for more details https://github.com/urfave/cli/issues/910#issuecomment-542353576

I suggest we should print to stdout the signatures Tracee loads when it starts. Something like the following:
```
./dist/tracee-rules --input-tracee file:./out.test --input-tracee format:json --rules TRC-1 --rules TRC-2                         
Loaded signature:  TRC-1
Loaded signature:  TRC-2

*** Detection ***
Time: 2021-03-15T23:22:27Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: 
Hostname: 
```

What do you think about this?

We should probably update the README. Currently we say to comma separate. I will start a PR to do that.

**Comment by itaysk** [comment]
SGTM thanks!
