### ISSUE TITLE
use gotemplates in stdout

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#611]
We already use gotemplates for compiling wehbook payload. the same could be used to compile the stdout message. this has the following benefits:

1. generally, same features should be supported in stdout and webhook printing, so no reason of having two implementations (like now)
2. easier to detect bugs/issues
3. allows the user to customize the stdout template like in tracee-ebpf `--output gotemplate=/path/to/template`

**Comment by simar7** [comment]
For my understanding, are the following assumptions correct to qualify as an _acceptance criteria_?

1. `tracee-rules` will support an `--output` flag.
2. The above mentioned `--output` flag will only support one argument as an option, i.e. a gotemplate param: `--output gotemplate=path/to/my.tmpl`.
3. If no `--output` flag is specified the output will be the human readable output we support today. Which for posterity is:
```
*** Detection ***
Time: 2021-03-15T23:45:41Z
Signature ID: TRC-2
Signature: Anti-Debugging
Data: map[]
Command: 
Hostname: 
```
4. Sample usage of the new feature will look as follows:
```
./tracee-rules --rules TRC-1  --output gotemplate=path/to/csv.tmpl
TRC-2,Anti-Debugging

```

Where the `csv.tmpl` is as follows:
```
{{ .ID }},{{ .Name }}

```

**Comment by itaysk** [comment]
yes, with the addition that

>If no --output flag is specified the output will be the human readable output we support today.

will be using a gotemplate as well

**Comment by simar7** [comment]
Closed via https://github.com/aquasecurity/tracee/pull/630
