### ISSUE TITLE
add sprig to gotemplates

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#614]
[sprig](http://masterminds.github.io/sprig/) is a popular and useful library of functions that helps authoring go templates. kind of like a stdlib for gotemplates. I think it would be a good addition to whomever writes templates in tracee-ebpf/tracee-rules. 

It might also help address some outstanding issues like https://github.com/aquasecurity/tracee/pull/582#discussion_r584263304

**Comment by simar7** [comment]
Added in https://github.com/aquasecurity/tracee/pull/630
