### ISSUE TITLE
Tracee Configuration API

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#636]
In order to allow configuration of tracee-ebpf during runtime, for example to change filters, an API definition is required to communicate to tracee-ebpf.
This API can then be implemented through gRPC, HTTP or any other integration method deemed appropriate.

work breakdown from https://github.com/aquasecurity/tracee/issues/636#issuecomment-943216262:

- [ ] Load/unload a bpf program in runtime
- [ ] Attach/detach an event to a bpf program in runtime
- [ ] (depends on 1+2) - enable/disable events in runtime
- [ ] Update filters in runtime (#1726 )
- [ ] Update capture options in runtime

**Comment by yanivagman** [comment]
Having a unix socket may be a better fit for this use case

**Comment by grantseltzer** [comment]
What is the use case for this where tracee couldn't just restart? Could we start a new instance of tracee-ebpf and then close the old one?

**Comment by itaysk** [comment]
+ @eidans

**Comment by itaysk** [comment]
https://github.com/developer-guy/falco-hot-reload-with-sidecar

**Comment by itaysk** [comment]
related discussions:
https://github.com/aquasecurity/tracee/pull/405
https://github.com/aquasecurity/tracee/pull/454

**Comment by rafaeldtinoco** [comment]
One thing that will allow this to happen is the discussion being made at:

https://github.com/aquasecurity/libbpfgo/pull/78#issuecomment-920315415

which will allow links to be detached/destroyed and re-attached/created again.

**Comment by yanivagman** [comment]
This issue is too big. I think we should split it to the following issues:
1. Load/unload a bpf program in runtime
2. Attach/detach an event to a bpf program in runtime
3. (depends on 1+2) - enable/disable events in runtime
4. Update filters in runtime
5. Update capture options in runtime

**Comment by mtcherni95** [comment]
I think we should achieve most of the requirements by for example adding a gRPC server within tracee-ebpf. We can define in a proto a grpc service like "Configuration" with many rpcs, each of them regarding a "domain" like update of filter, captures, events and so on.

**Comment by itaysk** [comment]
We should consider what's the widest common interface that tracee's users would like. I'm not sure that's GRPC

**Comment by yanivagman** [comment]
Updated the issue to include things from #1725, which is a dup

**Comment by yanivagman** [comment]
Closing in favor of #2991
