### ISSUE TITLE
Create architecture diagram of the interaction between tracee-ebpf and tracee-rules

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#637]
We need more documentation explaining how the different pieces interact with one another. It'd be good to have a reference-able blog post about it as well.

**Comment by simar7** [comment]
Recommend: https://excalidraw.com

**Comment by simar7** [comment]
Are you working on this @grantseltzer? - if not I can tackle it today.

**Comment by grantseltzer** [comment]
@simar7 I was going to but wouldn't be getting to it until early next week, go for it!

**Comment by simar7** [comment]
@grantseltzer I added a high level overview. Usually for inter software communication I would've used a ladder diagram but as I was drafting it I realized there isn't a whole lot of back-and-forth between tracee-ebpf and tracee-rules (in fact the latter is just a pure consumer of the former).
