### ISSUE TITLE
Fix documentation content issues

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#652]
- [x] make sure links are not broken, both in docs and readmes, change to relative links
- [x] Headers should match navigation
- [x] tables are not formatted right (probably different markdown parser)
- [x] small typos
- [ ] beef up content is possible (remember those docs are user facing, not contributor facing)

**Comment by grantseltzer** [comment]
Using this to take notes on observations:

- Add libbpf to prerequisites
- Logo in top left is messed up
-

**Comment by grantseltzer** [comment]
per @yanivagman:

- Links are broken
- No one-liner of tracee-ebpf
- Even if choosing to only keep the main readme tracee one-liner, the is no "-it" for interactive mode, which enables the use of ctrl+c
- No links from tracee-ebpf readme to the docs (capture, secure tracing, and other stuff)

**Comment by itaysk** [comment]
fixed in: #673
