### ISSUE TITLE
adding to tracee-ebpf event data epoc time

### ISSUE THREAD

**Issue by idanr1986** [aquasecurity/tracee#658]

**Comment by simar7** [comment]
Correct me if I'm wrong but my understanding:
1. The time for investigation purposes should be the actual incident time and not the detection time.
2. Accuracy: time between detection in tracee-rules and actual incident are slightly different

**Comment by simar7** [comment]
https://man7.org/linux/man-pages/man7/bpf-helpers.7.html

```

       u64 bpf_ktime_get_ns(void)

              Description
                     Return the time elapsed since system boot, in
                     nanoseconds.  Does not include time the system was
                     suspended.  See: clock_gettime(CLOCK_MONOTONIC)

              Return Current ktime.
```

**Comment by yanivagman** [comment]
Done in https://github.com/aquasecurity/tracee/pull/837
