### ISSUE TITLE
Generate/package a vmlinux.h file for shipping with tracee-ebpf CO:RE functionality

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#663]
CO:RE functionality (#662) if we import a vmlinux.h file. We should be able to ship one version of vmlinux.h and not have any issue with running it on different kernels, but we could attempt to generate a fresh one on build. Need to explore the proper way of shipping this more.

More on vmlinux.h [here](https://blog.aquasec.com/vmlinux.h-ebpf-programs)

**Comment by rainkin1993** [comment]
It seems that only kernel 5.2+ supports BTF compiling configuration to generate vmlinux.h. 
If tracee require vmlinux.h, does it mean that tracee cannot run in older  kernel version (e.g., 4.19)?

**Comment by grantseltzer** [comment]
@rainkin1993 This would likely be true if we only supported a BTF version of tracee, but we will support building against particular kernel headers (therefore run on 4.19) for the foreseeable future. 

There are ways around supporting kernels that don't have BTF support. If you're curious check [this discussion](https://github.com/aquasecurity/tracee/discussions/713#discussioncomment-662230) out, but i'm not aware of plans to do so.

**Comment by rainkin1993** [comment]
You said "we will support building against particular kernel headers (therefore run on 4.19) for the foreseeable future."
If I understand it correctly, you mean generate different binaries for different kernel version by using particular kernel headers for corresponding old kernel version.
But in my understanding, ebpf C program w/ CO-RE is not compatible with ebpf C program w/o CO-RE (at least the #include file, and maybe more). So if tracee wants to support running in old kernel versions (without BTF, CO-RE) and newer version (with BTF, CO-RE), then the project should maintain two version of c program, one support CO-RE and another without CO-RE support.

I read the link you provided, if that is possible, it seems that the best solution is 
1) generates BTF files for **old kernel versions** to let them support CO-RE
2) only maintain one version of tracee C source code enabling CO-RE (e.g., including vmlinux.h header)
3) Compile Once in dev machines, and Run Everywhere in production machines.

**Comment by yanivagman** [comment]
@rainkin1993 the plan is to keep support for old kernel versions w/o the need to generate BTF for them.
This can be done by maintaining one source file, which will have some compilation flags to support these two options

**Comment by grantseltzer** [comment]
> You said "we will support building against particular kernel headers (therefore run on 4.19) for the foreseeable future."
> If I understand it correctly, you mean generate different binaries for different kernel version by using particular kernel headers for corresponding old kernel version.

Correct. We plan on having CI/CD that will take different versions of the kernel-headers package and compile against those so people can just download the binary and run it. I can elaborate more on how that works if you're curious!

> But in my understanding, ebpf C program w/ CO-RE is not compatible with ebpf C program w/o CO-RE (at least the #include file, and maybe more). So if tracee wants to support running in old kernel versions (without BTF, CO-RE) and newer version (with BTF, CO-RE), then the project should maintain two version of c program, one support CO-RE and another without CO-RE support.

Correct, if you look [here](https://github.com/grantseltzer/tracee/blob/co-re-kernel-reads/tracee-ebpf/tracee/tracee.bpf.c#L253-L265), i'm currently trying to use a conditional compile so that it's only 1 file.

The thing that makes it non-compatible is the application of attribute 'preserve_access_index' which is applied to all data structures at the top of vmlinux.h like this:

```
#ifndef BPF_NO_PRESERVE_ACCESS_INDEX
#pragma clang attribute push (__attribute__((preserve_access_index)), apply_to = record)
#endif
```

Theoretically you should be able to do this with kernel headers, and not need vmlinux.h, but we import headers that are architecture specific and breaks the preserve_acces_index attribute.

> 
> I read the link you provided, if that is possible, it seems that the best solution is
> 
> 1. generates BTF files for **old kernel versions** to let them support CO-RE
> 2. only maintain one version of tracee C source code enabling CO-RE (e.g., including vmlinux.h header)
> 3. Compile Once in dev machines, and Run Everywhere in production machines.

Certainly something we have and will keep considering. Happy to bounce these ideas around with you!

**Comment by rainkin1993** [comment]
Thanks for your explanation. @yanivagman @grantseltzer 

> Correct. We plan on having CI/CD that will take different versions of the kernel-headers package and compile against those so people can just download the binary and run it. I can elaborate more on how that works if you're curious!

I am really interested in how it works in detail.

> Certainly something we have and will keep considering. Happy to bounce these ideas around with you!

I try to run the ebpf CO-RE binary provided by the link and it does works in my ubuntu 18.04 which does not have built-in BTF files.
Basically, 
1) it compiles a ebpf C code into binary in a kernel 5.x
2) generate BTF files for old kernels (i.e., 4.x) into a certain directory.
3) install a patched libbpf (the patch is used to let libbpf to search the BTF files in the 2) directory)
4) directly run the ebpf binary generated from 1) in the old kernel (4.x)

Futuremore, it releases the BTF files for different old kernels in ubuntu package. So users only need to apt install the packet to get the BTF files directly.

**Comment by grantseltzer** [comment]
> Thanks for your explanation. @yanivagman @grantseltzer
> 
> > Correct. We plan on having CI/CD that will take different versions of the kernel-headers package and compile against those so people can just download the binary and run it. I can elaborate more on how that works if you're curious!
> 
> I am really interested in how it works in detail.

If you take a look at `tracee.bpf.c` you can see that we import all those header files (for one example, `linux/sched.h` which contains the definition for task_struct). Those are provided by various [packages](https://pkgs.org/search/?q=kernel-dev) that linux distributions provide and installed in standard locations. When we compile tracee, we specify specific paths for finding those headers ([link](https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/Makefile#L83-L92)).

Those headers/packages correspond to specific versions of the kernel, so the data structures in them should match the definitions that your running kernel knows about. An example of why this is important: if we want to extract the PID from the task_struct in a ebpf program, it'll be an issue if we compiled with kernel headers that say the pid can be found at the 30th byte of the data structure, but in reality it's at the 32nd.

We can achieve 'portability' if we compile with specific header packages, so the compiled tracee bpf program can be run on the kernel that corresponds with that header package. Header packages should correspond with specific kernel versions (At least typically the ones that major distributions ship with). Very similar to what BCC does except we're trying to give the option to  do the compilation before shipping.

We compile the bpf object and the go program separately, the Go program uses libbpf to load the bpf object. We are working on using go:embed to make it a single artifact.

> 
> > Certainly something we have and will keep considering. Happy to bounce these ideas around with you!
> 
> I try to run the ebpf CO-RE binary provided by the link and it does works in my ubuntu 18.04 which does not have built-in BTF files.
> Basically,
> 
> 1. it compiles a ebpf C code with CO-RE into binary in a kernel 5.x
> 2. generate BTF files for old kernels (i.e., 4.x) into a certain directory.
> 3. install a patched libbpf (the patch is used to let libbpf to search the BTF files in the 2) directory)
> 4. load and run the ebpf binary generated from 1) in the old kernel (4.x)
> 
> Futuremore, it releases the BTF files for different old kernels in ubuntu package. So users only need to apt install the packet to get the BTF files directly.

Yea it sounds solid to me. Worth starting a new discussion over. 

There are still other challenges to using vmlinux.h though that i'm trying to work through. Big thing is that vmlinux.h only includes data structures, not functions or macros. So we still have to redefine those, which gets dicey if function/macros are version specific. In my trace branch I linked you to I have a 'missing_macros.h' file. 

Another thing is that the CORE helpers in libbpf increase memory usage and blow the 512 byte stack limit in tracee.

**Comment by rainkin1993** [comment]
> If you take a look at tracee.bpf.c you can see that we import all those header files (for one example, linux/sched.h which contains the definition for task_struct). Those are provided by various packages that linux distributions provide and installed in standard locations. When we compile tracee, we specify specific paths for finding those headers (link).
> 
> Those headers/packages correspond to specific versions of the kernel, so the data structures in them should match the definitions that your running kernel knows about. An example of why this is important: if we want to extract the PID from the task_struct in a ebpf program, it'll be an issue if we compiled with kernel headers that say the pid can be found at the 30th byte of the data structure, but in reality it's at the 32nd.
> 
> We can achieve 'portability' if we compile with specific header packages, so the compiled tracee bpf program can be run on the kernel that corresponds with that header package. Header packages should correspond with specific kernel versions (At least typically the ones that major distributions ship with). Very similar to what BCC does except we're trying to give the option to do the compilation before shipping.
> 
> We compile the bpf object and the go program separately, the Go program uses libbpf to load the bpf object. We are working on using go:embed to make it a single artifact.

Do you have a docker container to do that automatically?
If you have finished that, is it possible to release that container because I think this is a general problem for other bpf projects and I also want to apply it to my projects.

**Comment by grantseltzer** [comment]
Yes sir! https://hub.docker.com/r/aquasec/tracee
