### ISSUE TITLE
Parsing error in signature

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#667]
reported by @eidans 
tracee-rules output:

```
21/04/01 14:34:04 error handling event by signature Standard Input/Output Over Socket: invalid character '\x11' in string literal
2021/04/01 14:34:05 error handling event by signature Standard Input/Output Over Socket: invalid character '\x11' in string literal
```

started tracee-ebpf -> tracee-rules using GOB

**Comment by yanivagman** [comment]
By (only) looking at the code, the only place which can return this kind of error in the stdio_over_socket, is from the GetAddrStructFromArg() function, which unmarshals the connect syscall addr argument. For some reason, it contains the \x11 character (vertical tab).
If there is an environment where this is reproducible - I suggest checking that the output of tracee-ebpf for the connect syscall addr argument is correct

**Comment by itaysk** [comment]
@eidans is this reproducible?

**Comment by yanivagman** [comment]
@eidans?

**Comment by yanivagman** [comment]
This is not reproducible, and no answer was given by @eidans so I'm closing it.
Please reopen if reproduced in v0.6.0 or later.
