### ISSUE TITLE
Incorporate Tracee Signatures into AVD database

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#669]
Just like other AVD components on each of our tools, we'd like to have a page for each AVD signature.

Acceptance Criteria:
- Have a page for each Tracee first party Signature that documents the impact and other important information related to it.

**Comment by simar7** [comment]
The PR for AVD was merged. Whenever we solve the AVD generation process problem, this can be closed.

**Comment by simar7** [comment]
They are available now. e.g. https://avd.aquasec.com/tracee/trc3/

**Comment by itaysk** [comment]
nice! @simar7  so how did you end up reading go signatures' metadata?
