### ISSUE TITLE
Add container start/stop events

### ISSUE THREAD

**Issue by tomyweiss** [aquasecurity/tracee#676]

**Comment by itaysk** [comment]
I'm splitting this into 2 separate issues as these are unrelated.

**Comment by yanivagman** [comment]
@tomyweiss @itaysk maybe we can add this functionality with some helper function, but why do you think a signature is required here?

**Comment by itaysk** [comment]
true, our signature library should be for detecting suspicious behaviors. if people want to add signatures for operational insights, that's fine but doesn't belong in tracee-rules

**Comment by yanivagman** [comment]
I updated this issue so that we should add container start/stop events.
This can be done using higher level events
