### ISSUE TITLE
Update go based signatures for new Finding interface

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#684]
Looks like this was missed out when changing the Finding interface struct and needs to be updated accordingly: https://github.com/aquasecurity/tracee/blob/a6ceb2ee5db7fd7c98e3b916172e647230f4eebe/tracee-rules/signatures/golang/stdio_over_socket.go#L179-L185

**Comment by itaysk** [comment]
I think you were looking at an old commit, it's fine on main
