### ISSUE TITLE
Create a github actions runner environment with latest kernel

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#685]
Now that we have access to infrastructure for testing/CI we should set up multiple environments with different kernels/distributions. 

We should discuss what distributions (and their kernels) we want to explicitly support but doing a custom kernel is easy enough. For starters let's get one set up that supports CO:RE. 

Setting up the runner is pretty easy, scripts for setting up a self-hosted runner are provided by github:

```
# Create a folder
$ mkdir actions-runner && cd actions-runner# Download the latest runner package
$ curl -o actions-runner-osx-x64-2.277.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.277.1/actions-runner-osx-x64-2.277.1.tar.gz# Extract the installer
$ tar xzf ./actions-runner-osx-x64-2.277.1.tar.gz

Configure

# Create the runner and start the configuration experience
$ ./config.sh --url https://github.com/aquasecurity/tracee --token <KEY># Last step, run it!
$ ./run.sh
```

After that we can configure all of our jobs to run on the self-hosted runners (in addition to ones provided by github) like so:

```
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [self-hosted-1, self-hosted-2, ubuntu-20.04]
```

**Comment by yanivagman** [comment]
@grantseltzer should this be part of 0.7.0 milestone?

**Comment by rafaeldtinoco** [comment]
This is being implemented at: https://github.com/aquasecurity/tracee-test-kernels and a PR will integrate it to our PR/actions workflow.
