### ISSUE TITLE
Document how to upgrade libbpfgo module for tracee-ebpf

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#689]
Typically when upgrading a go module you can simply do `go get module/pkg/name@<hash>` but because libbpfgo uses cgo that will want to link against various packages when `go get` tries to build, this will cause all kinds of issues.

Therefore environment variables must be passed with the `go get` command like so:

`GOOS=linux GOARCH=amd64 CC=clang CGO_CFLAGS=-I/home/vagrant/go/src/github.com/aquasecurity/tracee/tracee-ebpf/dist/libbpf/usr/include CGO_LDFLAGS=/home/vagrant/go/src/github.com/aquasecurity/tracee/tracee-ebpf/dist/libbpf/libbpf.a go get github.com/aquasecurity/tracee/libbpfgo@c1d1dd1313cb501df561f7c791921fd5923de8a4`

**Comment by itaysk** [comment]
I just update the `go.mod` entry (like I do with any other dependency), and then build tracee regularly

**Comment by itaysk** [comment]
related comment by @eyakubovich :
>  I want to make sure go get works as smooth as possible. Can we add -lbpf to #cgo LDFLAGS in the source file? If the user has libbpf installed in standard location, it'll just work. Otherwise they'll need to to set CGO_LDFALGS=-L/path/to/lib prior to go get

https://github.com/aquasecurity/tracee/discussions/727#discussioncomment-742269

**Comment by rafaeldtinoco** [comment]
I believe this can be closed now with the new building schema. If not, please re-open.
