### ISSUE TITLE
release tracee

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#69]
build and release artifacts for tracee. probably with goreleaser. will need to version before.
@lizrice what do you think about the version:
1. officially "start counting" - `0.0.1`
2. don't start counting `0.0.0`
3. 1 with exnension: `0.0.1-rc1`
4. 2 with extension: `0.0.0-rc1`
Or if you have another suggestion. Note that this will be the git tag so applied to python as well

**Comment by lizrice** [comment]
Yes, let's "start counting". So long as the major version is 0, I don't think we need rc extensions. We could do a 0.0.1 to check that everything is going smoothly with the versioning, and for testing on different distributions, shortly followed by 0.1.0 - first minor release. Wdyt?

**Comment by itaysk** [comment]
sounds good to me. I'll release 0.0.1 once https://github.com/aquasecurity/tracee/pull/71 is merged
