### ISSUE TITLE
Tracee-ebpf prints multiple EOF after shutdown

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#690]
When running tracee-ebpf and pressing `ctrl+c` to terminate the process, I get a lot of `EOF` printed to stdout.

I found that this behavior started after merging https://github.com/aquasecurity/tracee/pull/638.
When I comment out `close(eventsChan)` from `func (pb *PerfBuffer) Stop()`, the issue disappears.
Not sure yet why this happens

**Comment by itaysk** [comment]
I get it too now

**Comment by grantseltzer** [comment]
(just taking notes)

I traced the error back to here:

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.go#L1282-L1290

**Comment by itaysk** [comment]
fixed by #696
