### ISSUE TITLE
Tracee panic when cannot allocate memory

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#691]
Reported by @eidans 

```
michael@MichaelsLenovo:~/workarea/tracee$ sudo ./dist/tracee-ebpf --perf-buffer-size=16384 --security-alerts -t event=execve,security_bprm_check,security_file_open,fork,vfork,clone,sched_process_exit,sec
urity_inode_unlink,ptrace,bpf,process_vm_writev,connect,accept,bind,mem_prot_alert,init_module,finit_module,dup,dup2,dup3,close --output=format:gob | ./dist/tracee-rules --input-tracee=file:stdin --input
-tracee=format:gob
OOOOOOO
Loaded signature(s): [TRC-1 TRC-2 TRC-BYPASS TRC-3 TRC-RUNTIME-CONTAINER-START TRC-RUNTIME-CONTAINER-STOP TRC-4 TRC-5 TRC-6 TRC-7]
libbpf: failed to mmap perf buffer on cpu #7: Cannot allocate memory
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34 pc=0x642b87]

runtime stack:
runtime.throw(0x7b29b4, 0x2a)
/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 23 [syscall]:
runtime.cgocall(0x631890, 0xc00003a738, 0x0)
/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00003a708 sp=0xc00003a6d0 pc=0x40581b
github.com/aquasecurity/tracee/libbpfgo._Cfunc_perf_buffer__poll(0xfffffffffffffff4, 0xc00000012c, 0x0)
_cgo_gotypes.go:467 +0x48 fp=0xc00003a738 sp=0xc00003a708 pc=0x573388
github.com/aquasecurity/tracee/libbpfgo.(*PerfBuffer).poll.func1(0xc0000b4b70, 0xc000096180)
/root/go/pkg/mod/github.com/aquasecurity/tracee/libbpfgo@v0.0.0-20210318031738-f66f7bedda26/libbpfgo.go:764 +0x65 fp=0xc00003a770 sp=0xc00003a738 pc=0x5783a5
github.com/aquasecurity/tracee/libbpfgo.(*PerfBuffer).poll(0xc0000b4b70, 0x761b40, 0x806d90)
/root/go/pkg/mod/github.com/aquasecurity/tracee/libbpfgo@v0.0.0-20210318031738-f66f7bedda26/libbpfgo.go:764 +0x55 fp=0xc00003a7c8 sp=0xc00003a770 pc=0x576d55
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00003a7d0 sp=0xc00003a7c8 pc=0x46c961
created by github.com/aquasecurity/tracee/libbpfgo.(*PerfBuffer).Start
/root/go/pkg/mod/github.com/aquasecurity/tracee/libbpfgo@v0.0.0-20210318031738-f66f7bedda26/libbpfgo.go:746 +0x3f

 

goroutine 1 [chan receive]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).Run(0xc000128400, 0x0, 0x0)
/home/michael/workarea/tracee/tracee-ebpf/tracee/tracee.go:867 +0x1d0
main.main.func1(0xc000113e80, 0x0, 0x14)
/home/michael/workarea/tracee/tracee-ebpf/main.go:80 +0x685
github.com/urfave/cli/v2.(*App).RunContext(0xc000082a80, 0x843e78, 0xc0000ba010, 0xc000092180, 0x6, 0x6, 0x0, 0x0)
/root/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:311 +0x6fe
github.com/urfave/cli/v2.(*App).Run(...)
/root/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
/home/michael/workarea/tracee/tracee-ebpf/main.go:144 +0x832

 

goroutine 22 [runnable]:
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:21
created by os/signal.Notify.func1.1
/usr/local/go/src/os/signal/signal.go:151 +0x45
```

Comment from @yanivagman 
```
Cannot allocate memory. The size is in multiples of 4k (page size), so 16k will give 64mb per each cpu
```

**Comment by itaysk** [comment]
to be clear, this is a user error (invalid input). the action item is to print a better error instead of crashing

**Comment by simar7** [comment]
I'm unable to reproduce this on both the HEAD of main or the v0.5.0 released tag. I've tried various perf-buffer-size inputs: (16384,32768,65536,131072) the last of which results in the process getting killed by the OS but still no panic.


@eidans what kernel version did you observe this on? What version of tracee were you using?

**Comment by yanivagman** [comment]
It was weird to me that we didn't get an error from our code:
https://github.com/aquasecurity/tracee/blob/main/libbpfgo/libbpfgo.go#L56
So I checked libbpf code again, and I think that our current error checking is wrong.
I've mistakenly thought that negative values signify an error (pb < 0), but libbpf has a very weird way to report an error when pointers are returned.
Here is the error in libbpf: https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L10559
And note that the perf_init function return ERR_PTR: https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L10762
Which is defined here: https://github.com/libbpf/libbpf/blob/master/include/linux/err.h
So I think that we should use something like: https://github.com/libbpf/libbpf/blob/master/include/linux/err.h#L11

**Comment by simar7** [comment]
> It was weird to me that we didn't get an error from our code:
> https://github.com/aquasecurity/tracee/blob/main/libbpfgo/libbpfgo.go#L56
> So I checked libbpf code again, and I think that our current error checking is wrong.
> I've mistakenly thought that negative values signify an error (pb < 0), but libbpf has a very weird way to report an error when pointers are returned.
> Here is the error in libbpf: https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L10559
> And note that the perf_init function return ERR_PTR: https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L10762
> Which is defined here: https://github.com/libbpf/libbpf/blob/master/include/linux/err.h
> So I think that we should use something like: https://github.com/libbpf/libbpf/blob/master/include/linux/err.h#L11

I see. This makes a lot more sense now. I was also curious where the error was coming from.

**Comment by simar7** [comment]
Shouldn't we use https://github.com/libbpf/libbpf/blob/e60460f4e5137ab0c4aa4994fd30ada30ab31415/include/linux/err.h#L23-L26 instead?

**Comment by yanivagman** [comment]
If we will include the header in the c code, then yes

**Comment by simar7** [comment]
Got it. I created a PR to handle that change. Still unclear where the Go panic comes from as the line numbers don't seem to match with what the code has. My guess is this wasn't master/released version code.
