### ISSUE TITLE
docs site is not being built

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#704]
just released 0.5.1 which should have triggered `mkdocs-latest` workflow, but it didn't.

**Comment by itaysk** [comment]
it appears to be by design, a github workflow cannot trigger another workflow https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854

**Comment by itaysk** [comment]
actually, this is not done yet. I intentionally only linked the PRs and not closed it. Those PRs allowed us to manually build the docs site on demand. but the GH action workflow is still broken

**Comment by yanivagman** [comment]
@itaysk I see that our docs site only covers dev and 0.5.1.
What are we still missing here?

**Comment by itaysk** [comment]
> the GH action workflow is still broken

> a github workflow will not trigger another workflow if using the built in GITHUB_TOKEN

**Comment by yanivagman** [comment]
Closing this. Being built automatically by now.
