### ISSUE TITLE
libbpfgo crashes when some of libbpf functions fail

### ISSUE THREAD

**Issue by eyakubovich** [aquasecurity/tracee#708]
When `libbpf` functions returning pointers fail, they sometimes return a `NULL` and sometimes encode `errno` inside the pointer (by using kernel's `ERR_PTR` mechanism). As such it is not sufficient to just check for NULL as it leads the error to not be detected and causes a subsequent crash.

**Comment by yanivagman** [comment]
Fixed by #694 and related to #691
