### ISSUE TITLE
Handle error if InitKernelConfig() fails

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#717]
### Issue
Currently if InitKernelConfig() fails, we silently ignore it and move on. This displays an error message that lacks some context. See below:
```
$ docker run --name tracee --rm --privileged  -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro -v /tmp/tracee:/tmp/tracee -it tracee:latest
2021/05/04 22:25:15 kernel is not properly configured, missing: [CONFIG_BPF CONFIG_BPF_SYSCALL CONFIG_KPROBE_EVENTS CONFIG_BPF_EVENTS]
```

### Line in reference
https://github.com/aquasecurity/tracee/blob/e6f1f18cf41e11e57a57aacf3904c3cef64c47f1/tracee-ebpf/main.go#L924

### Acceptance criteria
1. Add a failing test to verify this behaviour. `missingKernelConfigOptions` is the function in question. It is currently _untested_.
2. Handle this error, early terminate (fail close) and display it meaningfully.
3. The test added in step 1 should now pass.

**Comment by yanivagman** [comment]
@simar7 can we close this now that #746 is merged?
