### ISSUE TITLE
libbpfgo should be in its own repo

### ISSUE THREAD

**Issue by ecbaldwin** [aquasecurity/tracee#731]
Looking at the potential to use libbpfgo in other applications. It needs a little bit of work; for example XDP attachment.

It would be much easier to vendor this library into other projects and contribute to its further development if it were in its own repository. Please consider this.

**Comment by grantseltzer** [comment]
Already on it :-)

Closing this in favor of https://github.com/aquasecurity/tracee/discussions/727 but I'll be opening up the libbpfgo repo very soon.

**Comment by ecbaldwin** [comment]
Sweet! Sorry I didn't think to look in the discussions (cuz I've never used discussions in github).

**Comment by grantseltzer** [comment]
Yea discussions are kinda hard to see, no worries at all! But do check back there for updates
