### ISSUE TITLE
Can't run Tracee on CoreOS 

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/tracee#735]
I am trying to run Tracee according to the documentation:

> docker run --name tracee --rm --privileged -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro -v /tmp/tracee:/tmp/tracee -it aquasec/tracee:latest

I am getting the following error:

> /run/torcx/bin/docker: Error response from daemon: error while creating mount source path '/usr/src': mkdir /usr/src: read-only file system.

Seems like "/usr/src" does not exist on the host, therefore the Docker start command tries to create this directory on the host, which is not allowed (read-only file system).

cat /etc/os-release:
Container Linux by CoreOS 2079

uname -a:
4.19.34-coreos

**Comment by yanivagman** [comment]
Tracee's docs include the following note:

> Note: You may need to change the volume mounts for the kernel headers based on your setup. See Linux Headers section for more info

Can you please remove the "/usr/src" mount and retry?

**Comment by yanivagman** [comment]
Please reopen if the issue persists after trying the above

**Comment by jerbia** [comment]
@yanivagman it worked without the /usr/src mount.
Maybe remove this mount from the command line?
