### ISSUE TITLE
Error running Tracee from the Docker container on Ubuntu 20.04

### ISSUE THREAD

**Issue by raesene** [aquasecurity/tracee#745]
Host OS: Ubuntu 20.04
Kernel Version: Linux csf 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Confirmation that headers are installed:

```bash
dpkg -l | grep -i linux-headers
ii  linux-headers-5.4.0-74               5.4.0-74.83                        all          Header files related to Linux kernel version 5.4.0
ii  linux-headers-5.4.0-74-generic       5.4.0-74.83                        amd64        Linux kernel headers for version 5.4.0 on 64 bit x86 SMP
ii  linux-headers-generic                5.4.0.74.77                        amd64        Generic Linux kernel headers
```

When I run the Docker container (As specificed in the READMe), I'm getting the following error

```
docker run --name tracee --rm --privileged -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro -v /tmp/tracee:/tmp/tracee -it aquasec/tracee:latest
Loaded signature(s):  [TRC-1 TRC-2 TRC-3 TRC-4 TRC-5 TRC-6 TRC-7]
2021/06/04 13:33:07 kernel is not properly configured, missing: [CONFIG_BPF_EVENTS CONFIG_BPF CONFIG_BPF_SYSCALL CONFIG_KPROBE_EVENTS]
```

The message is the same as in #717 but (as far as I can see) I've got the pre-req's in place?

**Comment by yanivagman** [comment]
This might be related to the fact that we don't check for error in InitKernelConfig:
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/main.go#L903
While we should: https://github.com/aquasecurity/libbpfgo/blob/main/helpers/kernel_features.go#L149

**Comment by krol3** [comment]
@raesene  It seems to work now, It works for me.

**Comment by itaysk** [comment]
let us know if this is still an issue

**Comment by raesene** [comment]
Just tested, looks like it's working now :)
