### ISSUE TITLE
Update checkRequiredCapabilities to support newer kernels

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#747]
We currently only check for CAP_SYS_ADMIN when running Tracee (https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/main.go#L885), which was correct for old kernels.
For newer kernels, CAP_SYS_ADMIN was split into combination of 3 other capabilities:
CAP_BPF, CAP_PERFMON and CAP_NET_ADMIN as described in https://lwn.net/Articles/820560/, and https://lwn.net/Articles/822362/
Update checkRequiredCapabilities() to support these newer kernels.

Also related: #286

**Comment by rajibmitra** [comment]
would it be ok if I take this one @itaysk  @yanivagman

**Comment by yanivagman** [comment]
@rajibmitra of course, please do

**Comment by cdelzotti** [comment]
Hello ! It's me again :)

I see that this issue has been opened for a while, can I be assigned to it ?

**Comment by yanivagman** [comment]
This is related to #1202 . I know that @AlonZivony tried to tackle this there, but we found out that it is more tricky than it may seem - @AlonZivony can you please relate to this?

**Comment by AlonZivony** [comment]
So this one is a duplicate of #1815.
The issue here was that some distros didn't work without `CAP_SYS_ADMIN` event though it should work with their kernel version.
To do this bugfix, the reason for the error in #1803 should be resolved.
I don't have the time for it right now, so if @cdelzotti want to solve it, it would be great :)

**Comment by cdelzotti** [comment]
Of course, thanks. I'll be away for a week but I'll check it out when I come back.

**Comment by yanivagman** [comment]
I'm closing this one in favor of #1815
