### ISSUE TITLE
Improve file naming when capturing artifacts

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#757]
When saving captured artifacts we can simplify the names of the files that are created on disk with the following suggestion:

A simplification suggestion (not for this PR).
The ctx.Ts is included in the captured file name in order to distinguish between different captured files with same path name.
IIUC you track the FirstExecutionTs field in order to reconstruct the same file name when calculating the hash.

Suggestion is to replace the ctx.Ts in captured file names with the file's ctime (it makes more sense regardless of this PR even), and then the unique id of a captured/profiled file includes just the mntid, path, and ctime and is consistent between the file names (which you use for hash calculation), and the map keys (which you use for the profile).
The profile maps from destinationFilePath to executions counter (and hash if needed). This eliminates reconstructing the file names which might be error prone, and simplify the code flow as no need to track ctx.Ts in the map and pass it around.

_Originally posted by @itaysk in https://github.com/aquasecurity/tracee/issues/725#issuecomment-856633040_

**Comment by yanivagman** [comment]
Closing this one.
Profile is now part of tracee-actions.
