### ISSUE TITLE
Tracee consume API

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#768]
Programs can run tracee-ebpf operations as part of their process by creating a Tracee struct with it's configuration and calling [`Run`](https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.go#L893). This is what we do in `tracee-ebpf/main.go`. 

The main issue with this is that output can only be specified as a file or stdout by default. This can be difficult for managing the tracee operations. We should have an API on the tracee object which exposes the actual Go channel which channels come off of.

**Comment by yanivagman** [comment]
A channel can now be given when configuring tracee #793
