### ISSUE TITLE
Clarify usage of --install-path

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#770]
Currently `--install-path` flag has a usage that says:

```
   --install-path value                path where tracee will install or lookup it's resources (default: "/tmp/tracee")
```

**What I expected:**
Based on this my understanding is that all artifacts (runtime or otherwise) that Tracee requires will be placed here. This includes `tracee.pid` as well.

**What I observed:**
`tracee.pid` is placed under `/tmp/tracee/out` regardless of `--install-path` being specified. 

Either this is a bug when it comes to placing artifacts like `tracee.pid` or a documentation gap that we need to improve to document this flag.

**Comment by itaysk** [comment]
there are 2 important directories for tracee (both configurable): output directory, and install directory. I think of the install more as input to tracee (the ebpf probe, maybe static configuration files) and output as output (what the trace produced), so in this case I think it makes sense to place the pid file where it is. feel free to present a counter argument, or improve the documentation

**Comment by yanivagman** [comment]
Closing this since tracee.pid is now saved to the output directory
