### ISSUE TITLE
Add a step to CO:RE compilation attempting to generate a vmlinux.h file

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#776]
We have a lot of conditional compile flags in tracee.bpf.c which check the kernel version and use appropriate data structure definitions. With CO:RE we have a vmlinux.h file committed to the repo which should be used as a backup. On kernels where BTF are supported, those kernel version flags are still checked, and if the definition doesn't match what's in the committed vmlinux.h (generated on linux 5.14), there's a compilation error.

This would add the dependency of execing out to bpftool so special care has to be taken to make sure we properly document this step.

**Comment by yanivagman** [comment]
Can you please give an example to such an error and where it happens in the code?

**Comment by grantseltzer** [comment]
I believe in #759 we addressed this issue according to [this](https://github.com/aquasecurity/tracee/pull/759#issuecomment-864499084) description.
