### ISSUE TITLE
Embed CO:RE bpf object file in Go binary at compile time

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#783]
When CORE=y is specified with `make` the resulting object file should be embedded into the go binary. This avoids any issue with the go binary trying to find the correct object. 

Similarly we should consider statically compiling the go binary when CORE is enabled

**Comment by yanivagman** [comment]
Done in #818

**Comment by itaysk** [comment]
also need to update the release workflow @grantseltzer
