### ISSUE TITLE
Cannot compile Tracee-eBPF on Ubuntu 20

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#786]
Here a snapshot of compilation error:
![image](https://user-images.githubusercontent.com/39140425/123133876-e2126900-d458-11eb-96a1-4ed7fee0ed8e.png)

**Comment by grantseltzer** [comment]
Can you paste `uname -a` ?

**Comment by mtcherni95** [comment]
> Can you paste `uname -a` ?

![image](https://user-images.githubusercontent.com/39140425/123135189-2f430a80-d45a-11eb-8935-5c652fdd16a1.png)

**Comment by yanivagman** [comment]
This seems to be the same issue that was fixed by #305 
Maybe the fact that we moved types.h header to be after this define is related?

**Comment by grantseltzer** [comment]
Looks like it could be a regression from the CO:RE commit: https://github.com/aquasecurity/tracee/commit/4bf8ca6bd33bc59e64e849eec89d33d3fe8bc08d

I moved the lines:

```
#ifdef asm_inline
#undef asm_inline
#define asm_inline asm
#endif
```

To _before_ including types.h. That must have something to do with it.

**Comment by yanivagman** [comment]
@mtcherni95 can you please confirm that PR #787 fixes this on your environment?

**Comment by mtcherni95** [comment]
> @mtcherni95 can you please confirm that PR #787 fixes this on your environment?

yep, that commit of the PR fixes that issue :)
