### ISSUE TITLE
Tracee-Rules dynamic signature loading

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#797]
we want to support loading/unloading signatures at runtime (today sigs are provided one time at engine-initialization time):

1. `engine.Load(types.Signature) error`
2. `engine.Unload(types.Signature) error`
3. on signature interface, add `signature.Close()` that should clean after `signature.Init()`

Now that we allow loading/unloading signatures at runtime, the internal maps need to be thread safe.

**Comment by mtcherni95** [comment]
We should consider to change as well the following logics by waiting to run as until there are loaded signatures, and if there are not wait. We could do by simply using a condition variable. 
![image](https://user-images.githubusercontent.com/39140425/124021009-b0b71180-d9f3-11eb-87f0-86364b476bf4.png)

**Comment by itaysk** [comment]
I don't see why the engine should care about which signatures are loaded, since signatures can come and go. What if all the signatures were unloaded should the engine stop? I don't think so. I think it would just keep consuming the input sources and dispatch to no signatures. WDYT?

**Comment by itaysk** [comment]
BTW there is some logic from start/stop the will need to be in load/unload of course. Since it's not just adding and removing from the maps

**Comment by mtcherni95** [comment]
exactly, that's what I am saying. We don't want to stop if there are no signatures. In the current code, if there are no signatures, then the loop at line 71 will exit and we will push 'done' to channel. We don't want such a scenario.

**Comment by mtcherni95** [comment]
In other words, we need to add a synchronisation mechanism (condition variable suits best in this case), where the predicat of the condition variable is that there is at least one loaded signatures.

**Comment by itaysk** [comment]
> We don't want to stop if there are no signatures.

the current code won't stop if there are not signatures, it will block on <-done, which is good IMO see next

> In the current code, if there are no signatures, then the loop at line 71 will exit and we will read from 'done' channel. We don't want such a scenario.

Isn't this what we want? at this point the engine is running and consuming sources, and you can still load signatures to it

**Comment by itaysk** [comment]
reopening this issue since the closing PR didn't cover Go signatures
