### ISSUE TITLE
Can't run tracee - getting error about long argument list

### ISSUE THREAD

**Issue by michaelkatch** [aquasecurity/tracee#815]
Hello,

I'm trying to run tracee-ebpf with no specific arguments on the following kernel :
*5.3.0-1023-aws #25~18.04.1-Ubuntu SMP Fri Jun 5 15:18:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux*

This is the error I get 
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/70207874/125458506-c57884a1-1cde-4b72-8ff6-e9a66ecd650f.png)

Thank you

**Comment by michaelkatch** [comment]
Hey Grant,

I'm compiling using Docker with the command "make DOCKER=1" so I don't have bpftool binary on the machine.
I ran the commands you wrote and compiled again via Docke and still the same error.

**Comment by grantseltzer** [comment]
Could you paste the output of the first two commands in my last comment? Essentially what i'm looking for is to make sure the kernel you're running supports tracee/bpf.

**Comment by grantseltzer** [comment]
```
...
last_idx 2807 first_idx 2799
regs=4 stack=0 before 2806: (b7) r2 = 16
2808: (61) r2 = *(u32 *)(r10 -236)
; len = (d_name.len+1) & (MAX_STRING_SIZE-1);
2809: (07) r2 += 1
; len = (d_name.len+1) & (MAX_STRING_SIZE-1);
2810: (57) r2 &= 4095
; if (off <= buf_off) { // verify no wrap occured
2811: (bf) r1 = r9
2812: (67) r1 <<= 32
2813: (77) r1 >>= 32
; if (off <= buf_off) { // verify no wrap occured
2814: (2d) if r2 > r1 goto pc+8132
 R0=inv(id=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R2_w=inv(id=0,umax_value=4095,var_off=(0x0; 0xfff)) R6=inv(id=0) R7=inv(id=0) R8=inv(id=0) R9=inv(id=0,smin_value=-20449,smax_value=47244656640) R10=fp0 fp-8=???m???? fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=mmmmmmmm fp-104=mmmm???? fp-128=????0000 fp-232=mmmmmmmm fp-240=mmmmmmmm fp-256=mmmmmmmm fp-264=inv4294967295 fp-272=map_value fp-280=mmmmmmmm fp-288=mmmmmmmm fp-296=ctx fp-304=mmmmmmmm fp-312=mmmmmmmm
;
2815: (79) r3 = *(u64 *)(r10 -232)
; off = buf_off - len;
2816: (bf) r4 = r9
BPF program is too large. Processed 1000001 insn
processed 1000001 insns (limit 1000000) max_states_per_insn 86 total_states 74866 peak_states 5034 mark_read 690

libbpf: -- END LOG --
libbpf: failed to load program 'trace_ret_vfs_write'
libbpf: failed to load object '/home/ubuntu/tracee/tracee-ebpf/dist/tracee.bpf.5_4_0-1051-aws.v0_5_4-24-gb3b7346.o'
2021/07/14 17:57:22 error creating Tracee: failed to load BPF object
```

Turns out this issue is an instruction limit infraction. Investigating further

**Comment by grantseltzer** [comment]
This only occurs in events that call `do_vfs_write_writev` or `do_vfs_write_writev_tail`

**Comment by yanivagman** [comment]
@grantseltzer are you sure about that? In the screenshot above I see that libbpf complains about trace_security_bprm_check, which doesn't call any of the vfs_write functions

**Comment by grantseltzer** [comment]
@yanivagman On the machine i'm testing this on (Michael gave me access to the environment in which he reported this bug from) there's no issue running security_bprm_check:

![Screen Shot 2021-07-15 at 1 46 27 PM](https://user-images.githubusercontent.com/10857349/125833717-d60db8fe-7c40-4877-8168-e716c816775f.png)

**Comment by grantseltzer** [comment]
@danielpacak and I were able to reproduce this on ubuntu 20.04:

`Linux ubuntu-focal 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Daniel discovered that the commit which breaks this is 422e86ebce71ee23a29849a74ffbca2f9687d8ce. Reverting these changes fixes the issue, but investigating further.

**Comment by yanivagman** [comment]
Thats a good finding. So now you can tweak the values for kernels >5.2 and fix with a lower value where needed until it works. I used high values as these worked on my environment, but maybe these are too high?

**Comment by grantseltzer** [comment]
@yanivagman Can you provide insight into the use case for these macro limits? For example: `MAX_BIN_CHUNKS` appears to limit the size of binaries being read? and `MAX_STR_ARR_ELEM` appears to limit the size of strings being read in `save_str_arr_to_buf`?

What I find strange is that in the case of this bug, the verifier limit is 4096, but 1000000. I want to find out what bpf setting it is that would cause there to be more instructions. Less optimization in certain versions of clang?

**Comment by yanivagman** [comment]
As bpf code before kernel 5.3 didn't allow the use of (bounded) loops, we use #program unroll to unroll loops. This loop unrolling means that the same logic inside the loop is copied by the number of times given by these limits, which means that the number of instructions of the bpf program is increased linearly according to the given limit used to unroll the loop.
For kernels before 5.2, this instruction limit is set to 4096. For newer kernels, the instruction complexity is limited to 1M instructions, which gives the ability to use much higher limits for the loop unrolling.
The method that I used to find these limits is trial and error. As the program can run without getting an error of "argument list too long", I increased these limits. When the limit is reached, I used a value which is a little smaller to have some space to increase the program size if required to add some more logic in the future. I did this test both for kernels before 5.2 (specifically I used 4.19), and after (5.9). Using these kernels, I got the values you see in the commit.

So, if there is still a problem with these values for kernel 5.4 (which SHOULD support instruction limit much higher than 4096), we need to understand why. Did you try to find what is the maximum value you can set for each of these limits in your environment? Are these values close to what we have for kernels < 5.2? If so, maybe there is a way to set this limit from userspace?

**Comment by yanivagman** [comment]
By the way, this difference between the environments might be related to the clang/llvm version used on your environment, which might perform different optimizations for the instruction count

**Comment by danielpacak** [comment]
> Thats a good finding. So now you can tweak the values for kernels >5.2 and fix with a lower value where needed until it works. I used high values as these worked on my environment, but maybe these are too high?

I tried in my environment different values for `MAX_PATH_COMPONENTS` and it breaks once I set it to 85.

```console
$ clang -v
Ubuntu clang version 12.0.0-3ubuntu1~20.04.3
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

```console
$ uname -a
Linux tracee 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yanivagman** [comment]
Did you only need to change  MAX_PATH_COMPONENTS for this to work? If so, let's set this value to 80 to avoid this error. Anyways before this commit https://github.com/aquasecurity/tracee/commit/422e86ebce71ee23a29849a74ffbca2f9687d8ce we had it set to 20, so 80 is a good option for now. In the future (kernels >5.3), we can use bounded loops to reduce the instruction count.

**Comment by danielpacak** [comment]
> Did you only need to change MAX_PATH_COMPONENTS for this to work? If so, let's set this value to 80 to avoid this error. Anyways before this commit [422e86e](https://github.com/aquasecurity/tracee/commit/422e86ebce71ee23a29849a74ffbca2f9687d8ce) we had it set to 30, so 80 is a good option for now. In the future (kernels >5.3), we can use bounded loops to reduce the instruction count.

Yup. I only adjusted MAX_PATH_COMPONENTS. MAX_BIN_CHUNKS was left intact.

**Comment by yanivagman** [comment]
@danielpacak Can you please open a PR that change its value to 80 then? Thanks!
