### ISSUE TITLE
failed to go get tracee-ebpf because of go:embed

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#816]
I am trying to go get to the latest tracee-ebpf commit:
`go get github.com/aquasecurity/tracee/tracee-ebpf@b3b73465ede22
../../../go/pkg/mod/github.com/aquasecurity/tracee/tracee-ebpf@v0.0.0-20210712152556-b3b73465ede2/main.go:28:12: pattern dist/tracee.bpf/*: no matching files found`

I guess it fails becasue it cannot find the embedded directory.

**Comment by grantseltzer** [comment]
I'm investigating how we can make go:embed directives fail safe, especially since #818 adds another embed directive.

**Comment by itaysk** [comment]
we should either conditionally skip embed, or embed from source which will always succeed (for this particular error)

**Comment by grantseltzer** [comment]
This commit demonstrates what seems to be the way to conditionally skip embedding: 

https://github.com/aquasecurity/tracee/pull/818/commits/a8a6404b8c69b71673204f5c8deb8c8e7bccd4ba

Though for this case embedding from source seems like a better workaround.

**Comment by itaysk** [comment]
I'm removing the bug label after a discussion with @grantseltzer where he correctly reminded that we currently don't support using tracee as a library for external users - It is possible, but functionally incomplete. I'm not sure if we want to close the issue, but at least it's not a bug

**Comment by mtcherni95** [comment]
> I'm removing the bug label after a discussion with @grantseltzer where he correctly reminded that we currently don't support using tracee as a library for external users - It is possible, but functionally incomplete. I'm not sure if we want to close the issue, but at least it's not a bug

@itaysk I see what you mean. what would you suggest now though? we still would like to upgrade the tracee-ebpf API version we are using .

**Comment by itaysk** [comment]
One option is to `go get -d`, but not ideal.
A better way is to prevent building main when just the library is imported
Can you confirm how your import like look like? maybe adding `/tracee` to specify the package will help?

**Comment by itaysk** [comment]
regardless, I think it's not ideal that we embed artifacts which are not part of the project's source code. We might need to revisit Grant's suggestion from before

**Comment by rafaeldtinoco** [comment]
I'm implementing the work from @grantseltzer together with some more things into:

https://github.com/aquasecurity/tracee/pull/1125

so embeds are defined by go build tags (including BTFHub files).

**Comment by yanivagman** [comment]
@mtcherni95 is this still an issue?

**Comment by rafaeldtinoco** [comment]
Per https://github.com/aquasecurity/tracee/issues/816#issuecomment-964599702, I believe this has been already addressed by `embedded.go` and `embedded-bpf.go` (not discussing room for improvements, just the fact that this can be closed after tree refactoring).
