### ISSUE TITLE
tracee-ebpf errors

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#817]
I am running tracee-ebpf as a library in my application. From time to time I see these logs generated by tracee-ebpf:
![image](https://user-images.githubusercontent.com/39140425/125465469-1807079a-bbc7-476a-84e7-44e979c5d773.png)

**Comment by mtcherni95** [comment]
For the moment I am using tracee-ebpf module from commit ae07c82dc6a9 and bpf object tracee.bpf.5_8_0-55-generic.v0_5_4-10-gae07c82.o

**Comment by yanivagman** [comment]
Event id 1022 is security_sb_mount.
probably one of these fail on this event (in bpf code), and the number of arguments received does not equal to 4:
```
save_str_to_buf(submit_p, (void *)dev_name, DEC_ARG(0, *tags));
save_str_to_buf(submit_p, (void *)&string_p->buf[*off], DEC_ARG(1, *tags));
save_str_to_buf(submit_p, (void *)type, DEC_ARG(2, *tags));
save_to_submit_buf(submit_p, &flags, sizeof(unsigned long), ULONG_T, DEC_ARG(3, *tags));
```

A possible fix:
```
u8 argnum = 0;
argnum += save_str_to_buf(submit_p, (void *)dev_name, DEC_ARG(0, *tags));
argnum += save_str_to_buf(submit_p, (void *)&string_p->buf[*off], DEC_ARG(1, *tags));
 argnum += save_str_to_buf(submit_p, (void *)type, DEC_ARG(2, *tags));
argnum += save_to_submit_buf(submit_p, &flags, sizeof(unsigned long), ULONG_T, DEC_ARG(3, *tags));
context.argnum = argnum;
save_context_to_buf(submit_p, (void*)&context);
events_perf_submit(ctx);
```

Can you please try and see if that works for you?

**Comment by mtcherni95** [comment]
![image](https://user-images.githubusercontent.com/39140425/125476442-5d38870d-a9b6-475c-b30b-8a6330f42d9f.png)
and eventually:

libbpf: failed to load program 'trace_security_sb_mount'
libbpf: failed to load object '/opt/aquasec/tr/tracee.bpf.5_8_0-55-generic.v0_5_4-10-gae07c82.o'

**Comment by eidans** [comment]
@itaysk , please prioritize.

**Comment by itaysk** [comment]
what's the repro? @mtcherni95

**Comment by mtcherni95** [comment]
I am personally running an app using tracee-ebpf as a lib. However I am pretty sure that if you run tracee-ebpf for enough time you will also manage to get the errors. The issue is due to event 1022 (SECURITY_SB_MOUNT) which should be called whenever a mount is happening in the system.

**Comment by itaysk** [comment]
I haven't encountered this error and also when I manually perform mount operations they are correctly traced, so there's some different mount operation that your machine does that I'm unable to reproduce.. 
If you don't know how to reproduce the specific event, that's ok

**Comment by yanivagman** [comment]
@mtcherni95 I opened #847 that may fix this problem.
Can you please run this branch on your environment and write if it solves it?
