### ISSUE TITLE
Implement BTF support, BTF & BPF decision path for CO-RE and non CO-RE BPF objects execution

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#833]
Currently (or once #818 is merged) the following logic is followed for deciding  which bpf object to use:

1. check for /sys/kernel/btf
2. if yes, use CO-RE binary
3. if no, look for BPF.o for running kernel
4. if no BPF.o, compile BPF.o for running kernel

Once we have BTF Hub the following logic should be implemented:

- CO-RE phase:

1. check for /sys/kernel/btf.
2. if yes, use CO-RE binary
3. if no sysfs btf, look for BPF support in running kernel.
4. if BPF support, get BTF for running kernel from BTFHUB
5. if BTFHUB file exists use CO-RE binary with downloaded/cached BTF file

- Legacy phase:

6. if BTFHUB file does not exist look for BPF.o for running kernel
4. if no, compile BPF.o for running kernel

_See comment posted by @rafaeldtinoco in https://github.com/aquasecurity/tracee/issues/818#issuecomment-883759923_

**Comment by rafaeldtinoco** [comment]
I'm currently working on this. Scratch for [btfhub retrieval and distro discovery](https://gist.github.com/rafaeldtinoco/3e7cdff16cccbcffc45d0cacaff61f01) to be included in tracee.

**Comment by itaysk** [comment]
Should add that if user explicitly provides BPF file (TRACEE_BPF_FILE) it overrides all defaults.

**Comment by itaysk** [comment]
this might be changed based on discussion in #839 
The possible change is to remove step legacy-6.
Also, I presume that we no longer for for object file that is next to the binary (same dir)

**Comment by rafaeldtinoco** [comment]
I haven't read #839 discussion yet (will do it tomorrow my morning) but wanted to put WIP here based on previous talk with @itaysk about decisions based on existing tracee environment:

I'll try to read #839 tomorrow morning, for now WIP on decision making on startup:

https://github.com/rafaeldtinoco/tracee/commit/d23c48e6a7678f0b79a4465e58230bb7a0f3e400

**Comment by rafaeldtinoco** [comment]
This is being implemented at:

**Comment by rafaeldtinoco** [comment]
BTW, this issue is to track the full BTFHUB API usage as, from recent merges, you will see parts of BTF support are already being merged here and there (because of CNDR needs). With that said, I'll re-work 'external-btf' so it uses a BTF API that we will agree on.
