### ISSUE TITLE
Export system/kernel exploring functions

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#835]
As part of integrating Tracee as a library we would like to have the ability to use functions like 'missingKernelConfigOptions', 'checkRequiredCapabilities' etc.

**Comment by grantseltzer** [comment]
We can potentially put these in the helpers sub-package of libbpfgo

**Comment by mtcherni95** [comment]
In particular: we would like to have the following APIs:
- GetKernelAndDistroVersion
- GetTraceeVersion
- LoadObjectFromPath

This will allow us to:
- Skip steps that are part of the init of Tracee that we don’t do in our app such as compiling eBPF locally with kernel headers.

**Comment by itaysk** [comment]
Tracee version is not so easy to reason about, we could print the version but in your case it might be incorrect. Unlike the other runtime properties, this is a compile-time property. Since in your case the compilation is under your control (you're using Tracee as a library and compiling a different artifact then tracee-ebpf), then it's up to you to embed the correct version. Another alternative is that you inspect the module version at runtime (IDK if it's possible)

**Comment by itaysk** [comment]
Thinking of this again.. Correct me if I'm wrong but I think the reason why you need the Tracee version is only so you can identify a compatible object file. This is a use case that we can and should support, even without exporting the Tracee version. I propose we start versioning the ABI between the eBPF probe and the userspace program. It doesn't have to align with Tracee versions. Actually, in most cases it wouldn't, which means we can reuse the probe in more versions.
This is important not only for this use case, but also for potentially BTF Hub. I'll start a new issue to track it.

**Comment by yanivagman** [comment]
> In particular, we would like to have the following APIs:
> 
> GetKernelAndDistroVersion
> GetTraceeVersion
> LoadObjectFromPath
> This will allow us to:
> 
> Skip steps that are part of the init of Tracee that we don’t do in our app such as compiling eBPF locally with kernel headers.

**GetKernelAndDistroVersion** - Nothing special here - just a simple uname. I don't think that this is something we should export.
**LoadObjectFromPath** - You can already provide an environment variable to set a path for an object, so consider this already "exported".
**GetTraceeVersion** - See my comment in #839

**Comment by itaysk** [comment]
closed by: https://github.com/aquasecurity/libbpfgo/pull/53
