### ISSUE TITLE
Explicitly version the ABI between the ebpf and userspace

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#839]
Tracee when tracee starts it needs to identify a compatible eBPF object file. Compatibility is defined by target OS (kernel) and the version of Tracee. Tracee version was chosen as an indicator to the eBPF code version, but as Tracee grows, the version of Tracee (the project) will not always be related to the eBPF code. For example, there may be many versions of Tracee where the eBPF code is not changed, or changed in a way that doesn't break compatibility. And also  is not a good indicator This is a use case that we can and should support, even without exporting the Tracee version. 
I propose we start to explicitly version the ABI between the eBPF probe and the userspace program. This has a few benefits:
1. Simplify the discovery of compatible obj file. see #835 
2. Dramatically reduce the amount of compilation artifacts we need to maintain, as the same obj version could serve many Tracee versions.
3. (related to 2) less overhead on BTF Hub

**Comment by itaysk** [comment]
As for implementation, a simple solution can be a constant in the Go code that says what ABI version this Go code expects, this can be used by the obj file discovery to find matching file. The C code can do the same for self-documentation (const declares what ABI version this C code produce), but I think more practically it would just use the object file name, where we will replace the Tracee version with Tracee ABI version.

**Comment by yanivagman** [comment]
This is only relevant for old kernels that don't have BTF enabled. For new kernels, the bpf object is already embedded as part of the tracee binary, and there is no need to check for compatibility in this case.
Also, with CO-RE and BTFhub, this will also be irrelevant, as there would still be one CO-RE object embedded in the tracee binary, and a finite set of btf files, with which the embedded CO-RE object will be able to run.
So there is nothing to do here with less overhead on the BTF hub, as it will have a finite amount of btf files (for older kernels) you will need to have there anyway, and the first thing that tracee will try to do on older kernels is to get a btf for the running kernel, no matter what is the version of the bpf object or tracee userspace program.

**Comment by itaysk** [comment]
what you say makes complete sense to me, but it means we eliminate the case phase of discovering a compatible obj file, taht we discussed here: https://github.com/aquasecurity/tracee/pull/818#issuecomment-883759923

so there will be just these options:
1. CORE 
  1. with kernel provided btf
  2. with btf hub
2. specialized compiled object file  
  1. provided by the user
  2. compiled by tracee

and specialized compiled object file is assumed to be compatible, we will not verify it right?
This sounds good to me, just making sure I understand you

**Comment by yanivagman** [comment]
We can still verify it by using the tracee version, exactly as we do today, but I don't mind if we won't.
We could have moved to ABI version checks as you suggested, but I see no big advantage in doing so, as the future of tracee is co-re, and these checks will be rare anyway.

**Comment by itaysk** [comment]
> We can still verify it by using the tracee version, exactly as we do today

will not work for library users, that's why I created this issue

I think that IF we do any check, it should be ABI version. But since we no longer "discover" the obj file but always the user explicitly provides it, we can probably skip the verification and avoid this problem.

**Comment by yanivagman** [comment]
See my comment in https://github.com/aquasecurity/tracee/issues/835#issuecomment-886251846 - library users can use their own version to do this check - there is no meaning for using tracee version, just to make sure that the bpf object is compatible with the running userspace program, be it part of the tracee binary or any other binary

**Comment by itaysk** [comment]
you are assuming that every library consumer also builds the bpf object, and names it appropriately, right? I was operating under the assumption that the library user still can use the "tracee" object file.

**Comment by yanivagman** [comment]
Yes, my assumption is that a user of tracee as a library will also build the bpf object, which I think is reasonable.
Can we close this issue then?

**Comment by itaysk** [comment]
https://github.com/falcosecurity/libs/blob/master/proposals/20210818-driver-semver.md

**Comment by yanivagman** [comment]
> https://github.com/falcosecurity/libs/blob/master/proposals/20210818-driver-semver.md

Now that we use the embedded CO-RE object, I don't see any reason to even consider such a change
