### ISSUE TITLE
To detect whether a given BPF file (env) is CO-RE capable or not

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#844]
With the changes being made to #833, it might be needed to detect whether the BPF file is CO-RE or not. I checked both ELFs and realized that they're only different because CO-RE BPF is not being stripped and regular BPF object is.

![image](https://user-images.githubusercontent.com/7395852/127153327-07dd5219-94e6-4381-ac4a-c26087e1d5cb.png)

After stripping, both section headers are the same and it is hard to distinguish between the 2 files.  My suggestion, since we should be stripping CO-RE file also...

1) Strip CO-RE BPF file being generated but keep 1 small section header for CO-RE bpf

With that, during tracee initialization I can readelf its section headers and distinguish both: CO-RE and non-CO-RE BPF objects.

[Update]

Clarification: Idea is to keep a small section during strip of CO-RE ELF file OR to create a small section that differentiate both: CO-RE and non-CO-RE objects.

**Comment by yanivagman** [comment]
@rafaeldtinoco how do you plan to use this data? Don't we always embed co-re object and non co-re object is always a non embedded file? Isn't klnowing this fact enough?

**Comment by grantseltzer** [comment]
I'm surprised that stripping the CO-RE binary doesn't break anything, but it saves 3M so we should strip it regardless.

**Comment by rafaeldtinoco** [comment]
@yanivagman This was born from discussion with @itaysk when we thought that TRACEE_BPF_FILE environment could be used to pass on any BPF object (CO-RE or NOT). In the decision make (on which BPF/BTF files to use) we will have combinations being explored at:

https://github.com/rafaeldtinoco/tracee/commit/d23c48e6a7678f0b79a4465e58230bb7a0f3e400

**Comment by itaysk** [comment]
@yanivagman if user provides obj file, we don't know if it's CORE or not. We need to know, because we might need to load/not the BTF file. We could let the user tell us if it's CORE or not, but here Rafael is suggesting a potentially better way

**Comment by rafaeldtinoco** [comment]
> Is there a way to just compile in a magic number into a variable that can be exposed via a flag?

We can have it as a small string in the string table.. or something like it.

> Also i'm surprised that stripping the CO-RE binary doesn't break anything, but it saves 3M so we should strip it regardless.

I'm glad you did not, I was looking for ELF differences yesterday and all I could find was this =), so it gave me the sections idea.

**Comment by yanivagman** [comment]
Creating a section is as simple as creating a dummy ebpf program in our c code (using the SEC macro)

**Comment by rafaeldtinoco** [comment]
Currently we have the following decisions in place:

```
Decisions in order:
1. external BPF file given and BTF (vmlinux or env) exists: always load BPF as CO-RE
2. external BPF file given and no BTF exists: it is a non CO-RE BPF, no need to build
3. no external BPF file given and BTF (vmlinux or env) exists: load embedded BPF as CO-RE
4. no external BPF file given and no BTF exists: build non CO-RE BPF
```

and it has been recently proposed (within btfhub support PR) the following:

```
// Decisions in order:
// 1. external BPF file given and BTF (vmlinux or env) exists: always load BPF as CO-RE
// 2. external BPF file given and no BTF exists: it is a non CO-RE BPF, no need to build
// 3. no external BPF file given and BTF (vmlinux or env) exists: load embedded BPF as CO-RE
// 4. no external BPF file given and no vmlinux BTF available: check embedded BTF files
// 5. no external BPF file given, no vmlinux BTF and no embedded BTF: build non CO-RE BPF
```

and we agreed that a given external BPF file will always be treated following this decision ordering, removing the need to detect whether the given BPF file is CO-RE or not. 

With that, I'm closing this issue.
