### ISSUE TITLE
There is no lock in save_path_to_str_buf

### ISSUE THREAD

**Issue by vito11** [aquasecurity/tracee#852]
To get a full path from a struct path,  save_path_to_str_buf() tries to traversal the dentry tree and mount point.  However, this is no mount lock or  dentry rename lock that be used in the loop.  Will this lead to bugs while mount and rename is busy?

**Comment by yanivagman** [comment]
That's a very good point.
Unfortunately, it is not possible to access these locks in our bpf program as there are no bpf helpers for this task - so the answer to your question is yes, there might be bugs in the form of incorrect paths if reading the path during mount/unmount/rename operations.
A new bpf helper named `bpf_d_path` might solve this issue in the future, but it is not available for the kernels supported by Tracee. In fact, this helper is not even accessible from any bpf program, as the functinon from which it is called should be in its allowlist. There is actually a new patch which might be merged soon that adds most of the functions required by tracee to the allowlist. I even previously asked to expand this list with the functions required by us: https://lore.kernel.org/bpf/CAMy7=ZUB36TL-8PmtJ_Nm48PFmdjSBVLYXWKyFiqm6QCOYZrMA@mail.gmail.com/. This however, will take some time before it will be available for most distros, so we will have to stay with the current implementation.
If you have any ideas for improvements, I will be happy to check and implement if possible.

**Comment by vito11** [comment]
> That's a very good point.
> Unfortunately, it is not possible to access these locks in our bpf program as there are no bpf helpers for this task - so the answer to your question is yes, there might be bugs in the form of incorrect paths if reading the path during mount/unmount/rename operations.
> A new bpf helper named `bpf_d_path` might solve this issue in the future, but it is not available for the kernels supported by Tracee. In fact, this helper is not even accessible from any bpf program, as the functinon from which it is called should be in its allowlist. There is actually a new patch which might be merged soon that adds most of the functions required by tracee to the allowlist. I even previously asked to expand this list with the functions required by us: https://lore.kernel.org/bpf/CAMy7=ZUB36TL-8PmtJ_Nm48PFmdjSBVLYXWKyFiqm6QCOYZrMA@mail.gmail.com/. This however, will take some time before it will be available for most distros, so we will have to stay with the current implementation.
> If you have any ideas for improvements, I will be happy to check and implement if possible.

Thanks for your reply.  Besides bugs in the form of incorrect path，I want to know that if this implementation may cause a crash in the bpf VM？Because I am working on a product that have the same requirement（get full path in ebpf program），but I am not quite familiar with ebpf.  Are there some test cases about running this function during mount/unmount/rename operations？

BTW，I noticed that https://github.com/Gui774ume/fsprobe have the similar implement，and it uses a Map (<inode_num, mount_id> as key,  <d_name, parant_key> as value) to form a dentry tree to transfer full path info to user program. FYI.

**Comment by yanivagman** [comment]
> Thanks for your reply. Besides bugs in the form of incorrect path，I want to know that if this implementation may cause a crash in the bpf VM？

Well, I can't guarantee you that since this is a workaround to some missing functionality (bpf_d_path() helper), but from my understanding, no crash should happen because we only read and do it in a safe way (using bpf_probe_read()).

> Because I am working on a product that have the same requirement（get full path in ebpf program），incorrect path is acceptable, but crash is unacceptable , and I am not quite familiar with ebpf.

If I may ask, what product is that?

> Also, are there some test cases about running this function during mount/unmount/rename operations？

No, we don't have such test cases - contributions are welcome :-)

> BTW，I noticed that https://github.com/Gui774ume/fsprobe has the similar implement，and it uses a Map (<inode_num, mount_id> as key, <d_name, parent_key> as value) to form a dentry tree to transfer full path info to user program. FYI.

Thanks, I'll take a look

**Comment by vito11** [comment]
> If I may ask, what product is that?
It‘s a anti-virus product,  the full file path is sent to user space for on access scanning.  From my opinion , on access scanning for linux servers is not a essential  feature,  some incorrect path is allowed, because we also have scheduled scanning to cover this bug in case of missing some malware at real time.
