### ISSUE TITLE
There is no guide for signature writing

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#854]
I can't find an exact guide to how to write a signature.
This is important because there are assumptions we take as obvious but are not.
For example, there is no place where it is written that the source of all signatures should be "tracee" in the current version.
This is becoming more relevant now, that we add meaning to the signatures Tags - which specify the expected event origin.
I think it should be prioritized to create some guide or documentation on the signature structure.

**Comment by yanivagman** [comment]
Have you seen https://aquasecurity.github.io/tracee/v0.5.1/rules-authoring/ in the docs?

**Comment by itaysk** [comment]
I agree that doc could be more detailed.. contributions welcome ;)

**Comment by AlonZivony** [comment]
> Have you seen https://aquasecurity.github.io/tracee/v0.5.1/rules-authoring/ in the docs?

I did, and it lacks specifications.
For golang signature, you get only the interface and the example.
However, as I wrote, there are thinks that are lacking in the code itself. Maybe we should add documentation to the interface.
I think it would be a lot more easier to write new signatures if there was a guide, but I know that it takes some time and might not be our most urgent mission.

**Comment by itaysk** [comment]
closing this as docs improvement is an evergreen task. I would mention that Rory has written some instructions here: https://blog.aquasec.com/runtime-security-tracee-rules and the we should see how to take from those to the docs.

**Comment by AlonZivony** [comment]
Maybe we should add a link to it from the doc?

**Comment by itaysk** [comment]
yes, see #1314
