### ISSUE TITLE
tracee-rules --input-file ~ sign not supported

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#855]
When trying to run tracee-rules with the --input-file option set to a file containing the ~ sign, tracee-rules yield this error:
```
invalid Tracee input file
```

command line: 
```
./tracee-rules --output-template ../templates/rawjson.tmpl  --input-tracee file:~/somefile.json --input-tracee format:json
```

Relative paths (.. and .) works.

**Comment by itaysk** [comment]
`~` is expanded by the shell, so Tracee wouldn't know what to do with it. as a workaround could be something like 
```
file:`echo ~/somefile.json`
```
