### ISSUE TITLE
containerid doesn't work for existing containers

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#862]
![image](https://user-images.githubusercontent.com/7395852/127900726-2e2b5d61-2968-498f-94c8-8cc3002f8d1a.png)

Initial traces were from a previously started container, showing no containerid.

**Comment by rafaeldtinoco** [comment]
We currently have a "pid_to_cont_id_map" with container_id <-> pid mappings. Whenever a pid is traced, its container_id comes from reading the BPF_HASH `key=pid(u32) -> value=container_id`.

This map only gets populated in the following tracepoints:

1. raw_tracepoint/sched_process_fork (when process is created)
2. raw_tracepoint/cgroup_attach_task (when task is attached to cgroup)

And gets deleted in:

1. raw_tracepoint/sched_process_exit (when process exits)

In order to have existing container_ids in the BPF MAP we can populate that map from tracee.go, during initialization, with the existing containers by the time tracee-ebpf is initialized (from populateBPFMaps() or similar).

Working on it...

**Comment by itaysk** [comment]
> we can populate that map from tracee.go, during initialization

👍

**Comment by yanivagman** [comment]
This is not a bug, but a missing feature as I noted here:
https://github.com/aquasecurity/tracee/pull/749#issuecomment-861373065

**Comment by rafaeldtinoco** [comment]
@yanivagman I'll wrap lsns (from util-linux) output and populate the BPF_HASH pid_to_cont_id_map during startup if its okay for you. Writing our own tool to traverse procfs with all peculiarities dealt by lsns.c (from util-linux/sys-utils/lsns.c) seems unnecessary for me and the tool already provides JSON output with columns chooser and so on (to list all existing ns).

**Comment by yanivagman** [comment]
@rafaeldtinoco I'm actually unfamiliar with this tool. If it only iterates procfs, how do you plan to get the container id with it?

**Comment by rafaeldtinoco** [comment]
![image](https://user-images.githubusercontent.com/7395852/127916435-f5e9f825-65a3-4641-b406-731d87a848f1.png)

**Comment by yanivagman** [comment]
But the map is pid to container id. To populate it, you will need to know the container id of the existing pids.

**Comment by yanivagman** [comment]
The method I used to get the container ids in runtime is to use the cgroup (dentry) name, which contains the container id in it (initialized as such by the container runtimes).
So you can take a similar approach at init time - traverse cgroupfs, and for each non-host cgroup, extract the pids and container ids out of it.

No matter what approach you will eventually take, a race condition will exist between the time you populate the map and until the bpf program starts to monitor the cgroup attach and clone events. To mitigate this problem, it will probably be required to traverse the cgroup(proc)fs more than once, until we see that no new pids are added into it, and repeat this process after the bpf programs are started. But this is not a must for the first phase and can be done after we add the initial support

**Comment by rafaeldtinoco** [comment]
True.. I can then do a a docker inspect to each existing container:

![image](https://user-images.githubusercontent.com/7395852/127917769-419c5aec-7786-4a6d-9afe-1ddec836c01c.png)

Get the initial pid and all its namespaces and check which processes are in the same namespaces.

![image](https://user-images.githubusercontent.com/7395852/127918144-9a921e4f-7b5f-4b29-a555-b564ce9e1c4b.png)

**Comment by rafaeldtinoco** [comment]
Yep, I tried to get namespaces to identify existing containers, bad idea. And wasn't sure from where container_id was coming from, was about to learn =).

> The method I used to get the container ids in runtime is to use the cgroup (dentry) name, which contains the container id in it (initialized as such by the container runtimes).
> So you can take a similar approach at init time - traverse cgroupfs, and for each non-host cgroup, extract the pids and container ids out of it.

Positive. I'll check what is best.

> No matter what approach you will eventually take, a race condition will exist between the time you populate the map and until the bpf program starts to monitor the cgroup attach and clone events. To mitigate this problem, it will probably be required to traverse the cgroup(proc)fs more than once, until we see that no new pids are added into it, and repeat this process after the bpf programs are started. But this is not a must for the first phase and can be done after we add the initial support

Yep, I had that in mind as well. And I do agree that is not a must for this initial phase. But having the logic offloaded to a coroutine doing the population until a timeout occurs might be simple enough, lets see.

**Comment by yanivagman** [comment]
> Yep, I tried to get namespaces to identify existing containers, bad idea. And wasn't sure from where container_id was coming from, was about to learn =).

This is not a bad idea at all. In some sense, a mount namespace represents a container (all the other namespaces can be equal to host and it will still represent a container, however, a mount namespace is the first thing that comes to mind when thinking about containers). The only thing is that after identifying the existing mntns on the system, you still need to map them to a container id.

**Comment by rafaeldtinoco** [comment]
> > Yep, I tried to get namespaces to identify existing containers, bad idea. And wasn't sure from where container_id was coming from, was about to learn =).
> 
> This is not a bad idea at all. In some sense, a mount namespace represents a container (all the other namespaces can be equal to host and it will still be considered a container, however, a mount namespace is the first thing that comes to mind when thinking about containers). The only thing is that after identifying the existing mntns on the system, you still need to map them to a container id.

**Comment by rafaeldtinoco** [comment]
Ooops, closed by accident sorry.

**Comment by rafaeldtinoco** [comment]
![image](https://user-images.githubusercontent.com/7395852/127920675-542eb4d1-5bf6-4f60-beab-8fa7b0fec32f.png)

Yep, I'll do something like this to each running container and populate the map with the info.

**Comment by yanivagman** [comment]
Note that you also have an entry in the cgroupfs for each cgroup that tells you which tasks are attached to it.

**Comment by rafaeldtinoco** [comment]
![image](https://user-images.githubusercontent.com/7395852/127959745-1de769b5-6c82-48da-814d-94307027265a.png)

Working fine. I'll do a PR and mention both issues.

**Comment by rafaeldtinoco** [comment]
@yanivagman good for a new review. After this is merged we can go for a fix for LXC/LXD (or at least filter them out from our container filtering logic). I opened issue: https://github.com/aquasecurity/tracee/issues/884 for that.

**Comment by rafaeldtinoco** [comment]
Rebased and fixed wrong return after cgroupsv1 check in _Populate() after reviewing this partially with @itaysk .

**Comment by rafaeldtinoco** [comment]
Okay, the issue: https://github.com/aquasecurity/tracee/issues/894 was driving me crazy and that is why this had so many force pushes and back and forth. I'm pushing my latest version for review BUT this can't be merged until issue #894 is solved.

**Comment by rafaeldtinoco** [comment]
@itaysk I have simplified the regex logic like we've talked about today. I have also fixed the return for cgroupsv1 before running cgroupsv2. Ready for a new review.
