### ISSUE TITLE
tracee-ebpf --output ignore flag

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#876]
When using the capture command we still see the stream of events continuously printed to stdout (or another output), but for capturing one might not care about the events, only the artifacts captured. To ignore the events, we may redirect the output to `/dev/null` but it still generates IO.

I wonder if supporting an extra flag for a [printer](https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/printer.go#L17) that ignores the output, avoiding any extra work on it, would make sense. eg:

`tracee-ebpf --capture write=/home/user/test.txt* --output ignore`

(I'm willing to contribute a PR if you agree the change makes sense.)

**Comment by grantseltzer** [comment]
I think this is a great idea @josedonizetti! Would be happy to accept a PR with this addition.
