### ISSUE TITLE
Improve observability

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#887]
Tracee-ebpf collect some [stats](https://github.com/aquasecurity/tracee/blob/aee7e8f04e08b2b869e8526dbff70e1562d016b5/tracee-ebpf/tracee/tracee.go#L255), which are printed as the epilogue when tracee-ebpf exits. For someone running tracee as a daemonset on a K8S cluster, those metrics (possibly even newer metrics in the future) would be scattered on the N nodes.  To allow a better observability, tracee could support prometheus (or open-telemetry?), which would allow users to have a central view of all tracee metrics on all pods running.

**Comment by itaysk** [comment]
Yes! this was on my radar for a while but always de-prioritized. If you're interested in that, it'll be very much appreciated.

**Comment by itaysk** [comment]
brainstorming here some potentially useful and not too hard to collect data. (this is of course incremental work, not for the initial PR)

metric | description | type | dimentions
--- | --- | --- | ---
tracee_ebpf_events_total | # events collected by Tracee-eBPF | counter | event id/name, container id
tracee_ebpf_lostevents_total | # events lost in the submission buffer | counter |
tracee_ebpf_write_lostevents_total | # events lost in the write buffer | counter |
tracee_ebpf_network_lostevents_total | # events lost in the network buffer | counter |
tracee_capture_$capturetype | # captured $capturetype files | counter |
tracee_capture_$capturetype_bytes_total | # bytes captured $capturetype files | counter |
tracee_rules_events_total | # events ingested by Tracee-Rules | counter | source (currently just Tracee)
tracee_signatures_total | # of loaded signatures | counter
tracee_detections_total | # detections made | counter | signature id, container id, severity
tracee_detections_latency_seconds | how long did it take for a detection to be made (finding.timestamp - finding.context.timestamp) | histogram

- hostname labels can be added during prometheus ingestion
- only if using the `--debug` flag, we can add Go's and OPA's default metrics (for troubleshooting)

**Comment by NDStrahilevitz** [comment]
Since #1404 was merged, are there any other observability improvements we want to add before the milestone? If not we can probably remove this issue from the milestone and reintroduce it to a later one when relevant again.
