### ISSUE TITLE
Fix minimum required capabilities

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#888]
Tracee should verify the proper required capabilities to allow a user to run without privilege. Currently tracee checks only for [`CAP_SYS_ADMIN`](https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/main.go#L970), but if we try to run either the direct process, or a docker container we get:

```
docker run --na tracee --rm --cap-add CAP_SYS_ADMIN -it aquasec/tracee:latest
libbpf: failed to mmap perf buffer on cpu #7: Operation not permitted
libbpf: failed to mmap perf buffer on cpu #7: Operation not permitted
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3f pc=0x7133d3]

runtime stack:
runtime.throw(0x7e9f70, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5
```

Libbpf doesn't have the proper permissions. This also triggers a panic on golang, because libbpfgo doesn't handle the error properbly, but I have fixed this issue -> https://github.com/aquasecurity/libbpfgo/pull/49

To allow either a docker container or a process on the host to run, tracee also needs `CAP_IPC_LOCK`. 

eg:
```
docker run  --name tracee --rm --cap-add CAP_SYS_ADMIN --cap-add CAP_IPC_LOCK -it aquasec/tracee:latest
Loaded signature(s):  [TRC-1 TRC-2 TRC-3 TRC-4 TRC-5 TRC-6 TRC-7]
```

If you agree, I'm willing to make a PR to fix it.

**Comment by josedonizetti** [comment]
@yanivagman Let me know what you think, pls.

**Comment by yanivagman** [comment]
@josedonizetti agreed - many thanks for all your recent contributions!
