### ISSUE TITLE
Use READ_KERN macros instead of bpf_probe_read() helpers

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#898]
As we now use core, we should switch to using co-re helpers when co-re is enabled.
To do that, we already have READ_KERN macro which selects the relevant helper according to if co-re is enabled or not in the build.
We can create the following macros as well:
READ_USER
READ_KERN_STR
READ_USER_STR
and also the same macros with XXX_INTO (same semantics as of the xxx_into() helpers of libbpf)

**Comment by yanivagman** [comment]
We also still have some places in the code where we get a pointer to a field of a struct directly (e.g. `&file->f_path`). To keep the code portable with core, we will probably need to wrap this with something like `__builtin_preserve_access_index`

**Comment by rafaeldtinoco** [comment]
Yes... we're documenting some of your previous work in a presentation, and explaining access differences to each. The overall picture is:

- **LIBBPF NON-CO-RE**
  - bpf_**probe**_read(&pid, sizeof(pid), &task->pid);
- **LIBBPF CO-RE** (same as bpf_probe_read() with __builtin_preserve_access_index())
  - bpf_**core**_read(&pid, sizeof(pid), &task->pid);
- **LIBBPF + BPF_PROG_TYPE_TRACING (v5.4-rc3)**
  - pid_t pid = task->pid;
- **LIBBPF + BPF_PROG_TYPE_TRACING + BPF CO-RE**
  - **__builtin_preserve_access_index**() LLVM built-in support: Accesses to aggregate data structures (structs, unions, arrays) in the argument will have appropriate CO-RE relocation information generated.
  - pid_t pid = **__builtin_preserve_access_index**(({ task->pid; }));

**Comment by yanivagman** [comment]
This shouldn't have been closed by #1107

**Comment by rafaeldtinoco** [comment]
@yanivagman @itaysk has asked me to prioritize this. Are you working on this issue ? Just asking so we avoid duplicate work. Thanks.

**Comment by yanivagman** [comment]
No, I'm not working on this.
Please, go ahead.

**Comment by rafaeldtinoco** [comment]
The PR https://github.com/aquasecurity/tracee/pull/1160 is addressing the slim vmlinux generation. This, together with the fix (same PR) for https://github.com/aquasecurity/tracee/issues/1132, gives us guarantee that we're using CO-RE for accessed fields or-else libbpf relocation would fail.

**Comment by yanivagman** [comment]
> The PR #1160 is addressing the slim vmlinux generation. This, together with the fix (same PR) for #1132, gives us guarantee that we're using CO-RE for accessed fields or-else libbpf relocation would fail.
> 
> > We don't necessarily need to use the MACROS (as, sometimes, we do need to call bpf_core_read() directly, for example). I believe after the mentioned PR we will have full CO-RE support.

I'm not sure about that.
Here are the places that I think we should fix for CO-RE (where we refer to an offset inside a kernel struct):
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1022
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1029
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1039
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1512
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1538
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1539
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1540
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1556
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1575
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1614
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1633
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L3644
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L3646

**Comment by rafaeldtinoco** [comment]
Yes, wherever we refer offsets we "break" CO-RE (potentially) and we have to maintain the entire struct (and hope there are no changes in the kernel we're running eBPF at). You're right.

**Comment by rafaeldtinoco** [comment]
As the urls were pointing to HEAD, I'l listing here the cases you mentioned

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1022 

```C
static __always_inline volatile unsigned char get_sock_state(struct sock *sock)
{
    volatile unsigned char sk_state_own_impl;
    bpf_probe_read((void *)&sk_state_own_impl, sizeof(sk_state_own_impl), (const void *)&sock->sk_state); => HERE
    return sk_state_own_impl;
}
```

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1029 

```C
static __always_inline struct ipv6_pinfo* get_inet_pinet6(struct inet_sock *inet)
{
    struct ipv6_pinfo *pinet6_own_impl;
    bpf_probe_read(&pinet6_own_impl, sizeof(pinet6_own_impl), &inet->pinet6); => HERE
    return pinet6_own_impl;
}
```

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1039 

```C
static __always_inline struct sockaddr_un get_unix_sock_addr(struct unix_sock *sock)
{
    struct unix_address* addr = READ_KERN(sock->addr);
    int len = READ_KERN(addr->len);
    struct sockaddr_un sockaddr = {};
    if (len <= sizeof(struct sockaddr_un)) {
        bpf_probe_read(&sockaddr, len, addr->name); => HERE
    }
    return sockaddr;
}
```

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1512 

```C
static __always_inline void* get_path_str(struct path *path)
{
    struct path f_path;
    bpf_probe_read(&f_path, sizeof(struct path), path);
    char slash = '/';
    int zero = 0;
    struct dentry *dentry = f_path.dentry;
    struct vfsmount *vfsmnt = f_path.mnt;
    struct mount *mnt_parent_p;

    struct mount *mnt_p = real_mount(vfsmnt);
    bpf_probe_read(&mnt_parent_p, sizeof(struct mount*), &mnt_p->mnt_parent); => HERE

    u32 buf_off = (MAX_PERCPU_BUFSIZE >> 1);
    struct dentry *mnt_root;
```

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1538 
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1539 
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1540 

```C
        if (dentry == mnt_root || dentry == d_parent) {
            if (dentry != mnt_root) {
                // We reached root, but not mount root - escaped?
                break;
            }
            if (mnt_p != mnt_parent_p) {
                // We reached root, but not global root - continue with mount point path
                bpf_probe_read(&dentry, sizeof(struct dentry*), &mnt_p->mnt_mountpoint); => HERE
                bpf_probe_read(&mnt_p, sizeof(struct mount*), &mnt_p->mnt_parent); => HERE
                bpf_probe_read(&mnt_parent_p, sizeof(struct mount*), &mnt_p->mnt_parent); => HERE
                vfsmnt = &mnt_p->mnt;
                continue;
            }
            // Global root - path fully parsed
            break;
        }
```

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1556 

```C
// Is string buffer big enough for dentry name?
sz = 0;
if (off <= buf_off) { // verify no wrap occurred
    len = len & ((MAX_PERCPU_BUFSIZE >> 1)-1);
    sz = bpf_probe_read_str(&(string_p->buf[off & ((MAX_PERCPU_BUFSIZE >> 1)-1)]), len, (void *)d_name.name); => HERE
}
```

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1575 

```C
if (buf_off == (MAX_PERCPU_BUFSIZE >> 1)) {
    // memfd files have no path in the filesystem -> extract their name
    buf_off = 0;
    d_name = get_d_name_from_dentry(dentry);
    bpf_probe_read_str(&(string_p->buf[0]), MAX_STRING_SIZE, (void *)d_name.name); => HERE
}
```

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1614 

```C
// Is string buffer big enough for dentry name?
int sz = 0;
if (off <= buf_off) { // verify no wrap occurred
    len = len & ((MAX_PERCPU_BUFSIZE >> 1)-1);
    sz = bpf_probe_read_str(&(string_p->buf[off & ((MAX_PERCPU_BUFSIZE >> 1)-1)]), len, (void *)d_name.name); => HERE
}
```

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L1633 

```C
if (buf_off == (MAX_PERCPU_BUFSIZE >> 1)) {
    // memfd files have no path in the filesystem -> extract their name
    buf_off = 0;
    struct qstr d_name = get_d_name_from_dentry(dentry);
    bpf_probe_read_str(&(string_p->buf[0]), MAX_STRING_SIZE, (void *)d_name.name); => HERE
}
```

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L3644 
https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.bpf.c#L3646

```C
if (event_id == VFS_WRITE) {
    if (header_bytes < FILE_MAGIC_HDR_SIZE)
        bpf_probe_read(header, header_bytes & FILE_MAGIC_MASK, ptr); => HERE
    else
        bpf_probe_read(header, FILE_MAGIC_HDR_SIZE, ptr); => HERE
}
else {
    struct iovec io_vec;
    bpf_probe_read(&io_vec, sizeof(struct iovec), &vec[0]);
    if (header_bytes < FILE_MAGIC_HDR_SIZE)
        bpf_probe_read(header, header_bytes & FILE_MAGIC_MASK, io_vec.iov_base); => HERE
    else
        bpf_probe_read(header, FILE_MAGIC_HDR_SIZE, io_vec.iov_base); => HERE
}
```

**Comment by rafaeldtinoco** [comment]
I'm removing any custom MACROS we have in favor of libbpf's default and maintained macros, to avoid duplicity, guarantee compatibility AND readability for those familiar with libbpf. Check https://github.com/aquasecurity/tracee/pull/3133/commits for more info.
