### ISSUE TITLE
get_syscall_ev_id_from_regs doesn't work when CO-RE is enabled

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#900]
The get_syscall_ev_id_from_regs function is used to extract the syscall which called some internal kernel function.
This is used either when `--output option:detect-syscall` is chosen, or when `security_file_open` event is chosen (to check if it was originated from open/openat syscalls (which we shuold reconsider if still necessary, but that is for another issue).

When used with a BTF enabled kernel (Manjaro 5.10 in my case) - this functino returns 0, and not the syscall number as expected.
When I compile the code without BTF enabled (by changing the code directly in main.go), the function works as expected.

**Comment by rafaeldtinoco** [comment]
Check my comment at: https://github.com/aquasecurity/tracee/pull/924#pullrequestreview-731264161

I was not able to reproduce in a 5.11 kernel with that commit.
