### ISSUE TITLE
tracee-rules doesn't load rules

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#904]
regression from #893 , the `findRegoSigs` function used to filter discovered files to only `*.rego` files and now it doesn't, which causes it to try to load a Go Signature from that same rules directory (`*.so`). We simple need to reinstate the rego filter there.

cc: @josedonizetti  @jan0ski since you are both working on this section so possibly you'd want to fix this as well

**Comment by josedonizetti** [comment]
@itaysk  Yup, I have the PR ready already, found this early today while testing. Sorry for the regression.
