### ISSUE TITLE
tracee-ebpf - load bpf program failed: Argument list too long in kernel 5.4.0 

### ISSUE THREAD

**Issue by shayyo** [aquasecurity/tracee#923]
@yanivagman 

Full log is attached in file 'tracee.tar.gz'.

More information will be provided as per request

Output of command "lsb_release -a"
No LSB modules are available.
Distributor ID:	Ubuntu
[tracee.tar.gz](https://github.com/aquasecurity/tracee/files/6990839/tracee.tar.gz)

Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by shayyo** [comment]
[tracee.tar.gz](https://github.com/aquasecurity/tracee/files/6990850/tracee.tar.gz)

**Comment by yanivagman** [comment]
@shayyo with which tracee version do you work? v0.6.0? main branch?
If with main branch - can you please check if the problem occurs with v0.6.0?
If the problem doesn't reproduce with v0.6.0 - can you please try to apply https://github.com/aquasecurity/tracee/pull/918 and check if it helps?

**Comment by shayyo** [comment]
@yanivagman, @roikol 

Here is the 'Labels' section of command 'docker inspect <container_id>':

            "Labels": {
                "org.label-schema.build-date": "2021-08-03T21:05:10Z",
                "org.label-schema.description": "Linux Runtime Security and Forensics using eBPF",
                "org.label-schema.name": "tracee",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-branch": "main",
                "org.label-schema.vcs-ref": "703a7a9",
                "org.label-schema.vcs-url": "https://github.com/aquasecurity/tracee",
                "org.label-schema.vendor": "Aqua Security",
                "org.label-schema.version": "v0.6.0"
            }

commit 703a7a9d614724d864fff19e7bc72fd966af4fae (tag: v0.6.0)
Author: roikol <roi.kol@aquasec.com>
Date:   Tue Aug 3 22:12:10 2021 +0300

I'll try to patch to [https://github.com/aquasecurity/tracee/pull/918]  and update accordingly

**Comment by yanivagman** [comment]
No need to apply the patch if v0.6.0 doesn't work for you.

From the logs we can see that the offending bpf program is trace_security_sb_mount (loaded when security_sb_mount event is chosen). So, as a workaround, you can try not to use this event.

We will need to reproduce to see why this happens, but I think that @rafaeldtinoco already stumbled into this, and maybe he can add to this discussion.

**Comment by yanivagman** [comment]
Yes, he did.
The fix should already be in main branch - https://github.com/aquasecurity/tracee/pull/889
Can you please apply and check again?

**Comment by shayyo** [comment]
In main branch it seems to be OK. I close the issue
