### ISSUE TITLE
Wait for tracee-ebpf to init before signaling readiness

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#930]
Currently, when starting the tracee container with the default values, we print:
`Loaded signature(s):  [TRC-1 TRC-2 TRC-3 TRC-4 TRC-5 TRC-6 TRC-7]`
This message is printed even when tracee-ebpf failed to load (or is still initializing) and may mislead the user which might think that tracee is up and running.
We should either wait with this message until tracee-ebpf finish its initialization phase or signal readiness with another message.

**Comment by grantseltzer** [comment]
Moving this to milestone v0.6.3
