### ISSUE TITLE
group similar syscalls in the ux

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#94]
some sycalls have different variants: `open`/`openat`/`open_by_handle_at`,  `dup`/`dup2`/`dup3`.
perhaps we can accept a flag `-e open* -e dup*` which will catch all related syscalls. we can do a literal search by prefix which will work for most examples.

**Comment by yanivagman** [comment]
I suggest doing this in a different way.
We can add a concept of tags to the events map.
Example of tags can be: file, process, network, security, default, etc...
The user will be able to choose one or more of these tags. When a tag us given by the user, all the events with the given tag are chosen. If no tag is given, the 'default' tag is chosen.
This way we can group events not only by names, but by similar functionality.
WDYT?

**Comment by itaysk** [comment]
Yes this is a good idea, but I don't think it's replacing this one, it can be created as a new issue. 
Sometimes I know what I want to trace but I don't know which variation of the syscall will be called: open? openat? / dup1/2/3? So this can help me to express my intent without knowing how the usermode libraries will call it. If you want to think it it as the groups feature, we can create groups for every syscall with all of it's variations (open group, dup group), but I think wildcard suffix (*) is easier to implement and answers all the use cases I though of

**Comment by yanivagman** [comment]
Both write and pwrite syscalls write to a file, but have different prefixes. Other examples exists as well.

Anyways, we can implement both like you suggested

**Comment by itaysk** [comment]
Good point. So maybe instead of `-e open*` it will be `-e ~open` which is both prefix and suffix

**Comment by yanivagman** [comment]
But then you will also get unrelated events, such as perf_event_open and mq_open :-)

**Comment by itaysk** [comment]
Also good point :) do you think we can just hand pick a list of  patterns we want to support? For example `*at` `f*` `*[1-9]` etc. does it make sense?

**Comment by yanivagman** [comment]
We can do something like regular expressions, but I don't think it will be used that much. Your original idea of using prefixes is good, and I don't think we need more than that.

I will probably want to implement the grouping by tags I described before, as I see many use cases for that. After implementing this, it will also be easier to add many system calls we didn't add up to this point l, as they were not related to the security scope.

**Comment by itaysk** [comment]
Ok sounds good

**Comment by yanivagman** [comment]
Hi Itay - do you still think this is needed? If so - I think this can be a "good first issue" labeled

**Comment by itaysk** [comment]
I still think it would be nice but obviously not super important. I'll add the label thanks

**Comment by jan0ski** [comment]
Hey there - I'd like to pick this one up if we think all the requirements are ironed out.

**Comment by itaysk** [comment]
Thanks @jan0ski just note that the UX has changed a bit since we wrote this, we no longer have the `-e` flag, now it's `-t event=`. also just to set you on the right path, this should stay within the boundaries of main.go, and mostly in `prepareEventsToTrace ` function. also, please make sure to update the cli help accordingly and add appropriate test cases.
