### ISSUE TITLE
Broken makefile because of RHEL_RELEASE_CODE

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#942]
I can no longer build tracee-ebpf with the makefile

```
fedo grant in ~> tracee-ebpf on ~> staticbuild
[*] make                                                                                130 ↵
/bin/sh: << 8 | : syntax error: operand expected (error token is "<< 8 | ")
clang \
	-I dist/libbpf/usr/include/bpf \
	-I 3rdparty/include \
	-I tracee/x86_64 \
	-DCORE \
	-D__TARGET_ARCH_x86 \
	-D__BPF_TRACING__ \
	-D__VM_LINUX_H__ \
	-D__KERNEL__ \
	-DLINUX_VERSION_CODE=331014 \
	-DRHEL_RELEASE_CODE= \
	-target bpf \
	-O2 -c -g -o dist/tracee.bpf.core.o tracee/tracee.bpf.c
tracee/tracee.bpf.c:323:24: error: invalid token at start of a preprocessor expression
#if (RHEL_RELEASE_CODE >= RHEL_RELEASE_VERSION(8, 0))
                       ^
1 error generated.
make: *** [Makefile:129: dist/tracee.bpf.core.o] Error 1

```

The content of my /etc/redhat-release file is:

```
[*] cat /etc/redhat-release                                                              
Fedora release 33 (Thirty Three)
```

uname
```
[*] uname -a                                                                            130 ↵
Linux localhost.localdomain 5.13.6-100.fc33.x86_64 #1 SMP Wed Jul 28 15:30:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yanivagman** [comment]
These are the checks done in the makefile:
```
ifneq (,$(wildcard /etc/redhat-release))
	RHEL_MAJOR := $(shell grep -Eoh -m 1 '[0-9]+\.[0-9]+' /etc/redhat-release | cut -d '.' -f 1)
	RHEL_MINOR := $(shell grep -Eoh -m 1 '[0-9]+\.[0-9]+' /etc/redhat-release | cut -d '.' -f 2)
	RHEL_RELEASE_CODE := $(shell echo $$(($(RHEL_MAJOR) << 8 | $(RHEL_MINOR))))
else
	RHEL_RELEASE_CODE := 0
endif
```

I think that the problem here is that the macros expect the version to be of format MAJOR.MINOR, but here you have 33.
We can grep for Fedora and calculate RHEL_RELEASE_CODE differently (not sure if and how this is calculated for fedora)

**Comment by grantseltzer** [comment]
Further adding to inconsistencies here is that centos doesn't even have this file. /etc/centos-release is of a different format to the fedora one:

```
$ cat /etc/centos-release
CentOS Linux release 8.3.2011
```

`/etc/system-release` on both fedora and centos are symlinks to these respective files, so that should be used regardless.

In [this red hat support thread](https://access.redhat.com/discussions/1312334) someone share sthat they've seen sysadmins edit this file as well.

@yanivagman what can you tell me about how `RHEL_RELEASE_GT_8_0` is used in the bpf code? It seems that in RHEL 8 forward there's some kernel header differences. This seems like it's to specifically support 4.18 kernels that aren't red hat derivatives.

**Comment by rafaeldtinoco** [comment]
BTW, I think we should start using /etc/os-release for things like that, just like I did with the BTFInfo functions.

**Comment by grantseltzer** [comment]
@rafaeldtinoco That seems like the best option, has what seems like a more standard format.

**Comment by yanivagman** [comment]
> @yanivagman what can you tell me about how RHEL_RELEASE_GT_8_0 is used in the bpf code? It seems that in RHEL 8 forward there's some kernel header differences. This seems like it's to specifically support 4.18 kernels that aren't red hat derivatives.

Snip from the code:

```
#if (LINUX_VERSION_CODE < KERNEL_VERSION(4, 19, 0) && !defined(RHEL_RELEASE_GT_8_0))
    // kernel 4.14-4.18:
    return READ_KERN(READ_KERN(task->pids[PIDTYPE_PID].pid)->numbers[level].nr);
#else
    // kernel 4.19 onwards, and CO:RE:
    struct pid *tpid = READ_KERN(task->thread_pid);
    return READ_KERN(tpid->numbers[level].nr);
#endif
```

So the thing is that redhat backported a change from 4.19 to 4.18 which changes the way we need to access task_struct to extract pids. The RHEL_RELEASE_GT_8_0 macro is then used in place of the kernel version check. This macro is defined when the RHEL version is greater or equal to version 8.0 as follows:
```
#ifdef RHEL_RELEASE_CODE
#if (RHEL_RELEASE_CODE >= RHEL_RELEASE_VERSION(8, 0))
#define RHEL_RELEASE_GT_8_0
#endif
#endif
```

**Comment by rafaeldtinoco** [comment]
We will be able to pass any 'kconfig like' value through a new eBPF map Im creating to satisfy the CO-RE issues with embedded kconfig maps for the kconfig relocations:

```
// https://x-lore.kernel.org/all/20210821203108.215937-1-rafaeldtinoco@gmail.com/
// TODO: after 5.4 kernels support we may rely entirely in kconfig externs & relocations
struct {
	__uint(type, BPF_MAP_TYPE_HASH);
	__uint(max_entries, 128);	  // 128 kconfig symbols used by object seem enough
	__type(key, u8);
	__type(value, u8);
} kconfigs SEC(".maps");		  // ignore existing r/o 'kconfig' map, use this one

static __always_inline int getkconfigvalue(u8 key)
{
	u8 *value = NULL;
	value = bpf_map_lookup_elem(&kconfigs, &key);
	if (value)
		return (int) *value;

	return 0;
}
```

FYIO ^

**Comment by grantseltzer** [comment]
@rafaeldtinoco Are you planning on populating this kconfigs map manually in userspace? Why not use the r/o kconfig map that we're given by default?

**Comment by rafaeldtinoco** [comment]
> @rafaeldtinoco Are you planning on populating this kconfigs map manually in userspace? Why not use the r/o kconfig map that we're given by default?

Its broken. Check: https://github.com/aquasecurity/tracee/issues/851#issuecomment-903074596 for further info.
