### ISSUE TITLE
Add a "verifier passed" check for different kernels

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#956]
We recently had some regressions where a bpf program didn't pass the verifier on some specific kernel versions.
We should add a test that will run on different kernel versions (including old kernels like 4.18) and will try to load all of our bpf programs to check that load succeeds without failing in the verifier.

**Comment by yanivagman** [comment]
@rafaeldtinoco this issue might be related to your current environments tests work

**Comment by rafaeldtinoco** [comment]
This is being implemented at: https://github.com/aquasecurity/tracee-test-kernels and a PR will integrate it to our PR/actions workflow.
