### ISSUE TITLE
Error running Tracee when compiled from source

### ISSUE THREAD

**Issue by jmickey** [aquasecurity/tracee#96]
Hi,

I'm building `tracee` on Ubuntu 18.04. I have built and installed `bcc` from source as mentioned in the following instructions: https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source

I am able to build `tracee` successfully, but when I run it I get the following error:

```
vagrant@vagrant:~/dev/tracee$ dist/tracee
/virtual/main.c:1284:1: warning: declaration of 'struct tracepoint__raw_syscalls__sys_enter' will not be visible outside of this function [-Wvisibility]
TRACEPOINT_PROBE(raw_syscalls, sys_enter) {
^
/virtual/include/bcc/helpers.h:996:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:151:1: note: expanded from here
tracepoint__raw_syscalls__sys_enter
^
/virtual/main.c:1300:47: error: incomplete definition of type 'struct tracepoint__raw_syscalls__sys_enter'
    save_to_submit_buf(submit_p, (void*)&(args->id), sizeof(int), INT_T);
                                          ~~~~^
/virtual/main.c:1284:1: note: forward declaration of 'struct tracepoint__raw_syscalls__sys_enter'
TRACEPOINT_PROBE(raw_syscalls, sys_enter) {
^
/virtual/include/bcc/helpers.h:996:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:151:1: note: expanded from here
tracepoint__raw_syscalls__sys_enter
^
1 warning and 1 error generated.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x533556]

goroutine 1 [running]:
github.com/iovisor/gobpf/bcc.(*Module).Load(0x0, 0xc00001ac40, 0xe, 0x2, 0x0, 0x0, 0xe, 0x80, 0x0)
	/go/pkg/mod/github.com/iovisor/gobpf@v0.0.0-20200529092446-49b58e11a4b5/bcc/module.go:202 +0x26
github.com/iovisor/gobpf/bcc.(*Module).LoadKprobe(...)
	/go/pkg/mod/github.com/iovisor/gobpf@v0.0.0-20200529092446-49b58e11a4b5/bcc/module.go:177
github.com/aquasecurity/tracee/tracee.(*Tracee).initBPF(0xc0000b6300, 0xc000124000, 0xb350, 0x0, 0x61f4a2)
	/tracee/tracee/tracee.go:235 +0x58f
github.com/aquasecurity/tracee/tracee.New(0xc00000ad00, 0x40, 0x40, 0x0, 0x61f4a2, 0x5, 0x40, 0xc00005a7c0, 0x0, 0x0)
	/tracee/tracee/tracee.go:192 +0x1cd
main.main.func1(0xc00005a780, 0xc00000ec00, 0x10)
	/tracee/main.go:36 +0x351
github.com/urfave/cli/v2.(*App).RunContext(0xc000001b00, 0x667440, 0xc00001a0c0, 0xc0000121e0, 0x1, 0x1, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:311 +0x6be
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
	/tracee/main.go:93 +0x74d
```

Any assistance would be greatly appreciated.

**Comment by yanivagman** [comment]
Hi,

I think I saw this error when I once run it without sudo.
Maybe this is also the case here?

**Comment by jmickey** [comment]
Hi @yanivagman, good catch. I ran `tracee` with `sudo` and got the following error instead:

`2020/06/24 13:50:44 error creating Tracee: error loading kprobe dup3: error loading BPF program: errno 524`

**Comment by yanivagman** [comment]
Can you please try to run with a specific event? For example:
sudo ./dist/tracee -e execve

This should catch only execve system calls.
If this works, then try to run with dup3 event.

**Comment by yanivagman** [comment]
Also, please try to run with the python version:
sudo ./start.py

Does the problem persist?

Thanks

**Comment by jmickey** [comment]
Running `sudo ./dist/tracee -e execve` works. Same error when running with `dup3` though. When I run `sudo ./start.py` I get:

```
Traceback (most recent call last):
  File "./start.py", line 61, in <module>
    event_monitor.init_bpf()
  File "/home/vagrant/dev/tracee/tracee/tracer.py", line 922, in init_bpf
    self.bpf.attach_kretprobe(event=syscall_fnname, fn_name="trace_ret_" + syscall)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 697, in attach_kretprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 406, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program trace_ret_dup3: Unknown error 524
```

**Comment by yanivagman** [comment]
Interesting. I wonder if this only happens with dup3 or other events as well.
This can be tested by putting dup3 as a comment in tracee/consts.go (syscall number 292) and recompiling.
Hopefully, the issue only happens with this syscall and then we will have to figure out why

**Comment by jmickey** [comment]
I commented `dup3` in `tracee/consts.go` and recompiled. Running `sudo dist/tracee` now starts tracee without any errors, so it just appears to be this specific event.

Thanks very much for your assistance so far @yanivagman!

**Comment by yanivagman** [comment]
Thanks @jmickey for opening this issue.
We will try to check why dup3 might not work on a ubuntu 18.04 environment

**Comment by yanivagman** [comment]
I dug a bit about this issue, and found the following (needs further investigation):
1. errno 524 is ENOTSUPP (https://elixir.bootlin.com/linux/v4.9/source/include/linux/errno.h#L25)
2. As mentioned, the error is "error loading kprobe dup3: error loading BPF program: errno 524", which happens in tracee when loading the kprobe function: kp, err := t.bpfModule.LoadKprobe(fmt.Sprintf("syscall__%s", eName)), meaning when loading the function syscall__dup3, which is our function in tracee, and before attaching to the dup3 kprobe itself (which I find a bit strange)
3. Eventually, the path taken when loading a kprobe is the following:
int BPFModule::bcc_func_load is called (bcc: src/cc/bpf_module.cc), which calls:
bcc_prog_load_xattr (bcc: src/cc/libbpf.c), which calls:
bpf_load_program_xattr (kernel: tools/lib/bpf/bpf.c)

**Comment by yanivagman** [comment]
You can now workaround this issue by using the --exclude-event flag.
This flag can be use to exclude specific events either to reduce output verbosity, or, as in this case, avoid errors caused by specific events which may happen on some environments (for example, event is not supported on a given kernel)

I'm closing this issue, as we were not able to reproduce it on a ubuntu 18.04.3 environment
