### ISSUE TITLE
Exit gracefully when not running as root

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#97]
As described in https://github.com/aquasecurity/tracee/issues/96, errors might occur when not running tracee as root.
We need to exit gracefully when this happens, and tell the user to run tracee as root

**Comment by itaysk** [comment]
Should we check for root or for the required capabilities? If so We need to determine the minimum required

**Comment by yanivagman** [comment]
Better finding the minimal required capabilities (CAP_SYS_ADMIN?), but also a root check should be good as a first step
