### ISSUE TITLE
raw_syscalls shouldn't be in the output by default

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#98]
After merging https://github.com/aquasecurity/tracee/commit/799ed4f6f2164ff33ad369c49c4676d30e461d65, raw_syscalls events are now shown in the output even when not explicitly run with --raw-syscalls.
Need to disable these events by default, and only show them when --raw-syscalls flag is set

**Comment by itaysk** [comment]
Duplicate of #93
