### ISSUE TITLE
Possibility to add new sched_* kernel function tracing

### ISSUE THREAD

**Issue by SericaLaw** [aquasecurity/tracee#983]
Hi, this issue is a feature request (if possible). I'm in need of tracing kernel functions like `sched_wakeup_new` and `sched_switch` to get the information of what process is running (also get to know the process if its clone/fork/exec event is not traced because the tracer may be running after the process is created), and the parent-child relationship ahead of time.

So I gently open this issue to ask if you can add support for these sched_* events. Thanks.

**Comment by rafaeldtinoco** [comment]
Your request is unclear to me. 

You say that we should create events for the tracepoints:

- sched_wakeup_new
- sched_switch

and say those would be needed to get information about already running processes existence (for the parent-child relationship).

1. There is no need for those events to be created if that is the main reason. Any probe is able to update the parent <-> child relationship as they all got pointers to current() and its task struct.

2. both tracepoints are fine grained traces for scheduling measurements, not sure we would like to probe each time a context switch happens for all processes.

3. We could populate maps of all existing tasks, if not doing (1), during tracee load time (for example), as we do to some other bpf maps currently (like pid <-> container_id map, etc).

Could you describe little further your intent ? Give an example of an execution and the problem to be solved ?

**Comment by SericaLaw** [comment]
@rafaeldtinoco Thanks for your reply. The concern of my use case is that I don't want every event to send to contain the process's parent pid, and also the process's name(comm), so just get these information from the sched_* events' args to reduce the redundancy. Does this makes sense to you, or do you think there is a better way?

**Comment by rafaeldtinoco** [comment]
You can use `--output json` and parse it with [jq](https://stedolan.github.io/jq/) for example. You can create very complex parsing results with JQ, just like if it was a mini database for the json you obtained from tracee (for example).

Example 01:
```
$ sudo ./dist/tracee-ebpf --trace uid=1000 --trace pid=new --trace event=execve --trace event=cap_capable --output option:detect-syscall --output json | jq         
```

```json
{
  "timestamp": 1630634972076893200,
  "processId": 3541282,
  "threadId": 3541282,
  "parentProcessId": 3534954,
  "hostProcessId": 3541282,
  "hostThreadId": 3541282,
  "hostParentProcessId": 3534954,
  "userId": 1000,
  "mountNamespace": 4026531840,
  "pidNamespace": 4026531836,
  "processName": "bash",
  "hostName": "fujitsu",
  "containerId": "",
  "eventId": "59",
  "eventName": "execve",
  "argsNum": 2,
  "returnValue": 0,
  "stackAddresses": null,
  "args": [
    {
      "name": "pathname",
      "type": "const char*",
      "value": "/bin/exa"
    },
    {
      "name": "argv",
      "type": "const char*const*",
      "value": [
        "exa",
        "--color=auto"
      ]
    }
  ]
}
{
  "timestamp": 1630634972086186800,
  "processId": 3541285,
  "threadId": 3541285,
  "parentProcessId": 3541284,
  "hostProcessId": 3541285,
  "hostThreadId": 3541285,
  "hostParentProcessId": 3541284,
  "userId": 1000,
  "mountNamespace": 4026531840,
  "pidNamespace": 4026531836,
  "processName": "bash",
  "hostName": "fujitsu",
  "containerId": "",
  "eventId": "59",
  "eventName": "execve",
  "argsNum": 2,
  "returnValue": 0,
  "stackAddresses": null,
  "args": [
    {
      "name": "pathname",
      "type": "const char*",
      "value": "/home/rafaeldtinoco/scripts/git"
    },
    {
      "name": "argv",
      "type": "const char*const*",
      "value": [
        "git",
        "branch"
      ]
    }
  ]
}
```
Example 02:
Now getting specific fields with jq:
```
$ sudo ./dist/tracee-ebpf --trace uid=1000 --trace pid=new --trace event=execve --trace event=cap_capable --output option:detect-syscall --output json | jq         
```


jq '. | {eventName,processName,args}'
```
{
  "eventName": "execve",
  "processName": "bash",
  "args": [
    {
      "name": "pathname",
      "type": "const char*",
      "value": "/bin/sed"
    },
    {
      "name": "argv",
      "type": "const char*const*",
      "value": [
        "sed",
        "-e",
        "/^[^*]/d",
        "-e",
        "s/* \\(.*\\)/\\1/"
      ]
    }
  ]
}
{
  "eventName": "execve",
  "processName": "git",
  "args": [
    {
      "name": "pathname",
      "type": "const char*",
      "value": "/usr/bin/git"
    },
    {
      "name": "argv",
      "type": "const char*const*",
      "value": [
        "/usr/bin/git",
        "branch"
      ]
    }
  ]
}
```

**Comment by SericaLaw** [comment]
@rafaeldtinoco I got your point, but the concern here is that I want to know the process name and its parent, but I don't need to send this information in every messages. E.g., there are a log of read events happening in a second, and all of the reads is performed by the same process. Then, all of the messages contains the process's name and other context information, which is useless. So this information can be carried through sched_* events's arg fields, and it happens less often than other process activities like read/writes.

**Comment by rafaeldtinoco** [comment]
> @rafaeldtinoco I got your point, but the concern here is that I want to know the process name and its parent, but I don't need to send this information in every messages. E.g., there are a log of read events happening in a second, and all of the reads is performed by the same process. 

Right. What is the use case for this ? Could you give an example ?

> Then, all of the messages contains the process's name and other context information, which is useless. So this information can be carried through sched_* events's arg fields, and it happens less often than other process activities like read/writes.

Ok, I got what you meant now. 

@yanivagman what do you think ? There is the **proc_sched** set for those type of events...

**Comment by SericaLaw** [comment]
@rafaeldtinoco My use case is to plan to do the security analysis based on the data that tracee has collected, and needs to know the information I mentioned above. Since the data will be of huge amount and in order not to give the system much burden, the context field (e.g. process name, ppid) for each event should be as less as possible. So, rather than learn this information from the context field, I want to know from the args field from some specific events, i.e. sched_* events.

**Comment by yanivagman** [comment]
@SericaLaw if I understand correctly, you want to add these tracepoints because you may run Tracee after some processes that you want to investigate already run. So, theoretically, if tracee would have run at system start, sched_process_exec, sched_process_fork, and sched_process_exit (which already exist in tracee) would have been enough. is that correct? Or is there any other thing I'm missing here?

Assuming the above is correct, I have two questions:
1. Wouldn't traversing procfs before starting Tracee to get the parent-child relationships be enough?
2. According to https://elixir.bootlin.com/linux/latest/source/include/trace/events/sched.h#L220 this tracepoint contains data about the previous and next running tasks, which arguments will be required for your use case? Is there any data other than the pid (userspace tid) given by the tracepoint required (e.g. parent_pid/parent_tgid)?

**Comment by SericaLaw** [comment]
@yanivagman Thanks for your reply.

>  if tracee would have run at system start, sched_process_exec, sched_process_fork, and sched_process_exit (which already exist in tracee) would have been enough. is that correct?

Yes.

> Wouldn't traversing procfs before starting Tracee to get the parent-child relationships be enough?

Because I want to only reply on a single tracer and don't take other data sources as system input.

> According to https://elixir.bootlin.com/linux/latest/source/include/trace/events/sched.h#L220 this tracepoint contains data about the previous and next running tasks, which arguments will be required for your use case? Is there any data other than the pid (userspace tid) given by the tracepoint required (e.g. parent_pid/parent_tgid)?
> If adding sched_switch tracepoint, what do we need sched_wakeup_new for?

In my use case, I need the `tid` and `comm` fields.

**Comment by yanivagman** [comment]
@SericaLaw can you please check #1002 and tell if that is what you meant?

**Comment by SericaLaw** [comment]
@yanivagman Thanks for your update. I think my use case also needs "prev_tid" and "prev_comm". I appreciate your help very much. I think I can add "sched_wakeup_new" myself later if needed.

**Comment by yanivagman** [comment]
Yes, in the beggining I added "prev_tid" and "prev_comm" as well, but then I saw that these are always equal to the pid and comm given in the context, so I removed it so there will be no duplications of the same data in the event
