### ISSUE TITLE
json unmarshaling issues

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#986]
reported by @idanr1986 

- [x] empty string array

```
panic: interface conversion: interface {} is nil, not []interface {}
```

- [ ] commit creds

```
commit_creds - panic: interface conversion: interface {} is map[string]interface {}, not external.SlimCred
```

- [ ] bytes

```
magic_write - panic: interface conversion: interface {} is string, not []uint8
```

**Comment by itaysk** [comment]
we probably need to cover all of the `Argument.Type`s

**Comment by itaysk** [comment]
```
❯ awk 'BEGIN {FS="\""} /Type/ { print $2 }' /home/vagrant/dev/tracee/tracee-ebpf/tracee/consts.go | sort | uniq

aio_context_t
alert_t
cap_user_header_t
char*
const char *
const char*
const clockid_t
const sigset_t*
const stack_t*
const struct timespec*
const struct timeval*
const void*
dev_t
gid_t
gid_t*
int
int*
int[2]
io_context_t
key_t
long
mode_t
mqd_t
pid_t
sigset_t*
slim_cred_t
struct __sysctl_args*
struct clone_args*
struct perf_event_attr*
struct pollfd*
struct robust_list_head*
struct rseq*
struct sysinfo*
struct timeval*
struct timex*
struct tms*
struct user_desc*
struct utsname*
time_t*
timer_t
u32
u64
uid_t
uid_t*
unsigned int
unsigned int*
unsigned long
void*
```

**Comment by grantseltzer** [comment]
How can I reproduce these issues? I created a test signature that consumes commit_creds, built it, and ran it like so:

`sudo ../tracee-ebpf/dist/tracee-ebpf --trace event=commit_creds --output format:json | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json`

I didn't run into this interface conversion panic

**Comment by mtcherni95** [comment]
@grantseltzer any update regarding reproduction?

**Comment by yanivagman** [comment]
> I'm not able to reproduce, no.

@grantseltzer have you seen #988? To me it seems as something that needs to be fixed.
But we can't merge it as is, and first need to handle #1029 to avoid regressions as @itaysk noted.

**Comment by yanivagman** [comment]
last status was unreproducible
